--
-- Table structure for table `lse_cr_adm_rq`
--

DROP TABLE IF EXISTS `lse_cr_adm_rq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_cr_adm_rq` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `rq_nds_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '요청배서구분코드',
  `rq_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '요청업무구분코드',
  `reqdt` date NOT NULL COMMENT '요청일자',
  `vlt_mtt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위반사항구분코드',
  `stdt` date DEFAULT NULL COMMENT '기준일자',
  `rtamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환급금구분코드',
  `vlt_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위배내용',
  `ch_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경직업코드',
  `injr_rnk` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수',
  `pym_xmp_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입면제세부구분코드',
  `xtn_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소멸세부구분코드',
  `nvd_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무효세부구분코드',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주명',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `crt_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자관계코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `pln_rc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장수령여부',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `dmd_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자직원번호',
  `cr_adm_chr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약관리담당직원번호',
  `nds_dl_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서처리담당자직원번호',
  `dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리여부',
  `dldt` date DEFAULT NULL COMMENT '처리일자',
  `nt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통지여부',
  `nds_dl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서처리기관코드',
  `ud_cplt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사완료여부',
  `ud_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사의견',
  `xmn_rst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토결과구분코드',
  `dl_perdt` date DEFAULT NULL COMMENT '처리기한일자',
  `ud_cpldt` date DEFAULT NULL COMMENT '심사완료일자',
  `ud_dl_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사처리방법코드',
  `pl_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설계접수번호',
  `cn_pronm_snd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '내용증명발송여부',
  `cer_flt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집자과실여부',
  `adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주소구분코드',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `rec_cn_rpr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '녹취해지통보여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_cr_adm_rq_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`cc_seq`,`rq_nds_flgcd`,`rq_bsns_flgcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계약관리요청';
