--
-- Table structure for table `lse_mdcs_cc_bsc`
--

DROP TABLE IF EXISTS `lse_mdcs_cc_bsc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_mdcs_cc_bsc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `xi_py_spc_seqno` decimal(3,0) NOT NULL COMMENT '추산지급내역순번',
  `ccmtd_seqno` decimal(3,0) NOT NULL COMMENT '산출식순번',
  `mdcs_cc_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '의료비산출구분코드',
  `rmdy_spc_seqno` decimal(3,0) NOT NULL COMMENT '치료내역순번',
  `onw_mdcs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신구의료비구분코드',
  `stzn_mdcs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준화의료비여부',
  `hlt_ins_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건강보험여부',
  `slr_t_mdcs` decimal(17,2) DEFAULT NULL COMMENT '급여총의료비',
  `nsly_t_mdcs` decimal(17,2) DEFAULT NULL COMMENT '비급여총의료비',
  `t_mdcs_sm` decimal(17,2) NOT NULL COMMENT '총의료비합계',
  `slr_self_chamt` decimal(17,2) NOT NULL COMMENT '급여자기부담금액',
  `nsly_self_chamt` decimal(17,2) NOT NULL COMMENT '비급여자기부담금액',
  `self_chamt_sm` decimal(17,2) NOT NULL COMMENT '자기부담금액합계',
  `slr_self_chrg_rt` decimal(5,2) NOT NULL COMMENT '급여본인부담비율',
  `non_appr_cs` decimal(17,2) NOT NULL COMMENT '불인정비용',
  `mdcs_ccmtd_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비산출식내용',
  `pyamt` decimal(17,2) NOT NULL COMMENT '지급금액',
  `hsprt_isamt` decimal(15,0) NOT NULL COMMENT '입원실료가입금액',
  `hsprt_ccamt` decimal(15,0) NOT NULL COMMENT '입원실료산출금액',
  `hsprt_ppamt` decimal(15,0) NOT NULL COMMENT '입원실료기지급금액',
  `hsprt_accm_pyamt` decimal(15,0) NOT NULL COMMENT '입원실료누계지급금액',
  `hsprt_fnl_ccamt` decimal(15,0) NOT NULL COMMENT '입원실료최종산출금액',
  `hsp_wlcst_isamt` decimal(15,0) NOT NULL COMMENT '입원제비용가입금액',
  `hsp_wlcst_ccamt` decimal(15,0) NOT NULL COMMENT '입원제비용산출금액',
  `hsp_wlcst_ppamt` decimal(15,0) NOT NULL COMMENT '입원제비용기지급금액',
  `hsp_wlcst_accm_pyamt` decimal(15,0) NOT NULL COMMENT '입원제비용누계지급금액',
  `hsp_wlcst_fnl_ccamt` decimal(15,0) NOT NULL COMMENT '입원제비용최종산출금액',
  `opccs_isamt` decimal(15,0) NOT NULL COMMENT '수술비가입금액',
  `opccs_ccamt` decimal(15,0) NOT NULL COMMENT '수술비산출금액',
  `opccs_ppamt` decimal(15,0) NOT NULL COMMENT '수술비기지급금액',
  `opccs_accm_pyamt` decimal(15,0) NOT NULL COMMENT '수술비누계지급금액',
  `opccs_fnl_ccamt` decimal(15,0) NOT NULL COMMENT '수술비최종산출금액',
  `nsly_ward_diamt` decimal(15,0) NOT NULL COMMENT '비급여병실차액',
  `ap_ward_diamt` decimal(15,0) NOT NULL COMMENT '적용병실차액',
  `t_hsp_days` decimal(5,0) NOT NULL COMMENT '총입원일수',
  `upr_ward_hsp_days` decimal(5,0) NOT NULL COMMENT '상급병실입원일수',
  `std_ward_diamt` decimal(15,0) NOT NULL COMMENT '표준병실차액',
  `spls_cpamt` decimal(15,0) NOT NULL COMMENT '초과보상금액',
  `otp_dm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원청구구분코드',
  `nstd_uiamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비표준공제금액구분코드',
  `otp_mdcs_cmprt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원의료비보상비율구분코드',
  `isamt` decimal(17,2) NOT NULL COMMENT '가입금액',
  `cvr_non_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '담보불인정금액',
  `hsprt_non_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '입원실료불인정금액',
  `hswst_non_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '입원제비용불인정금액',
  `opccs_non_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '수술비불인정금액',
  `auto_ccamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '자동산출금액',
  `ccmtd_lm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산출식한도내용',
  `hsprt_auto_ccamt` decimal(17,2) DEFAULT NULL COMMENT '입원실료자동산출금액',
  `hswst_auto_ccamt` decimal(17,2) DEFAULT NULL COMMENT '입원제비용자동산출금액',
  `opccs_auto_ccamt` decimal(17,2) DEFAULT NULL COMMENT '수술비자동산출금액',
  `hsprt_ccmtd_lm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입원실료산출식한도내용',
  `hswst_ccmtd_lm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입원제비용산출식한도내용',
  `opccs_ccmtd_lm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술비산출식한도내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_mdcs_cc_bsc_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`cc_seq`,`xi_py_spc_seqno`,`ccmtd_seqno`,`mdcs_cc_flgcd`,`rmdy_spc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='의료비산출근거';
