--
-- Table structure for table `lse_lsetm_ud_requ`
--

DROP TABLE IF EXISTS `lse_lsetm_ud_requ`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_lsetm_ud_requ` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `clm_nv_seqno` decimal(3,0) NOT NULL COMMENT '사고조사순번',
  `mdud_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '의료심사구분코드',
  `requ_seq` decimal(3,0) NOT NULL COMMENT '의뢰회차',
  `prg_seq` decimal(5,0) NOT NULL COMMENT '진행회차',
  `mdud_dtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '의료심사상세코드',
  `requ_dthms` datetime NOT NULL COMMENT '의뢰일시',
  `xmn_rq_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토요청사항',
  `mdud_prg_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사진행상태코드',
  `rqcl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰자직원번호',
  `rqcl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰자기관코드',
  `md_udwr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사자직원번호',
  `md_udwr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사자기관코드',
  `temp_save_dthms` datetime DEFAULT NULL COMMENT '임시저장일시',
  `temp_save_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임시저장직원번호',
  `temp_save_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임시저장기관코드',
  `md_udcpt_dthms` datetime DEFAULT NULL COMMENT '의료심사완료일시',
  `md_udcpt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사완료직원번호',
  `md_udcpt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사완료기관코드',
  `mdud_prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사결재구분코드',
  `mdud_prv_dthms` datetime DEFAULT NULL COMMENT '의료심사결재일시',
  `ud_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사결재직원번호',
  `ud_prv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사결재기관코드',
  `no1_mdud_dgncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번의료심사진단코드',
  `no1_mdud_dgncd_sno` decimal(5,0) DEFAULT NULL COMMENT '1번의료심사진단코드일련번호',
  `no2_mdud_dgncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번의료심사진단코드',
  `no2_mdud_dgncd_sno` decimal(5,0) DEFAULT NULL COMMENT '2번의료심사진단코드일련번호',
  `no3_mdud_dgncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번의료심사진단코드',
  `no3_mdud_dgncd_sno` decimal(5,0) DEFAULT NULL COMMENT '3번의료심사진단코드일련번호',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고내용',
  `main_rmdy_crs_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주요치료과정내용',
  `ud_xmn_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사검토내용',
  `lsetm_ud_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사심사결과코드',
  `ud_rst_ctn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사결과의견',
  `trpa_ud_exec_rt` decimal(5,2) DEFAULT NULL COMMENT '진료비심사이행율',
  `cmp_chrps_ctncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상담당자의견코드',
  `cmp_chrps_ctn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상담당자의견',
  `mdud_dcn_dthms` datetime DEFAULT NULL COMMENT '의료심사확정일시',
  `mdud_dcn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사확정직원번호',
  `mdud_dcn_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사확정기관코드',
  `dm_dmamt` decimal(17,2) DEFAULT NULL COMMENT '청구손해액',
  `ud_retn_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사반려사유코드',
  `ud_retn_rs_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사반려사유내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_lsetm_ud_requ_00` (`rcp_yymm`,`rcp_nv_seqno`,`dm_seqno`,`clmps_seqno`,`clm_nv_seqno`,`mdud_flgcd`,`requ_seq`,`prg_seq`,`mdud_dtcd`),
  KEY `idx_lse_lsetm_ud_requ_10` (`md_udwr_stfno`,`requ_dthms`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손사심사의뢰';
