--
-- Table structure for table `lse_ntc_vlt_cr`
--

DROP TABLE IF EXISTS `lse_ntc_vlt_cr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_ntc_vlt_cr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `rq_nds_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '요청배서구분코드',
  `rq_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '요청업무구분코드',
  `cr_ud_seqno` decimal(3,0) NOT NULL COMMENT '계약심사순번',
  `cc_seq` decimal(3,0) DEFAULT NULL COMMENT '산출회차',
  `hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원코드',
  `fsvs_hsp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금감원병원구분코드',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `hspnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원명',
  `rmdy_strdt` date DEFAULT NULL COMMENT '치료시작일자',
  `rmdy_nddt` date DEFAULT NULL COMMENT '치료종료일자',
  `hsp_days` decimal(5,0) DEFAULT NULL COMMENT '입원일수',
  `otp_days` decimal(5,0) DEFAULT NULL COMMENT '통원일수',
  `dgncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진단코드',
  `dgncd_sno` decimal(5,0) DEFAULT NULL COMMENT '진단코드일련번호',
  `dgnnm` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진단명',
  `mdct_rmdy_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '투약치료여부',
  `phtrt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물리치료여부',
  `op_rmdy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술치료여부',
  `nsp_rmdy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검사치료여부',
  `et_rmdy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타치료여부',
  `et_rmdy_spc` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타치료내역',
  `mmi3_dsas_dcn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내질병확정여부',
  `mmi3_dsas_dubt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내질병의심여부',
  `mmi3_hsp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내입원여부',
  `mmi3_op_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내수술여부',
  `mmi3_mdct_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내투약여부',
  `mmi3_medi_eat_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내약물복용여부',
  `y1wi_ad_nsp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1년이내추가검사여부',
  `embr_abov_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '태아이상여부',
  `hnd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애여부',
  `y5w_hsp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내입원여부',
  `y5w_op_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내수술여부',
  `y5w_ad7_rmdy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내7일이상치료여부',
  `y5w_da30_mdct_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내30일이상투약여부',
  `y5w_10dsa_dgn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내10대질병진단여부',
  `y5w_10dsa_rmdy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내10대질병치료여부',
  `y5w_10dsa_hsp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내10대질병입원여부',
  `y5w_10dsa_op_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내10대질병수술여부',
  `y5w_10dsa_mdct_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내10대질병투약여부',
  `y5w_10dsa_cancr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내10대질병암여부',
  `ud_rst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사결과구분코드',
  `ud_xmn_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사검토내용',
  `ud_crr_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사이력내용',
  `ntvlt_cr_adm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고지위반계약관리구분코드',
  `md_bhvr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료행위구분코드',
  `comp_dsas_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중대질환위반여부',
  `dsas_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '질병위반여부',
  `hnd_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애위반여부',
  `embr_dsas_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '태아질환위반여부',
  `mmi3_dsas_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3개월내질환위반여부',
  `y5w_t7_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5년내7회위반여부',
  `y1wi_rensp_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1년이내재검사위반여부',
  `ntclt_outdt` date DEFAULT NULL COMMENT '안내문출력일자',
  `tth_cnn_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '치아관련위반여부',
  `spl_ntc_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간편고지위반여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_ntc_vlt_cr_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`dm_seqno`,`rq_nds_flgcd`,`rq_bsns_flgcd`,`cr_ud_seqno`,`mdct_rmdy_yn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='고지위반계약';
