--
-- Table structure for table `lse_mdud_cnst_requ`
--

DROP TABLE IF EXISTS `lse_mdud_cnst_requ`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_mdud_cnst_requ` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `ud_seq` decimal(3,0) NOT NULL COMMENT '심사회차',
  `clm_nv_seqno` decimal(3,0) NOT NULL COMMENT '사고조사순번',
  `nrdps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객번호',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `nrdps_ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객식별번호',
  `md_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료구분코드',
  `dmd_stfno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자직원번호구분코드',
  `dmd_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자직원번호',
  `dmd_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자기관코드',
  `asr_stfno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신직원번호구분코드',
  `asr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신직원번호',
  `asr_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신직원명',
  `asr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신기관코드',
  `asr_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신기관명',
  `rcv_plac_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수신처명',
  `hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원코드',
  `trmt_sbjcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료과목코드',
  `xmn_rq_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토요청내용',
  `sel_obs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '후유장해여부',
  `cht_intp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차트해석여부',
  `cnbd_ap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기여도적용여부',
  `cvr_propt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보적정여부',
  `trpa_dtspc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료비세부내역여부',
  `et_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타여부',
  `asr_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신내용',
  `main_rmdy_crs_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주요치료과정내용',
  `adx_da_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '첨부자료내용',
  `rqudt` date DEFAULT NULL COMMENT '의뢰일자',
  `mdud_asrdt` date DEFAULT NULL COMMENT '의료심사회신일자',
  `mdud_prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사결재구분코드',
  `prvdt` date DEFAULT NULL COMMENT '결재일자',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고내용',
  `clmtm_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고시직업코드',
  `clmtm_jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고시직업명',
  `hspnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원명',
  `cmp_ky_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상키년도',
  `cmp_ky_seqno` decimal(10,0) DEFAULT NULL COMMENT '보상키순번',
  `hdof_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본사담당자직원번호',
  `hdof_cnfdt` date DEFAULT NULL COMMENT '본사확인일자',
  `hdof_cnfm_ctn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본사확인자의견',
  `hdof_ap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본사승인여부',
  `dm_rd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해감소여부',
  `slobs_dm_rdamt` decimal(15,0) DEFAULT NULL COMMENT '후유장해손해감소금액',
  `dascs_dm_rdamt` decimal(15,0) DEFAULT NULL COMMENT '진단비손해감소금액',
  `asr_1_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신1내용',
  `auto_requ_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동의뢰여부',
  `acrc_mdud_ccl_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정밀의료심사취소사유코드',
  `acrc_mdud_ccl_rs` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정밀의료심사취소사유',
  `dm_seqno` decimal(5,0) DEFAULT NULL COMMENT '청구순번',
  `prv_info_seqno` decimal(5,0) DEFAULT NULL COMMENT '결재정보순번',
  `md_udwr_ardc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사자전결여부',
  `md_cnst_cspy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문비용지급여부',
  `cs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비용구분코드',
  `pylno` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처번호',
  `pylnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처명',
  `pypl_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처고객번호',
  `pypl_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처은행코드',
  `dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주명',
  `pypl_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처계좌번호',
  `cs_uramt` decimal(15,0) DEFAULT NULL COMMENT '비용발생금액',
  `cs_pcamt` decimal(15,0) DEFAULT NULL COMMENT '비용원금',
  `cs_ixamt` decimal(15,0) DEFAULT NULL COMMENT '비용소득세액',
  `cs_rxamt` decimal(15,0) DEFAULT NULL COMMENT '비용주민세액',
  `mdud_ctn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료심사의견',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_mdud_cnst_requ_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`ud_seq`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='의료심사자문의뢰';
