--
-- Table structure for table `lse_otcm_cr`
--

DROP TABLE IF EXISTS `lse_otcm_cr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_otcm_cr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '배서번호',
  `cr_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '계약상태코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험종목코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품코드',
  `crrnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '계약자명',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `owrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자명',
  `ojnm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물명',
  `cnrdt` date NOT NULL COMMENT '계약일자',
  `cr_seek_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '계약찾기구분코드',
  `imu_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '면책여부',
  `end_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '종결여부',
  `enddt` date DEFAULT NULL COMMENT '종결일자',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급직원번호',
  `ce_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '모집직원번호',
  `clm_prg_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고진행상태코드',
  `otcm_plyno` varchar(25) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사증권번호',
  `qtrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '지분율',
  `crt_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자고객번호',
  `nrdps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객번호',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '인수형태코드',
  `mgcmp_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간사사코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `clm_thtm_age` decimal(3,0) DEFAULT NULL COMMENT '사고당시연령',
  `cr_rnd_yyct` decimal(3,0) DEFAULT NULL COMMENT '계약경과년수',
  `cr_rnd_mc` decimal(3,0) DEFAULT NULL COMMENT '계약경과월수',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직원번호',
  `clm_bj_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '사고대상여부',
  `dcn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확정여부',
  `ch_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경사유코드',
  `ndsno_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호변경여부',
  `frc_ad_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '강제추가여부',
  `ndsch_frc_ad_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서변경강제추가사유코드',
  `cr_pout_mtt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약특이사항여부',
  `wr_dher_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '불량취급자계약여부',
  `rcp_mdcs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수의료비구분코드',
  `rcp_seqno` decimal(5,0) NOT NULL COMMENT '접수순번',
  `thcp_pfrt` decimal(7,4) DEFAULT NULL COMMENT '당사참여율',
  `lap_durn_clm_py_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실효중사고지급사유코드',
  `lap_durn_clm_py_chrps_ctn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실효중사고지급담당자의견',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_otcm_cr_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`),
  KEY `idx_lse_otcm_cr_01` (`nrdps_ctmno`,`ikd_grpcd`,`aid`,`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`),
  KEY `idx_lse_otcm_cr_10` (`plyno`)
) ENGINE=InnoDB AUTO_INCREMENT=4836 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고자계약';
