--
-- Table structure for table `lse_law_md_cnst`
--

DROP TABLE IF EXISTS `lse_law_md_cnst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_law_md_cnst` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `requ_seqno` decimal(5,0) NOT NULL COMMENT '의뢰순번',
  `ch_seq` decimal(10,0) NOT NULL COMMENT '변경회차',
  `clmps_seqno` decimal(3,0) DEFAULT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `ikdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `nrdps_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자주민번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `crt_cd` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자코드',
  `law_md_cnst_frmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법률의료자문양식코드',
  `law_md_cnst_prg_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법률의료자문진행상태코드',
  `drftr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기안자직원번호',
  `drftr_ofcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기안자점포명',
  `drftr_dep_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기안자부서코드',
  `asrdt` date DEFAULT NULL COMMENT '회신일자',
  `asr_drftr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신기안자직원번호',
  `asr_drftr_ofcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신기안자점포명',
  `asr_drftr_dep_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신기안자부서코드',
  `asr_iptdt` date DEFAULT NULL COMMENT '회신입력일자',
  `rq_prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청결재구분코드',
  `rq_prvmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청결재자직원번호',
  `rq_prv_ofcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청결재점포명',
  `rq_prv_dep_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청결재부서코드',
  `rq_prvdt` date DEFAULT NULL COMMENT '요청결재일자',
  `asr_prv_csf_lvl` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신결재분류레벨',
  `asr_prvmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신결재자직원번호',
  `asr_prv_ofcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신결재점포명',
  `asr_prv_dep_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신결재부서코드',
  `asr_prvdt` date DEFAULT NULL COMMENT '회신결재일자',
  `asr_prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신결재구분코드',
  `rcpnt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인구분코드',
  `rcpnt_admno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인관리번호',
  `rtpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인명',
  `dcuno` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '문서번호',
  `cvr_ojnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보목적물명',
  `cvr_rknm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보위험명',
  `victm_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자성명',
  `victm_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자성별코드',
  `victm_age` decimal(3,0) DEFAULT NULL COMMENT '피해자연령',
  `victm_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자주민번호',
  `victm_jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자직업명',
  `md_cnst_main_1_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문주요1내용',
  `md_cnst_main_2_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문주요2내용',
  `md_cnst_main_3_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문주요3내용',
  `md_cnst_main_4_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문주요4내용',
  `md_cnst_main_5_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문주요5내용',
  `md_cnst_main_6_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문주요6내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_law_md_cnst_00` (`rcp_yymm`,`rcp_nv_seqno`,`requ_seqno`,`ch_seq`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='법률의료자문';
