--
-- Table structure for table `lse_otp_mdcs_cc_bsc`
--

DROP TABLE IF EXISTS `lse_otp_mdcs_cc_bsc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_otp_mdcs_cc_bsc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `xi_py_spc_seqno` decimal(3,0) NOT NULL COMMENT '추산지급내역순번',
  `ccmtd_seqno` decimal(3,0) NOT NULL COMMENT '산출식순번',
  `mdcs_cc_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '의료비산출구분코드',
  `otp_mdcs_seqno` decimal(3,0) NOT NULL COMMENT '통원의료비순번',
  `otp_dt` date NOT NULL COMMENT '통원일자',
  `hsp_t_mdcs` decimal(15,0) NOT NULL COMMENT '병원총의료비',
  `hsp_self_chamt` decimal(15,0) NOT NULL COMMENT '병원본인부담금액',
  `phar_t_mdcs` decimal(15,0) NOT NULL COMMENT '약국총의료비',
  `phar_self_chamt` decimal(15,0) NOT NULL COMMENT '약국본인부담금액',
  `sm_t_mdcs` decimal(17,2) DEFAULT NULL COMMENT '합계총의료비',
  `sm_t_self_chamt` decimal(15,0) DEFAULT NULL COMMENT '합계총본인부담금액',
  `std_uiamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준공제금액구분코드',
  `uiamt` decimal(17,2) DEFAULT NULL COMMENT '공제금액',
  `non_appr_cs` decimal(17,2) DEFAULT NULL COMMENT '불인정비용',
  `pyamt` decimal(17,2) NOT NULL COMMENT '지급금액',
  `otp_mdcs_ccmtd_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원의료비산출식내용',
  `hlt_ins_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건강보험여부',
  `otp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원구분코드',
  `otp_hsp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원병원구분코드',
  `trmt_tamt` decimal(17,2) DEFAULT '0.00' COMMENT '진료총금액',
  `pbco_chamt_amt` decimal(17,2) DEFAULT '0.00' COMMENT '공단부담금금액',
  `hsp_laco_self_chamt` decimal(17,2) DEFAULT '0.00' COMMENT '병원법정본인부담금액',
  `hsp_nsly_amt` decimal(17,2) DEFAULT '0.00' COMMENT '병원비급여금액',
  `prtn_laco_self_chamt` decimal(17,2) DEFAULT '0.00' COMMENT '처방법정본인부담금액',
  `prtn_nsly_amt` decimal(17,2) DEFAULT '0.00' COMMENT '처방비급여금액',
  `laco_self_chrg_tamt` decimal(17,2) DEFAULT '0.00' COMMENT '법정본인부담총금액',
  `nsly_self_chrg_tamt` decimal(17,2) DEFAULT '0.00' COMMENT '비급여본인부담총금액',
  `hsp_trmt_tamt` decimal(17,2) DEFAULT '0.00' COMMENT '병원진료총금액',
  `prtn_trmt_tamt` decimal(17,2) DEFAULT '0.00' COMMENT '처방진료총금액',
  `hsp_tamt_self_chamt` decimal(17,2) DEFAULT '0.00' COMMENT '병원전액본인부담금액',
  `hsp_nsly_slc_amt` decimal(17,2) DEFAULT '0.00' COMMENT '병원비급여선택금액',
  `non_appr_md_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '불인정조정사유코드',
  `non_appr_md_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '불인정조정사유',
  `hsp_pbco_chamt_amt` decimal(17,2) DEFAULT '0.00' COMMENT '병원공단부담금금액',
  `prtn_pbco_chamt_amt` decimal(17,2) DEFAULT '0.00' COMMENT '처방공단부담금금액',
  `cvr_non_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '담보불인정금액',
  `hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원코드',
  `hspnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원명',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `fsvs_hsp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금감원병원구분코드',
  `pt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환자구분코드',
  `auto_ccamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '자동산출금액',
  `ccmtd_lm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산출식한도내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_otp_mdcs_cc_bsc_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`cc_seq`,`xi_py_spc_seqno`,`ccmtd_seqno`,`mdcs_cc_flgcd`,`otp_mdcs_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='통원의료비산출근거';
