--
-- Table structure for table `lse_hamt_clm`
--

DROP TABLE IF EXISTS `lse_hamt_clm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_hamt_clm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `inp_seq` decimal(3,0) NOT NULL COMMENT '입력회차',
  `hamt_clm_rptg_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고액사고보고서종류코드',
  `cnn_1_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련1접수번호',
  `cnn_2_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련2접수번호',
  `cnn_3_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련3접수번호',
  `cnn_4_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련4접수번호',
  `dbins_spc` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중복보험내역',
  `clm_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고원인',
  `dmspc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해내역',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `accm_xol_ibamt` decimal(17,2) DEFAULT NULL COMMENT '누계XOL보험금액',
  `clm_nv_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고조사종류코드',
  `adm_chrps_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리담당자팀기관코드',
  `adm_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리담당자직원번호',
  `amt_cc_rt` decimal(7,2) DEFAULT NULL COMMENT '금액산출비율',
  `stfaf_dmamt` decimal(17,2) DEFAULT NULL COMMENT '상계후손해금액',
  `acm_uiamt` decimal(15,0) DEFAULT NULL COMMENT '누적공제금액',
  `pibam_smamt` decimal(17,2) DEFAULT NULL COMMENT '지급보험금합계금액',
  `clc_ref_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산정참고사항',
  `condt_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동인수내용',
  `rins_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재보험내용',
  `hamt_clm_oj_tpnm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고액사고목적물유형명',
  `tr_sctnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송구간명',
  `vslnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선박명',
  `hamt_clm_lad_plyno` varchar(40) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고액사고선하증권번호',
  `dh_brcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지점코드',
  `dh_offc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급점포기관코드',
  `clm_rsm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고개요내용',
  `ap_xcrt` decimal(12,6) DEFAULT NULL COMMENT '적용환율',
  `isamt_sm` decimal(15,0) DEFAULT NULL COMMENT '가입금액합계',
  `sm_ivamt` decimal(17,2) DEFAULT NULL COMMENT '합계보험가액',
  `dmamt_sm` decimal(17,2) DEFAULT NULL COMMENT '손해액합계',
  `sm_sbamt` decimal(17,2) DEFAULT NULL COMMENT '합계잔존물금액',
  `t_py_ibnf` decimal(15,0) DEFAULT NULL COMMENT '총지급보험금',
  `psrt` decimal(12,6) DEFAULT NULL COMMENT '보유율',
  `accm_ps_ibamt` decimal(17,2) DEFAULT NULL COMMENT '누계보유보험금액',
  `sm_ndamt` decimal(17,2) DEFAULT NULL COMMENT '합계순손해금액',
  `tot_agamt` decimal(17,2) DEFAULT NULL COMMENT '전체합의금액',
  `cmplm_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상한도내용',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `hprm_nv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'HPRM조사구분코드',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_hamt_clm_00` (`rcp_yymm`,`rcp_nv_seqno`,`inp_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='고액사고';
