--
-- Table structure for table `lse_nia_condt_tlm`
--

DROP TABLE IF EXISTS `lse_nia_condt_tlm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_nia_condt_tlm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `dl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래구분코드',
  `dat_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '데이터구분코드',
  `dat_sno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '데이터일련번호',
  `nia_mgcmp_cd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회간사사코드',
  `mgcmp_clmno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '간사사사고번호',
  `mgcmp_plyno` varchar(30) COLLATE utf8mb4_bin NOT NULL COMMENT '간사사증권번호',
  `nia_trtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회특약코드',
  `cvrnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '담보명',
  `nia_ikdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회보종코드',
  `nia_py_seq` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회지급회차',
  `nia_ptccd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회참여사코드',
  `nia_end_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회종결구분코드',
  `nia_py_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회지급구분코드',
  `ppdt` date NOT NULL COMMENT '계상일자',
  `gdnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '상품명',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `nia_psn_crp_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회개인법인구분코드',
  `crt_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자식별번호',
  `ins_st` date NOT NULL COMMENT '보험시기',
  `ins_clstr` date NOT NULL COMMENT '보험종기',
  `nia_dmgit_seqno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '손보협회피해물순번',
  `clm_rcpdt` date DEFAULT NULL COMMENT '사고접수일자',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고내용',
  `clm_tpnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고유형명',
  `nia_py_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손보협회지급유형코드',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `pyamt` decimal(17,2) DEFAULT NULL COMMENT '지급금액',
  `woncr_cv_pyamt` decimal(17,2) DEFAULT NULL COMMENT '원화환산지급금액',
  `cs_amt` decimal(17,2) DEFAULT NULL COMMENT '비용금액',
  `woncr_cv_csamt` decimal(17,2) DEFAULT NULL COMMENT '원화환산비용금액',
  `qtrt` decimal(12,6) DEFAULT NULL COMMENT '지분율',
  `condt_pyamt` decimal(17,2) DEFAULT NULL COMMENT '공동인수지급금액',
  `condt_woncr_cv_pyamt` decimal(17,2) DEFAULT NULL COMMENT '공동인수원화환산지급금액',
  `condt_csamt` decimal(17,2) DEFAULT NULL COMMENT '공동인수비용금액',
  `condt_woncv_csamt` decimal(17,2) DEFAULT NULL COMMENT '공동인수원화환산비용금액',
  `dmst_trt_rert` decimal(12,6) DEFAULT NULL COMMENT '국내특약출재율',
  `dmst_optn_rert` decimal(12,6) DEFAULT NULL COMMENT '국내임의출재율',
  `ovse_trt_rert` decimal(12,6) DEFAULT NULL COMMENT '해외특약출재율',
  `ovse_optn_rert` decimal(12,6) DEFAULT NULL COMMENT '해외임의출재율',
  `dmst_trt_re_ibamt` decimal(17,2) DEFAULT NULL COMMENT '국내특약출재보험금액',
  `dmst_trt_woncv_re_ibamt` decimal(15,0) DEFAULT NULL COMMENT '국내특약원화환산재보험금액',
  `dmst_optn_re_ibamt` decimal(17,2) DEFAULT NULL COMMENT '국내임의출재보험금액',
  `dmst_optn_woncv_re_ibamt` decimal(15,0) DEFAULT NULL COMMENT '국내임의원화환산재보험금액',
  `ovse_trt_re_ibamt` decimal(17,2) DEFAULT NULL COMMENT '해외특약출재보험금액',
  `ovse_trt_woncv_re_ibamt` decimal(15,0) DEFAULT NULL COMMENT '해외특약원화환산재보험금액',
  `ovse_optn_re_ibamt` decimal(17,2) DEFAULT NULL COMMENT '해외임의출재보험금액',
  `ovse_optn_woncv_re_ibamt` decimal(15,0) DEFAULT NULL COMMENT '해외임의원화환산재보험금액',
  `dmst_trt_re_csamt` decimal(17,2) DEFAULT NULL COMMENT '국내특약출재비용금액',
  `dmst_trt_woncv_re_csamt` decimal(15,0) DEFAULT NULL COMMENT '국내특약원화환산출재비용금액',
  `dmst_optn_re_csamt` decimal(17,2) DEFAULT NULL COMMENT '국내임의출재비용금액',
  `dmst_optn_woncv_re_csamt` decimal(15,0) DEFAULT NULL COMMENT '국내임의원화환산출재비용금액',
  `ovse_trt_re_csamt` decimal(17,2) DEFAULT NULL COMMENT '해외특약출재비용금액',
  `ovse_trt_woncv_re_csamt` decimal(15,0) DEFAULT NULL COMMENT '해외특약원화환산출재비용금액',
  `ovse_optn_re_csamt` decimal(17,2) DEFAULT NULL COMMENT '해외임의출재비용금액',
  `ovse_optn_woncv_re_csamt` decimal(15,0) DEFAULT NULL COMMENT '해외임의원화환산출재비용금액',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자명',
  `chrps_clpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직급명',
  `chrps_cntad` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자연락처',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_nia_condt_tlm_00` (`cls_yymm`,`dl_flgcd`,`dat_flgcd`,`dat_sno`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손보협회공동인수전문';
