--
-- Table structure for table `lse_clm_nv_cs_vl`
--

DROP TABLE IF EXISTS `lse_clm_nv_cs_vl`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_clm_nv_cs_vl` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `cs_spc_seqno` decimal(3,0) NOT NULL COMMENT '비용내역순번',
  `cs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비용구분코드',
  `nv_arecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사지역코드',
  `nv_arecd_sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사지역코드시군구',
  `lsetm_chrps_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사담당자직원명',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `xcrt` decimal(12,6) DEFAULT '0.000000' COMMENT '환율',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `ba_rwfe` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '기본보수료',
  `woncv_ba_rwfe` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산기본보수료',
  `daycs_rq_apamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '일비신청승인금액',
  `woncv_daycs_rq_apamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산일비신청승인금액',
  `trfx_rqamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '교통비신청금액',
  `woncv_trfx_rqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산교통비신청금액',
  `cnst_cs` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '자문비용',
  `woncv_cnst_cs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산자문비용',
  `inctv_csamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '인센티브비용금액',
  `woncv_inctv_csamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산인센티브비용금액',
  `et_cs_usamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '기타비용사용금액',
  `woncv_et_cs_usamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산기타비용사용금액',
  `et1_cs_usamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '기타1비용사용금액',
  `woncv_et1_cs_usamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산기타1비용사용금액',
  `cs_sm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '비용합계',
  `woncv_cs_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산비용합계',
  `quf_dlgdt` date DEFAULT NULL COMMENT '자격위임일자',
  `prsdt` date DEFAULT NULL COMMENT '제출일자',
  `rnd_days` decimal(5,0) DEFAULT NULL COMMENT '경과일수',
  `man_dlg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인위임구분코드',
  `prprt_dlg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재물위임구분코드',
  `man_crmn_nv_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인계약유지조사결과코드',
  `man_dmas_nv_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인손해사정조사결과코드',
  `prprt_dmas_nv_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재물손해사정조사결과코드',
  `cnfst_clrq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확인서징구여부',
  `wr_are_nv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '불량지역조사여부',
  `idm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상여부',
  `cvap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원여부',
  `lw_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송여부',
  `ins_crme_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험범죄여부',
  `emamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '청구금액',
  `pyamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급금액',
  `dm_rdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '손해감소금액',
  `nv_rptg_fuldg_crccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사보고서충실도정도코드',
  `bsns_cprt_crccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무협력정도코드',
  `bsns_fuldg_crccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무충실도정도코드',
  `pln_nv_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '현장조사평가점수',
  `pln_nv_rptg_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '현장조사보고서평가점수',
  `end_rptg_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '종결보고서평가점수',
  `crct_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '정확평가점수',
  `rptg_cpmt_rq_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '보고서보완요청평가점수',
  `cnndc_adx_propt_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '관련서류첨부적정평가점수',
  `dlay_rsdoc_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '지연사유서평가점수',
  `xpnm_cn_yn_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '설명내용여부평가점수',
  `issu_slut_blt_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '문제해결능력평가점수',
  `fsvs_cvap_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '금감원민원평가점수',
  `ntt_clm_sjtdn_vlpoc` decimal(5,0) DEFAULT NULL COMMENT '고의사고적발평가점수',
  `clm_nv_vlpoc_sm` decimal(15,0) DEFAULT '0' COMMENT '사고조사평가점수합계',
  `bsns_vlrt_cv_poct` decimal(17,2) DEFAULT '0.00' COMMENT '업무평가율환산점수',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_clm_nv_cs_vl_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`cc_seq`,`cs_spc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고조사비용평가';
