--
-- Table structure for table `lse_clm_nv`
--

DROP TABLE IF EXISTS `lse_clm_nv`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_clm_nv` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `clm_nv_seqno` decimal(3,0) NOT NULL COMMENT '사고조사순번',
  `dm_str_seqno` decimal(3,0) NOT NULL COMMENT '청구시작순번',
  `dm_nd_seqno` decimal(3,0) NOT NULL COMMENT '청구종료순번',
  `clm_nvdt` date NOT NULL COMMENT '사고조사일자',
  `clm_nv_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '사고조사시분',
  `clm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고유형코드',
  `clm_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고원인코드',
  `clm_2_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고2원인코드',
  `clm_3_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고3원인코드',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `clm_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고시분',
  `nv_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사내용',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '환율',
  `clm_nv_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고조사종류코드',
  `prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재구분코드',
  `prvdt` date DEFAULT NULL COMMENT '결재일자',
  `cmp_ky_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상키년도',
  `cmp_ky_seqno` decimal(10,0) DEFAULT NULL COMMENT '보상키순번',
  `lctn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지구분코드',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `idm_xp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상예상여부',
  `lw_xp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송예상여부',
  `siu_xp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SIU예상여부',
  `cvap_xp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원예상여부',
  `udrtk_atps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수유의자여부',
  `obs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장해여부',
  `dm_sy_ctn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해사정인의견',
  `de_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망여부',
  `drct_ders_de_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직접사인사망원인',
  `mid_prcg_de_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중간선행사망원인',
  `prcg_ders_de_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선행사인사망원인',
  `et_de_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타사망원인',
  `de_plc_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소우편번호',
  `de_plc_sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소시도',
  `de_plc_sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소시군구',
  `de_plc_twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소읍면동',
  `deplc_ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소리/대량배달처',
  `de_plc_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소상세주소',
  `deplc_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소참고항목',
  `deplc_road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소도로명',
  `deplc_undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소지하구분코드',
  `deplc_mn_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소주건물번호',
  `deplc_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소부건물번호',
  `deplc_nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망장소신규주소구분코드',
  `de_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망종류코드',
  `de_dt_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망세부종류코드',
  `de_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망구분코드',
  `dedt` date DEFAULT NULL COMMENT '사망일자',
  `de_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망시분',
  `de_dgn_hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망진단병원코드',
  `de_dgn_hsp_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망진단병원사업자번호',
  `de_dgn_hspnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망진단병원명',
  `de_dgn_hsp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망진단병원구분코드',
  `de_dgn_drnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망진단의사명',
  `de_dgn_intns_licno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망진단의사면허번호',
  `pvsp_cnbrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '기왕증기여율',
  `pvsp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기왕증여부',
  `hsp_tdy` decimal(5,0) DEFAULT NULL COMMENT '입원총일수',
  `hsp_tsm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '입원총합계',
  `woncv_hsp_tsm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산입원총합계',
  `hsp_slfch_tsm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '입원자기부담금총합계',
  `woncv_hsp_slfch_tsm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산입원자기부담금총합계',
  `otp_tdy` decimal(5,0) DEFAULT NULL COMMENT '통원총일수',
  `otp_tsm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '통원총합계',
  `woncv_otp_tsm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산통원총합계',
  `otp_slfch_tsm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '통원자기부담금총합계',
  `woncv_otp_slfch_tsm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산통원자기부담금총합계',
  `hsp_appr_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '입원인정손해액',
  `otp_appr_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '통원인정손해액',
  `hagth_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입통원여부',
  `op_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술여부',
  `otcm_cr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사계약가입여부',
  `dlalz_cnf_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근태확인내용',
  `dlalz_cnf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근태확인구분코드',
  `clm_cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고차량용도코드',
  `clm_oper_crcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고운행차량코드',
  `jb_ch_seqno` decimal(5,0) DEFAULT NULL COMMENT '직업변경순번',
  `nv_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사직업코드',
  `dgndt` date DEFAULT NULL COMMENT '진단일자',
  `dgn_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진단시분',
  `atkdt` date DEFAULT NULL COMMENT '발병일자',
  `atk_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발병시분',
  `ns_dgndt` date DEFAULT NULL COMMENT '개호진단일자',
  `cancr_dcn_dgndt` date DEFAULT NULL COMMENT '암확정진단일자',
  `nv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사기관코드',
  `nw_tth_supm_ct` decimal(3,0) DEFAULT NULL COMMENT '신규치아보철갯수',
  `prev_tth_supm_ct` decimal(3,0) DEFAULT NULL COMMENT '기존치아보철개수',
  `mnth_icamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '월소득금액',
  `mnth_ic_evdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '월소득증빙코드',
  `fltrt` decimal(3,0) NOT NULL COMMENT '과실율',
  `nsamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '개호비',
  `next_mdcf` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '향후치료비',
  `cslmn_tamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '위자료총금액',
  `idac_dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재처리여부',
  `idark` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재급',
  `idacl` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재호',
  `obsdt` date DEFAULT NULL COMMENT '장해일자',
  `psbsn_slamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '휴업급여금액',
  `obs_slamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '장해급여금액',
  `rcpr_slamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '요양급여금액',
  `srvfm_slamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '유족급여금액',
  `fnrcs` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '장제비',
  `et_slamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '기타급여금액',
  `idac_dl_pout_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재처리특이사항',
  `dl_org` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리기관',
  `chrps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자성명',
  `chrps_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화지역번호',
  `chrps_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화국번',
  `chrps_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화일련번호',
  `md_cnst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문여부',
  `law_cnst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법률자문여부',
  `ic_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득기준구분코드',
  `ccpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직종코드',
  `st_ic_seqno` decimal(3,0) DEFAULT NULL COMMENT '기준소득순번',
  `st_ic_ap_strdt` date DEFAULT NULL COMMENT '기준소득적용시작일자',
  `actvt_nddt` date DEFAULT NULL COMMENT '가동종료일자',
  `merg_obsrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '병합장해율',
  `ag_amt` decimal(17,2) DEFAULT NULL COMMENT '합의금액',
  `owrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자명',
  `ownr_cmp_bjps_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자보상대상자관계코드',
  `rpair_days` decimal(5,0) DEFAULT NULL COMMENT '수리일수',
  `dm_crccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해정도코드',
  `prg_moral_ndx` decimal(5,0) DEFAULT NULL COMMENT '진행모랄지수',
  `wrk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '작업형태코드',
  `btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종코드',
  `rt_ap_mngm_ccpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율적용영위직종코드',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `bn_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종분류코드',
  `nv_org_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사기관종류코드',
  `tnd_plc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰장소',
  `tnd_cnt_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰연락전화지역번호',
  `tnd_cnt_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰연락전화국번',
  `tnd_cnt_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰연락전화일련번호',
  `tnd_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰유형코드',
  `psbsn_days` decimal(5,0) DEFAULT NULL COMMENT '휴업일수',
  `victm_fltrt` decimal(3,0) NOT NULL COMMENT '피해자과실율',
  `drct_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '직접손해금액',
  `drt_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '간접손해금액',
  `et_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '기타손해금액',
  `tr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송구분코드',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `sng_co_seadm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단독공동해손구분코드',
  `co_seadm_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동해손명',
  `lttd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도구분코드',
  `lttd_dgr` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도도',
  `lttd_min` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도분',
  `lttd_sec` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도초',
  `hdn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도구분코드',
  `hdn_dgr` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도도',
  `hdn_min` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도분',
  `hdn_sec` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도초',
  `loss_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'LOSS원인',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `ntncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국가코드',
  `ctycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도시코드',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `temp_save_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임시저장여부',
  `clm_info_inp_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고정보입력코드',
  `nml_inp_impr_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정상입력불가사유코드',
  `nml_inp_impr_rs` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정상입력불가사유',
  `chrps_rq_dt_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자요청세부사항',
  `chrps_inp_cnf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자입력확인구분코드',
  `inp_er_chek_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력오류체크사유코드',
  `inp_er_chek_rs` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력오류체크사유',
  `inp_er_cnfm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력오류확인자직원번호',
  `xp_dmamt` decimal(17,5) DEFAULT NULL COMMENT '예상손해액',
  `self_chamt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금액',
  `re_requ_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재의뢰구분코드',
  `py_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급은행코드',
  `py_dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급예금주명',
  `py_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급계좌번호',
  `dpsr_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주식별번호',
  `py_act_cnfyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급계좌확인여부',
  `drct_ders_de_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직접사인사망원인코드',
  `py_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급방법코드',
  `dpsr_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주고객번호',
  `lsetm_rtx_db_dm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사영수증중복청구여부',
  `lsetm_rtx_ninpt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사영수증미입력여부',
  `clm_rcp_inp_cnf_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수입력확인코드',
  `clm_rcp_inp_ercd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수입력오류코드',
  `clm_rcp_inp_er_rs` varchar(800) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수입력오류사유',
  `clm_rcp_inp_retn_dt` date DEFAULT NULL COMMENT '사고접수입력반려일자',
  `clm_rcp_inp_cpmt_dt` date DEFAULT NULL COMMENT '사고접수입력보완일자',
  `thrps_invtn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제3자개입여부',
  `carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호',
  `info_inp_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보입력결과코드',
  `info_inp_rst_ercd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보입력결과오류코드',
  `info_inp_rst_er_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보입력결과오류사유',
  `info_inp_cnf_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보입력확인코드',
  `info_inp_cnf_ercd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보입력확인오류코드',
  `info_inp_cnf_er_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보입력확인오류사유',
  `cnf_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확인직원번호',
  `clm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고구분코드',
  `slfch_dc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기부담금공제구분코드',
  `temp_save_dthms` datetime DEFAULT NULL COMMENT '임시저장일시',
  `temp_save_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임시저장직원번호',
  `rcp_retn_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수반려상태코드',
  `mn_dgncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주진단코드',
  `rtx_ch_yncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증변경여부코드',
  `nt_prpn_cr_yncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통지비례발생여부코드',
  `dtspc_inp_cnfdt` date DEFAULT NULL COMMENT '세부내역입력확인일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_clm_nv_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`clm_nv_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=640 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고조사';
