--
-- Table structure for table `lse_xi_py_spc`
--

DROP TABLE IF EXISTS `lse_xi_py_spc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_xi_py_spc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `xi_py_spc_seqno` decimal(3,0) NOT NULL COMMENT '추산지급내역순번',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `pyamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급금액',
  `woncr_cv_pyamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '원화환산지급금액',
  `remn_xi_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔여추산화폐코드',
  `remn_xi_amt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '잔여추산금액',
  `fr_cc_xiamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '최초산출추산금액',
  `rk_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험유형코드',
  `cmp_py_rltno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상지급연계번호',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `dlay_nt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지연이자',
  `woncv_ibnf_dlay_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산보험금지연이자',
  `xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '환율',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `py_spc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급내역구분코드',
  `cvr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태코드',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고담보코드',
  `oj_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물유형코드',
  `ojnm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물명',
  `oj_dt_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물상세내용',
  `cr_cvrcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약담보코드',
  `self_chamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자기부담금액',
  `isamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액',
  `isamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액화폐코드',
  `oj_seqno` decimal(5,0) DEFAULT NULL COMMENT '목적물순번',
  `lctcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지코드',
  `ivamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험가액구분코드',
  `ivamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '보험가액',
  `cdamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '발생손해금액',
  `sbamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '잔존물금액',
  `ndamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '순손해금액',
  `woncr_cv_isamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산가입금액',
  `ltcvr_re_ibamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '장기담보출재보험금액',
  `ltcvr_re_remn_xiamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '장기담보출재잔여추산금액',
  `ltrm_rert` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '장기출재율',
  `odclm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구사고담보코드',
  `cvr_seqno` decimal(5,0) DEFAULT NULL COMMENT '담보순번',
  `ndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기코드',
  `cmp_lmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '보상한도액',
  `ltins_pstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기보험경유처코드',
  `ltins_rins_ps` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기보험재보험자',
  `imu_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면책담보여부',
  `ibnf_cc_amt` decimal(17,2) DEFAULT NULL COMMENT '보험금산출금액',
  `chc_amt` decimal(17,2) DEFAULT NULL COMMENT '변동금액',
  `norm_cla_dc_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보통약관공제방식코드',
  `spc_cla_dc_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별약관공제방식코드',
  `auto_slc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동선택여부',
  `prpn_cmp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비례보상여부',
  `ivamt_coins_rt_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험가액공동보험비율코드',
  `spcl_slfch_amt` decimal(17,2) DEFAULT NULL COMMENT '특별약관자기부담금금액',
  `mdud_seq` decimal(3,0) DEFAULT NULL COMMENT '의료심사회차',
  `acrc_mdud_apamt` decimal(17,2) DEFAULT NULL COMMENT '정밀의료심사승인금액',
  `acrc_mdud_py_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정밀의료심사지급유형코드',
  `re_trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재특약구분코드',
  `opccs_udamt` decimal(15,0) DEFAULT NULL COMMENT '수술비심사금액',
  `opccs_ud_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술비심사승인구분코드',
  `opccs_ud_cpmt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술비심사보완유형코드',
  `opccs_ud_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술비심사의견',
  `re_sply_vlamt` decimal(17,5) DEFAULT NULL COMMENT '재조달가액',
  `rlpmi_cvr_db_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손담보중복가입여부',
  `cvrcl_dm_dmamt` decimal(17,2) DEFAULT NULL COMMENT '담보별청구손해액',
  `re_dlay_ntamt` decimal(17,2) DEFAULT NULL COMMENT '출재지연이자금액',
  `nt_ppcp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통지비례보상여부',
  `tmppy_qck_py_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가지급신속지급구분코드',
  `rs_rlv_dt` date DEFAULT NULL COMMENT '사유해당일자',
  `ltrm_dlynt_re_ibamt` decimal(17,2) DEFAULT NULL COMMENT '장기지연이자출재보험금액',
  `ibnf_md_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금조정구분코드',
  `ibnf_md_flg_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금조정구분상세코드',
  `ibnf_mdamt` decimal(17,2) DEFAULT NULL COMMENT '보험금조정금액',
  `lsetm_pypl_rel_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사지급처관계구분코드',
  `dm_dmamt` decimal(17,2) DEFAULT NULL COMMENT '청구손해액',
  `cc_dmamt` decimal(17,2) DEFAULT '0.00' COMMENT '산출손해액',
  `xi_amt` decimal(15,0) DEFAULT '0' COMMENT '추산금액',
  `pvpy_amt` decimal(15,0) DEFAULT '0' COMMENT '기지급금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_xi_py_spc_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`cc_seq`,`xi_py_spc_seqno`),
  KEY `idx_lse_xi_py_spc_10` (`plyno`)
) ENGINE=InnoDB AUTO_INCREMENT=1839 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='추산지급내역';
