--
-- Table structure for table `lse_clm_nv_obj`
--

DROP TABLE IF EXISTS `lse_clm_nv_obj`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_clm_nv_obj` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `clm_nv_seqno` decimal(3,0) NOT NULL COMMENT '사고조사순번',
  `clm_nvgd_seqno` decimal(3,0) NOT NULL COMMENT '사고조사물순번',
  `prprt_prdm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재물대물구분코드',
  `dmgnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물명',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `sbamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '잔존물금액',
  `trtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약명',
  `isamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액',
  `ivamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험가액구분코드',
  `ivamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '보험가액',
  `cdamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '발생손해금액',
  `ndamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '순손해금액',
  `drct_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '직접손해금액',
  `drt_dmamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '간접손해금액',
  `hous_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주택종류코드',
  `tot_pysz` decimal(13,2) DEFAULT NULL COMMENT '전체평수',
  `dmge_pysz` decimal(13,2) DEFAULT NULL COMMENT '피해평수',
  `siu_dmgit_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SIU피해물유형코드',
  `rk_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험분류코드',
  `oj_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물분류코드',
  `clm_plc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소여부',
  `cctv_da_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'CCTV자료유무',
  `negh_are_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인근지역여부',
  `lhtn_rpair_entp_xstyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '낙뢰수리업체존재여부',
  `lhtn_rpair_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '낙뢰수리업체코드',
  `lhtn_rpair_eamt` decimal(15,0) DEFAULT NULL COMMENT '낙뢰수리견적금액',
  `oj_rank1_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물1급포함여부',
  `oj_rank2_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물2급포함여부',
  `oj_rank3_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물3급포함여부',
  `oj_rank4_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물4급포함여부',
  `bn_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종분류코드',
  `btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종코드',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `dfsaf_rpair_entp_xstyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '풍수재수리업체존재여부',
  `dfsaf_rpair_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '풍수재수리업체코드',
  `dfsaf_rpair_eamt` decimal(15,0) DEFAULT NULL COMMENT '풍수재수리견적금액',
  `glfcs_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '골프장코드',
  `cady_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '캐디명',
  `cady_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '캐디주민등록번호',
  `eyewt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목격자명',
  `eyewt_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목격자주민등록번호',
  `mnftr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제조사명',
  `ctpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종명',
  `carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호',
  `chsno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차대번호',
  `haeq_rpair_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중장비수리업체코드',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국내외구분코드',
  `clm_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고차량번호',
  `rpair_rnt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리렌트여부',
  `car_rpair_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량수리업체코드',
  `car_rnt_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량렌트업체코드',
  `dmgit_dt_mtt` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물세부사항',
  `self_chamt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금액',
  `rpair_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리업체코드',
  `re_sply_vlamt` decimal(17,5) DEFAULT NULL COMMENT '재조달가액',
  `ojnm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물명',
  `prev_clm_acm_ibnf` decimal(15,0) DEFAULT NULL COMMENT '기존사고누적보험금',
  `isamt_pd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액안분여부',
  `su_ins_isamt` decimal(15,0) DEFAULT NULL COMMENT '잔존보험가입금액',
  `re_sply_cnd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재조달조건여부',
  `inrt` decimal(12,6) DEFAULT NULL COMMENT '부보율',
  `iramt_amt` decimal(15,0) DEFAULT NULL COMMENT '부보금액',
  `prpn_cpamt` decimal(15,0) DEFAULT NULL COMMENT '비례보상금액',
  `tmppy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가지급여부',
  `tmppy_amt` decimal(15,0) DEFAULT NULL COMMENT '가지급금액',
  `py_ibamt` decimal(15,0) DEFAULT NULL COMMENT '지급보험금액',
  `part_ins_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부보험여부',
  `db_ins_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중복보험여부',
  `bld_use` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물용도',
  `bld_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물용도코드',
  `t_are` decimal(17,2) DEFAULT NULL COMMENT '총면적',
  `oj_str_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물구조명',
  `oj_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물구조코드',
  `rof_nm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지붕명',
  `rofcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지붕코드',
  `rlv_part_nm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해당부분명',
  `rlv_are` decimal(17,2) DEFAULT NULL COMMENT '해당면적',
  `xcpt_part_nm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제외부분명',
  `xcpt_are` decimal(17,2) DEFAULT NULL COMMENT '제외면적',
  `rlv_isamt_pdamt` decimal(15,0) DEFAULT NULL COMMENT '해당가입금안분금액',
  `xcpt_isamt_pdamt` decimal(15,0) DEFAULT NULL COMMENT '제외가입금안분금액',
  `isamt_sm` decimal(15,0) DEFAULT NULL COMMENT '가입금액합계',
  `isamt_pdamt` decimal(17,2) DEFAULT NULL COMMENT '가입금액안분금액',
  `rlv_re_sply_vlamt_pdamt` decimal(15,0) DEFAULT NULL COMMENT '해당재조달가액안분금액',
  `xcpt_re_sply_vlamt_pdamt` decimal(15,0) DEFAULT NULL COMMENT '제외재조달가액안분금액',
  `re_sply_vlamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '재조달가액합계금액',
  `pd_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '안분재조달가액',
  `rlv_vlamt_pdamt` decimal(15,0) DEFAULT NULL COMMENT '해당가액안분금액',
  `xcpt_vlamt_pdamt` decimal(15,0) DEFAULT NULL COMMENT '제외가액안분금액',
  `sm_vlamt` decimal(15,0) DEFAULT NULL COMMENT '합계가액',
  `pd_ivamt` decimal(15,0) DEFAULT NULL COMMENT '안분보험가액',
  `adtx_appr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부가세인정여부',
  `adtx_rt` decimal(12,6) DEFAULT NULL COMMENT '부가세율',
  `t_rdt_dprt` decimal(12,6) DEFAULT NULL COMMENT '총감가상각율',
  `pt20_ivamt` decimal(15,0) DEFAULT NULL COMMENT '20퍼센트보험가액',
  `qest_amt_othcs_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적산금액잡비명',
  `qest_amt_othcs_rt` decimal(12,6) DEFAULT NULL COMMENT '적산금액잡비비율',
  `qest_amt_othcs_md_rt` decimal(12,6) DEFAULT NULL COMMENT '적산금액잡비조정비율',
  `qest_amt_othcs_amt` decimal(15,0) DEFAULT NULL COMMENT '적산금액잡비금액',
  `qest_amt_othcs_incld_amt` decimal(15,0) DEFAULT NULL COMMENT '적산금액잡비포함금액',
  `qest_amt_axamt` decimal(15,0) DEFAULT NULL COMMENT '적산금액부가세액',
  `sb_elmnt_cs_othcs_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물제거비용잡비명',
  `sb_elmnt_cs_othcs_rt` decimal(12,6) DEFAULT NULL COMMENT '잔존물제거비용잡비비율',
  `sb_elmnt_cs_othcs_amt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용잡비금액',
  `sb_elmnt_cs_othcs_incld_amt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용잡비포함금액',
  `sb_elmnt_cs_lmrt` decimal(12,6) DEFAULT NULL COMMENT '잔존물제거비용한도율',
  `sb_elmnt_cs_lm_xmn_amt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용한도검토금액',
  `sb_elmnt_cs_axamt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용부가세액',
  `sb_elmnt_cs_vl_dm_smamt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용평가손해합계금액',
  `sb_elmnt_cs_rdt_bf_dmamt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용감가전손해금액',
  `sb_elmnt_cs_rdt_dpamt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용감가상각금액',
  `sb_elmnt_cs_rdt_af_dmamt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용감가후손해금액',
  `sb_elmnt_cs_rdt_stamt` decimal(15,0) DEFAULT NULL COMMENT '잔존물제거비용감가기준금액',
  `sm_wgt_are` decimal(17,2) DEFAULT NULL COMMENT '합계가중치면적',
  `avg_rdt_dprt` decimal(12,6) DEFAULT NULL COMMENT '평균감가상각율',
  `ttare` decimal(17,2) DEFAULT NULL COMMENT '연면적',
  `are_per_unprc` decimal(15,0) DEFAULT NULL COMMENT '면적당단가',
  `nwcon_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신축년월',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `rnd_yyct` decimal(5,0) DEFAULT NULL COMMENT '경과년수',
  `rnd_mc` decimal(5,0) DEFAULT NULL COMMENT '경과월수',
  `rnd_yy_rdt_dprt` decimal(12,6) DEFAULT NULL COMMENT '경과년감가상각율',
  `sramt_rt` decimal(12,6) DEFAULT NULL COMMENT '잔존가액율',
  `cmpx_rdt_rt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '복합감가율여부',
  `eamt_othcs_amt` decimal(15,0) DEFAULT NULL COMMENT '견적금액잡비금액',
  `othcs_incld_eamt` decimal(15,0) DEFAULT NULL COMMENT '잡비포함견적금액',
  `eamt_axamt` decimal(15,0) DEFAULT NULL COMMENT '견적금액부가세액',
  `eamt_rdt_bf_dmamt` decimal(15,0) DEFAULT NULL COMMENT '견적금액감가전손해금액',
  `eamt_rdt_dpamt` decimal(15,0) DEFAULT NULL COMMENT '견적금액감가상각금액',
  `eamt_rdt_af_dmamt` decimal(15,0) DEFAULT NULL COMMENT '견적금액감가후손해금액',
  `rest_amt_othcs_amt` decimal(15,0) DEFAULT NULL COMMENT '복구금액잡비금액',
  `othcs_incld_rest_amt` decimal(15,0) DEFAULT NULL COMMENT '잡비포함복구금액',
  `rest_amt_axamt` decimal(15,0) DEFAULT NULL COMMENT '복구금액부가세액',
  `rest_amt_rdt_bf_dmamt` decimal(15,0) DEFAULT NULL COMMENT '복구금액감가전손해금액',
  `rest_amt_rdt_dpamt` decimal(15,0) DEFAULT NULL COMMENT '복구금액감가상각금액',
  `rest_amt_rdt_af_dmamt` decimal(15,0) DEFAULT NULL COMMENT '복구금액감가후손해금액',
  `othcs_incld_appr_dmamt` decimal(15,0) DEFAULT NULL COMMENT '잡비포함인정손해금액',
  `appr_dmamt_axamt` decimal(15,0) DEFAULT NULL COMMENT '인정손해금액부가세액',
  `appr_dmamt_rdt_bf_dmamt` decimal(15,0) DEFAULT NULL COMMENT '인정손해금액감가전손해금액',
  `appr_dmamt_rdt_dpamt` decimal(15,0) DEFAULT NULL COMMENT '인정손해금액감가상각금액',
  `appr_dmamt_rdt_af_dmamt` decimal(15,0) DEFAULT NULL COMMENT '인정손해금액감가후손해금액',
  `diamt_othcs_amt` decimal(15,0) DEFAULT NULL COMMENT '차액잡비금액',
  `othcs_incld_diamt` decimal(15,0) DEFAULT NULL COMMENT '잡비포함차액',
  `diamt_axamt` decimal(15,0) DEFAULT NULL COMMENT '차액부가세액',
  `diamt_rdt_bf_dmamt` decimal(15,0) DEFAULT NULL COMMENT '차액감가전손해금액',
  `diamt_rdt_dpamt` decimal(15,0) DEFAULT NULL COMMENT '차액감가상각금액',
  `diamt_rdt_af_dmamt` decimal(15,0) DEFAULT NULL COMMENT '차액감가후손해금액',
  `dbins_isamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '중복보험가입금액합계금액',
  `db_ivamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '중복보험가액합계금액',
  `db_iramt_amt_smamt` decimal(15,0) DEFAULT NULL COMMENT '중복부보금액합계금액',
  `db_net_dmamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '중복순손해액합계금액',
  `db_indpd_rpamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '중복독립책임금액합계금액',
  `db_pibam_smamt` decimal(15,0) DEFAULT NULL COMMENT '중복지급보험금합계금액',
  `isamt_ppcp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액비례보상여부',
  `pt50_dmamt` decimal(15,0) DEFAULT NULL COMMENT '50퍼센트손해금액',
  `db_pd_metd_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중복안분방식내용',
  `uiamt_ap_metd_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제금액적용방식내용',
  `if_pibam` decimal(15,0) DEFAULT NULL COMMENT '추정지급보험금액',
  `gdprc_ndx_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물가지수적용여부',
  `gdprc_ndx_ap_metd_nm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물가지수적용방식명',
  `oj_seqno` decimal(5,0) DEFAULT NULL COMMENT '목적물순번',
  `re_sply_vlamt_pd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재조달가액안분여부',
  `ivamt_pd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험가액안분여부',
  `rlv_tare` decimal(17,2) DEFAULT NULL COMMENT '해당총면적',
  `rlv_isamt` decimal(15,0) DEFAULT NULL COMMENT '해당가입금액',
  `db_pd_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중복안분방식코드',
  `uiamt_ap_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제금액적용방식코드',
  `sns_are_per_unprc` decimal(15,0) DEFAULT NULL COMMENT '건축면적당단가',
  `clm_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고년월',
  `axamt` decimal(15,0) DEFAULT NULL COMMENT '부가세액',
  `othcs_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잡비코드',
  `sb_elmnt_pw_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물제거공정코드',
  `ap_gdprc_ndx_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용물가지수명',
  `qant_eqlyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수량일치여부',
  `smp_vl_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간이평가적용여부',
  `mave_icamt` decimal(15,0) DEFAULT NULL COMMENT '월평균소득금액',
  `ic_stamt` decimal(15,0) DEFAULT NULL COMMENT '소득기준금액',
  `hgd_tool_lvl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가재도구레벨',
  `md_cfc` decimal(12,6) DEFAULT NULL COMMENT '조정계수',
  `fmlct` decimal(5,0) DEFAULT NULL COMMENT '가족수',
  `fmlct_stamt` decimal(15,0) DEFAULT NULL COMMENT '가족수기준금액',
  `hgd_tool_ivamt` decimal(15,0) DEFAULT NULL COMMENT '가재도구보험가액',
  `cuty_rule_lsamt` decimal(15,0) DEFAULT NULL COMMENT '당해규정손실금액',
  `oyr_rule_lsamt` decimal(15,0) DEFAULT NULL COMMENT '차년도규정손실금액',
  `rule_ls_amt_diamt` decimal(15,0) DEFAULT NULL COMMENT '규정손실금차액',
  `leas_cnrdt` date DEFAULT NULL COMMENT '리스계약일자',
  `leas_clm_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리스사고년월',
  `leas_rndmc` decimal(3,0) DEFAULT NULL COMMENT '리스경과월수',
  `leas_mnth_pd_amt` decimal(15,0) DEFAULT NULL COMMENT '리스월할금액',
  `claq_rule_lsamt` decimal(15,0) DEFAULT NULL COMMENT '약관상규정손실금액',
  `schd_rule_lsamt` decimal(15,0) DEFAULT NULL COMMENT '일정규정손실금액',
  `rlv_rule_lsamt` decimal(15,0) DEFAULT NULL COMMENT '해당규정손실금액',
  `leas_ivamt` decimal(15,0) DEFAULT NULL COMMENT '리스보험가액',
  `rule_lsamt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '규정손실금액여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_clm_nv_obj_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`clm_nv_seqno`,`clm_nvgd_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고조사물';
