--
-- Table structure for table `lse_rtro_clm_rcp_xi_py`
--

DROP TABLE IF EXISTS `lse_rtro_clm_rcp_xi_py`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_rtro_clm_rcp_xi_py` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `rtro_ppno` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '수재계상번호',
  `rinsc_clmno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재보사사고번호',
  `xi_py_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '추산지급구분코드',
  `ibnf_cs_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험금비용구분코드',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '담당자직원번호',
  `chrps_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '담당자기관코드',
  `end_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '종결여부',
  `rcpdt` date NOT NULL COMMENT '접수일자',
  `clm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고유형코드',
  `clm_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고원인코드',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고내용',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국내외구분코드',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `ntncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국가코드',
  `ctycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도시코드',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재구분코드',
  `cmp_ky_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상키년도',
  `cmp_ky_seqno` decimal(10,0) DEFAULT NULL COMMENT '보상키순번',
  `prvdt` date DEFAULT NULL COMMENT '결재일자',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `pyamt` decimal(17,2) NOT NULL COMMENT '지급금액',
  `woncr_cv_pyamt` decimal(17,2) NOT NULL COMMENT '원화환산지급금액',
  `remn_xi_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔여추산화폐코드',
  `xi_xcrt` decimal(12,6) DEFAULT NULL COMMENT '추산환율',
  `remn_xi_amt` decimal(17,2) NOT NULL COMMENT '잔여추산금액',
  `rtro_pyamt` decimal(17,2) NOT NULL COMMENT '수재지급금액',
  `rtro_woncr_cv_pyamt` decimal(17,2) NOT NULL COMMENT '수재원화환산지급금액',
  `rtro_remn_xi_amt` decimal(17,2) NOT NULL COMMENT '수재잔여추산금액',
  `cs_mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '비용화폐코드',
  `cs_amt` decimal(17,2) NOT NULL COMMENT '비용금액',
  `woncr_cv_csamt` decimal(17,2) NOT NULL COMMENT '원화환산비용금액',
  `remn_xi_csamt` decimal(17,2) NOT NULL COMMENT '잔여추산비용금액',
  `rtro_cs_amt` decimal(17,2) NOT NULL COMMENT '수재비용금액',
  `rtro_woncr_cv_csamt` decimal(15,0) NOT NULL COMMENT '수재원화환산비용금액',
  `rtro_remn_xi_csamt` decimal(17,2) NOT NULL COMMENT '수재잔여추산비용금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_rtro_clm_rcp_xi_py_00` (`rcp_yymm`,`rcp_nv_seqno`,`cc_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='수재사고접수추산지급';
