--
-- Table structure for table `lse_cvrcl_ibnf_spvsn`
--

DROP TABLE IF EXISTS `lse_cvrcl_ibnf_spvsn`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_cvrcl_ibnf_spvsn` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `xi_py_spc_seqno` decimal(3,0) NOT NULL COMMENT '추산지급내역순번',
  `spvsn_flg_cd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '감리구분코드',
  `cr_cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '계약담보코드',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `spvsn_prg_st_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '감리진행상태구분코드',
  `fnl_ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종승인직원번호',
  `fnl_ap_stf_psgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종승인직원소속기관코드',
  `o1_spvsn_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차감리승인구분코드',
  `o1_spvsn_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '1차감리인정금액',
  `o1_spvsn_nappr_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차감리불인정사유코드',
  `o1_spvsn_dt` date DEFAULT NULL COMMENT '1차감리일자',
  `o1_spvsn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차감리직원번호',
  `o1_spvsn_stf_psgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차감리직원소속기관코드',
  `o1_spvsn_dtcn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차감리세부내용',
  `xpnt_rs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소명사유구분코드',
  `re_spvsn_rqamt` decimal(17,2) DEFAULT NULL COMMENT '재감리요청금액',
  `spvsn_non_accpt_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '감리불수용사유코드',
  `xpnt_dt` date DEFAULT NULL COMMENT '소명일자',
  `xpnt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소명직원번호',
  `xpnt_stf_psgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소명직원소속기관코드',
  `xpnt_dtcn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소명세부내용',
  `fnl_spvsn_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종감리승인구분코드',
  `fnl_spvsn_appr_amt` decimal(17,2) DEFAULT NULL COMMENT '최종감리인정금액',
  `fnl_spvsn_nappr_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종감리불인정사유코드',
  `fnl_spvsn_dt` date DEFAULT NULL COMMENT '최종감리일자',
  `fnl_spvsn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종감리직원번호',
  `fnl_spvsn_stf_psgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종감리직원소속기관코드',
  `fnl_spvsn_dtcn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종감리세부내용',
  `o1_spvsn_er_amt` decimal(17,2) DEFAULT NULL COMMENT '1차감리오류금액',
  `spvsn_xpnt_er_amt` decimal(17,2) DEFAULT NULL COMMENT '감리소명오류금액',
  `fnl_spvsn_er_amt` decimal(17,2) DEFAULT NULL COMMENT '최종감리오류금액',
  `spvsn_prg_dt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL DEFAULT '0000' COMMENT '감리진행세부구분코드',
  `dl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리기관코드',
  `cmp_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상담당자직원번호',
  `prvmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재자직원번호',
  `prvdt` date DEFAULT NULL COMMENT '결재일자',
  `dm_rdamt` decimal(15,0) DEFAULT NULL COMMENT '손해감소금액',
  `clm_nv_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고조사종류코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_cvrcl_ibnf_spvsn_00` (`rcp_yymm`,`rcp_nv_seqno`,`clmps_seqno`,`plyno`,`cc_seq`,`xi_py_spc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='담보별보험금감리';
