--
-- Table structure for table `ccm_lw_bf_iq_rq`
--

DROP TABLE IF EXISTS `ccm_lw_bf_iq_rq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_lw_bf_iq_rq` (
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `iq_rq_seqno` decimal(3,0) NOT NULL COMMENT '심의신청순번',
  `lw_iq_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '소송심의상태코드',
  `lw_iq_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '소송심의업무구분코드',
  `lwprp_tycd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '소제기형태코드',
  `iq_rq_dthms` datetime NOT NULL COMMENT '심의요청일시',
  `iq_rq_cnr_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '심의요청센터기관코드',
  `iq_rq_tm_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '심의요청팀기관코드',
  `iq_rq_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '심의요청직원번호',
  `iq_rcpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심의접수번호',
  `trbl_dt_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁상세내용',
  `trbl_dmnst_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁입증내용',
  `lw_iq_rq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송심의신청구분코드',
  `lw_iq_xmn_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송심의검토결과코드',
  `befo_xmn_ctn_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전검토의견내용',
  `befo_xmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전검토직원번호',
  `befo_xmn_dthms` datetime DEFAULT NULL COMMENT '사전검토일시',
  `fnl_lw_iq_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종소송심의결과코드',
  `fnl_acdno_crtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종사건번호법원코드',
  `fnl_acdno_rcp_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종사건번호접수년도',
  `fnl_acdno_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종사건번호분류코드',
  `fnl_acdno_seqno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종사건번호순번',
  `fnl_jg_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종판결결과코드',
  `fnl_dl_dtcn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종처리세부내용',
  `iq_end_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심의종결직원번호',
  `iq_end_dthms` datetime DEFAULT NULL COMMENT '심의종결일시',
  `icps_py_ibamt` decimal(15,0) DEFAULT NULL COMMENT 'ICPS지급보험금액',
  `mn_hsp_rs` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주입원사유',
  `t_hsp_days` decimal(5,0) DEFAULT NULL COMMENT '총입원일수',
  `md_cnst_propt_hsp_days` decimal(5,0) DEFAULT NULL COMMENT '의료자문적정입원일수',
  `md_cnst_absc_days` decimal(5,0) DEFAULT NULL COMMENT '의료자문부재일수',
  `if_mnth_icamt` decimal(15,0) DEFAULT NULL COMMENT '추정월소득금액',
  `gn_injr_hsp_ddamt` decimal(15,0) DEFAULT NULL COMMENT '일반상해입원일당금액',
  `dsas_hsp_ddamt` decimal(15,0) DEFAULT NULL COMMENT '질병입원일당금액',
  `injr_de_ibamt` decimal(15,0) DEFAULT NULL COMMENT '상해사망보험금액',
  `sel_obs_ibamt` decimal(15,0) DEFAULT NULL COMMENT '후유장해보험금액',
  `otcm_inct` decimal(5,0) DEFAULT NULL COMMENT '타사가입건수',
  `otcm_ins_cr_mtt` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사보험계약사항',
  `y2_wthin_mx_ins_inct` decimal(3,0) DEFAULT NULL COMMENT '2년이내최대보험가입건수',
  `lw_out_ag_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송외합의여부',
  `cr_ch_mttcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약변경사항코드',
  `cvap_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원내용',
  `end_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결사유코드',
  `end_dt_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결상세사유',
  `befo_mdud_chrps_ctn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전의료심사담당자의견',
  `befo_ud_ctncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전심사의견코드',
  `cmp_cnr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상센터기관코드',
  `cmp_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상팀기관코드',
  `cmp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상직원번호',
  `trbl_rltcp_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁상대방명',
  `trbl_summ_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁요약내용',
  `fnl_pyamt` decimal(15,0) DEFAULT NULL COMMENT '최종지급금액',
  `agdt` date DEFAULT NULL COMMENT '합의일자',
  `lw_out_ag_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송외합의사유',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`rcp_yymm`,`rcp_nv_seqno`,`iq_rq_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='소송전심의신청';
