--
-- Table structure for table `ccm_lw_prg`
--

DROP TABLE IF EXISTS `ccm_lw_prg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_lw_prg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `lw_prg_sno` decimal(10,0) NOT NULL COMMENT '소송진행일련번호',
  `lw_rcp_yr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '소송접수년도',
  `lw_sno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '소송일련번호',
  `lwjd` decimal(2,0) NOT NULL COMMENT '심급',
  `lw_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '소송서열',
  `lw_prg_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '소송진행구분코드',
  `prg_dgre` decimal(3,0) NOT NULL COMMENT '진행차수',
  `prgdt` date NOT NULL COMMENT '진행일자',
  `plat_ramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원고요구금액',
  `thcp_prst_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '당사제시금액',
  `ag_amt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '합의금액',
  `agdt` date DEFAULT NULL COMMENT '합의일자',
  `t_pyrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '총지급율',
  `merg_obsrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '병합장해율',
  `bd_ap_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신체감정종류코드',
  `bd_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신체감정구분코드',
  `bd_org_ap_dgre` decimal(3,0) DEFAULT NULL COMMENT '신체원감정차수',
  `hsp_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원고객번호',
  `hsp_cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '병원협력업체순번',
  `ap_rqapl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '감정신청인구분코드',
  `ap_jon_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '감정참가유무',
  `ap_prsps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '감정참석자직원번호',
  `propt_hsp_days` decimal(5,0) DEFAULT NULL COMMENT '적정입원일수',
  `ns_ap_sbjcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개호감정과목코드',
  `ns_strdt` date DEFAULT NULL COMMENT '개호시작일자',
  `ns_nddt` date DEFAULT NULL COMMENT '개호종료일자',
  `ns_yyct` decimal(5,0) DEFAULT NULL COMMENT '개호년수',
  `dy1_ns_hms` decimal(2,0) DEFAULT NULL COMMENT '1일개호시간',
  `dy1_nspct` decimal(2,0) DEFAULT NULL COMMENT '1일개호인수',
  `ns_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개호성별코드',
  `ns_quf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개호자격구분코드',
  `lftb_ap_stdy` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생명표적용기준년도',
  `nml_rol` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '정상여명',
  `exp_rol` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '기대여명',
  `sht_rol` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '단축여명',
  `ic_st_bsccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득기준근거코드',
  `actvt_age` decimal(3,0) DEFAULT NULL COMMENT '가동연령',
  `mnth_actvt_days` decimal(5,0) DEFAULT NULL COMMENT '월가동일수',
  `mnth_icamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '월소득금액',
  `livg_rt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '생계비율',
  `fltrt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '과실율',
  `amvt_ever_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한시영구구분코드',
  `crt_appr_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법원인정직업코드',
  `crt_appr_jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법원인정직업명',
  `pgamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '진행금액합계',
  `md_ntamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '조정이자금액',
  `t_hsp_days` decimal(5,0) DEFAULT NULL COMMENT '총입원일수',
  `t_otp_days` decimal(5,0) DEFAULT NULL COMMENT '총통원일수',
  `py_mdcf` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급치료비',
  `np_mdcf` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '미지급치료비',
  `jg_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '판결유형코드',
  `rcpdt` date DEFAULT NULL COMMENT '접수일자',
  `apl_dmur_clsdt` date DEFAULT NULL COMMENT '상소이의마감일자',
  `dscn_end_py_clsdt` date DEFAULT NULL COMMENT '변론종결지급마감일자',
  `py_perdt` date DEFAULT NULL COMMENT '지급기한일자',
  `tmp_xcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '가집행금액',
  `lwamt_cmp_rt` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '소송가액대비비율',
  `plats_lw_cs_rt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '원고측소송비용비율',
  `as_jon_cs_rt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '보조참가비용비율',
  `end_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결사유코드',
  `wsut_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승소구분코드',
  `thcp_mng_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당사조치구분코드',
  `lwr_acpt_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변호사승복내용',
  `emamt_cmp_wsurt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '청구금액대비승소율',
  `xp_jgamt_cmp_wsurt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '예상판결액대비승소율',
  `apl_prg_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상소진행사유코드',
  `apl_prg_chr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상소진행담당직원번호',
  `apl_prg_ctn_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상소진행의견내용',
  `idm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상여부',
  `idm_cr_prs_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상발생대표유형코드',
  `idmpl_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상처내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_lw_prg_00` (`lw_prg_sno`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='소송진행';
