--
-- Table structure for table `ins_vlamt_vl`
--

DROP TABLE IF EXISTS `ins_vlamt_vl`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_vlamt_vl` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `vlamt_vl_no` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '가액평가번호',
  `wrk_cplyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '작업완료여부',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `crt_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자우편번호',
  `crt_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자기본주소',
  `crt_et_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자기타주소',
  `nw_adr_onw_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신주소신구구분코드',
  `radnm_dsc_kyvl` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명식별키값',
  `radnm_baadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명기본주소',
  `radnm_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명상세주소',
  `btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종코드',
  `vl_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가년월',
  `gdprc_ndx_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물가지수년월',
  `bld_vl_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물평가방법코드',
  `vlr_pst_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가자소속기관코드',
  `vlr_offcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가자점포코드',
  `vlr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가자직원번호',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기준년월',
  `bld_cqamt` decimal(15,0) DEFAULT NULL COMMENT '건물취득금액',
  `bld_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '건물예상재조달가액',
  `bld_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '건물현재평가액',
  `stru_cqamt` decimal(15,0) DEFAULT NULL COMMENT '구축물취득금액',
  `stru_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '구축물예상재조달가액',
  `stru_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '구축물현재가액',
  `eqmt_cqamt` decimal(15,0) DEFAULT NULL COMMENT '시설취득금액',
  `eqmt_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '시설예상재조달가액',
  `eqmt_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '시설현재가액',
  `mcheq_cqamt` decimal(15,0) DEFAULT NULL COMMENT '기계장치취득금액',
  `mcheq_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '기계장치예상재조달가액',
  `mcheq_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '기계장치현재가액',
  `cr_cqamt` decimal(15,0) DEFAULT NULL COMMENT '차량취득금액',
  `cr_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '차량예상재조달가액',
  `cr_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '차량현재가액',
  `tls_cqamt` decimal(15,0) DEFAULT NULL COMMENT '공구취득금액',
  `tls_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '공구예상재조달가액',
  `tls_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '공구현재가액',
  `hshgd_cqamt` decimal(15,0) DEFAULT NULL COMMENT '집기취득금액',
  `hshgd_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '집기예상재조달가액',
  `hshgd_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '집기현재가액',
  `schnd_cqamt` decimal(15,0) DEFAULT NULL COMMENT '중고취득금액',
  `schnd_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '중고예상재조달가액',
  `schnd_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '중고현재가액',
  `leas_cqamt` decimal(15,0) DEFAULT NULL COMMENT '리스취득금액',
  `leas_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '리스예상재조달가액',
  `leas_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '리스현재가액',
  `nvase_cqamt` decimal(15,0) DEFAULT NULL COMMENT '재고자산취득금액',
  `nvase_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '재고자산예상재조달가액',
  `nvase_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '재고자산현재가액',
  `ase_1_cqamt` decimal(15,0) DEFAULT NULL COMMENT '자산1취득금액',
  `ase_1_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '자산1예상재조달가액',
  `ase_1_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '자산1현재가액',
  `ase_2_cqamt` decimal(15,0) DEFAULT NULL COMMENT '자산2취득금액',
  `ase_2_xp_re_sply_vlamt` decimal(15,0) DEFAULT NULL COMMENT '자산2예상재조달가액',
  `ase_2_crnt_vlamt` decimal(15,0) DEFAULT NULL COMMENT '자산2현재가액',
  `cqamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '취득가액합계금액',
  `xp_re_sply_smamt` decimal(15,0) DEFAULT NULL COMMENT '예상재조달합계금액',
  `crnt_vlamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '현재가액합계금액',
  `note` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고',
  `inp_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력지점기관코드',
  `inp_offc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력점포기관코드',
  `mdf_chrps_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수정담당자기관코드',
  `mdf_chrps_offcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수정담당자점포코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_vlamt_vl_00` (`vlamt_vl_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='가액평가';
