--
-- Table structure for table `ins_fire_safe_dgn_rptg`
--

DROP TABLE IF EXISTS `ins_fire_safe_dgn_rptg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_fire_safe_dgn_rptg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호',
  `actvt_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가동년도',
  `rlavt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실가동여부',
  `fct_psbsn_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장휴업사유',
  `annu_slamt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연간매출액내용',
  `bfyy_cut_npft_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전년도당기순이익내용',
  `wrk_psct` decimal(7,0) NOT NULL COMMENT '근무인원수',
  `chif_grd_prsn` decimal(7,0) NOT NULL COMMENT '주간경비원인원',
  `niht_grd_prsn` decimal(7,0) NOT NULL COMMENT '야간경비원인원',
  `cctv_da_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'CCTV자료유무',
  `wtman_grd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무인경비원여부',
  `asmt_smok_plc` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지정흡연장소',
  `nw_rnw_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규갱신구분코드',
  `clm_crr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고경력여부',
  `no1_clmdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번사고일자',
  `no2_clmdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번사고일자',
  `no3_clmdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번사고일자',
  `no4_clmdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번사고일자',
  `no5_clmdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번사고일자',
  `no1_clmcu_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번사고원인내용',
  `no2_clmcu_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번사고원인내용',
  `no3_clmcu_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번사고원인내용',
  `no4_clmcu_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번사고원인내용',
  `no5_clmcu_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번사고원인내용',
  `no1_clm_dmamt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번사고손해액내용',
  `no2_clm_dmamt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번사고손해액내용',
  `no3_clm_dmamt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번사고손해액내용',
  `no4_clm_dmamt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번사고손해액내용',
  `no5_clm_dmamt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번사고손해액내용',
  `no1_et_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번기타내용',
  `befo_y1_dmgrt` decimal(12,6) NOT NULL COMMENT '직전1년손해율',
  `befo_y3_dmgrt` decimal(12,6) NOT NULL COMMENT '직전3년손해율',
  `exnr_ct` decimal(3,0) NOT NULL COMMENT '소화기개수',
  `exnr_ntl_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소화기설치장소',
  `indr_hydr_ct` decimal(3,0) NOT NULL COMMENT '옥내소화전개수',
  `oudr_hydr_ct` decimal(3,0) NOT NULL COMMENT '옥외소화전개수',
  `hydr_ntl_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소화전설치장소',
  `sprkl_xstn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '스프링클러존재여부',
  `sprkl_ct` decimal(7,0) NOT NULL COMMENT '스프링클러개수',
  `sprkl_ntl_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '스프링클러설치장소',
  `gas_xtng_equ_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가스소화설비여부',
  `gas_xtng_equ_ntl_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가스소화설비설치장소',
  `no2_et_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번기타내용',
  `first_nm` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소방서명',
  `first_dstnc_dst` decimal(2,0) NOT NULL COMMENT '소방서이격거리',
  `arv_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도착시분',
  `entr_road_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진입도로코드',
  `cmkng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공지여부',
  `no1_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번건물명',
  `no2_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번건물명',
  `no3_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번건물명',
  `no4_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번건물명',
  `no5_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번건물명',
  `no6_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번건물명',
  `no7_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번건물명',
  `no8_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번건물명',
  `no9_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번건물명',
  `no10_bldnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번건물명',
  `no1_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번건물구조코드',
  `no2_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번건물구조코드',
  `no3_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번건물구조코드',
  `no4_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번건물구조코드',
  `no5_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번건물구조코드',
  `no6_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번건물구조코드',
  `no7_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번건물구조코드',
  `no8_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번건물구조코드',
  `no9_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번건물구조코드',
  `no10_bld_strcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번건물구조코드',
  `no1_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번건물층수',
  `no2_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번건물층수',
  `no3_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번건물층수',
  `no4_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번건물층수',
  `no5_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번건물층수',
  `no6_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번건물층수',
  `no7_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번건물층수',
  `no8_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번건물층수',
  `no9_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번건물층수',
  `no10_bld_flct` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번건물층수',
  `no1_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '1번건물연면적',
  `no2_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '2번건물연면적',
  `no3_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '3번건물연면적',
  `no4_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '4번건물연면적',
  `no5_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '5번건물연면적',
  `no6_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '6번건물연면적',
  `no7_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '7번건물연면적',
  `no8_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '8번건물연면적',
  `no9_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '9번건물연면적',
  `no10_bld_ttare` decimal(17,2) DEFAULT NULL COMMENT '10번건물연면적',
  `no1_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번건물용도내용',
  `no2_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번건물용도내용',
  `no3_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번건물용도내용',
  `no4_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번건물용도내용',
  `no5_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번건물용도내용',
  `no6_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번건물용도내용',
  `no7_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번건물용도내용',
  `no8_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번건물용도내용',
  `no9_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번건물용도내용',
  `no10_bld_use_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번건물용도내용',
  `no1_bzwpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번사업장명',
  `no2_bzwpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번사업장명',
  `no3_bzwpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번사업장명',
  `no4_bzwpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번사업장명',
  `no1_bn_cn` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번업종내용',
  `no2_bn_cn` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번업종내용',
  `no3_bn_cn` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번업종내용',
  `no4_bn_cn` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번업종내용',
  `no1_dtclt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번이격거리내용',
  `no2_dtclt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번이격거리내용',
  `no3_dtclt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번이격거리내용',
  `no4_dtclt_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번이격거리내용',
  `rama_knd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재종류',
  `rama_num` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재수',
  `rama_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재장소',
  `rama_fir_dist_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재방화구획여부',
  `rama_nfmbt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재가연성여부',
  `rama_vola_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재휘발성여부',
  `rama_incbs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원자재불연성여부',
  `prdt_knd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품종류',
  `prdt_num` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품수',
  `prdt_keep_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품보관장소',
  `prdt_fir_dist_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품방화구획여부',
  `prdt_nfmbt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품가연성여부',
  `prdt_vola_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품휘발성여부',
  `prdt_incbs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제품불연성여부',
  `no1_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번점화원여부',
  `no2_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번점화원여부',
  `no3_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번점화원여부',
  `no4_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번점화원여부',
  `no5_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번점화원여부',
  `no6_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번점화원여부',
  `no7_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번점화원여부',
  `no8_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번점화원여부',
  `no9_igso_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번점화원여부',
  `no1_rkgd_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번위험물내용',
  `no2_rkgd_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번위험물내용',
  `no3_rkgd_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번위험물내용',
  `no3_et_cn` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번기타내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_fire_safe_dgn_rptg_00` (`plno`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='화재안전진단보고서';
