--
-- Table structure for table `ins_rk_nv`
--

DROP TABLE IF EXISTS `ins_rk_nv`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_rk_nv` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rk_nv_rqno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '위험조사의뢰번호',
  `psn_crp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인법인구분코드',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `lctn_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지우편번호',
  `lctn_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지주소',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `prd_narnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생산품명',
  `hmpag_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '홈페이지주소',
  `instm_fire_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목화재여부',
  `instm_prop_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목재산여부',
  `instm_bnc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목방카여부',
  `instm_cst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목건설여부',
  `instm_sns_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목건축여부',
  `instm_et_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목기타여부',
  `instm_rv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목예비여부',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_st_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험시기시각',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `ins_clstr_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종기시각',
  `ins_trm` decimal(3,0) DEFAULT NULL COMMENT '보험기간',
  `isamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액화폐코드',
  `isamt` decimal(17,2) DEFAULT NULL COMMENT '가입금액',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `prm` decimal(17,2) DEFAULT NULL COMMENT '보험료',
  `oj_bld_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물건물여부',
  `oj_stru_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물구축물여부',
  `oj_mcheq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물기계장치여부',
  `oj_hshgd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물집기여부',
  `oj_mvpr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물동산여부',
  `oj_cst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물건설여부',
  `oj_sns_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물건축여부',
  `oj_et_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물기타여부',
  `oj_rv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물예비여부',
  `rq_mtt_udrtk_iq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항인수심의여부',
  `rq_mtt_rk_nv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항위험조사여부',
  `rq_mtt_rtaqr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항요율구득여부',
  `rq_mtt_vlamt_vl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항가액평가여부',
  `rq_mtt_cst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항건설여부',
  `rq_mtt_rv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항예비여부',
  `nw_rnw_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규갱신코드',
  `befo_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이전증권번호',
  `rk_nv_dl_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험조사처리상태코드',
  `dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리여부',
  `rq_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청내용',
  `requ_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰내용',
  `ref_mtt_sfchk_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고사항안전점검여부',
  `ref_mtt_korlg_rtaqr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고사항국문요율구득여부',
  `ref_mtt_eng_rtaqr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고사항영문요율구득여부',
  `ref_mtt_vlamt_vl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고사항가액평가여부',
  `ref_mtt_rv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고사항예비여부',
  `trv_1_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장1직원번호',
  `trv_2_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장2직원번호',
  `trv_3_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장3직원번호',
  `trv_4_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장4직원번호',
  `requ_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰담당자직원번호',
  `requ_chrps_offcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰담당자점포코드',
  `requ_chrps_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰담당자지점기관코드',
  `requ_prvmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰결재자직원번호',
  `requ_retn_rs` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰반려사유',
  `requ_prv_reqdt` date DEFAULT NULL COMMENT '의뢰결재요청일자',
  `requ_prv_dthms` datetime DEFAULT NULL COMMENT '의뢰결재일시',
  `requ_prvmn_prv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의뢰결재자결재여부',
  `rcp_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수담당자직원번호',
  `rcp_chrps_offcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수담당자점포코드',
  `rcp_chrps_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수담당자지점기관코드',
  `rcp_retn_rs` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수반려사유',
  `rcp_prv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수결재여부',
  `rcp_prv_reqdt` date DEFAULT NULL COMMENT '접수결재요청일자',
  `bsns_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무담당자직원번호',
  `bsns_chrps_prv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무담당자결재여부',
  `bsns_prvmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무결재자직원번호',
  `bsns_prv_reqdt` date DEFAULT NULL COMMENT '업무결재요청일자',
  `bsns_prv_dthms` datetime DEFAULT NULL COMMENT '업무결재일시',
  `bsns_prvmn_prv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무결재자결재여부',
  `trv_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장담당자직원번호',
  `trv_chrps_prv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장담당자결재여부',
  `trv_prv_dthms` datetime DEFAULT NULL COMMENT '출장결재일시',
  `rcn_hpdt` date DEFAULT NULL COMMENT '실사희망일자',
  `trv_pl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장계획여부',
  `img_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이미지유무',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_rk_nv_00` (`rk_nv_rqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='위험조사';
