--
-- Table structure for table `ins_pln_rcn_adm`
--

DROP TABLE IF EXISTS `ins_pln_rcn_adm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_pln_rcn_adm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호',
  `fnl_nds_seq` decimal(3,0) DEFAULT NULL COMMENT '최종배서회차',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `rcn_rq_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사요청상태코드',
  `fnl_rcn_rst_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종실사결과상태코드',
  `rcn_ccl_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사취소사유코드',
  `et_ccl_rs_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타취소사유내용',
  `rcn_rq_xc_ct` decimal(2,0) DEFAULT NULL COMMENT '실사요청정산건수',
  `rcn_rq_mvo_ct` decimal(2,0) DEFAULT NULL COMMENT '실사요청출동건수',
  `nw_nds_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규배서구분코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `nds_seq` decimal(3,0) DEFAULT NULL COMMENT '배서회차',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `nds_stdt` date DEFAULT NULL COMMENT '배서기준일자',
  `o1_cr_ndscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차자동차배서코드',
  `o2_cr_ndscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차자동차배서코드',
  `rcn_rq_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사요청유형코드',
  `img_file_key` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이미지파일KEY',
  `nrdps_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `ch_rgt_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경등록차량번호',
  `ch_bj_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경대상차량명',
  `relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계코드',
  `dmdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자명',
  `dmd_1_cntad_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자1연락처구분코드',
  `dmd_1_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자1전화지역번호',
  `dmd_1_tlof_no` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자1전화국번호',
  `dmd_1_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자1전화일련번호',
  `dmd_2_cntad_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자2연락처구분코드',
  `dmd_2_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자2전화지역번호',
  `dmd_2_tlof_no` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자2전화국번호',
  `dmd_2_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자2전화일련번호',
  `rcn_plc_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사장소우편번호',
  `rcn_plc_baadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사장소기본주소',
  `rcn_plc_et_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사장소기타주소',
  `rcn_ctn` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사의견',
  `mvo_entnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동업체명',
  `mvo_engnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사명',
  `mvo_engnr_cntad_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사연락처구분코드',
  `mvo_engnr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사전화지역번호',
  `mvo_engnr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사전화국번',
  `mvo_engnr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사전화일련번호',
  `rcpdt` date DEFAULT NULL COMMENT '접수일자',
  `rcp_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수시간',
  `rq_iptdt` date DEFAULT NULL COMMENT '요청입력일자',
  `rq_inp_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청입력시간',
  `fr_rsv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초예약구분코드',
  `fr_rsvdt` date DEFAULT NULL COMMENT '최초예약일자',
  `fr_rsv_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초예약시간',
  `fnl_rsv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종예약구분코드',
  `fnl_ch_rsvdt` date DEFAULT NULL COMMENT '최종변경예약일자',
  `fnl_ch_rsv_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종변경예약시간',
  `mvo_cpldt` date DEFAULT NULL COMMENT '출동완료일자',
  `mvo_cplt_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동완료시간',
  `photo_pht_cpldt` date DEFAULT NULL COMMENT '사진촬영완료일자',
  `photo_pht_cplt_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사진촬영완료시간',
  `rcn_rst_pout_mtt` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사결과특이사항',
  `afc_rcpno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴사접수번호',
  `dh_aregp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지역단기관코드',
  `dh_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지점기관코드',
  `dher_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급자직원번호',
  `dh_usr_no` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급사용인번호',
  `fr_dmd_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초요청자직원번호',
  `rq_mtt_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청사항변경여부',
  `mvo_mtt_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동사항변경여부',
  `apl_ers_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청약삭제여부',
  `pln_rcn_img_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장실사이미지등록여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_pln_rcn_adm_00` (`plno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='현장실사관리';
