--
-- Table structure for table `ins_gren_cr_info`
--

DROP TABLE IF EXISTS `ins_gren_cr_info`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_gren_cr_info` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cr_seqno` decimal(7,0) NOT NULL COMMENT '발생순번',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `cnrdt` date NOT NULL COMMENT '계약일자',
  `dvpns_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원증권번호',
  `cr_dscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차식별번호',
  `trm_sno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기일련번호',
  `trm_autno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기인증번호',
  `istm_cr_rgtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '가입시차량등록지코드',
  `ndtm_cr_rgtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '만기시차량등록지코드',
  `fr_cr_crsdt` date DEFAULT NULL COMMENT '최초차차량등록일자',
  `istm_dabrd_trvl_dst` decimal(10,0) DEFAULT NULL COMMENT '가입시계기판주행거리',
  `ndtm_dabrd_trvl_dst` decimal(10,0) DEFAULT NULL COMMENT '만기시계기판주행거리',
  `st_dst` decimal(10,0) DEFAULT NULL COMMENT '기준거리',
  `obd_dvpns_rgt_dthms` datetime DEFAULT NULL COMMENT 'OBD개발원등록일시',
  `istm_obd_trvl_dst` decimal(10,0) DEFAULT NULL COMMENT '가입시OBD주행거리',
  `ndtm_obd_trvl_dst` decimal(10,0) DEFAULT NULL COMMENT '만기시OBD주행거리',
  `fuel_conqn` decimal(7,0) DEFAULT NULL COMMENT '연료소모량',
  `intrd_dabrd_oper_dst` decimal(10,0) DEFAULT NULL COMMENT '보험기간중계기판운행거리',
  `intrd_obd_oper_dst` decimal(7,0) DEFAULT NULL COMMENT '보험기간중OBD운행거리',
  `suamt_pystd_oper_dst` decimal(10,0) DEFAULT NULL COMMENT '지원금지급기준운행거리',
  `thcp_suamt_pybj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당사지원금지급대상여부',
  `thcp_suamt_nbj_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당사지원금비대상사유코드',
  `logor_suamt_pybj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지자체지원금지급대상여부',
  `logor_suamt_pynbj_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지자체지원금지급비대상사유코드',
  `sht_dst` decimal(7,0) DEFAULT NULL COMMENT '단축거리',
  `suamt` decimal(15,0) DEFAULT NULL COMMENT '지원금액',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `obd_atprd` date NOT NULL COMMENT 'OBD부착기한',
  `obd_tkprd` date DEFAULT NULL COMMENT 'OBD탈착기한',
  `obd_att_dthms` datetime DEFAULT NULL COMMENT 'OBD부착일시',
  `obd_tk_dthms` datetime DEFAULT NULL COMMENT 'OBD탈착일시',
  `obd_att_jnscd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OBD부착가맹점코드',
  `obd_tk_jnscd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OBD탈착가맹점코드',
  `obd_att_mtd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OBD부착방법구분코드',
  `obd_tk_mtd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OBD탈착방법구분코드',
  `obd_chg_dthms` datetime DEFAULT NULL COMMENT 'OBD교체일시',
  `chgtm_dabrd_trvl_dst` decimal(7,2) DEFAULT NULL COMMENT '교체시계기판주행거리',
  `chgtm_obd_trvl_dst` decimal(7,2) DEFAULT NULL COMMENT '교체시OBD주행거리',
  `trt_is_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약가입구분코드',
  `jngnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점명',
  `dmd_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자전화번호',
  `py_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급심사직원번호',
  `py_ud_apdt` date DEFAULT NULL COMMENT '지급심사승인일자',
  `py_prdt` date DEFAULT NULL COMMENT '지급예정일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_gren_cr_info_00` (`plyno`,`cr_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='녹색자동차정보';
