--
-- Table structure for table `ins_smamt_clm_ex`
--

DROP TABLE IF EXISTS `ins_smamt_clm_ex`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_smamt_clm_ex` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `nrdps_ctm_dscno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자고객식별번호',
  `crt_ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자고객식별번호',
  `carno_hngl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호한글',
  `annu1_clmct` decimal(3,0) DEFAULT NULL COMMENT '1년간사고건수',
  `annu3_clmct` decimal(3,0) DEFAULT NULL COMMENT '3년간사고건수',
  `prdm_y1_clmct` decimal(5,0) DEFAULT NULL COMMENT '대물1년사고건수',
  `prdm_y3_clmct` decimal(5,0) DEFAULT NULL COMMENT '대물3년사고건수',
  `prdm_y1_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '대물1년사고점수',
  `prdm_y3_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '대물3년사고점수',
  `prdm_y1_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '대물1년사고금액',
  `prdm_y3_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '대물3년사고금액',
  `bdin_y1_clmct` decimal(5,0) DEFAULT NULL COMMENT '대인1년사고건수',
  `bdin_y3_clmct` decimal(5,0) DEFAULT NULL COMMENT '대인3년사고건수',
  `bdin_y1_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '대인1년사고점수',
  `bdin_y3_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '대인3년사고점수',
  `bdin_y1_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '대인1년사고금액',
  `bdin_y3_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '대인3년사고금액',
  `obi_y1_clmct` decimal(5,0) DEFAULT NULL COMMENT '자손1년사고건수',
  `obi_y3_clmct` decimal(5,0) DEFAULT NULL COMMENT '자손3년사고건수',
  `obi_y1_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '자손1년사고점수',
  `obi_y3_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '자손3년사고점수',
  `obi_y1_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '자손1년사고금액',
  `obi_y3_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '자손3년사고금액',
  `o1_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '1차할인할증요소요율',
  `o2_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '2차할인할증요소요율',
  `o3_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '3차할인할증요소요율',
  `o4_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '4차할인할증요소요율',
  `o5_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '5차할인할증요소요율',
  `o6_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '6차할인할증요소요율',
  `o7_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '7차할인할증요소요율',
  `o8_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '8차할인할증요소요율',
  `o9_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '9차할인할증요소요율',
  `o10_dc_xc_elm_rt` decimal(10,2) DEFAULT NULL COMMENT '10차할인할증요소요율',
  `o1_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차할인할증요소구분코드',
  `o2_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차할인할증요소구분코드',
  `o3_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차할인할증요소구분코드',
  `o4_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4차할인할증요소구분코드',
  `o5_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5차할인할증요소구분코드',
  `o6_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6차할인할증요소구분코드',
  `o7_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7차할인할증요소구분코드',
  `o8_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8차할인할증요소구분코드',
  `o9_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9차할인할증요소구분코드',
  `o10_dc_xc_elm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10차할인할증요소구분코드',
  `smamt_ex_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소액환입구분코드',
  `bfcr_no` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약번호',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `bdin_clm_poct` decimal(5,1) DEFAULT NULL COMMENT '대인사고점수',
  `bdin_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '대인사고금액',
  `obi_clm_poct` decimal(5,1) DEFAULT NULL COMMENT '자손사고점수',
  `obi_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '자손사고금액',
  `prdm_clm_poct` decimal(5,1) DEFAULT NULL COMMENT '대물사고점수',
  `prdm_clm_amt` decimal(15,0) DEFAULT NULL COMMENT '대물사고금액',
  `bfcr_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약할인할증등급코드',
  `bfcr_dc_xc_rt` decimal(5,2) DEFAULT NULL COMMENT '전계약할인할증요율',
  `ex_bf_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입전할인할증등급코드',
  `exaf_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입후할인할증등급코드',
  `ex_bf_dc_xc_rt` decimal(5,2) DEFAULT NULL COMMENT '환입전할인할증요율',
  `exaf_dc_xc_rt` decimal(5,2) DEFAULT NULL COMMENT '환입후할인할증요율',
  `bfcr_y3_clmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약3년사고코드',
  `ex_bf_y3_clmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입전3년사고코드',
  `exaf_y3_clmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입후3년사고코드',
  `bfcr_y3_clm_rt` decimal(5,2) DEFAULT NULL COMMENT '전계약3년사고요율',
  `ex_bf_y3_clm_rt` decimal(5,2) DEFAULT NULL COMMENT '환입전3년사고요율',
  `exaf_y3_clm_rt` decimal(5,2) DEFAULT NULL COMMENT '환입후3년사고요율',
  `bfcr_apprm` decimal(17,2) DEFAULT NULL COMMENT '전계약적용보험료',
  `ex_bf_apprm` decimal(17,2) DEFAULT NULL COMMENT '환입전적용보험료',
  `exaf_apprm` decimal(17,2) DEFAULT NULL COMMENT '환입후적용보험료',
  `bfcr_plno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약설계번호',
  `rnw_plno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신설계번호',
  `o1_clm_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차사고접수번호',
  `o2_clm_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차사고접수번호',
  `o3_clm_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차사고접수번호',
  `o4_clm_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4차사고접수번호',
  `o5_clm_rcpno` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5차사고접수번호',
  `dpdt` date DEFAULT NULL COMMENT '입금일자',
  `cmp_dldt` date DEFAULT NULL COMMENT '보상처리일자',
  `dmamt` decimal(15,0) DEFAULT NULL COMMENT '손해금액',
  `aregp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지역단기관코드',
  `br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지점기관코드',
  `dher_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급자직원번호',
  `cmp_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상담당자직원번호',
  `rv_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납담당자직원번호',
  `iptdt` date DEFAULT NULL COMMENT '입력일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_smamt_clm_ex_00` (`plyno`,`nrdps_ctm_dscno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='소액사고환입';
