--
-- Table structure for table `ins_dherc_sts`
--

DROP TABLE IF EXISTS `ins_dherc_sts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_dherc_sts` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `dher_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급자직원번호',
  `dher_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '취급자구분코드',
  `ins_itm_smccd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험종목소분류코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품코드',
  `ctp_usecd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '차종용도코드',
  `gn_co_obj_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '일반공동물건구분코드',
  `bj_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '대상년월',
  `br_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '지점기관코드',
  `dh_brof_cd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '취급출장소코드',
  `rn_ct` decimal(7,0) DEFAULT NULL COMMENT '원수건수',
  `cn_ct` decimal(9,0) DEFAULT NULL COMMENT '해지건수',
  `incm_ct` decimal(7,0) DEFAULT NULL COMMENT '수입건수',
  `rnwct` decimal(9,0) DEFAULT NULL COMMENT '갱신건수',
  `nwct` decimal(9,0) DEFAULT NULL COMMENT '신규건수',
  `nw_otcm_ct` decimal(9,0) DEFAULT NULL COMMENT '신규타사건수',
  `cr_rnamt` decimal(15,0) DEFAULT NULL COMMENT '자동차원수금액',
  `cn_amt` decimal(15,0) DEFAULT NULL COMMENT '해지금액',
  `inamt` decimal(15,0) DEFAULT NULL COMMENT '수입금액',
  `rnw_amt` decimal(15,0) DEFAULT NULL COMMENT '갱신금액',
  `nw_amt` decimal(15,0) DEFAULT NULL COMMENT '신규금액',
  `nw_otcm_amt` decimal(15,0) DEFAULT NULL COMMENT '신규타사금액',
  `adct` decimal(7,0) DEFAULT NULL COMMENT '추가건수',
  `pypct` decimal(9,0) DEFAULT NULL COMMENT '분납건수',
  `cr_ccl_ct` decimal(9,0) DEFAULT NULL COMMENT '계약취소건수',
  `ptyct` decimal(9,0) DEFAULT NULL COMMENT '추징건수',
  `ad_naamt` decimal(15,0) DEFAULT NULL COMMENT '추가계약금액',
  `pyp_amt` decimal(15,0) DEFAULT NULL COMMENT '분납금액',
  `cr_ccl_amt` decimal(15,0) DEFAULT NULL COMMENT '계약취소금액',
  `cr_ptamt` decimal(15,0) DEFAULT NULL COMMENT '계약추징금액',
  `cn_thcp_dbct` decimal(9,0) DEFAULT NULL COMMENT '해지당사중복건수',
  `cn_otcm_dbct` decimal(9,0) DEFAULT NULL COMMENT '해지타사중복건수',
  `cn_rsr_ct` decimal(9,0) DEFAULT NULL COMMENT '해지말소건수',
  `cn_optn_ct` decimal(9,0) DEFAULT NULL COMMENT '해지임의건수',
  `cn_etct` decimal(9,0) DEFAULT NULL COMMENT '해지기타건수',
  `cn_thcp_db_amt` decimal(15,0) DEFAULT NULL COMMENT '해지당사중복금액',
  `cn_otcm_db_amt` decimal(15,0) DEFAULT NULL COMMENT '해지타사중복금액',
  `cn_rsr_amt` decimal(15,0) DEFAULT NULL COMMENT '해지말소금액',
  `cn_optn_amt` decimal(15,0) DEFAULT NULL COMMENT '해지임의금액',
  `cn_etamt` decimal(15,0) DEFAULT NULL COMMENT '해지기타금액',
  `o1_ppy_tp_ct` decimal(9,0) DEFAULT NULL COMMENT '1차선납유형건수',
  `o2_ppy_tp_ct` decimal(9,0) DEFAULT NULL COMMENT '2차선납유형건수',
  `o3_ppy_tp_ct` decimal(9,0) DEFAULT NULL COMMENT '3차선납유형건수',
  `o4_ppy_tp_ct` decimal(9,0) DEFAULT NULL COMMENT '4차선납유형건수',
  `nxmm_ppy_ct` decimal(9,0) DEFAULT NULL COMMENT '익월선납건수',
  `o1_ppy_tp_amt` decimal(15,0) DEFAULT NULL COMMENT '1차선납유형금액',
  `o2_ppy_tp_amt` decimal(15,0) DEFAULT NULL COMMENT '2차선납유형금액',
  `o3_ppy_tp_amt` decimal(15,0) DEFAULT NULL COMMENT '3차선납유형금액',
  `o4_ppy_tp_amt` decimal(15,0) DEFAULT NULL COMMENT '4차선납유형금액',
  `nxmm_ppamt` decimal(15,0) DEFAULT NULL COMMENT '익월선납금액',
  `cr_saare_ct` decimal(9,0) DEFAULT NULL COMMENT '자동차SA지역건수',
  `cr_a_arect` decimal(10,0) DEFAULT NULL COMMENT '자동차A지역건수',
  `cr_b_arect` decimal(10,0) DEFAULT NULL COMMENT '자동차B지역건수',
  `cr_c_arect` decimal(10,0) DEFAULT NULL COMMENT '자동차C지역건수',
  `cr_d_arect` decimal(9,0) DEFAULT NULL COMMENT '자동차D지역건수',
  `cr_saare_avamt` decimal(15,0) DEFAULT NULL COMMENT '자동차SA지역실적금액',
  `cr_a_are_av` decimal(15,0) DEFAULT NULL COMMENT '자동차A지역실적',
  `cr_b_are_av` decimal(15,0) DEFAULT NULL COMMENT '자동차B지역실적',
  `cr_c_areav` decimal(15,0) DEFAULT NULL COMMENT '자동차C지역실적',
  `cr_dare_avamt` decimal(15,0) DEFAULT NULL COMMENT '자동차D지역실적금액',
  `self_arect` decimal(9,0) DEFAULT NULL COMMENT '자기지역건수',
  `ot_arect` decimal(9,0) DEFAULT NULL COMMENT '타지역건수',
  `self_are_avamt` decimal(15,0) DEFAULT NULL COMMENT '자기지역실적금액',
  `otare_avamt` decimal(15,0) DEFAULT NULL COMMENT '타지역실적금액',
  `wcvis_ct` decimal(9,0) DEFAULT NULL COMMENT '전담보가입건수',
  `same_ct` decimal(9,0) DEFAULT NULL COMMENT '동일건수',
  `bdin1_inct` decimal(9,0) DEFAULT NULL COMMENT '대인1가입건수',
  `bdin2_cvr_inct` decimal(9,0) DEFAULT NULL COMMENT '대인2담보가입건수',
  `prdm_cvr_inct` decimal(9,0) DEFAULT NULL COMMENT '대물담보가입건수',
  `obi_cvr_inct` decimal(9,0) DEFAULT NULL COMMENT '자손담보가입건수',
  `unins_cr_injr_inct` decimal(9,0) DEFAULT NULL COMMENT '무보험차량상해가입건수',
  `owcr_cvr_inct` decimal(9,0) DEFAULT NULL COMMENT '자차담보가입건수',
  `sbinj_inct` decimal(9,0) DEFAULT NULL COMMENT '자상가입건수',
  `plus_owcr_inct` decimal(9,0) DEFAULT NULL COMMENT '플러스자차가입건수',
  `emgmv_tp_1_inct` decimal(9,0) DEFAULT NULL COMMENT '긴급출동유형1가입건수',
  `emgmv_tp_2_inct` decimal(9,0) DEFAULT NULL COMMENT '긴급출동유형2가입건수',
  `etcvr_inct` decimal(9,0) DEFAULT NULL COMMENT '기타담보가입건수',
  `wcvis_amt` decimal(15,0) DEFAULT NULL COMMENT '전담보가입금액',
  `same_amt` decimal(15,0) DEFAULT NULL COMMENT '동일금액',
  `bdin1_isamt` decimal(15,0) DEFAULT NULL COMMENT '대인1가입금액',
  `bdin2_cvr_isamt` decimal(15,0) DEFAULT NULL COMMENT '대인2담보가입금액',
  `prdm_cvr_isamt` decimal(15,0) DEFAULT NULL COMMENT '대물담보가입금액',
  `obi_cvr_isamt` decimal(15,0) DEFAULT NULL COMMENT '자손담보가입금액',
  `unins_cr_injr_isamt` decimal(15,0) DEFAULT NULL COMMENT '무보험차량상해가입금액',
  `owcr_cvr_isamt` decimal(15,0) DEFAULT NULL COMMENT '자차담보가입금액',
  `sbinj_isamt` decimal(15,0) DEFAULT NULL COMMENT '자상가입금액',
  `plus_owcr_isamt` decimal(15,0) DEFAULT NULL COMMENT '플러스자차가입금액',
  `emgmv_tp_1_isamt` decimal(15,0) DEFAULT NULL COMMENT '긴급출동유형1가입금액',
  `emgmv_tp_2_isamt` decimal(15,0) DEFAULT NULL COMMENT '긴급출동유형2가입금액',
  `etcvr_isamt` decimal(15,0) DEFAULT NULL COMMENT '기타담보가입금액',
  `gir_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '지로책임액건수',
  `gir_avct` decimal(9,0) DEFAULT NULL COMMENT '지로실적건수',
  `tf_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '이체책임액건수',
  `tf_avct` decimal(9,0) DEFAULT NULL COMMENT '이체실적건수',
  `drct_cm_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '직접수금책임액건수',
  `drct_cm_avct` decimal(9,0) DEFAULT NULL COMMENT '직접수금실적건수',
  `gir_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '지로책임액보험료',
  `gir_av_prm` decimal(15,0) DEFAULT NULL COMMENT '지로실적보험료',
  `tf_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '이체책임액보험료',
  `tf_av_prm` decimal(15,0) DEFAULT NULL COMMENT '이체실적보험료',
  `drct_cm_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '직접수금책임액보험료',
  `drct_cmav_prm` decimal(15,0) DEFAULT NULL COMMENT '직접수금실적보험료',
  `pyp_gir_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '분납지로책임액건수',
  `pyp_gir_avct` decimal(9,0) DEFAULT NULL COMMENT '분납지로실적건수',
  `pyp_tf_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '분납이체책임액건수',
  `pyp_tf_avct` decimal(9,0) DEFAULT NULL COMMENT '분납이체실적건수',
  `pyp_drct_cm_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '분납직접수금책임액건수',
  `pyp_drct_cm_avct` decimal(9,0) DEFAULT NULL COMMENT '분납직접수금실적건수',
  `pyp_gir_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '분납지로책임액보험료',
  `pyp_gir_av_prm` decimal(15,0) DEFAULT NULL COMMENT '분납지로실적보험료',
  `pyp_tf_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '분납이체책임액보험료',
  `pyp_tf_av_prm` decimal(15,0) DEFAULT NULL COMMENT '분납이체실적보험료',
  `pyp_drct_cm_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '분납직접수금책임액보험료',
  `pyp_drct_cmav_prm` decimal(15,0) DEFAULT NULL COMMENT '분납직접수금실적보험료',
  `rv_bf_gir_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '수납전지로책임액건수',
  `rv_bf_gir_avct` decimal(9,0) DEFAULT NULL COMMENT '수납전지로실적건수',
  `rv_bf_tf_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '수납전이체책임액건수',
  `rv_bf_tf_avct` decimal(9,0) DEFAULT NULL COMMENT '수납전이체실적건수',
  `rv_bf_drct_cm_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '수납전직접수금책임액건수',
  `rv_bf_drct_cm_avct` decimal(9,0) DEFAULT NULL COMMENT '수납전직접수금실적건수',
  `rv_bf_gir_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전지로책임액보험료',
  `rv_bf_gir_av_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전지로실적보험료',
  `rv_bf_tf_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전이체책임액보험료',
  `rv_bf_tf_av_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전이체실적보험료',
  `rv_bf_drct_cm_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전직접수금책임액보험료',
  `rv_bf_drct_cmav_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전직접수금실적보험료',
  `rv_bf_pyp_gir_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '수납전분납지로책임액건수',
  `rv_bf_pyp_gir_avct` decimal(9,0) DEFAULT NULL COMMENT '수납전분납지로실적건수',
  `rv_bf_pyp_tf_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '수납전분납이체책임액건수',
  `rv_bf_pyp_tf_avct` decimal(9,0) DEFAULT NULL COMMENT '수납전분납이체실적건수',
  `rv_bf_pyp_drct_cm_rpamt_ct` decimal(9,0) DEFAULT NULL COMMENT '수납전분납직접수금책임액건수',
  `rv_bf_pyp_drct_cm_avct` decimal(9,0) DEFAULT NULL COMMENT '수납전분납직접수금실적건수',
  `rv_bf_pyp_gir_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전분납지로책임액보험료',
  `rv_bf_pyp_gir_av_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전분납지로실적보험료',
  `rv_bf_pyp_tf_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전분납이체책임액보험료',
  `rv_bf_pyp_tf_av_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전분납이체실적보험료',
  `rv_bf_pyp_drct_cm_rpamt_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전분납직접수금책임액보험료',
  `rv_bf_pyp_drct_cmav_prm` decimal(15,0) DEFAULT NULL COMMENT '수납전분납직접수금실적보험료',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_dherc_sts_00` (`dher_stfno`,`dher_flgcd`,`ins_itm_smccd`,`gdcd`,`ctp_usecd`,`gn_co_obj_flgcd`,`bj_yymm`,`br_orgcd`,`dh_brof_cd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='취급자별통계';
