--
-- Table structure for table `fin_crpca_us_spc`
--

DROP TABLE IF EXISTS `fin_crpca_us_spc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_crpca_us_spc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `crd_apdt` date NOT NULL COMMENT '카드승인일자',
  `crdno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '카드번호',
  `crd_apno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '카드승인번호',
  `ap_seqno` decimal(5,0) NOT NULL COMMENT '승인순번',
  `nml_ccl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL DEFAULT '01' COMMENT '정상취소구분코드',
  `crd_cmpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '카드회사코드',
  `apamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '승인금액',
  `jnsno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점번호',
  `jngnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '가맹점명',
  `jns_tot_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점전체주소',
  `jns_tlno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점전화번호',
  `jns_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점사업자번호',
  `evdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙번호',
  `crd_usamt_pydt` date DEFAULT NULL COMMENT '카드사용금액지급일자',
  `ccldt` date DEFAULT NULL COMMENT '취소일자',
  `crd_ap_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드승인시간',
  `syamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공급가액',
  `axamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부가세액',
  `svcg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '봉사료',
  `andus` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연회비',
  `arrs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연체료',
  `etamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기타금액',
  `ovse_us_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '해외사용여부',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `mcc_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'MCC코드',
  `mcc_cdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'MCC코드명',
  `jns_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점우편번호',
  `jns_pdtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점대표자명',
  `sl_no` varchar(35) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '매출번호',
  `us_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용용도코드',
  `us_rs` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용사유',
  `us_cnf_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용확인직원번호',
  `us_cnf_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용확인기관코드',
  `us_cnfdt` date DEFAULT NULL COMMENT '사용확인일자',
  `ccl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '취소여부',
  `us_spc_inq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용내역조회구분코드',
  `us_spc_inq_bjscd` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용내역조회대상자코드',
  `reqst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청탁여부',
  `bydt` date DEFAULT NULL COMMENT '매입일자',
  `crpca_info_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인카드정보구분코드',
  `bsns_file_key` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무파일KEY',
  `finm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '파일명',
  `erp_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송여부',
  `dcn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확정여부',
  `erp_nots` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP적요',
  `crpca_tlm_seq` decimal(5,0) DEFAULT NULL COMMENT '법인카드전문회차',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_crpca_us_spc_00` (`crd_apdt`,`crdno`,`crd_apno`,`ap_seqno`,`nml_ccl_flgcd`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='법인카드사용내역';
