--
-- Table structure for table `fin_mb_auth_rst_spc_tlm`
--

DROP TABLE IF EXISTS `fin_mb_auth_rst_spc_tlm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_mb_auth_rst_spc_tlm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `tsdt` date NOT NULL COMMENT '전송일자',
  `tlm_ts_hms` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '전문전송시간',
  `trc_no` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '추적번호',
  `lpnt_tlm_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '엘포인트전문구분코드',
  `tlm_anscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전문응답코드',
  `tlm_ans_dtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전문응답상세코드',
  `dat_size_vl` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '데이터크기값',
  `sys_us_vl` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시스템사용값',
  `crdno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드번호',
  `pnt_ctmno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '포인트고객번호',
  `lpnt_ctm_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '엘포인트고객구분코드',
  `lpnt_dl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '엘포인트거래구분코드',
  `lpnt_dl_rscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '엘포인트거래사유코드',
  `coop_jnsno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴가맹점번호',
  `pos_no` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'POS번호',
  `avb_pnt_num` decimal(15,0) NOT NULL COMMENT '가용포인트수',
  `remn_pnt_num` decimal(15,0) NOT NULL COMMENT '잔여포인트수',
  `afc_remn_pnt_num` decimal(15,0) NOT NULL COMMENT '제휴사잔여포인트수',
  `pnt_cu_avyn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '포인트적립가능여부',
  `pnt_us_avyn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '포인트사용가능여부',
  `msg_cn` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지내용',
  `msg_dt_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지상세내용',
  `coop_crd_cdvl` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴카드코드값',
  `fllr_vl` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '필러값',
  `afc_mb_grd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴사회원등급',
  `mbrs_mb_grd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '멤버스회원등급',
  `stf_flg_vl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직원구분값',
  `afc_crp_flg_vl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴사법인구분값',
  `frst_dl_pnt_py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처음거래포인트지급여부',
  `birt_pnt_py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생일포인트지급여부',
  `birt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생일',
  `wdg_mmdy_pnt_py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결혼기념일포인트지급여부',
  `wdg_mmdy` date DEFAULT NULL COMMENT '결혼기념일',
  `cash_rtx_auto_ss_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현금영수증자동발행여부',
  `mbno` bigint(20) unsigned DEFAULT NULL COMMENT '회원번호',
  `mbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회원명',
  `tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화번호',
  `hndph_no` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰번호',
  `ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기본주소',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `afc_lats_deldt` date DEFAULT NULL COMMENT '제휴사최근거래일자',
  `mntr_ofcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주거래점포명',
  `ptcoi_domn_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참여사영역내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_mb_auth_rst_spc_tlm_00` (`tsdt`,`tlm_ts_hms`,`trc_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='회원인증결과내역전문';
