--
-- Table structure for table `fin_imty_wdrc_tlm`
--

DROP TABLE IF EXISTS `fin_imty_wdrc_tlm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_imty_wdrc_tlm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `upls_tlm_tsdt` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '유플러스전문전송일자',
  `upls_tlm_ts_hms` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '유플러스전문전송시간',
  `upls_tmmno` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '유플러스전문번호',
  `upls_tlmcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유플러스전문코드',
  `upls_bsns_flgcd` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '유플러스업무구분코드',
  `mthr_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모계좌번호',
  `scrno` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비밀번호',
  `dbl_pwd` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이중암호',
  `rvbk_tf_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당행이체거래구분코드',
  `tfamt` decimal(15,0) DEFAULT NULL COMMENT '이체금액',
  `tblam_sign` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔액부호',
  `tblam` decimal(18,3) DEFAULT NULL COMMENT '잔액',
  `dl_act_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래계좌은행코드',
  `dl_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래계좌번호',
  `cm` decimal(15,0) DEFAULT NULL COMMENT '수수료',
  `cmscd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'CMS코드',
  `rmtr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금인성명',
  `rvbk_tf_rlnm_no` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당행이체실명번호',
  `pyr_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납부자번호',
  `rvbk_tf_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당행이체고객번호',
  `bk_tmmno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행전문번호',
  `cap_mrk_inr_law_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자본시장통합법적용구분코드',
  `cmnpt_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공통부은행코드',
  `ndvdp_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개별부은행코드',
  `tf_fd_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이체자금종류코드',
  `rvbk_tf_part_wdrc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당행이체부분출금여부',
  `dlamt` decimal(15,0) DEFAULT NULL COMMENT '처리금액',
  `rvbk_tf_ndamt` decimal(15,0) DEFAULT NULL COMMENT '당행이체미처리금액',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납대기번호',
  `ldg_rflt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원장반영상태코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `wdrc_agre_da_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출금동의자료구분코드',
  `wdrc_agre_da_kyvl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출금동의자료키값',
  `dpsr_rlnm_no_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주실명번호종류코드',
  `rq_chn_sys_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청채널시스템구분코드',
  `crt_hp_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자휴대폰전화국번',
  `crt_hp_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자휴대폰전화지역번호',
  `crt_hp_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자휴대폰전화일련번호',
  `chr_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '문자수신여부',
  `chr_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '문자내용',
  `msg_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지전송여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_imty_wdrc_tlm_00` (`upls_tlm_tsdt`,`upls_tlm_ts_hms`,`upls_tmmno`,`upls_tlmcd`,`upls_bsns_flgcd`),
  KEY `idx_fin_imty_wdrc_tlm_01` (`mthr_actno`,`tfamt`),
  KEY `idx_fin_imty_wdrc_tlm_02` (`upls_tmmno`,`upls_tlmcd`,`upls_bsns_flgcd`,`upls_tlm_tsdt`)
) ENGINE=InnoDB AUTO_INCREMENT=52612 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='즉시출금전문';
