--
-- Table structure for table `ccm_idm_cvr`
--

DROP TABLE IF EXISTS `ccm_idm_cvr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_idm_cvr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `idm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '구상접수년월',
  `idm_rcp_sno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '구상접수일련번호',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `idm_cvr_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '구상담보상태코드',
  `idm_wrsps_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '구상전담제여부',
  `idm_cr_prs_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상발생대표유형코드',
  `rltcp_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대방차량번호',
  `rltcp_ins_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대방보험종류코드',
  `rltcp_inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대방보험사코드',
  `imu_stic_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면책부책구분코드',
  `imu_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면책사유코드',
  `rcv_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환수입력유무',
  `xp_fltrt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '예상과실율',
  `dcn_fltrt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '확정과실율',
  `fr_xp_rgt_dthms` datetime DEFAULT NULL COMMENT '최초예상등록일시',
  `fr_idm_cr_dthms` datetime DEFAULT NULL COMMENT '최초구상발생일시',
  `fnl_ers_dthms` datetime DEFAULT NULL COMMENT '최종삭제일시',
  `fnl_rvi_dthms` datetime DEFAULT NULL COMMENT '최종부활일시',
  `xtn_prsc_cpldt` date DEFAULT NULL COMMENT '소멸시효완료일자',
  `end_dthms` datetime DEFAULT NULL COMMENT '종결일시',
  `idm_cvr_end_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상담보종결구분코드',
  `idm_end_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상종결유형코드',
  `abd_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '포기사유코드',
  `md_abd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조정포기구분코드',
  `md_abamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '조정포기금액',
  `end_chrps_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결담당자팀기관코드',
  `end_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결년월',
  `end_sno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결일련번호',
  `end_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결담당자직원번호',
  `de_nm_acq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무명의획득여부',
  `de_nm_acq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무명의획득구분코드',
  `de_nm_acqdt` date DEFAULT NULL COMMENT '채무명의획득일자',
  `idm_av_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상실적팀기관코드',
  `idm_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상담당자직원번호',
  `idm_pl` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상계획',
  `idm_cr_row` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상발생경위',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `prv_rq_ch_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재요청변경사유코드',
  `prv_rq_dt_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재요청상세사유',
  `detc_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사기관명',
  `acdno_crtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호법원코드',
  `sjtdn_amt` decimal(15,0) DEFAULT NULL COMMENT '적발금액',
  `sdpst_acd_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건년도',
  `sdpst_acdno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건번호',
  `crmcs_jstno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사재판번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_idm_cvr_00` (`idm_rcp_yymm`,`idm_rcp_sno`,`clm_cvrcd`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='구상담보';
