--
-- Table structure for table `ccm_idm_prg`
--

DROP TABLE IF EXISTS `ccm_idm_prg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_idm_prg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `idm_prg_sno` decimal(10,0) NOT NULL COMMENT '구상진행일련번호',
  `idm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '구상접수년월',
  `idm_rcp_sno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '구상접수일련번호',
  `cidps_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피구상자서열',
  `idm_prg_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '구상진행구분코드',
  `prg_seq` decimal(5,0) NOT NULL COMMENT '진행회차',
  `mngdt` date NOT NULL COMMENT '조치일자',
  `idm_mngcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상조치코드',
  `mng_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조치내용',
  `acdno_crtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호법원코드',
  `acdno_rcp_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호접수년도',
  `acdno_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호분류코드',
  `acdno_seqno` decimal(7,0) DEFAULT NULL COMMENT '사건번호순번',
  `emamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '청구금액',
  `dsdt` date DEFAULT NULL COMMENT '결정일자',
  `ds_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정구분코드',
  `dsamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '결정금액',
  `dcndt` date DEFAULT NULL COMMENT '확정일자',
  `dcn_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확정담당자직원번호',
  `lgmng_cnc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법적조치해제여부',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '협력업체순번',
  `oord_end_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외주종결구분코드',
  `rq_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '요청원금액',
  `dlay_ntamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지연이자금액',
  `rqamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '의뢰금액합계',
  `enddt` date DEFAULT NULL COMMENT '종결일자',
  `oord_prg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외주진행구분코드',
  `oord_tab_pend_amt` decimal(15,0) DEFAULT NULL COMMENT '외주추심미결금액',
  `oord_requ_dtcn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외주의뢰세부내용',
  `oord_adm_opedt` date DEFAULT NULL COMMENT '외주관리시행일자',
  `lgmng_idm_prg_sno` decimal(10,0) DEFAULT NULL COMMENT '법적조치구상진행일련번호',
  `frc_xc_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '강제집행대상구분코드',
  `rqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '신청금액',
  `sdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '배당금액',
  `oord_requ_idmpg_sno` decimal(10,0) DEFAULT NULL COMMENT '외주의뢰구상진행일련번호',
  `ry_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회수구분코드',
  `ryamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '회수금액',
  `tab_cs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '추심비용',
  `tab_cs_pydt` date DEFAULT NULL COMMENT '추심비용지급일자',
  `de_nm_acq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무명의획득구분코드',
  `de_nm_acqdt` date DEFAULT NULL COMMENT '채무명의획득일자',
  `xtn_prsc_cpldt` date DEFAULT NULL COMMENT '소멸시효완료일자',
  `crmcs_acdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사사건번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_idm_prg_00` (`idm_prg_sno`),
  KEY `idx_ccm_idm_prg_10` (`idm_rcp_sno`,`idm_rcp_yymm`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='구상진행';
