--
-- Table structure for table `ccm_trbl_iq_dm`
--

DROP TABLE IF EXISTS `ccm_trbl_iq_dm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_trbl_iq_dm` (
  `trbl_iq_rcpno` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '분쟁심의접수번호',
  `dm_man_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인회사코드',
  `dm_man_depnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인부서명',
  `dm_man_tmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인팀명',
  `dm_man_chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인담당자명',
  `dm_man_chrps_cntad` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인담당자연락처',
  `dm_man_rcpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인접수번호',
  `dm_man_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구인차량번호',
  `cdm_man_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인회사코드',
  `cdm_man_depnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인부서명',
  `cdm_man_tmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인팀명',
  `cdm_man_chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인담당자명',
  `cdm_man_cntad` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인연락처',
  `cdm_man_rcpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인접수번호',
  `cdm_man_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피청구인차량번호',
  `clm_dthms` datetime DEFAULT NULL COMMENT '사고일시',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `bdin_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인담보가입여부',
  `prdm_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물담보가입여부',
  `owcr_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자차담보가입여부',
  `unins_injr_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무보험상해담보가입여부',
  `sbinj_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자상담보가입여부',
  `et_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타담보가입여부',
  `trbl_flt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁과실여부',
  `trbl_injr_hnd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁상해장애여부',
  `trbl_cvap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁민원여부',
  `trbl_imu_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁면책여부',
  `trbl_et_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁기타여부',
  `cdm_man_rpbl_rt` decimal(3,0) DEFAULT NULL COMMENT '피청구인책임비율',
  `dm_man_emamt` decimal(15,0) DEFAULT NULL COMMENT '청구인청구금액',
  `trbl_iq_dm_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁심의청구상태코드',
  `trbl_iq_rcp_dthms` datetime DEFAULT NULL COMMENT '분쟁심의접수일시',
  `trbl_iq_prg_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁심의진행상태코드',
  `trbl_iq_ch_dthms` datetime DEFAULT NULL COMMENT '분쟁심의변경일시',
  `trbl_iq_chrct_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분쟁심의인물구분코드',
  `same_rcpno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일접수번호',
  `agmt_cmp_ts_dthms` datetime DEFAULT NULL COMMENT '협정회사전송일시',
  `asso_ts_dthms` datetime DEFAULT NULL COMMENT '협회전송일시',
  `dmbil_retn_dthms` datetime DEFAULT NULL COMMENT '청구서반려일시',
  `dmbil_retn_ps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구서반려자명',
  `retn_ps_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반려자구분코드',
  `retn_rs_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반려사유내용',
  `dmbil_wrter_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구서작성자명',
  `dmbil_wrt_dthms` datetime DEFAULT NULL COMMENT '청구서작성일시',
  `dmbil_chps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구서변경자명',
  `dmbil_ch_dthms` datetime DEFAULT NULL COMMENT '청구서변경일시',
  `ch_stdt` date DEFAULT NULL COMMENT '변경기준일자',
  `clm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수년월',
  `clm_rcp_nv_seqno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수조사순번',
  `ds_fdbck_ctn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정피드백의견구분코드',
  `ds_fdbck_ctn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정피드백의견',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`trbl_iq_rcpno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='분쟁심의청구';
