--
-- Table structure for table `lse_gn_ibnr_ba_et`
--

DROP TABLE IF EXISTS `lse_gn_ibnr_ba_et`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_gn_ibnr_ba_et` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `ikdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종코드',
  `ibnr_cc_cyccd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'IBNR산출주기코드',
  `ibnr_cvr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IBNR담보구분코드',
  `no1_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '1번원수경과보험료',
  `no1_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '1번수재경과보험료',
  `no1_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '1번출재경과보험료',
  `no2_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '2번원수경과보험료',
  `no2_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '2번수재경과보험료',
  `no2_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '2번출재경과보험료',
  `no3_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '3번원수경과보험료',
  `no3_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '3번수재경과보험료',
  `no3_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '3번출재경과보험료',
  `no4_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '4번원수경과보험료',
  `no4_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '4번수재경과보험료',
  `no4_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '4번출재경과보험료',
  `no5_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '5번원수경과보험료',
  `no5_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '5번수재경과보험료',
  `no5_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '5번출재경과보험료',
  `no6_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '6번원수경과보험료',
  `no6_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '6번수재경과보험료',
  `no6_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '6번출재경과보험료',
  `no7_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '7번원수경과보험료',
  `no7_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '7번수재경과보험료',
  `no7_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '7번출재경과보험료',
  `no8_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '8번원수경과보험료',
  `no8_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '8번수재경과보험료',
  `no8_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '8번출재경과보험료',
  `no9_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '9번원수경과보험료',
  `no9_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '9번수재경과보험료',
  `no9_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '9번출재경과보험료',
  `no10_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '10번원수경과보험료',
  `no10_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '10번수재경과보험료',
  `no10_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '10번출재경과보험료',
  `no11_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '11번원수경과보험료',
  `no11_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '11번수재경과보험료',
  `no11_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '11번출재경과보험료',
  `no12_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '12번원수경과보험료',
  `no12_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '12번수재경과보험료',
  `no12_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '12번출재경과보험료',
  `no13_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '13번원수경과보험료',
  `no13_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '13번수재경과보험료',
  `no13_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '13번출재경과보험료',
  `no14_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '14번원수경과보험료',
  `no14_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '14번수재경과보험료',
  `no14_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '14번출재경과보험료',
  `no15_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '15번원수경과보험료',
  `no15_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '15번수재경과보험료',
  `no15_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '15번출재경과보험료',
  `no16_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '16번원수경과보험료',
  `no16_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '16번수재경과보험료',
  `no16_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '16번출재경과보험료',
  `no17_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '17번원수경과보험료',
  `no17_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '17번수재경과보험료',
  `no17_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '17번출재경과보험료',
  `no18_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '18번원수경과보험료',
  `no18_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '18번수재경과보험료',
  `no18_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '18번출재경과보험료',
  `no19_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '19번원수경과보험료',
  `no19_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '19번수재경과보험료',
  `no19_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '19번출재경과보험료',
  `no20_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '20번원수경과보험료',
  `no20_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '20번수재경과보험료',
  `no20_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '20번출재경과보험료',
  `no21_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '21번원수경과보험료',
  `no21_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '21번수재경과보험료',
  `no21_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '21번출재경과보험료',
  `no22_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '22번원수경과보험료',
  `no22_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '22번수재경과보험료',
  `no22_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '22번출재경과보험료',
  `no23_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '23번원수경과보험료',
  `no23_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '23번수재경과보험료',
  `no23_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '23번출재경과보험료',
  `no24_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '24번원수경과보험료',
  `no24_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '24번수재경과보험료',
  `no24_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '24번출재경과보험료',
  `no25_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '25번원수경과보험료',
  `no25_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '25번수재경과보험료',
  `no25_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '25번출재경과보험료',
  `no26_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '26번원수경과보험료',
  `no26_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '26번수재경과보험료',
  `no26_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '26번출재경과보험료',
  `no27_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '27번원수경과보험료',
  `no27_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '27번수재경과보험료',
  `no27_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '27번출재경과보험료',
  `no28_rn_rnprm` decimal(17,2) DEFAULT NULL COMMENT '28번원수경과보험료',
  `no28_rtro_rnprm` decimal(17,2) DEFAULT NULL COMMENT '28번수재경과보험료',
  `no28_re_rnprm` decimal(17,2) DEFAULT NULL COMMENT '28번출재경과보험료',
  `idm_bnd_rnamt` decimal(17,2) DEFAULT NULL COMMENT '구상채권원수금액',
  `idm_bnd_rtro_amt` decimal(17,2) DEFAULT NULL COMMENT '구상채권수재금액',
  `idm_bnd_reamt` decimal(17,2) DEFAULT NULL COMMENT '구상채권출재금액',
  `rn_ry_avamt` decimal(17,2) DEFAULT NULL COMMENT '원수회수가능금액',
  `rtro_ry_avamt` decimal(17,2) DEFAULT NULL COMMENT '수재회수가능금액',
  `re_ry_avamt` decimal(17,2) DEFAULT NULL COMMENT '출재회수가능금액',
  `no1_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '1번보유경과손해율',
  `no2_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '2번보유경과손해율',
  `no3_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '3번보유경과손해율',
  `no4_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '4번보유경과손해율',
  `no5_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '5번보유경과손해율',
  `no6_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '6번보유경과손해율',
  `no7_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '7번보유경과손해율',
  `no8_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '8번보유경과손해율',
  `no9_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '9번보유경과손해율',
  `no10_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '10번보유경과손해율',
  `no11_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '11번보유경과손해율',
  `no12_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '12번보유경과손해율',
  `no13_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '13번보유경과손해율',
  `no14_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '14번보유경과손해율',
  `no15_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '15번보유경과손해율',
  `no16_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '16번보유경과손해율',
  `no17_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '17번보유경과손해율',
  `no18_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '18번보유경과손해율',
  `no19_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '19번보유경과손해율',
  `no20_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '20번보유경과손해율',
  `no21_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '21번보유경과손해율',
  `no22_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '22번보유경과손해율',
  `no23_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '23번보유경과손해율',
  `no24_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '24번보유경과손해율',
  `no25_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '25번보유경과손해율',
  `no26_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '26번보유경과손해율',
  `no27_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '27번보유경과손해율',
  `no28_ps_rnd_dmgrt` decimal(17,2) DEFAULT NULL COMMENT '28번보유경과손해율',
  `rtro_krre_rpr_amt` decimal(17,2) DEFAULT NULL COMMENT '수재코리안리통보금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_gn_ibnr_ba_et_00` (`cls_yymm`,`ikdcd`,`ibnr_cc_cyccd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='일반IBNR기초기타';
