--
-- Table structure for table `lse_gn_ibnr_acm_dvcf_avg`
--

DROP TABLE IF EXISTS `lse_gn_ibnr_acm_dvcf_avg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_gn_ibnr_acm_dvcf_avg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `ibnr_cvr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'IBNR담보구분코드',
  `ibnr_cc_cyccd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'IBNR산출주기코드',
  `ibnr_cls_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'IBNR마감구분코드',
  `cls_dvlp_yyodr_num` decimal(3,0) NOT NULL COMMENT '마감진전년차수',
  `ibnr_avg_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'IBNR평균구분코드',
  `dvcf_pldm_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수PLDM원수평균율',
  `dvcf_ildm_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수ILDM원수평균율',
  `dvcf_bfmpl_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수BFMPL원수평균율',
  `dvcf_bfmil_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수BFMIL원수평균율',
  `dvcf_pldm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수PLDM수재평균율',
  `dvcf_ildm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수ILDM수재평균율',
  `dvcf_bfmpl_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수BFMPL수재평균율',
  `dvcf_bfmil_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수BFMIL수재평균율',
  `dvcf_pldm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수PLDM출재평균율',
  `dvcf_ildm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수ILDM출재평균율',
  `dvcf_bfmpl_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수BFMPL출재평균율',
  `dvcf_bfmil_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '진전계수BFMIL출재평균율',
  `ifcf_pldm_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수PLDM원수평균율',
  `ifcf_ildm_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수ILDM원수평균율',
  `ifcf_bfmpl_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수BFMPL원수평균율',
  `ifcf_bfmil_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수BFMIL원수평균율',
  `ifcf_pldm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수PLDM수재평균율',
  `ifcf_ildm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수ILDM수재평균율',
  `ifcf_bfmpl_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수BFMPL수재평균율',
  `ifcf_bfmil_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수BFMIL수재평균율',
  `ifcf_pldm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수PLDM출재평균율',
  `ifcf_ildm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수ILDM출재평균율',
  `ifcf_bfmpl_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수BFMPL출재평균율',
  `ifcf_bfmil_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '추정계수BFMIL출재평균율',
  `lclmxcp_dvcf_pldm_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수PLDM평균율',
  `lclmxcp_dvcf_ildm_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수ILDM평균율',
  `lclmxcp_dvcf_bfmpl_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수BFMPL평균율',
  `lclmxcp_dvcf_bfmil_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수BFMIL평균율',
  `lclmxcp_dvcf_pldm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수PLDM수재평균율',
  `lclmxcp_dvcf_ildm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수ILDM수재평균율',
  `lclmxcp_dvcf_bfmpl_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수BFMPL수재평균율',
  `lclmxcp_dvcf_bfmil_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수BFMIL수재평균율',
  `lclmxcp_dvcf_pldm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수PLDM출재평균율',
  `lclmxcp_dvcf_ildm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수ILDM출재평균율',
  `lclmxcp_dvcf_bfmpl_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수BFMPL출재평균율',
  `lclmxcp_dvcf_bfmil_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외진전계수BFMIL출재평균율',
  `lclmxcp_ifcf_pldm_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수PLDM원수평균율',
  `lclmxcp_ifcf_ildm_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수ILDM원수평균율',
  `lclmxcp_ifcf_bfmpl_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수BFMPL원수평균율',
  `lclmxcp_ifcf_bfmil_rn_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수BFMIL원수평균율',
  `lclmxcp_ifcf_pldm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수PLDM수재평균율',
  `lclmxcp_ifcf_ildm_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수ILDM수재평균율',
  `lclmxcp_ifcf_bfmpl_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수BFMPL수재평균율',
  `lclmxcp_ifcf_bfmil_rtro_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수BFMIL수재평균율',
  `lclmxcp_ifcf_pldm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수PLDM출재평균율',
  `lclmxcp_ifcf_ildm_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수ILDM출재평균율',
  `lclmxcp_ifcf_bfmpl_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수BFMPL출재평균율',
  `lclmxcp_ifcf_bfmil_re_avrt` decimal(15,10) DEFAULT NULL COMMENT '대사고제외추정계수BFMIL출재평균율',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_gn_ibnr_acm_dvcf_avg_00` (`cls_yymm`,`ibnr_cvr_flgcd`,`ibnr_cc_cyccd`,`ibnr_cls_flgcd`,`cls_dvlp_yyodr_num`,`ibnr_avg_flgcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='일반IBNR누적진전계수평균';
