--
-- Table structure for table `ins_cvr_incm_prm_diss`
--

DROP TABLE IF EXISTS `ins_cvr_incm_prm_diss`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_cvr_incm_prm_diss` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) NOT NULL COMMENT '수입보험료발생순번',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `cvr_prm_diss_seqno` decimal(5,0) NOT NULL COMMENT '담보보험료분해순번',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `rp_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '영수보험료',
  `pr_bzcs_ppdt` date DEFAULT NULL COMMENT '예정사업비계상일자',
  `cvr_st_stmcv_seq` decimal(5,0) DEFAULT NULL COMMENT '담보시기기준월납환산회차',
  `isamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액',
  `rk_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '위험보험료',
  `rvi_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부활이자',
  `sv_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '저축보험료',
  `cn_prm` decimal(17,2) DEFAULT NULL COMMENT '해지보험료',
  `nprmt_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '순보험료식신계약비',
  `ppy_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선납보험료',
  `nelp_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '미경과보험료',
  `rnd_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '경과보험료',
  `rnd_yyct` decimal(5,0) DEFAULT NULL COMMENT '경과년수',
  `rnd_mc` decimal(5,0) DEFAULT NULL COMMENT '경과월수',
  `cnclb_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '해약식신계약비',
  `rpttp_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보고식신계약비',
  `bcpay_mncs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '완납전유지비',
  `acpay_mncs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '완납후유지비',
  `cmlcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '수금비',
  `gn_nrpym_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보장미상각신계약비',
  `gn_cnclb_sv_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보장해약식저축보험료',
  `gn_pr_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보장예정신계약비',
  `cu_nrpym_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립미상각신계약비',
  `cu_cnclb_sv_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립해약식저축보험료',
  `cu_pr_nwcrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립예정신계약비',
  `accbt_tfdt` date DEFAULT NULL COMMENT '계정간이체일자',
  `tf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이체여부',
  `tf_wrkdt` date NOT NULL COMMENT '이체작업일자',
  `rn_diss_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원수분해구분코드',
  `rn_diss_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원수분해세부구분코드',
  `tf_dlay_nt_stdt` date DEFAULT NULL COMMENT '이체지연이자기준일자',
  `tf_dlay_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '이체지연이자',
  `pr_bzcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '예정사업비',
  `pr_prf` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '예정이윤',
  `cvr_inprm_diss_bjpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '담보수입보험료분해대상코드',
  `prm_diss_ppdt` date DEFAULT NULL COMMENT '보험료분해계상일자',
  `pr_bzcs_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예정사업비대상여부',
  `ltrm_diss_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기분해대상여부',
  `pr_bzcs_dscno` varchar(14) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예정사업비식별번호',
  `oldpr_bzcs_dscno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구예정사업비식별번호',
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마감년월',
  `relpc_seqno` decimal(10,0) DEFAULT NULL COMMENT '관계자순번',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `pr_dm_nvcs` decimal(15,0) DEFAULT '0' COMMENT '예정손해조사비',
  `anul_bzprm_cmp_nwcrt` decimal(15,0) DEFAULT '0' COMMENT '매년영업보험료대비신계약비',
  `sustd_rp_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체영수보험료',
  `sustd_rk_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체위험보험료',
  `sustd_rvi_nt` decimal(15,0) DEFAULT NULL COMMENT '표준하체부활이자',
  `sustd_sv_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체저축보험료',
  `sustd_cn_prm` decimal(17,2) DEFAULT NULL COMMENT '표준하체해지보험료',
  `sustd_nprmt_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '표준하체순보험료식신계약비',
  `sustd_ppy_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체선납보험료',
  `sustd_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체미경과보험료',
  `sustd_rnd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체경과보험료',
  `sustd_cnclb_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '표준하체해약식신계약비',
  `sustd_rpttp_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '표준하체보고식신계약비',
  `sustd_bcpay_mncs` decimal(15,0) DEFAULT NULL COMMENT '표준하체완납전유지비',
  `sustd_acpay_mncs` decimal(15,0) DEFAULT NULL COMMENT '표준하체완납후유지비',
  `sustd_cmlcs` decimal(15,0) DEFAULT NULL COMMENT '표준하체수금비',
  `sustd_gn_nrpym_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '표준하체보장미상각신계약비',
  `sustd_gncnl_sv_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체보장해약식저축보험료',
  `sustd_gn_pr_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '표준하체보장예정신계약비',
  `sustd_pr_dm_nvcs` decimal(15,0) DEFAULT NULL COMMENT '표준하체예정손해조사비',
  `sustd_anbzp_cmp_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '표준하체매년영업보험료대비신계약비',
  `rfd_dscno` varchar(14) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '준비금식별번호',
  `sustd_rfd_dscno` varchar(14) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준하체준비금식별번호',
  `sustd_pr_bzcs_dscno` varchar(14) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준하체예정사업비식별번호',
  `std_netp_sv_prm` decimal(15,0) DEFAULT NULL COMMENT '표준순보식저축보험료',
  `nexca_prm` decimal(15,0) DEFAULT NULL COMMENT '미정산보험료',
  `retr_cls_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소급마감년월',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_cvr_incm_prm_diss_00` (`plyno`,`incm_prm_cr_seqno`,`cvrcd`,`cvr_seqno`,`cvr_prm_diss_seqno`,`tf_wrkdt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='담보수입보험료분해';
