--
-- Table structure for table `ins_whpy_bj`
--

DROP TABLE IF EXISTS `ins_whpy_bj`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_whpy_bj` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `py_bjno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급대상번호',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `py_cr_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생유형코드',
  `cc_stdt` date DEFAULT NULL COMMENT '산출기준일자',
  `rtamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '환급금액',
  `py_av_lmamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급가능한도금액',
  `pmamt_smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기지급중도금액감액환급금액합계액',
  `py_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급이자',
  `ccl_wdr_reqdt` date DEFAULT NULL COMMENT '취소철회요청일자',
  `py_rs_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급사유원인코드',
  `py_rs_lclcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급사유대분류코드',
  `py_rs_mdccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급사유중분류코드',
  `py_rs_smccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급사유소분류코드',
  `py_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급사유',
  `ex_rcv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입환수구분코드',
  `ac_dmcy_dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경리휴면처리여부',
  `ac_dmcy_dldt` date DEFAULT NULL COMMENT '경리휴면처리일자',
  `whpy_diss_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제지급분해대상여부',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `whpy_diss_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제지급분해여부',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '수입보험료발생순번',
  `ex_orpy_bjno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입원지급대상번호',
  `pyno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급번호',
  `whpy_rqdt` date DEFAULT NULL COMMENT '제지급신청일자',
  `ssno` decimal(5,0) DEFAULT NULL COMMENT '발행번호',
  `ss_dtno` decimal(3,0) DEFAULT NULL COMMENT '발행세부번호',
  `lnno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출번호',
  `samt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인지대',
  `clln_auto_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약대자동승인구분코드',
  `clln_udwr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약대심사자직원번호',
  `clln_ud_rst_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약대심사결과상태코드',
  `clln_udwdt` date DEFAULT NULL COMMENT '약대심사일자',
  `cr_stdt` date DEFAULT NULL COMMENT '발생기준일자',
  `rtamt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환급금유형코드',
  `rvi_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '부활발생순번',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관코드',
  `br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지점기관코드',
  `pybf_cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급전계약상태코드',
  `pybf_cr_dt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급전계약세부상태코드',
  `cu_cvr_endt` date DEFAULT NULL COMMENT '적립담보만기일자',
  `cfgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해약구분코드',
  `rnd_yyct` decimal(5,0) DEFAULT NULL COMMENT '경과년수',
  `rnd_mc` decimal(5,0) DEFAULT NULL COMMENT '경과월수',
  `nelp_yyct` decimal(5,0) DEFAULT NULL COMMENT '미경과년수',
  `nelp_mc` decimal(5,0) DEFAULT NULL COMMENT '미경과월수',
  `ap_dhtm_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용분법코드',
  `ba_gn_rnd_rfamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기본보장경과준비금액',
  `cu_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립원금',
  `cu_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립이자',
  `cu_part_nwcrt_dpcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립부분신계약비상각비',
  `ba_rnd_rfamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기본경과준비금액',
  `trt_gn_rnd_rfamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '특약보장경과준비금액',
  `gn_nelp_rfamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보장미경과준비금액',
  `ppy_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선납보험료',
  `ppy_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선납이자',
  `cv_cn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전환해약여부',
  `cr_befo_fnorg_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약이전금융기관사업자번호',
  `cr_befo_fn_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약이전금융기관명',
  `cr_dv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약배당구분코드',
  `ad_an_ypamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '가산연금연액',
  `nocr_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '미발생지급금액',
  `anrrf_stdt` date DEFAULT NULL COMMENT '연금개시책임준비금액기준일자',
  `anrrf_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연금개시책임준비금액원금',
  `anrrf_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연금개시책임준비금액이자',
  `anrrf_dchg_rato_cfc` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '연금개시책임준비금액부리이율계수',
  `an_pyaf_rpbl_rfamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '연금지급후책임준비금액',
  `an_yyodr` decimal(3,0) DEFAULT NULL COMMENT '연금년차',
  `an_mgnf_sm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '연금배율합계',
  `ayamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연금연액',
  `an_sep_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연금분할지급액',
  `an_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연금구분코드',
  `relpc_seqno` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '관계자순번',
  `ystr_rfamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '연시준비금액',
  `clln_ud_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약대심사대상구분코드',
  `cu_cvr_ins_st` date DEFAULT NULL COMMENT '적립담보보험시기',
  `gn_nelp_mnt_rfamt` decimal(15,0) DEFAULT '0' COMMENT '보장미경과개월준비금액',
  `gn_nelp_mitrm_rfamt` decimal(15,0) DEFAULT '0' COMMENT '보장미경과월기간내준비금액',
  `rk_prm` decimal(15,0) DEFAULT '0' COMMENT '위험보험료',
  `embr_nrdps_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '태아피보험자성별코드',
  `mw_py_af_rrfnd` decimal(15,0) DEFAULT '0' COMMENT '중도지급후책임준비금액',
  `mw_opn_rrfnd_pcamt` decimal(15,0) DEFAULT '0' COMMENT '중도개시책임준비금원금',
  `rcpdt` date DEFAULT NULL COMMENT '접수일자',
  `fire_lbtrs_cn_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화재배상책임해지사유코드',
  `ex_rcv_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입환수사유코드',
  `an_rc_rckdt` date DEFAULT NULL COMMENT '연금수령기산일자',
  `an_rc_yyodr` decimal(3,0) DEFAULT NULL COMMENT '연금수령년차',
  `an_rc_lmamt` decimal(17,2) DEFAULT NULL COMMENT '연금수령한도금액',
  `an_act_vlamt` decimal(17,2) DEFAULT NULL COMMENT '연금계좌평가금액',
  `remn_tx_xcamt` decimal(15,0) DEFAULT NULL COMMENT '잔여과세제외금액',
  `dedt` date DEFAULT NULL COMMENT '사망일자',
  `ply_rcdt` date DEFAULT NULL COMMENT '증권수령일자',
  `ntdtd_icamt_ayamt` decimal(15,0) DEFAULT NULL COMMENT '이자율차증액연금연액',
  `rkrtd_icamt_ayamt` decimal(15,0) DEFAULT NULL COMMENT '위험율차증액연금연액',
  `bzcsd_icamt_ayamt` decimal(15,0) DEFAULT NULL COMMENT '사업비차증액연금연액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_whpy_bj_00` (`py_bjno`),
  KEY `idx_ins_whpy_bj_10` (`plyno`),
  KEY `idx_ins_whpy_bj_11` (`ex_orpy_bjno`),
  KEY `idx_ins_whpy_bj_13` (`pyno`),
  KEY `idx_ins_whpy_bj_12` (`whpy_rqdt`,`ssno`,`ss_dtno`)
) ENGINE=InnoDB AUTO_INCREMENT=1055 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='제지급대상';
/*!40101 SET character_set_client = @saved_cs_client */;
