--
-- Table structure for table `ins_incm_prm`
--

DROP TABLE IF EXISTS `ins_incm_prm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_incm_prm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) NOT NULL COMMENT '수입보험료발생순번',
  `pym_seq` decimal(5,0) NOT NULL COMMENT '납입회차',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `fnl_pym_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종납입년월',
  `pyp_t_seq` decimal(5,0) DEFAULT NULL COMMENT '분납총회차',
  `rp_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '영수보험료',
  `ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '적용보험료',
  `dp_cascd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '입금원인코드',
  `dp_dt_cascd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '입금세부원인코드',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납대기번호',
  `ccldt` date DEFAULT NULL COMMENT '취소일자',
  `ccl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소구분코드',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급직원번호',
  `usrno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용인번호',
  `rp_admno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수관리번호',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `fc_ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '외화적용보험료',
  `usd_cv_ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '미화환산적용보험료',
  `xcrt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환율구분코드',
  `fc_ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '외화적용환율',
  `usd_ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '미화적용환율',
  `fc_condt_t_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '외화공동인수총보험료',
  `condt_t_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동인수총보험료',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `otcm_mg_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사간사회사코드',
  `cnn_incm_prmcr_seqno` decimal(5,0) DEFAULT NULL COMMENT '관련수입보험료발생순번',
  `hscs_hs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가계비가계구분코드',
  `pyp_ad_cs` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '분납추가비용',
  `ba_cvr_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기본담보보험료',
  `trt_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '특약보험료',
  `cu_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립보험료',
  `flpy_cvr_trt_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '일시납담보특약보험료',
  `dcbf_cu_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '할인전적립보험료',
  `cu_nprm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립순보험료',
  `ppy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선납여부',
  `ppy_dc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선납할인여부',
  `nwfsq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신초차구분코드',
  `auto_tf_dc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동이체할인여부',
  `rvi_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부활이자',
  `du_ar_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '응당연체구분코드',
  `prm_diss_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료분해여부',
  `cvr_prm_disbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보보험료분해대상여부',
  `dcbf_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '할인전보험료',
  `sb_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대체구분코드',
  `onds_dp_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구배서입금유형코드',
  `rtn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환급구분코드',
  `prm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료구분코드',
  `prm_efct_nddt` date DEFAULT NULL COMMENT '보험료효력종료일자',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `bk_brcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행지점코드',
  `bk_extn_qfp` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행유자격자',
  `bk_ipps` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행입력자',
  `bnc_admr` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카관리자',
  `pym_dudt` date DEFAULT NULL COMMENT '납입응당일자',
  `dbl_paym_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이중불입여부',
  `ac_tf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경리이체여부',
  `uc_prm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미수보험료여부',
  `co_crt_rv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동계약자수납구분코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `ccl_wdr_rtn_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '취소철회환급이자',
  `payao_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '즉시불여부',
  `amt_ndscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금액배서코드',
  `crt_relpc_seqno` decimal(10,0) DEFAULT NULL COMMENT '계약자관계자순번',
  `tincm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '집계수입보험료발생순번',
  `pyno_whpy_bjno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급번호제지급대상번호',
  `co_crt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동계약자여부',
  `cu_st_rpdt` date DEFAULT NULL COMMENT '적립기준영수일자',
  `self_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기계약여부',
  `rdch_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '승환계약여부',
  `rv_dldt` date DEFAULT NULL COMMENT '수납처리일자',
  `logor_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지자체유형코드',
  `adpym_belo_mw_wlamt` decimal(15,0) DEFAULT NULL COMMENT '추가납입이하중도인출금액',
  `pf_prm` decimal(15,0) DEFAULT NULL COMMENT '우대보험료',
  `np_acc_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미지급계정원장번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_incm_prm_00` (`plyno`,`incm_prm_cr_seqno`),
  KEY `idx_ins_incm_prm_08` (`dh_stfno`,`ppdt`,`ikd_grpcd`),
  KEY `idx_ins_incm_prm_01` (`rp_admno`,`dp_cascd`,`ikd_grpcd`,`ccldt`,`cnn_incm_prmcr_seqno`,`pym_seq`,`sb_flgcd`),
  KEY `idx_ins_incm_prm_11` (`usrno`,`ikd_grpcd`,`ppdt`,`rv_dldt`),
  KEY `idx_ins_incm_prm_06` (`rv_sbno`),
  KEY `idx_ins_incm_prm_07` (`ikd_grpcd`,`ppdt`,`udrtk_tycd`,`sb_flgcd`,`plyno`,`incm_prm_cr_seqno`),
  KEY `idx_ins_incm_prm_10` (`pyno_whpy_bjno`)
) ENGINE=InnoDB AUTO_INCREMENT=32029 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='수입보험료';
