--
-- Table structure for table `ins_prm_pym_pr`
--

DROP TABLE IF EXISTS `ins_prm_pym_pr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_prm_pym_pr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `pym_seq` decimal(5,0) NOT NULL COMMENT '납입회차',
  `crt_relpc_seqno` decimal(10,0) NOT NULL COMMENT '계약자관계자순번',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `ap_nddt` date NOT NULL COMMENT '적용종료일자',
  `ap_strdt` date NOT NULL COMMENT '적용시작일자',
  `ndsno` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '배서번호',
  `vald_nds_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '유효배서여부',
  `nds_ap_str_dthms` datetime NOT NULL COMMENT '배서승인시작일시',
  `nds_ap_nd_dthms` datetime NOT NULL COMMENT '배서승인종료일시',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `ba_cvr_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기본담보보험료',
  `trt_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '특약보험료',
  `cu_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립보험료',
  `flpy_cvr_trt_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '일시납담보특약보험료',
  `dcbf_cu_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '할인전적립보험료',
  `dcbf_flpy_cvrtr_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '할인전일시납담보특약보험료',
  `t1_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '1회보험료',
  `cumny_sb_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립금대체보험료',
  `ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '적용보험료',
  `dcbf_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '할인전보험료',
  `woncr_cv_ap_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산적용보험료',
  `condt_t_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동인수총보험료',
  `woncv_condt_t_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산공동인수총보험료',
  `thcpq_ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '당사분적용보험료',
  `thcpq_woncv_ap_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '당사분원화환산적용보험료',
  `nds_ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '배서적용보험료',
  `woncv_nds_ap_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산배서적용보험료',
  `pym_prdt` date DEFAULT NULL COMMENT '납입예정일자',
  `dcndt` date DEFAULT NULL COMMENT '확정일자',
  `hg_pym_perd` date DEFAULT NULL COMMENT '최고납입기한',
  `pyp_rt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '분납비율',
  `incm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '수입보험료발생순번',
  `prm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료구분코드',
  `nds_prm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서보험료여부',
  `xwpy_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '과오납금액',
  `pym_pr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입예정상태코드',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `cu_nprm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립순보험료',
  `prm_dcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보험료할인금액',
  `xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '환율',
  `dmpdt` date DEFAULT NULL COMMENT '최고일자',
  `npy_cnldt` date DEFAULT NULL COMMENT '미납해지일자',
  `wrdmp_snddt` date DEFAULT NULL COMMENT '최고문발송일자',
  `pf_prm` decimal(15,0) DEFAULT NULL COMMENT '우대보험료',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_prm_pym_pr_00` (`plyno`,`pym_seq`,`crt_relpc_seqno`,`mncd`,`ap_nddt`,`ap_strdt`,`ndsno`)
) ENGINE=InnoDB AUTO_INCREMENT=155766 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='보험료납입예정';
