--
-- Table structure for table `ins_ps_cst`
--

DROP TABLE IF EXISTS `ins_ps_cst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_ps_cst` (
  `ps_cstno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보유품의번호',
  `plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설계번호',
  `cgaf_ch_seqno` decimal(5,0) DEFAULT NULL COMMENT '발행후변경순번',
  `rk_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험유형코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `rt_aqr_rqno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율구득신청번호',
  `rk_nv_xec_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험조사실시여부',
  `rk_nv_admno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험조사관리번호',
  `cr_et_mtt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약기타사항',
  `rkgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험군코드',
  `rk_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험급수코드',
  `st_psamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기준보유금액',
  `vl_mx_dmgrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '평가최대손해율',
  `vl_mx_dmgcc_bsc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가최대손해율산출근거',
  `bfyy_psrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '전년보유율',
  `bfyy_psamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전년보유금액',
  `fprm_re_flgcd_1` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확보출재구분코드1',
  `fprm_re_flgcd_2` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확보출재구분코드2',
  `fprm_rert` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '확보출재율',
  `optn_re_cmrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '임의출재수수료율',
  `ps_et_mtt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보유기타사항',
  `st_psrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '기준보유율',
  `tsi_st_psamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT 'TSI기준보유금액',
  `risk_st_psamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT 'RISK기준보유금액',
  `cst_rqdt` date DEFAULT NULL COMMENT '품의신청일자',
  `prv_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재상태코드',
  `op_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OP계약여부',
  `cst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '품의구분코드',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `mg_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간사회사코드',
  `ps_cst_lvlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보유품의레벨코드',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `vsl_or_aipnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선박/항공기명',
  `vstp` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선종',
  `pp_1` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선급1',
  `pp_2` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선급2',
  `ntl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국적',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `csrdt` date DEFAULT NULL COMMENT '건조일자',
  `ttnct` decimal(13,2) DEFAULT NULL COMMENT '총톤수',
  `dwcpt_wght_tonno` decimal(10,2) DEFAULT NULL COMMENT '재화중량톤수',
  `ins_cnd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험조건',
  `dcamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제액화폐코드',
  `uiamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '공제금액',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `cst_cpldt` date DEFAULT NULL COMMENT '품의완료일자',
  `nxt_prvmn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '다음결재자직원번호',
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마감년월',
  `ps_rq_ad_xpnm` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보유요청추가설명',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`ps_cstno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='보유품의';
