--
-- Table structure for table `fin_et_rv_sb`
--

DROP TABLE IF EXISTS `fin_et_rv_sb`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_et_rv_sb` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '수납대기번호',
  `cr_syscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '발생시스템코드',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형2차분류코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급직원번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `rpdt` date DEFAULT NULL COMMENT '영수일자',
  `slpdt` date DEFAULT NULL COMMENT '전표일자',
  `slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표번호',
  `slp_lnno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표라인번호',
  `rvdt` date DEFAULT NULL COMMENT '수납일자',
  `rv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납기관코드',
  `rv_xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납정산번호',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `invln_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '투융자상품코드',
  `lnno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출번호',
  `tot_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '집계구분코드',
  `totct` decimal(7,0) DEFAULT NULL COMMENT '집계건수',
  `ln_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대출원금',
  `ln_ntamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대출이자금액',
  `ersta_rf_cm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '조기상환수수료',
  `spcl_bnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '특수채권금액',
  `lawlg_mng_cs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '법적조치비용',
  `fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '펀드코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `aseno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산번호',
  `ase_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산유형코드',
  `les_guamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대보증금액',
  `rent` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대료',
  `fxamt_admcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '정액관리비',
  `rxamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실비금액',
  `elnt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전기료',
  `wtrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '수도료',
  `pp_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선급금액',
  `rent_ar_nt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대료연체이자',
  `pkfe` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주차료',
  `plc_rntcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장소대관료',
  `cm_rnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '통신유보금액',
  `axamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부가세액',
  `syamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공급가액',
  `evd_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙종류코드',
  `sl_evdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '매출증빙번호',
  `uc_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미수발생여부',
  `acc_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정원장번호',
  `ase_cqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자산취득금액',
  `ase_ioamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자산매각금액',
  `rdt_dp_acamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '감가상각누계금액',
  `ad_rdt_dpamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '추가감가상각금액',
  `sramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '잔존가액',
  `dpsl_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '처분손이익금액',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기준년월',
  `dl_seqno` decimal(5,0) DEFAULT NULL COMMENT '처리순번',
  `deldt` date DEFAULT NULL COMMENT '거래일자',
  `cls_da_dl_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마감자료처리상태코드',
  `bzwpl_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업장사업자번호',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_et_rv_sb_00` (`rv_sbno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='기타수납대기';
