--
-- Table structure for table `fin_acc_ldg`
--

DROP TABLE IF EXISTS `fin_acc_ldg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_acc_ldg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `acc_ldgno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '계정원장번호',
  `acc_ldg_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '계정원장유형코드',
  `ntacc_cd` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '계정과목코드',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '회계기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `crdt` date DEFAULT NULL COMMENT '발생일자',
  `cr_fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '발생외화금액',
  `cr_woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '발생원화금액',
  `crnt_fc_tblam` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '현재외화잔액',
  `crnt_woncr_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '현재원화잔액',
  `fnl_rmdt` date DEFAULT NULL COMMENT '최종반제일자',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `dltfp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대처구분코드',
  `dltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대처코드',
  `vlbe_woncr_poamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '평가전원화계상금액',
  `vlbe_woncr_pvl_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '평가전원화계상잔액',
  `vlbe_ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '평가전적용환율',
  `ldg_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원장종류코드',
  `cr_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발생원장번호',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형2차분류코드',
  `rv_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납가능여부',
  `cnd_rv_apdt` date DEFAULT NULL COMMENT '조건수납승인일자',
  `cnd_rv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조건수납직원번호',
  `clg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결산여부',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `invln_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '투융자상품코드',
  `bsns_cnnno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무관련번호구분코드',
  `bsns_cnnno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무관련번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `rpdt` date DEFAULT NULL COMMENT '영수일자',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `dp_mnt` decimal(3,0) DEFAULT NULL COMMENT '상각개월',
  `dprnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금자명',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주명',
  `rm_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '반제상태코드',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납대기번호',
  `da_cr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자료발생구분코드',
  `acc_ldg_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정원장상태코드',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `crt_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자주민번호',
  `dl_hms` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래시각',
  `rv_py_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT '11' COMMENT '수납지급상태코드',
  `rv_py_psbdt` date DEFAULT NULL COMMENT '수납지급가능일자',
  `bnc_tot_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카집계구분코드',
  `lnwcr_rv_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기신계약수납가능여부',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `amg_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가상계좌번호',
  `fr_cr_ldg_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초발생원장종류코드',
  `fr_cr_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초발생원장번호',
  `erp_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송여부',
  `erp_tsdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송일자',
  `rtman_note_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금금권처리구분코드',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_acc_ldg_00` (`acc_ldgno`),
  KEY `idx_fin_acc_ldg_02` (`ntacc_cd`,`acc_ldg_stcd`,`crdt`,`act_orgcd`,`rm_stcd`),
  KEY `idx_fin_acc_ldg_10` (`cr_ldgno`),
  KEY `idx_fin_acc_ldg_11` (`bsns_cnnno`,`bsns_cnnno_flgcd`),
  KEY `idx_fin_acc_ldg_12` (`amg_actno`,`crdt`)
) ENGINE=InnoDB AUTO_INCREMENT=30758 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계정원장';
