--
-- Table structure for table `fin_ntacc`
--

DROP TABLE IF EXISTS `fin_ntacc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_ntacc` (
  `ntacc_cd` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '계정과목코드',
  `befo_ntacc_cd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이전계정과목코드',
  `vald_nddt` date NOT NULL DEFAULT '9999-12-31' COMMENT '유효종료일자',
  `vald_strdt` date NOT NULL COMMENT '유효시작일자',
  `acc_usecd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '계정용도코드',
  `ntacc_nm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '계정과목명',
  `ntacc_xpnm` varchar(500) COLLATE utf8mb4_bin NOT NULL COMMENT '계정과목설명',
  `acc_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '계정분류코드',
  `ntacc_lvlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정과목레벨코드',
  `ppr_ntacc_cd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위계정과목코드',
  `us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용여부',
  `ntacc_act_atrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정과목회계속성코드',
  `ifrs_badbt_adm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IFRS대손관리여부',
  `dm_ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해보험회사코드',
  `ifrs17_dv_bjyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IFRS17배분대상여부',
  `ifrs17_act_py_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IFRS17회계지급구분코드',
  `ifrs17_acc_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IFRS17계정군코드',
  `avtb_bzcs_itcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실적표사업비항목코드',
  `bdg_acc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예산계정여부',
  `dbcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차대구분코드',
  `adm_ldg_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리원장종류코드',
  `hdcft_slp_inpps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수기전표입력가능여부',
  `br_org_inpps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지점기관입력가능여부',
  `tot_acc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '집계계정여부',
  `ikd_grpcd_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드입력여부',
  `ins_imcd_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드입력여부',
  `rr_org_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속기관입력여부',
  `dltfp_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대처입력여부',
  `dltfp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대처구분코드',
  `tblam_adm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔액관리여부',
  `bzcs_dv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업비배분여부',
  `admno_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리번호입력여부',
  `lq_adm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산관리여부',
  `lq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산구분코드',
  `badbt_adm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대손관리여부',
  `badbt_stf_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대손상계계정과목코드',
  `part_rm_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부반제가능여부',
  `wcom_rtx_prmbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사내영수증허용대상여부',
  `dp_org_rr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발의기관귀속여부',
  `rrav_bzcs_o1_dvcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속가능사업비1차배분코드',
  `rrav_bzcs_o2_dvcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속가능사업비2차배분코드',
  `rrimp_bzcs_o1_dvcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속불가능사업비1차배분코드',
  `rrimp_bzcs_o2_dvcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속불가능사업비2차배분코드',
  `bzcs_tp_sbrst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업비유형부점기준여부',
  `rlt_ntacc_cd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상대계정과목코드',
  `dporg_rr_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발의기관귀속유형코드',
  `bdg_ctl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예산통제구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`ntacc_cd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계정과목';
