--
-- Table structure for table `fin_evd`
--

DROP TABLE IF EXISTS `fin_evd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_evd` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `evdno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '증빙번호',
  `evddt` date NOT NULL COMMENT '증빙일자',
  `evd_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '증빙종류코드',
  `pypl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처구분코드',
  `pypl_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처대상구분코드',
  `pylno` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처번호',
  `pylnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처명',
  `pypl_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처은행코드',
  `pypl_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처계좌번호',
  `pypl_dpsr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처예금주',
  `py_prdt` date DEFAULT NULL COMMENT '지급예정일자',
  `pydt` date DEFAULT NULL COMMENT '지급일자',
  `dlplc_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래처구분코드',
  `dlpno` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처번호',
  `dlpnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '거래처명',
  `evd_buy` decimal(5,0) DEFAULT NULL COMMENT '증빙매수',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화금액',
  `fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '외화금액',
  `syamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공급가액',
  `axamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부가세액',
  `etamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기타금액',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `dc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제유형코드',
  `dcrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '공제율',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형2차분류코드',
  `evd_spc_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙내역상세코드',
  `bzwpl_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업장사업자번호',
  `hqbld_rgtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사옥등록코드',
  `trste_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수탁자식별번호',
  `crd_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드회사코드',
  `crdno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드번호',
  `crd_apno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드승인번호',
  `crd_ownr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드소유자직원번호',
  `rl_us_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사용직원번호',
  `stmdy_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결제일코드',
  `rr_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속년월',
  `bj_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대상기관코드',
  `pymdt` date DEFAULT NULL COMMENT '납부일자',
  `pym_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납부은행코드',
  `gir_pymno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지로납부번호',
  `ic_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득구분코드',
  `ic_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득상세구분코드',
  `et_ic_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타소득유형코드',
  `bzic_bn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업소득업종구분코드',
  `rsd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거주구분코드',
  `bj_strdt` date DEFAULT NULL COMMENT '대상시작일자',
  `bj_nddt` date DEFAULT NULL COMMENT '대상종료일자',
  `need_bg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '필요경비',
  `ic_txrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '소득세율',
  `ic_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '소득세액',
  `rs_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주민세액',
  `fnf_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '농특세액',
  `crp_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '법인세액',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `shdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주주번호',
  `fn_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융상품코드',
  `rlnm_dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실명거래여부',
  `tx_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과세구분코드',
  `rcp_diay_inp_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '접대일지입력여부',
  `rcppc_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처식별번호',
  `rcppc_conm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처상호명',
  `rcppc_depnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처부서명',
  `rcppc_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처성명',
  `rcp_oj` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대목적',
  `rcp_et_mtt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대기타사항',
  `rcp_plc_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대장소사업자번호',
  `rcp_plc_conm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대장소상호명',
  `ap_retn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인반려구분코드',
  `dldt` date DEFAULT NULL COMMENT '처리일자',
  `dl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리기관코드',
  `dl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리직원번호',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `evd_ap_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙승인대상여부',
  `tmp_acc_ar_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가계정정리여부',
  `evd_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '증빙상태코드',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `inp_scr_id` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '입력화면ID',
  `rr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속기관코드',
  `nml_ccl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정상취소구분코드',
  `py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '지급여부',
  `elec_tx_bll_apno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전자세금계산서승인번호',
  `rstm_py_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산지급구분코드',
  `dlplc_bj_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처대상직원번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_evd_00` (`evdno`),
  KEY `idx_fin_evd_10` (`py_crno`),
  KEY `idx_fin_evd_11` (`crd_apno`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='증빙';
