--
-- Table structure for table `fin_crd_ldg`
--

DROP TABLE IF EXISTS `fin_crd_ldg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_crd_ldg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `crd_ldgno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '카드원장번호',
  `crd_apdt` date NOT NULL COMMENT '카드승인일자',
  `crd_apno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '카드승인번호',
  `crd_cmpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '카드회사코드',
  `crdno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `rs_bzmno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주민사업자번호',
  `owrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자명',
  `vald_trm` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유효기간',
  `at_mnt` decimal(3,0) NOT NULL COMMENT '할부개월',
  `crd_apamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '카드승인금액',
  `jnsno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '가맹점번호',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회계기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `crd_ap_metd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드승인방식구분코드',
  `crd_ownr_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드소유주관계코드',
  `vnccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'VAN사코드',
  `crd_rt_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드반송사유코드',
  `crd_ccl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드취소구분코드',
  `relps_evd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계인증빙구분코드',
  `ap_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인기관코드',
  `ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인직원번호',
  `apdt` date DEFAULT NULL COMMENT '승인일자',
  `ccl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소기관코드',
  `ccl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소직원번호',
  `ccldt` date DEFAULT NULL COMMENT '취소일자',
  `rv_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '수납가능여부',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `dmdt` date DEFAULT NULL COMMENT '청구일자',
  `afdm_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '후청구대상여부',
  `rpbl_opndt` date DEFAULT NULL COMMENT '책임개시일자',
  `stmdt` date DEFAULT NULL COMMENT '결제일자',
  `ovcrd_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전카드원장번호',
  `crd_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드상태코드',
  `rm_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반제상태코드',
  `crd_md_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드조정구분코드',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `bnc_tot_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카집계구분코드',
  `dm_prdt` date DEFAULT NULL COMMENT '청구예정일자',
  `org_dlno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원거래번호',
  `spdlg_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문거래시간',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `epay_auth_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '페이인증구분코드',
  `pay_prv_rq_id` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'PAY결재요청ID',
  `mbrs_ctmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '멤버스고객번호',
  `jns_dlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점거래번호',
  `fn_cmp_dl_auth_vl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융회사거래인증값',
  `fn_cmp_dl_auth_2_vl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융회사거래인증2값',
  `fn_cmp_dl_auth_3_vl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융회사거래인증3값',
  `fn_cmp_dl_auth_4_vl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융회사거래인증4값',
  `fn_cmp_dl_auth_5_vl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융회사거래인증5값',
  `ap_autno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인인증번호',
  `binno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'BIN번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_crd_ldg_00` (`crd_ldgno`)
) ENGINE=InnoDB AUTO_INCREMENT=226 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='카드원장';
