--
-- Table structure for table `fin_py_xc`
--

DROP TABLE IF EXISTS `fin_py_xc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_py_xc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `pydt` date NOT NULL COMMENT '지급일자',
  `py_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '지급기관코드',
  `py_xcno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '지급정산번호',
  `py_act_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '지급회계기관코드',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형2차분류코드',
  `py_mtdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급방법코드',
  `py_dl_o1_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처리1차구분코드',
  `py_dl_o2_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처리2차구분코드',
  `self_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본인여부',
  `rcr_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수령자주민번호',
  `rcr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수령자명',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `py_smct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '지급합계건수',
  `py_woncr_smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급원화합계금액',
  `py_fc_smamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급외화합계금액',
  `fx_pldoq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외환차손익구분코드',
  `fx_pqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '외환차손익금액',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `dfpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금상대처코드',
  `py_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급상태코드',
  `py_slpdt` date DEFAULT NULL COMMENT '지급전표일자',
  `py_slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급전표번호',
  `inp_scr_id` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력화면ID',
  `ccldt` date DEFAULT NULL COMMENT '취소일자',
  `ccl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소직원번호',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `vnccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'VAN사코드',
  `mtact_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모계좌은행코드',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `tlm_pno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문고유번호',
  `msg_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지ID',
  `msg_tp_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지유형분류코드',
  `upls_tlm_tsdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유플러스전문전송일자',
  `upls_tlm_ts_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유플러스전문전송시간',
  `upls_tmmno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유플러스전문번호',
  `upls_tlmcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유플러스전문코드',
  `upls_bsns_flgcd` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유플러스업무구분코드',
  `imty_tf_er_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '즉시이체오류구분코드',
  `acct_spcft` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통장명기',
  `pynct_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급금권유형코드',
  `acc_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정원장번호',
  `chk_dscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수표식별번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_py_xc_00` (`pydt`,`py_orgcd`,`py_xcno`)
) ENGINE=InnoDB AUTO_INCREMENT=926 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='지급정산';
