--
-- Table structure for table `fin_whtx_inr`
--

DROP TABLE IF EXISTS `fin_whtx_inr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_whtx_inr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rr_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '귀속년월',
  `spc_sno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '내역일련번호',
  `cr_syscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '발생시스템코드',
  `ic_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '소득구분코드',
  `ic_dt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '소득상세구분코드',
  `orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '기관코드',
  `pydt` date NOT NULL COMMENT '지급일자',
  `pyamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급금액',
  `need_bg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '필요경비',
  `icamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '소득금액',
  `txrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '세율',
  `ic_ds_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '소득결정세액',
  `rs_ds_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주민결정세액',
  `crp_ds_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '법인결정세액',
  `fnf_ds_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '농특결정세액',
  `ic_pvpy_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '소득기납부세액',
  `rs_pvpy_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주민기납부세액',
  `crp_pvpy_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '법인기납부세액',
  `fnf_pvpy_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '농특기납부세액',
  `ic_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '소득세액',
  `rs_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주민세액',
  `crp_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '법인세액',
  `fnf_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '농특세액',
  `ad_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '가산세액',
  `dlplc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처구분코드',
  `dlplc_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처식별번호',
  `stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직원번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `icrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득자명',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `bzwpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업장명',
  `rsd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거주구분코드',
  `rgfrg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '내외국인구분코드',
  `rsdpl_ntncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거주지국가코드',
  `bzic_bn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업소득업종구분코드',
  `et_ic_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타소득유형코드',
  `ic_rr_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득귀속년월',
  `bj_strdt` date DEFAULT NULL COMMENT '대상시작일자',
  `bj_nddt` date DEFAULT NULL COMMENT '대상종료일자',
  `nt_ic_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이자소득구분코드',
  `fn_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융상품코드',
  `rlnm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실명구분코드',
  `tx_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과세구분코드',
  `bnd_nt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권이자구분코드',
  `scr_ply_stdcd` varchar(12) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유가증권표준코드',
  `icr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득자구분코드',
  `chc_da_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변동자료구분코드',
  `ntrdt` date DEFAULT NULL COMMENT '입사일자',
  `retdt` date DEFAULT NULL COMMENT '퇴사일자',
  `lsev_mntct` decimal(3,0) DEFAULT '0' COMMENT '근속개월수',
  `mw_ret_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도퇴사여부',
  `bj_psct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '대상인원수',
  `tx_bj_psct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '과세대상인원수',
  `slr_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '급여지급금액',
  `bn_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '상여지급금액',
  `aw_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '수당지급금액',
  `ic_rramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '소득귀속금액',
  `frtx_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '비과세금액',
  `ic_smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '소득합계금액',
  `tx_bj_ic_smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '과세대상소득합계금액',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `evdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙번호',
  `da_cr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자료발생구분코드',
  `mdf_rpr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '수정신고여부',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `dh_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급회사코드',
  `tx_crfw_bjyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과세이연대상여부',
  `et_ic_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타소득구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_whtx_inr_00` (`rr_yymm`,`spc_sno`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='원천세통합';
