--
-- Table structure for table `fin_lq_ldg`
--

DROP TABLE IF EXISTS `fin_lq_ldg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_lq_ldg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `ppdt` date NOT NULL COMMENT '계상일자',
  `lq_ldgno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '청산원장번호',
  `ntacc_cd` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '계정과목코드',
  `lq_dltcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청산상대처코드',
  `lq_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청산구분코드',
  `dbcr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '차대구분코드',
  `cr_syscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '발생시스템코드',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형2차분류코드',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '회계기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `acc_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '계정분류코드',
  `lq_pr_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '청산예정년월',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `fc_poamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '외화계상금액',
  `woncr_poamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화계상금액',
  `crnt_fc_pvl_tblam` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '현재외화계상잔액',
  `crnt_woncr_pvl_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '현재원화계상잔액',
  `xcrt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환율구분코드',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `re_rtro_bsnno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재업무번호구분코드',
  `re_rtro_bsnno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재업무번호',
  `rertr_dt_bsnno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재세부업무번호구분코드',
  `re_rtro_dt_bsnno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재세부업무번호',
  `rtro_crano` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수재계약번호',
  `lq_dotno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산일계번호',
  `diamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차액구분코드',
  `diamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '차액금액',
  `re_rtro_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재구분코드',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국내외구분코드',
  `trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약구분코드',
  `ltrm_pend_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '장기미결여부',
  `payao_py_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '즉시불지급여부',
  `da_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료발생구분코드',
  `lq_bj_st_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산대상상태분류코드',
  `lq_bj_st_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산대상상태상세코드',
  `brk_rincd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브로커재보험자코드',
  `vlbe_woncr_poamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '평가전원화계상금액',
  `vlbe_woncr_pvl_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '평가전원화계상잔액',
  `vlbe_ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '평가전적용환율',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `clm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수조사순번',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납대기번호',
  `acc_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정원장번호',
  `rvdt` date DEFAULT NULL COMMENT '수납일자',
  `rv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납기관코드',
  `rv_xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납정산번호',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `bll_stmdt` date DEFAULT NULL COMMENT '어음결제일자',
  `mg_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간사회사코드',
  `incm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '수입보험료발생순번',
  `pyno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급번호',
  `qtrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '지분율',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `otcm_plyno` varchar(25) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사증권번호',
  `condt_t_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동인수총보험료',
  `co_udrtk_t_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동인수총보험금액',
  `lq_dsdt` date DEFAULT NULL COMMENT '청산지정일자',
  `lq_asmt_seqno` decimal(5,0) DEFAULT NULL COMMENT '청산지정순번',
  `lq_asmt_fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '청산지정외화금액',
  `lq_asmt_woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '청산지정원화금액',
  `asmt_ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '지정적용환율',
  `asmt_xcrt_apdt` date DEFAULT NULL COMMENT '지정환율적용일자',
  `asmt_xcrt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지정환율유형코드',
  `fx_pldoq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외환차손익구분코드',
  `fx_pqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '외환차손익금액',
  `asmt_nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지정적요사항',
  `lqdt` date DEFAULT NULL COMMENT '청산일자',
  `lq_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산기관코드',
  `lq_xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산정산번호',
  `lq_info_cr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청산정보발생구분코드',
  `lq_dl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청산처리구분코드',
  `rm_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '반제상태코드',
  `jonl_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '분개여부',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `inp_scr_id` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력화면ID',
  `slpdt` date DEFAULT NULL COMMENT '전표일자',
  `slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표번호',
  `slp_lnno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표라인번호',
  `fnl_rmdt` date DEFAULT NULL COMMENT '최종반제일자',
  `dh_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급회사코드',
  `rinsc_lq_dano` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재보사청산자료번호',
  `lq_asmt_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산지정번호',
  `lq_asmt_rqudt` date DEFAULT NULL COMMENT '청산지정의뢰일자',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `erp_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`,`ppdt`),
  KEY `idx_fin_lq_ldg_01` (`ppdt`,`lq_ldgno`),
  KEY `idx_fin_lq_ldg_10` (`lq_dsdt`,`lq_asmt_seqno`),
  KEY `idx_fin_lq_ldg_11` (`lq_ldgno`),
  KEY `idx_fin_lq_ldg_12` (`lq_asmt_no`,`lq_dltcd`)
) ENGINE=InnoDB AUTO_INCREMENT=54286 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='청산원장'
