--
-- Table structure for table `fin_dp_ldg`
--

DROP TABLE IF EXISTS `fin_dp_ldg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_dp_ldg` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `dp_ldgno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '예금원장번호',
  `dfpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '예금상대처코드',
  `deldt` date NOT NULL COMMENT '거래일자',
  `dl_hms` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래시각',
  `dp_ordr` decimal(7,0) NOT NULL COMMENT '예금순차',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '회계기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `dl_woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '거래원화금액',
  `dlaf_woncr_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '거래후원화잔액',
  `dl_fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '거래외화금액',
  `dlaf_fc_tblam` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '거래후외화잔액',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `mv_avg_cc_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '이동평균산출환율',
  `dp_wdrc_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '입금출금구분코드',
  `nml_ccl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '정상취소구분코드',
  `brald_ccl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취대취소여부',
  `dp_tp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금유형구분코드',
  `dp_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금상세구분코드',
  `dprnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금자명',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `bk_offcd_info` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행점포코드정보',
  `ctm_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객계좌번호',
  `rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주민번호',
  `chkno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수표번호',
  `dp_cr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '예금발생구분코드',
  `rm_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '반제여부',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형2차분류코드',
  `xcdt` date DEFAULT NULL COMMENT '정산일자',
  `xc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정산기관코드',
  `xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정산번호',
  `dsodt` date DEFAULT NULL COMMENT '발의일자',
  `bdg_dpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예산발의번호',
  `tlm_pno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문고유번호',
  `rm_slpdt` date DEFAULT NULL COMMENT '반제전표일자',
  `rm_slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반제전표번호',
  `rm_slp_lnno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반제전표라인번호',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `lq_dltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산상대처코드',
  `bk_orgnl_dl_tmmno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행원래거래전문번호',
  `rtman_note_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금금권처리구분코드',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_dp_ldg_00` (`dp_ldgno`),
  KEY `idx_fin_dp_ldg_12` (`tlm_pno`),
  KEY `idx_fin_dp_ldg_10` (`dfpcd`,`deldt`),
  KEY `idx_fin_dp_ldg_11` (`dh_stfno`,`deldt`),
  KEY `idx_fin_dp_ldg_13` (`rsno`)
) ENGINE=InnoDB AUTO_INCREMENT=26895 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='예금원장';
