--
-- Table structure for table `fin_py_st_ch_crr`
--

DROP TABLE IF EXISTS `fin_py_st_ch_crr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_py_st_ch_crr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `py_stno` varchar(15) COLLATE utf8mb4_bin NOT NULL COMMENT '지급정지번호',
  `ch_seqno` decimal(5,0) NOT NULL COMMENT '변경순번',
  `pypl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처구분코드',
  `py_st_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급정지구분코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형2차분류코드',
  `py_st_rcpdt` date DEFAULT NULL COMMENT '지급정지접수일자',
  `rgtdt` date NOT NULL COMMENT '등록일자',
  `deb_dscno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '채무자식별번호',
  `debnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '채무자명',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기본주소',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `bndps_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자식별번호',
  `bndnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자명',
  `bndps_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자우편번호',
  `bnd_self_org_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자기본주소',
  `bndps_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자상세주소',
  `bndps_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자전화지역번호',
  `bndps_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자전화국번',
  `bndps_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권자전화일련번호',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `tf_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이체계좌번호',
  `dpsr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주',
  `py_st_rqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급정지요청금액',
  `py_st_rq_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급정지요청잔액',
  `py_st_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정지사유코드',
  `bll_ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '어음원장번호',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `cnc_rgt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해제등록기관코드',
  `cnc_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해제등록직원번호',
  `cncdt` date DEFAULT NULL COMMENT '해제일자',
  `cnc_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해제사유',
  `py_st_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급정지상태코드',
  `pyst_dl_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정지처리업무구분코드',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `pyrs_bj_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급보류대상업무구분코드',
  `ap_scl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용범위구분코드',
  `sz_dcuno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '압류문서번호',
  `acdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호',
  `sz_dt` date DEFAULT NULL COMMENT '압류일자',
  `sz_org_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '압류기관구분코드',
  `sz_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '압류기관명',
  `rcp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수기관코드',
  `rcp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수직원번호',
  `rcpdt` date DEFAULT NULL COMMENT '접수일자',
  `ds_crtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정법원명',
  `tab_orddt` date DEFAULT NULL COMMENT '추심명령일자',
  `whol_orddt` date DEFAULT NULL COMMENT '전부명령일자',
  `whol_ord_efct_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전부명령효력여부',
  `ds_crt_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정법원우편번호',
  `ds_crt_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정법원기본주소',
  `ds_crt_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결정법원상세주소',
  `rgsno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '등기번호',
  `cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약여부',
  `scan_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '스캔여부',
  `stmt_ocnt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진술최고서여부',
  `anpe_dm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타인청구여부',
  `sz_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '압류사유코드',
  `pyst_cnc_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정지해제사유코드',
  `cnc_rcpdt` date DEFAULT NULL COMMENT '해제접수일자',
  `img_file_key` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이미지파일KEY',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_py_st_ch_crr_00` (`py_stno`,`ch_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='지급정지변경이력';
