--
-- Table structure for table `fin_fc_rm_rq`
--

DROP TABLE IF EXISTS `fin_fc_rm_rq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_fc_rm_rq` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rm_rqno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '송금신청번호',
  `fc_rm_rq_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '외화송금신청구분코드',
  `ref_no` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고번호',
  `rm_mtdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '송금방법코드',
  `rtpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인명',
  `rcpnt_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인주소',
  `rcpnt_ntl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '수취인국적구분코드',
  `rcpnt_ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인국적코드',
  `rcpnt_ntl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인국적명',
  `ovse_rqapl_rel_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '해외신청인관계구분코드',
  `ovse_rqapl_rel_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외신청인관계내용',
  `paym_bk_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '수취은행구분코드',
  `paym_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취은행코드',
  `paym_bknm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취은행명',
  `swf_cd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SWIFT코드',
  `paym_bk_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취은행주소',
  `rcpnt_ovse_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인해외계좌번호',
  `rm_pst_bknm_1` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금경유은행명1',
  `rm_pst_bknm_2` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금경유은행명2',
  `rm_pst_bknm_3` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금경유은행명3',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `fc_rm_amt` decimal(18,3) NOT NULL COMMENT '외화송금금액',
  `ovse_py_rs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급사유구분코드',
  `ovse_py_rs_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급사유내용',
  `osea_cm_chrg_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '국외수수료부담구분코드',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `rm_dl_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '송금처리상태코드',
  `slpdt` date DEFAULT NULL COMMENT '전표일자',
  `slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표번호',
  `fc_rm_img_bsnno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외화송금이미지업무번호',
  `rm_reqdt` date DEFAULT NULL COMMENT '송금요청일자',
  `rm_rq_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금요청기관코드',
  `rm_rq_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금요청직원번호',
  `rppsc_ap_reqdt` date DEFAULT NULL COMMENT '책임자승인요청일자',
  `rppsc_ap_rq_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임자승인요청기관코드',
  `rppsc_ap_rq_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임자승인요청직원번호',
  `rm_prvdt` date DEFAULT NULL COMMENT '송금결재일자',
  `rm_prv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금결재기관코드',
  `rm_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금결재직원번호',
  `rm_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금번호',
  `wdrc_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출금은행코드',
  `wdrc_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출금계좌번호',
  `dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주명',
  `rcpnt_fprt_ordr_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수취인앞지시사항',
  `msg_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지ID',
  `msg_tp_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지유형분류코드',
  `tlm_tsdt` date DEFAULT NULL COMMENT '전문전송일자',
  `tlm_pno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문고유번호',
  `tlm_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문종별코드',
  `spbz_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문업무구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_fc_rm_rq_00` (`rm_rqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='외화송금신청';
