--
-- Table structure for table `fin_act_cls_cfc_vrf`
--

DROP TABLE IF EXISTS `fin_act_cls_cfc_vrf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_act_cls_cfc_vrf` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `clsdt` date NOT NULL COMMENT '마감일자',
  `bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '업무구분코드',
  `cnn_tabnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '관련테이블명',
  `cnn_clmnm` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '관련컬럼명',
  `sno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '일련번호',
  `no1_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번항목명',
  `no2_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번항목명',
  `no3_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번항목명',
  `no4_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번항목명',
  `no5_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번항목명',
  `no6_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번항목명',
  `no7_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번항목명',
  `no8_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번항목명',
  `no9_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번항목명',
  `no10_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번항목명',
  `no11_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '11번항목명',
  `no12_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '12번항목명',
  `no13_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '13번항목명',
  `no14_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '14번항목명',
  `no15_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '15번항목명',
  `no16_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '16번항목명',
  `no17_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '17번항목명',
  `no18_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '18번항목명',
  `no19_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '19번항목명',
  `no20_itnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '20번항목명',
  `no1_amt` decimal(15,0) DEFAULT NULL COMMENT '1번금액',
  `no2_amt` decimal(15,0) DEFAULT NULL COMMENT '2번금액',
  `no3_amt` decimal(15,0) DEFAULT NULL COMMENT '3번금액',
  `no4_amt` decimal(15,0) DEFAULT NULL COMMENT '4번금액',
  `no5_amt` decimal(15,0) DEFAULT NULL COMMENT '5번금액',
  `no6_amt` decimal(15,0) DEFAULT NULL COMMENT '6번금액',
  `no7_amt` decimal(15,0) DEFAULT NULL COMMENT '7번금액',
  `no8_amt` decimal(15,0) DEFAULT NULL COMMENT '8번금액',
  `no9_amt` decimal(15,0) DEFAULT NULL COMMENT '9번금액',
  `no10_amt` decimal(15,0) DEFAULT NULL COMMENT '10번금액',
  `no11_amt` decimal(15,0) DEFAULT NULL COMMENT '11번금액',
  `no12_amt` decimal(15,0) DEFAULT NULL COMMENT '12번금액',
  `no13_amt` decimal(15,0) DEFAULT NULL COMMENT '13번금액',
  `no14_amt` decimal(15,0) DEFAULT NULL COMMENT '14번금액',
  `no15_amt` decimal(15,0) DEFAULT NULL COMMENT '15번금액',
  `no16_amt` decimal(15,0) DEFAULT NULL COMMENT '16번금액',
  `no17_amt` decimal(15,0) DEFAULT NULL COMMENT '17번금액',
  `no18_amt` decimal(15,0) DEFAULT NULL COMMENT '18번금액',
  `no19_amt` decimal(15,0) DEFAULT NULL COMMENT '19번금액',
  `no20_amt` decimal(15,0) DEFAULT NULL COMMENT '20번금액',
  `no21_amt` decimal(15,0) DEFAULT NULL COMMENT '21번금액',
  `no22_amt` decimal(15,0) DEFAULT NULL COMMENT '22번금액',
  `no23_amt` decimal(15,0) DEFAULT NULL COMMENT '23번금액',
  `no24_amt` decimal(15,0) DEFAULT NULL COMMENT '24번금액',
  `no25_amt` decimal(15,0) DEFAULT NULL COMMENT '25번금액',
  `no26_amt` decimal(15,0) DEFAULT NULL COMMENT '26번금액',
  `no27_amt` decimal(15,0) DEFAULT NULL COMMENT '27번금액',
  `no28_amt` decimal(15,0) DEFAULT NULL COMMENT '28번금액',
  `no29_amt` decimal(15,0) DEFAULT NULL COMMENT '29번금액',
  `no30_amt` decimal(15,0) DEFAULT NULL COMMENT '30번금액',
  `no31_amt` decimal(15,0) DEFAULT NULL COMMENT '31번금액',
  `no32_amt` decimal(15,0) DEFAULT NULL COMMENT '32번금액',
  `no33_amt` decimal(15,0) DEFAULT NULL COMMENT '33번금액',
  `no34_amt` decimal(15,0) DEFAULT NULL COMMENT '34번금액',
  `no35_amt` decimal(15,0) DEFAULT NULL COMMENT '35번금액',
  `no36_amt` decimal(15,0) DEFAULT NULL COMMENT '36번금액',
  `no37_amt` decimal(15,0) DEFAULT NULL COMMENT '37번금액',
  `no38_amt` decimal(15,0) DEFAULT NULL COMMENT '38번금액',
  `no39_amt` decimal(15,0) DEFAULT NULL COMMENT '39번금액',
  `no40_amt` decimal(15,0) DEFAULT NULL COMMENT '40번금액',
  `no41_amt` decimal(15,0) DEFAULT NULL COMMENT '41번금액',
  `no42_amt` decimal(15,0) DEFAULT NULL COMMENT '42번금액',
  `no43_amt` decimal(15,0) DEFAULT NULL COMMENT '43번금액',
  `no44_amt` decimal(15,0) DEFAULT NULL COMMENT '44번금액',
  `no45_amt` decimal(15,0) DEFAULT NULL COMMENT '45번금액',
  `no46_amt` decimal(15,0) DEFAULT NULL COMMENT '46번금액',
  `no47_amt` decimal(15,0) DEFAULT NULL COMMENT '47번금액',
  `no48_amt` decimal(15,0) DEFAULT NULL COMMENT '48번금액',
  `no49_amt` decimal(15,0) DEFAULT NULL COMMENT '49번금액',
  `no50_amt` decimal(15,0) DEFAULT NULL COMMENT '50번금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`cls_yymm`,`clsdt`,`bsns_flgcd`,`cnn_tabnm`,`cnn_clmnm`,`sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='회계마감계수검증';
