--
-- Table structure for table `fin_py_cr`
--

DROP TABLE IF EXISTS `fin_py_cr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_py_cr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `py_crno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '지급발생번호',
  `ldg_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원장종류코드',
  `ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원장번호',
  `crdt` date NOT NULL COMMENT '발생일자',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '회계기관코드',
  `rqog_cd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '요청기관코드',
  `rqfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '요청직원번호',
  `cr_syscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '발생시스템코드',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형2차분류코드',
  `pylno` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처번호',
  `pypl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처구분코드',
  `pypl_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처종류코드',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `pypl_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처계좌번호',
  `dpsr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주',
  `pylnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처명',
  `pynct_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급금권유형코드',
  `dfpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금상대처코드',
  `py_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급방법코드',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `py_prdt` date DEFAULT NULL COMMENT '지급예정일자',
  `py_pr_woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급예정원화금액',
  `py_pr_fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급예정외화금액',
  `py_dcn_woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급확정원화금액',
  `py_dcn_fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급확정외화금액',
  `rl_py_dcn_woamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실지급확정원화금액',
  `rl_py_dcn_fcamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '실지급확정외화금액',
  `fx_pldoq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외환차손익구분코드',
  `fx_pqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '외환차손익금액',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `fc_dcndt` date DEFAULT NULL COMMENT '외화확정일자',
  `fc_dcn_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외화확정직원번호',
  `fc_dcn_ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '외화확정적용환율',
  `self_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본인여부',
  `rcr_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수령자주민번호',
  `rcr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수령자명',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `invln_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '투융자상품코드',
  `bsns_cnnno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무관련번호구분코드',
  `bsns_cnnno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무관련번호',
  `crt_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자식별번호',
  `victm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자식별번호',
  `nrdps_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호',
  `dmgnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물명',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '펀드코드',
  `apdt` date DEFAULT NULL COMMENT '승인일자',
  `ap_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인기관코드',
  `ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인직원번호',
  `rp_admcr_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수관리증번호',
  `rp_admcr_outdt` date DEFAULT NULL COMMENT '영수관리증출력일자',
  `rp_admcr_outbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수관리증출력대상여부',
  `dsodt` date DEFAULT NULL COMMENT '발의일자',
  `bdg_dpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예산발의번호',
  `pydt` date DEFAULT NULL COMMENT '지급일자',
  `py_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급기관코드',
  `py_xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정산번호',
  `chbf_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전발생번호',
  `py_dl_o1_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처리1차구분코드',
  `py_dl_o2_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처리2차구분코드',
  `fr_dpdt` date DEFAULT NULL COMMENT '최초입금일자',
  `fr_dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초취급기관코드',
  `fr_dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초취급직원번호',
  `py_cr_rm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생반제유형코드',
  `jonl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분개여부',
  `py_dl_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처리오류여부',
  `py_er_nt_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급오류통지방법코드',
  `fc_by_iptdt` date DEFAULT NULL COMMENT '외화매입입력일자',
  `fc_by_inp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외화매입입력직원번호',
  `rm_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '반제상태코드',
  `py_cr_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급발생상태코드',
  `py_reqdt` date DEFAULT NULL COMMENT '지급요청일자',
  `repy_reqdt` date DEFAULT NULL COMMENT '재지급요청일자',
  `repy_rq_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재지급요청직원번호',
  `repy_rq_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재지급요청사유코드',
  `slpdt` date DEFAULT NULL COMMENT '전표일자',
  `slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표번호',
  `py_st_dv_dldt` date DEFAULT NULL COMMENT '지급정지배분처리일자',
  `pyst_dv_dl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정지배분처리직원번호',
  `pyst_dv_dl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정지배분처리기관코드',
  `pyno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급번호',
  `ccl_bj_pyno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소대상지급번호',
  `py_cstno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급품의번호',
  `ccl_bj_py_cstno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소대상지급품의번호',
  `py_st_dv_dlno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정지배분처리번호',
  `ccl_bj_ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소대상배서번호',
  `chrps_dsdt` date DEFAULT NULL COMMENT '담당자지정일자',
  `chrps_asmt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자지정기관코드',
  `chrps_asmt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자지정직원번호',
  `wdra_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인출은행코드',
  `wdra_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인출계좌번호',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기준년월',
  `bdl_tf_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일괄이체업무구분코드',
  `bdl_tf_dl_seqno` decimal(5,0) DEFAULT NULL COMMENT '일괄이체처리순번',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `pyst_dv_dl_seqno` decimal(5,0) DEFAULT NULL COMMENT '지급정지배분처리순번',
  `bdl_rm_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '일괄송금여부',
  `rcapm_org_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출납기관상세구분코드',
  `sms_py_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS지급유형코드',
  `bsns_adx_file_dscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무첨부파일식별번호',
  `elec_evd_img_bsnno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전자증빙이미지업무번호',
  `elec_prv_dcu_id` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전자결재문서아이디',
  `file_evd_gpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '파일증빙그룹번호',
  `myct_py_bjyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '다건지급대상여부',
  `db_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변계정과목코드',
  `crdt_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변계정과목코드',
  `py_dl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급처리구분코드',
  `inr_edamt_dldt` date DEFAULT NULL COMMENT '통합입출금처리일자',
  `inr_rtxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통합영수증번호',
  `sms_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS대상여부',
  `hpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴대폰번호',
  `chr_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '문자내용',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `kko_pay_py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카카오PAY지급여부',
  `kko_acc_id` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카카오계정ID',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_py_cr_00` (`py_crno`),
  KEY `idx_fin_py_cr_11` (`pylno`),
  KEY `idx_fin_py_cr_10` (`ldgno`),
  KEY `idx_fin_py_cr_12` (`py_xcno`),
  KEY `idx_fin_py_cr_13` (`pyno`),
  KEY `idx_fin_py_cr_14` (`rp_admcr_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1350 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='지급발생';
