--
-- Table structure for table `fin_dy_fd_adm`
--

DROP TABLE IF EXISTS `fin_dy_fd_adm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_dy_fd_adm` (
  `stdt` date NOT NULL COMMENT '기준일자',
  `av_pl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '실적계획구분코드',
  `incm_exp_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '수입지출구분코드',
  `gn_spc_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '일반특별구분코드',
  `fndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '펀드코드',
  `bfdy_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전일잔액',
  `cr_rnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자동차원수금액',
  `gn_rnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '일반원수금액',
  `ltrm_rnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장기원수금액',
  `nd_rtamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '만기환급금액',
  `cn_rtamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '해약환급금액',
  `tramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '신탁금액',
  `eoamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '예금금액',
  `lnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대출금액',
  `cla_lnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '약관대출금액',
  `skamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주식금액',
  `fgamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선물금액',
  `pf_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '수익증권금액',
  `bnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '채권금액',
  `ntp_blamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기업어음금액',
  `rnt_guamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임차보증금액',
  `les_inamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대수입금액',
  `nt_inamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '이자수입금액',
  `afrk_ntamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '후순위이자금액',
  `bnd_ntamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '채권이자금액',
  `spc_acamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '특별계정금액',
  `co_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동보험금액',
  `rins_lqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '재보험청산금액',
  `sprcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '판촉비',
  `bld_rpacs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '건물수선비',
  `mbamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '회원권금액',
  `crpca_usamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '법인카드사용금액',
  `pstg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '우편료',
  `tlcrg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전화료',
  `atpli_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자배책금액',
  `nppan_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '국민연금금액',
  `ofcl_lbamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임원배상금',
  `agy_cm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대리점수수료',
  `plr_aw` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '설계사수당',
  `slr_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '급여금액',
  `bn_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '상여금액',
  `edutx_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '교육세액',
  `axamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부가세액',
  `whtx_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원천세액',
  `pp_crptx_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선급법인세액',
  `fwdv_dnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선도거래금액',
  `envr_shamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '환경분담금액',
  `invst_fdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '투자자금금액',
  `shtm_fdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '단기자금금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`stdt`,`av_pl_flgcd`,`incm_exp_flgcd`,`gn_spc_flgcd`,`fndcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='일자금관리';
