--
-- Table structure for table `fin_lq_dot`
--

DROP TABLE IF EXISTS `fin_lq_dot`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_lq_dot` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `ppdt` date NOT NULL COMMENT '계상일자',
  `lq_dotno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '청산일계번호',
  `re_rtro_bsnno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재업무번호구분코드',
  `re_rtro_bsnno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재업무번호',
  `lq_dltcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청산상대처코드',
  `brk_rincd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브로커재보험자코드',
  `pt_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참여회사코드',
  `re_rtro_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재구분코드',
  `rertr_dt_bsnno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재세부업무번호구분코드',
  `re_rtro_dt_bsnno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재수재세부업무번호',
  `rtro_crano` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수재계약번호',
  `cr_syscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '발생시스템코드',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형2차분류코드',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회계기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `uc_np_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미수미지급구분코드',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `woncr_uc_npamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화미수미지급금액',
  `fc_uc_npamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '외화미수미지급금액',
  `xcrt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환율구분코드',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험종목코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `clm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수조사순번',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `incm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '수입보험료발생순번',
  `pyno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급번호',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `udrtk_dv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수배분구분코드',
  `otcm_plyno` varchar(25) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사증권번호',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국내외구분코드',
  `trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약구분코드',
  `trt_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약년월',
  `payao_py_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '즉시불지급여부',
  `xol_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT 'XOL여부',
  `xol_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'XOL특약코드',
  `rir_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재보상품코드',
  `rir_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재보특약코드',
  `rir_sctcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재보섹션코드',
  `pvl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계상구분코드',
  `lq_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청산구분코드',
  `lq_pr_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산예정년월',
  `da_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료발생구분코드',
  `rnamt_lq_pr_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유보금액청산예정년월',
  `lq_bj_st_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산대상상태분류코드',
  `lq_bj_st_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청산대상상태상세코드',
  `qtrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '지분율',
  `condt_t_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동인수총보험료',
  `co_udrtk_t_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공동인수총보험금액',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `slpdt` date DEFAULT NULL COMMENT '전표일자',
  `slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전표번호',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기준년월',
  `cls_da_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마감자료종류코드',
  `dl_seqno` decimal(5,0) DEFAULT NULL COMMENT '처리순번',
  `dh_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급회사코드',
  `erp_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송여부',
  `xc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정산여부',
  `trs_finm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송신파일명',
  `otcm_clmno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타사사고번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`,`ppdt`),
  KEY `idx_fin_lq_dot_01` (`ppdt`,`lq_dotno`)
) ENGINE=InnoDB AUTO_INCREMENT=18199 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='청산일계'
