--
-- Table structure for table `fin_rtman_tf`
--

DROP TABLE IF EXISTS `fin_rtman_tf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_rtman_tf` (
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급직원번호',
  `crdt` date NOT NULL COMMENT '발생일자',
  `sno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '일련번호',
  `rtman_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금처리구분코드',
  `rtman_dl_rkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금처리단계코드',
  `ikdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종코드',
  `dh_stf_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `av_dt` date DEFAULT NULL COMMENT '실적일자',
  `gr_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단체증권번호',
  `rtman_isps_plyno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금가입자증권번호',
  `rtxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증번호',
  `crt_cd` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자코드',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `rtman_pylno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금지급처번호',
  `pylnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처명',
  `rtman_py_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금지급형태코드',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `rl_pyamt` decimal(15,0) DEFAULT NULL COMMENT '실지급액',
  `pydt` date DEFAULT NULL COMMENT '지급일자',
  `py_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급기관코드',
  `rtman_py_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금지급구분코드',
  `rtman_py_sno` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금지급일련번호',
  `dpdt` date DEFAULT NULL COMMENT '입금일자',
  `rnd_days` decimal(5,0) DEFAULT NULL COMMENT '경과일수',
  `ntrt` decimal(5,2) DEFAULT NULL COMMENT '이자율',
  `ntamt` decimal(15,0) DEFAULT NULL COMMENT '이자금액',
  `rtman_pr_ntamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직연금예정이자금액',
  `chamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '부담금합계금액',
  `rt_rtamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '반송환급금합계액',
  `ictx_smamt` decimal(15,0) DEFAULT NULL COMMENT '소득세합계금액',
  `rstx_smamt` decimal(15,0) DEFAULT NULL COMMENT '주민세합계금액',
  `cn_ad_txamt` decimal(15,0) DEFAULT NULL COMMENT '해지가산세금액',
  `op_feamt` decimal(15,0) DEFAULT NULL COMMENT '운용수수료금액',
  `rtamt_smamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직금합계금액',
  `etamt` decimal(15,0) DEFAULT NULL COMMENT '기타금액',
  `fsti_chamt` decimal(15,0) DEFAULT NULL COMMENT '초회부담금액',
  `ctu_chamt` decimal(15,0) DEFAULT NULL COMMENT '계속부담금액',
  `fsti_chamt_rt_amt` decimal(15,0) DEFAULT NULL COMMENT '초회부담금반송액',
  `ctu_chamt_rt_amt` decimal(15,0) DEFAULT NULL COMMENT '계속부담금반송액',
  `rtman_chamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직연금부담금액',
  `fsti_rt_amt` decimal(15,0) DEFAULT NULL COMMENT '초회반송액',
  `ctu_rt_amt` decimal(15,0) DEFAULT NULL COMMENT '계속반송액',
  `dpt_py_rt_amt` decimal(15,0) DEFAULT NULL COMMENT '과납반송액',
  `rtm_dthms_amt_pyamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직일시금지급금액',
  `rtman_pyamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직연금지급금액',
  `crcn_rtamt` decimal(15,0) DEFAULT NULL COMMENT '계약해지환급금액',
  `spls_cuamt` decimal(15,0) DEFAULT NULL COMMENT '초과적립금액',
  `mw_wlamt` decimal(15,0) DEFAULT NULL COMMENT '중도인출금액',
  `psn_chamt` decimal(15,0) DEFAULT NULL COMMENT '개인부담금액',
  `pyamt` decimal(15,0) DEFAULT NULL COMMENT '지급액',
  `rtm_ixamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직소득세액',
  `et_ixamt` decimal(15,0) DEFAULT NULL COMMENT '기타소득세액',
  `nt_ictx` decimal(15,0) DEFAULT NULL COMMENT '이자소득세',
  `an_ixamt` decimal(15,0) DEFAULT NULL COMMENT '연금소득세액',
  `rtm_rxamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직주민세액',
  `et_rxamt` decimal(15,0) DEFAULT NULL COMMENT '기타주민세액',
  `nt_rxamt` decimal(15,0) DEFAULT NULL COMMENT '이자주민세액',
  `an_rxamt` decimal(15,0) DEFAULT NULL COMMENT '연금주민세액',
  `rtm_cr_slpno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직발생전표번호',
  `rtm_dl_slpno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직처리전표번호',
  `amg_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가상계좌번호',
  `dp_prdt` date DEFAULT NULL COMMENT '입금예정일자',
  `rnd_pr_days` decimal(3,0) DEFAULT NULL COMMENT '경과예정일수',
  `ky_itvl` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '키항목값',
  `rtm_icamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직소득금액',
  `et_icamt` decimal(15,0) DEFAULT NULL COMMENT '기타소득금액',
  `rtman_nt_icamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직연금이자소득금액',
  `rtman_an_icamt` decimal(15,0) DEFAULT NULL COMMENT '퇴직연금연금소득금액',
  `ase_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산기관코드',
  `rtman_dl_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금거래유형코드',
  `rtman_slp_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금전표유형코드',
  `rtman_itcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금항목코드',
  `py_cm_itcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급수수료항목코드',
  `no1_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번발생구분코드',
  `no2_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번발생구분코드',
  `spc_acc_db_1_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별계정차변1계정과목코드',
  `spc_acc_crdt_1_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별계정대변1계정과목코드',
  `spc_acc_db_2_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별계정차변2계정과목코드',
  `spc_acc_crdt_2_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별계정대변2계정과목코드',
  `spc_acc_nt_db_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별계정이자차변계정과목코드',
  `spc_acc_nt_crdt_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별계정이자대변계정과목코드',
  `rtman_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직연금펀드코드',
  `o1_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차지급펀드코드',
  `o2_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차지급펀드코드',
  `o3_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차지급펀드코드',
  `o4_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4차지급펀드코드',
  `o5_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5차지급펀드코드',
  `o6_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6차지급펀드코드',
  `o7_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7차지급펀드코드',
  `o8_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8차지급펀드코드',
  `o9_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9차지급펀드코드',
  `o10_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10차지급펀드코드',
  `o11_py_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '11차지급펀드코드',
  `py_cm_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급수수료펀드코드',
  `db_1_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변1계정과목코드',
  `crdt_1_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변1계정과목코드',
  `db_2_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변2계정과목코드',
  `crdt_2_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변2계정과목코드',
  `db_3_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변3계정과목코드',
  `crdt_3_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변3계정과목코드',
  `db_4_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변4계정과목코드',
  `crdt_4_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변4계정과목코드',
  `db_5_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변5계정과목코드',
  `crdt_5_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변5계정과목코드',
  `db_6_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변6계정과목코드',
  `crdt_6_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변6계정과목코드',
  `db_7_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변7계정과목코드',
  `crdt_7_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변7계정과목코드',
  `db_8_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변8계정과목코드',
  `crdt_8_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변8계정과목코드',
  `db_9_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변9계정과목코드',
  `crdt_9_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변9계정과목코드',
  `db_10_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변10계정과목코드',
  `crdt_10_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변10계정과목코드',
  `db_11_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변11계정과목코드',
  `crdt_11_acc_sbjcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변11계정과목코드',
  `db_spc_acc_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차변특별계정펀드코드',
  `crdt_spc_acc_fndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대변특별계정펀드코드',
  `o1_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '1차펀드금액',
  `o2_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '2차펀드금액',
  `o3_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '3차펀드금액',
  `o4_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '4차펀드금액',
  `o5_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '5차펀드금액',
  `o6_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '6차펀드금액',
  `o7_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '7차펀드금액',
  `o8_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '8차펀드금액',
  `o9_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '9차펀드금액',
  `o10_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '10차펀드금액',
  `o11_fund_amt` decimal(15,0) DEFAULT NULL COMMENT '11차펀드금액',
  `fndcd_mch_amt` decimal(15,0) DEFAULT NULL COMMENT '펀드코드매치금액',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `py_xcdt` date DEFAULT NULL COMMENT '지급정산일자',
  `py_xc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정산기관코드',
  `py_xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급정산번호',
  `erp_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송여부',
  `erp_tsdt` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP전송일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`dh_stfno`,`crdt`,`sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='퇴직연금이체';
