--
-- Table structure for table `fin_prm_rv_sb`
--

DROP TABLE IF EXISTS `fin_prm_rv_sb`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `fin_prm_rv_sb` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '수납대기번호',
  `cr_syscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '발생시스템코드',
  `dl_tp_o1_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형1차분류코드',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '거래유형2차분류코드',
  `rpdt` date DEFAULT NULL COMMENT '영수일자',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `invln_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '투융자상품코드',
  `ntacc_cd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계정과목코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '수입보험료발생순번',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `crt_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자주민번호',
  `rpbl_opndt` date DEFAULT NULL COMMENT '책임개시일자',
  `ltrm_cr_totno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기계약집계번호',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `dp_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금원인코드',
  `mnt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금종구분코드',
  `dpdt` date DEFAULT NULL COMMENT '입금일자',
  `rp_admno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수관리번호',
  `plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설계번호',
  `bsns_nds_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무배서구분코드',
  `clsaf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마감후여부',
  `tot_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '집계구분코드',
  `totct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '집계건수',
  `tot_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '전체보험료',
  `woncr_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화보험료',
  `cr_rn_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자동차원수보험료',
  `cr_dtamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자동차예수금액',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `fc_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '외화보험료',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `tf_cm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '이체수수료',
  `etamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타금액구분코드',
  `etamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기타금액',
  `rvdt` date DEFAULT NULL COMMENT '수납일자',
  `rv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납기관코드',
  `rv_xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납정산번호',
  `da_cr_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료발생유형코드',
  `gir_attf_er_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '지로자동이체오류여부',
  `gir_dp_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지로입금상태코드',
  `prm_pvl_slpdt` date DEFAULT NULL COMMENT '보험료계상전표일자',
  `prm_pvl_slpno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료계상전표번호',
  `prm_pvl_slp_lnno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료계상전표라인번호',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `uc_prm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미수보험료여부',
  `msg_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지ID',
  `msg_tp_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메시지유형분류코드',
  `tlm_tsdt` date DEFAULT NULL COMMENT '전문전송일자',
  `tlm_pno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문고유번호',
  `tlm_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문종별코드',
  `spbz_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문업무구분코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주명',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `inr_ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통합보종군코드',
  `inr_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통합증권번호',
  `inr_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '통합보험료',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `crd_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드회사코드',
  `ccl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소여부',
  `dh_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급회사코드',
  `crd_smamt_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드합계금액승인여부',
  `rv_dl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '수납처리구분코드',
  `inr_edamt_dldt` date DEFAULT NULL COMMENT '통합입출금처리일자',
  `inr_rtxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통합영수증번호',
  `fina_dat_vrf_flg1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분1값',
  `fina_dat_vrf_flg2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분2값',
  `fina_dat_vrf_flg3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재무데이터검증구분3값',
  `agr_entp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약정업체여부',
  `cr_rpbl_prm` decimal(17,2) DEFAULT '0.00' COMMENT '자동차책임보험료',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_fin_prm_rv_sb_00` (`rv_sbno`),
  KEY `idx_fin_prm_rv_sb_01` (`rp_admno`),
  KEY `idx_fin_prm_rv_sb_02` (`dh_orgcd`,`rpdt`,`ikd_grpcd`),
  KEY `idx_fin_prm_rv_sb_10` (`crt_rsno`),
  KEY `idx_fin_prm_rv_sb_11` (`dh_stfno`,`rvdt`),
  KEY `idx_fin_prm_rv_sb_12` (`plyno`)
) ENGINE=InnoDB AUTO_INCREMENT=32371 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='보험료수납대기';
