--
-- Table structure for table `cmp_psn_crdio_tp_rq`
--

DROP TABLE IF EXISTS `cmp_psn_crdio_tp_rq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cmp_psn_crdio_tp_rq` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `crdio_tp_rgtno` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '신용정보제공유형등록번호',
  `crdio_rltn_key` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공연계KEY',
  `crdio_cyc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공주기구분코드',
  `crdif_ofplc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공처구분코드',
  `crdio_bsc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공근거구분코드',
  `crdio_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공주소구분코드',
  `home_tlno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자택전화번호제공여부',
  `hpno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴대폰번호제공여부',
  `crdio_ikd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공보종구분코드',
  `cr_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약내용',
  `ln_cn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출내용',
  `ibnf_py_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금지급내용',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고내용',
  `et1_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타1내용',
  `et2_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타2내용',
  `nhgst_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차상위기관코드',
  `cmpu_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산담당자직원번호',
  `cnn_dcuno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련문서번호',
  `bsc_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근거내용',
  `crdio_metd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공방식구분코드',
  `crdio_rel_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공관계구분코드',
  `crdio_impdg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공중요도구분코드',
  `crdio_mtd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보제공방법구분코드',
  `ibnf_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금환수여부',
  `rcv_perd_mntct` decimal(3,0) DEFAULT NULL COMMENT '환수기한개월수',
  `strdt` date DEFAULT NULL COMMENT '시작일자',
  `nddt` date DEFAULT NULL COMMENT '종료일자',
  `o1_ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차승인직원번호',
  `o1_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차승인여부',
  `o1_apdt` date DEFAULT NULL COMMENT '1차승인일자',
  `o2_ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차승인직원번호',
  `o2_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차승인여부',
  `o2_apdt` date DEFAULT NULL COMMENT '2차승인일자',
  `wst_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '폐기직원번호',
  `wst_crdio_tp_rgtno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '폐기신용정보제공유형등록번호',
  `wstdt` date DEFAULT NULL COMMENT '폐기일자',
  `us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용여부',
  `info_us_oj` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보이용목적',
  `apdt` date DEFAULT NULL COMMENT '승인일자',
  `rqudt` date DEFAULT NULL COMMENT '의뢰일자',
  `info_ofdt` date DEFAULT NULL COMMENT '정보제공일자',
  `of_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제공내용',
  `orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관명',
  `depnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부서명',
  `stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직원명',
  `finm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '파일명',
  `inorg_dcu_doc_finm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대외기관문서공문파일명',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_cmp_psn_crdio_tp_rq_00` (`crdio_tp_rgtno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개인신용정보제공유형신청';
