--
-- Table structure for table `cmp_ctm_cnf_sys`
--

DROP TABLE IF EXISTS `cmp_ctm_cnf_sys`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cmp_ctm_cnf_sys` (
  `plno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호',
  `cgaf_ch_seqno` decimal(5,0) NOT NULL COMMENT '발행후변경순번',
  `relpc_seqno` decimal(10,0) NOT NULL COMMENT '관계자순번',
  `relpc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계자유형코드',
  `pfb_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자구분코드',
  `pldt` date DEFAULT NULL COMMENT '설계일자',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무구분코드',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `hngl_ctmnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글고객명',
  `eng_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문고객명',
  `ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국적코드',
  `btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `dh_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지점기관코드',
  `dh_aregp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지역단기관코드',
  `idnty_cnfc_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증종류코드',
  `idnty_cnfc_et_info` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증기타정보',
  `idnty_cnfc_isdt` date DEFAULT NULL COMMENT '신원확인증발급일자',
  `idnty_cnfc_is_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증발급기관명',
  `idnty_cnfc_no` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증번호',
  `ins_dl_oj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험거래목적구분코드',
  `dl_oj_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래목적내용',
  `dl_fd_sorc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래자금출처구분코드',
  `dl_fd_sorc_cn` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래자금출처내용',
  `psn_crp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인법인구분코드',
  `std_ind_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준산업분류코드',
  `crp_btpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인업종코드',
  `crp_fnd_ojccd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인설립목적코드',
  `crp_fnd_oj_et_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인설립목적기타내용',
  `pdt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자성명',
  `pdt_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자고객번호',
  `pdt_ennm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자영문명',
  `pdt_ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자국적코드',
  `pdt_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자생년월일',
  `ntp_sclcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업규모코드',
  `lstst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상장구분코드',
  `fnddt` date DEFAULT NULL COMMENT '설립일자',
  `crp_fnd_ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인설립국적코드',
  `rl_ownr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자여부',
  `rl_ownr_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자주민번호',
  `rl_own_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유고객명',
  `rl_ownr_eng_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자영문고객명',
  `rl_ownr_ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자국적코드',
  `rl_own_born_mndy` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유출생월일',
  `ctm_rel_dt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객관계세부유형코드',
  `agnt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인여부',
  `crt_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자관계코드',
  `crt_rel_et_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자관계기타내용',
  `agnt_auth_cnf_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인권한확인종류코드',
  `agnt_auth_cnf_et_cn` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인권한확인기타내용',
  `aml_rk_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AML위험구분코드',
  `ntn_rk_poct` decimal(7,5) DEFAULT NULL COMMENT '국가위험점수',
  `actn_rk_poct` decimal(7,5) DEFAULT NULL COMMENT '행동위험점수',
  `gdrk_poct` decimal(7,5) DEFAULT NULL COMMENT '상품위험점수',
  `ctm_rk_poct` decimal(7,5) DEFAULT NULL COMMENT '고객위험점수',
  `rkvl_poct` decimal(5,2) DEFAULT NULL COMMENT '위험평가점수',
  `rkvl_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험평가등급코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `wlst_fltr_rst` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'WATCHLIST필터링결과',
  `rl_area_nm_dcu_scan_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실지명의서류스캔여부',
  `crp_gr_fnd_evd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인단체설립증빙여부',
  `rl_ownr_evd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자증빙여부',
  `pfb_evd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자증빙여부',
  `laco_agnt_evd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법정대리인증빙여부',
  `ctm_dl_cnfst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객거래확인서여부',
  `o1_prv_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차결재결과코드',
  `o1_prv_ctn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차결재의견',
  `o2_prv_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차결재결과코드',
  `o2_prv_ctn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차결재의견',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`plno`,`cgaf_ch_seqno`,`relpc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='고객확인제도';
