--
-- Table structure for table `cmp_ad_scpt`
--

DROP TABLE IF EXISTS `cmp_ad_scpt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cmp_ad_scpt` (
  `scpt_rq_ty_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '스크립트요청형태구분코드',
  `reqdt` date NOT NULL COMMENT '요청일자',
  `rqog_cd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '요청기관코드',
  `seqno` decimal(5,0) NOT NULL COMMENT '순번',
  `ad_ud_org_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '광고심사기관구분코드',
  `ad_instm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '광고보험종목구분코드',
  `gdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품명',
  `ad_csf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '광고분류구분코드',
  `ad_nm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '광고명',
  `ad_bj_arenm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '광고대상지역명',
  `ad_metd_nm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '광고방식명',
  `usdt` date DEFAULT NULL COMMENT '사용일자',
  `rq_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청내용',
  `ad_reqdt` date DEFAULT NULL COMMENT '광고요청일자',
  `rqfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청직원번호',
  `dmd_cnfdt` date DEFAULT NULL COMMENT '요청자확인일자',
  `rq_adm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청관리직원번호',
  `rq_admr_cnfdt` date DEFAULT NULL COMMENT '요청관리자확인일자',
  `o1_ud_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차심사기관코드',
  `o1_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차심사직원번호',
  `o1_ud_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차심사관리자직원번호',
  `o2_ud_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차심사기관코드',
  `o2_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차심사직원번호',
  `o2_ud_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차심사관리자직원번호',
  `o3_ud_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차심사기관코드',
  `o3_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차심사직원번호',
  `o3_ud_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차심사관리자직원번호',
  `o4_ud_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4차심사기관코드',
  `o4_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4차심사직원번호',
  `o4_ud_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4차심사관리자직원번호',
  `o5_ud_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5차심사기관코드',
  `o5_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5차심사직원번호',
  `o5_ud_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5차심사관리자직원번호',
  `adm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관코드',
  `adm_org_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관직원번호',
  `adm_org_apdt` date DEFAULT NULL COMMENT '관리기관승인일자',
  `adm_org_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관관리자직원번호',
  `adm_org_admr_apdt` date DEFAULT NULL COMMENT '관리기관관리자승인일자',
  `adm_seqno` decimal(10,0) DEFAULT NULL COMMENT '관리순번',
  `asso_apdt` date DEFAULT NULL COMMENT '협회승인일자',
  `fnl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종기관코드',
  `fnl_org_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종기관직원번호',
  `fnl_org_apdt` date DEFAULT NULL COMMENT '최종기관승인일자',
  `fnl_org_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종기관관리자직원번호',
  `fnl_org_admr_apdt` date DEFAULT NULL COMMENT '최종기관관리자승인일자',
  `ud_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사의견',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`scpt_rq_ty_flgcd`,`reqdt`,`rqog_cd`,`seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='광고스크립트';
