--
-- Table structure for table `sam_incm_prm_bz_av`
--

DROP TABLE IF EXISTS `sam_incm_prm_bz_av`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sam_incm_prm_bz_av` (
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) NOT NULL COMMENT '수입보험료발생순번',
  `cv_prm_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '환산보험료합계',
  `vl_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '평가보험료',
  `ce_awamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '모집수당금액',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `ce_aw_pyrt` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '모집수당지급율',
  `aw_spc_dl_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '수당내역처리여부',
  `aw_spc_dldt` date NOT NULL COMMENT '수당내역처리일자',
  `aw_py_prdt` date NOT NULL COMMENT '수당지급예정일자',
  `prpn_aw_smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '비례수당합계금액',
  `ppdt` date NOT NULL COMMENT '계상일자',
  `gnte_cv_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보장성환산보험료',
  `cumt_cv_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '적립성환산보험료',
  `ltrm_mpy_cv_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장기월납환산보험료',
  `mn_awamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '유지수당금액',
  `cm_awamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '수금수당금액',
  `nw_ou_awamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '신규성과수당금액',
  `mn_ou_awamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '유지성과수당금액',
  `cu_cvrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '적립환산율',
  `gn_cvrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '보장환산율',
  `mn_aw_pyrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '유지수당지급율',
  `cm_aw_pyrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '수금수당지급율',
  `sv_cradm_awamt` decimal(15,0) DEFAULT '0' COMMENT '저축계약관리수당금액',
  `nrins_cradm_awamt` decimal(15,0) DEFAULT NULL COMMENT '통합보험계약관리수당금액',
  `pl_ou_awamt` decimal(15,0) DEFAULT NULL COMMENT '플랜성과수당금액',
  `gn_ase_ou_awamt` decimal(15,0) DEFAULT NULL COMMENT '보장자산성과수당금액',
  `rlpmi_cvr_prm` decimal(15,0) DEFAULT NULL COMMENT '실손담보보험료',
  `rlpmi_cvr_cv_prm` decimal(17,2) DEFAULT NULL COMMENT '실손담보환산보험료',
  `rnw_cradm_awamt` decimal(15,0) DEFAULT NULL COMMENT '갱신계약관리수당금액',
  `ltrm_nwcr_vl_prm` decimal(15,0) DEFAULT NULL COMMENT '장기신계약평가보험료',
  `rpbl_cv_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '책임환산보험료',
  `optn_cv_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '임의환산보험료',
  `rpbl_xc_prm_1` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임정산보험료1',
  `rpbl_xc_prm_2` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임정산보험료2',
  `optn_xc_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임의정산보험료',
  `rpbl_ins_pyrt_1` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '책임보험지급율1',
  `rpbl_ins_pyrt_2` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '책임보험지급율2',
  `optn_ins_pyrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '임의보험지급율',
  `rpbl_ins_awamt_1` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임보험수당금액1',
  `rpbl_ins_awamt_2` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임보험수당금액2',
  `optn_ins_awamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임의보험수당금액',
  `cm_mdf_prm` decimal(15,0) DEFAULT '0' COMMENT '수금수정보험료',
  `cm_cvrt` decimal(5,2) DEFAULT '0.00' COMMENT '수금환산율',
  `o1_nwcr_mdf_prm` decimal(15,0) DEFAULT '0' COMMENT '1차신계약수정보험료',
  `o1_mn_aw_pyrt` decimal(5,2) DEFAULT '0.00' COMMENT '1차유지수당지급율',
  `o1_mn_awamt` decimal(15,0) DEFAULT '0' COMMENT '1차유지수당금액',
  `o2_nwcr_mdf_prm` decimal(15,0) DEFAULT '0' COMMENT '2차신계약수정보험료',
  `o2_mn_aw_pyrt` decimal(5,2) DEFAULT '0.00' COMMENT '2차유지수당지급율',
  `o2_mn_awamt` decimal(15,0) DEFAULT '0' COMMENT '2차유지수당금액',
  `cradm_mn_aw_pyrt` decimal(5,2) DEFAULT '0.00' COMMENT '계약관리유지수당지급율',
  `cradm_mn_awamt` decimal(15,0) DEFAULT '0' COMMENT '계약관리유지수당금액',
  `re_prm` decimal(17,2) DEFAULT '0.00' COMMENT '출재보험료',
  `re_cm` decimal(17,2) DEFAULT '0.00' COMMENT '출재수수료',
  `re_cmrt` decimal(12,6) DEFAULT '0.000000' COMMENT '출재수수료율',
  `rp_prm` decimal(15,0) DEFAULT NULL COMMENT '영수보험료',
  `gn_prm` decimal(17,2) DEFAULT NULL COMMENT '보장보험료',
  `cu_prm` decimal(15,0) DEFAULT NULL COMMENT '적립보험료',
  `gnte_ce_awamt` decimal(17,5) DEFAULT NULL COMMENT '보장성모집수당금액',
  `cumt_ce_awamt` decimal(17,5) DEFAULT NULL COMMENT '적립성모집수당금액',
  `gnte_mn_awamt` decimal(17,5) DEFAULT NULL COMMENT '보장성유지수당금액',
  `cumt_mn_awamt` decimal(17,5) DEFAULT NULL COMMENT '적립성유지수당금액',
  `ltrm_aw_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기수당그룹코드',
  `bz_atrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업속성코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `dh_usr_no` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급사용인번호',
  `cr_bzav_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차영업실적군코드',
  `note` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`plyno`,`incm_prm_cr_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='수입보험료영업실적';
