--
-- Table structure for table `sam_cr_cscl_sl`
--

DROP TABLE IF EXISTS `sam_cr_cscl_sl`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sam_cr_cscl_sl` (
  `st_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '기준년월',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급직원번호',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cr_seqno` decimal(7,0) NOT NULL COMMENT '발생순번',
  `incm_prm_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '수입보험료발생순번',
  `plyno_st_cr_seqno` decimal(5,0) DEFAULT NULL COMMENT '증권번호기준발생순번',
  `dh_hdqt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급본부기관코드',
  `dh_bz_part_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급영업부문기관코드',
  `dh_aregp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지역단기관코드',
  `dh_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지점기관코드',
  `dh_brof_cd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급출장소코드',
  `dh_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급팀기관코드',
  `dptcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과코드',
  `agy_adm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점관리직원번호',
  `co_bzof_cd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동사무소코드',
  `usrno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용인번호',
  `brkr_cd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중개인코드',
  `ce_aregp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집지역단기관코드',
  `ce_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집지점기관코드',
  `cer_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집자직원번호',
  `ikd_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종분류코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `av_stdt` date DEFAULT NULL COMMENT '실적기준일자',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `appr_av_dt` date DEFAULT NULL COMMENT '인정실적일자',
  `rv_av_dt` date DEFAULT NULL COMMENT '수납실적일자',
  `relpc_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계자식별번호구분코드',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `crp_or_bzmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인/사업자번호',
  `crt_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자고객명',
  `rv_rtn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납환급구분코드',
  `rv_rtn_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납환급원인코드',
  `avct` decimal(10,0) DEFAULT NULL COMMENT '실적건수',
  `wn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '창구구분코드',
  `hscs_hs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가계비가계구분코드',
  `mnt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금종구분코드',
  `av_ta_appr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실적이관인정구분코드',
  `pym_du_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입응당년월',
  `pym_seq` decimal(5,0) DEFAULT NULL COMMENT '납입회차',
  `mstr_set_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마스터SET여부',
  `thcp_prm` decimal(17,2) DEFAULT NULL COMMENT '당사보험료',
  `t_prm` decimal(15,0) DEFAULT NULL COMMENT '총보험료',
  `nwcr_mdf_prm` decimal(17,2) DEFAULT NULL COMMENT '신계약수정보험료',
  `cm_mdf_prm` decimal(15,0) DEFAULT NULL COMMENT '수금수정보험료',
  `pltpt_prm` decimal(17,2) DEFAULT NULL COMMENT '정당보험료',
  `cash_prm` decimal(17,2) DEFAULT NULL COMMENT '현금보험료',
  `crd_prm` decimal(17,2) DEFAULT NULL COMMENT '카드보험료',
  `bll_prm` decimal(17,2) DEFAULT NULL COMMENT '어음보험료',
  `svi_prm` decimal(17,2) DEFAULT NULL COMMENT '저축성보험료',
  `rpbl_prm` decimal(15,0) DEFAULT NULL COMMENT '책임보험료',
  `gnte_prm` decimal(17,2) DEFAULT NULL COMMENT '보장성보험료',
  `optn_prm` decimal(15,0) DEFAULT NULL COMMENT '임의보험료',
  `rpbl_cm` decimal(17,2) DEFAULT NULL COMMENT '책임수수료',
  `ce_mn_cm` decimal(17,2) DEFAULT NULL COMMENT '모집유지수수료',
  `ba_cm` decimal(17,2) DEFAULT NULL COMMENT '기본수수료',
  `optn_cm` decimal(17,2) DEFAULT NULL COMMENT '임의수수료',
  `cm_cm` decimal(15,0) DEFAULT NULL COMMENT '수금수수료',
  `trt_cm` decimal(17,2) DEFAULT NULL COMMENT '특약수수료',
  `cm_sm` decimal(15,0) DEFAULT NULL COMMENT '수수료합계',
  `mmcv_avamt` decimal(15,0) DEFAULT NULL COMMENT '월납환산실적금액',
  `rn_avamt` decimal(15,0) DEFAULT NULL COMMENT '원수실적금액',
  `incm_avamt` decimal(15,0) DEFAULT NULL COMMENT '수입실적금액',
  `appr_avamt` decimal(15,0) DEFAULT NULL COMMENT '인정실적금액',
  `rv_avamt` decimal(15,0) DEFAULT NULL COMMENT '수납실적금액',
  `wcom_co_udtyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사내공동인수여부',
  `cm_pybj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수수료지급대상구분코드',
  `cm_crdt` date DEFAULT NULL COMMENT '수수료발생일자',
  `bll_prv_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '어음결재상태코드',
  `bll_endt` date DEFAULT NULL COMMENT '어음만기일자',
  `bll_prvdt` date DEFAULT NULL COMMENT '어음결재일자',
  `rvdt` date DEFAULT NULL COMMENT '수납일자',
  `rvi_appr_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부활인정코드',
  `gn_av_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일반실적구분코드',
  `sv_gnte_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '저축보장성구분코드',
  `dp_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금상태코드',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `pyp_seq` decimal(5,0) DEFAULT NULL COMMENT '분납회차',
  `cr_bzav_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차영업실적군코드',
  `fsyr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '초년도구분코드',
  `cr_rk_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차위험세부코드',
  `same_ply_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일증권여부',
  `bzav_pyp_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업실적분납상태코드',
  `cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약상태코드',
  `rpamt_cc_cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임액산출차량용도코드',
  `cr_bzcs_bz_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차사업비사업구분코드',
  `mpy_cv_pym_ct` decimal(5,0) DEFAULT NULL COMMENT '월납환산납입횟수',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종코드',
  `carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호',
  `rdch_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승환계약여부',
  `crcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차계약구분코드',
  `bfcr_ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약보험회사코드',
  `pym_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입방법코드',
  `gn_spcf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일반특정구분코드',
  `gp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '그룹구분코드',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `mgcmp_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간사사코드',
  `pst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경유구분코드',
  `rv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납여부',
  `coop_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴환수여부',
  `av_ch_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실적변경원인코드',
  `ccl_rtn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소환급구분코드',
  `av_ta_ccl_org_dher_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실적이관취소원취급자적용여부',
  `av_dv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실적배분구분코드',
  `bnc_cm_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카수수료환수여부',
  `sb_dher_st_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대체취급자기준적용여부',
  `flpy_cvr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일시납담보구분코드',
  `cr_chncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약채널코드',
  `sign_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '서명방법코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `ap_prm` decimal(17,2) DEFAULT NULL COMMENT '적용보험료',
  `rpbl_cv_prm` decimal(17,2) DEFAULT NULL COMMENT '책임환산보험료',
  `optn_cv_prm` decimal(17,2) DEFAULT NULL COMMENT '임의환산보험료',
  `gnte_cv_prm` decimal(15,0) DEFAULT NULL COMMENT '보장성환산보험료',
  `cumt_cv_prm` decimal(15,0) DEFAULT NULL COMMENT '적립성환산보험료',
  `rlpmi_cvr_cv_prm` decimal(17,2) DEFAULT NULL COMMENT '실손담보환산보험료',
  `flpy_cvr_cvprm` decimal(17,2) DEFAULT NULL COMMENT '일시납담보환산보험료',
  `ce_awamt` decimal(15,0) DEFAULT NULL COMMENT '모집수당금액',
  `mn_awamt` decimal(15,0) DEFAULT NULL COMMENT '유지수당금액',
  `cm_awamt` decimal(15,0) DEFAULT NULL COMMENT '수금수당금액',
  `sv_cradm_awamt` decimal(15,0) DEFAULT NULL COMMENT '저축계약관리수당금액',
  `cu_cvrt` decimal(5,2) DEFAULT NULL COMMENT '적립환산율',
  `gn_cvrt` decimal(5,2) DEFAULT NULL COMMENT '보장환산율',
  `ce_aw_pyrt` decimal(7,2) DEFAULT NULL COMMENT '모집수당지급율',
  `mn_aw_pyrt` decimal(5,2) DEFAULT NULL COMMENT '유지수당지급율',
  `cm_aw_pyrt` decimal(5,2) DEFAULT NULL COMMENT '수금수당지급율',
  `sv_cradm_pyrt` decimal(5,2) DEFAULT NULL COMMENT '저축계약관리지급율',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `drve_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전형태코드',
  `self_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기계약여부',
  `nsc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계열사여부',
  `cv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전환여부',
  `ltrm_type_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기종구분코드',
  `dp_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금원인코드',
  `dp_dt_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금세부원인코드',
  `sv_an_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '저축연금구분코드',
  `pym_trm` decimal(3,0) DEFAULT NULL COMMENT '납입기간',
  `rl_pym_trm` decimal(3,0) DEFAULT NULL COMMENT '실납입기간',
  `rp_pth_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수경로구분코드',
  `sl_chfcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '매출채널구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`st_yymm`,`dh_stfno`,`plyno`,`cr_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계약건별매출';
