--
-- Table structure for table `ccm_tnd_spc`
--

DROP TABLE IF EXISTS `ccm_tnd_spc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_tnd_spc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `tnd_dgre` decimal(3,0) NOT NULL COMMENT '입찰차수',
  `tnd_spc_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '입찰내역구분코드',
  `tnd_str_dt` date DEFAULT NULL COMMENT '입찰시작일자',
  `tnd_nd_dt` date DEFAULT NULL COMMENT '입찰종료일자',
  `tnddt` date NOT NULL COMMENT '입찰일자',
  `tnd_hms` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '입찰시간',
  `tnd_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '입찰유형코드',
  `hg_tnamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '최고입찰가액',
  `re_tnd_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재입찰사유코드',
  `tnd_rstcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '입찰결과코드',
  `fail_rscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '유찰사유코드',
  `tnd_plc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰장소',
  `resv_vlamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '내정가액',
  `resv_vlamt_clcdt` date DEFAULT NULL COMMENT '내정가액산정일자',
  `resv_vlamt_pout_mtt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '내정가액특이사항',
  `dnwd_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '격락사유코드',
  `dnwd_rt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '격락율',
  `crnt_mprc_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '현시세금액',
  `mprc_cnf_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시세확인방법코드',
  `dc_acsam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공제부품금액',
  `dc_wag_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공제공임금액',
  `dc_cs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '공제비용',
  `sb_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물유형코드',
  `sb_spc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물내역',
  `gear_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기어종류코드',
  `fuel_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연료구분코드',
  `tracs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '견인비',
  `keepc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보관료',
  `nv_rqcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '조사의뢰비',
  `et_csamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기타비용금액',
  `tnd_plc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰장소구분코드',
  `nxt_dgre_aucdt` date DEFAULT NULL COMMENT '다음차수경매일자',
  `nxt_dgre_auc_hms` decimal(4,0) DEFAULT NULL COMMENT '다음차수경매시간',
  `resv_vlamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '내정가액구분코드',
  `prdm_mprc_cramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대물시세차량가액',
  `dp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '매각구분코드',
  `sb_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물처리구분코드',
  `xp_py_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '예상지급보험금액',
  `sb_ex_xpamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '잔존물환입예상금액',
  `tnd_entp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입찰업체구분코드',
  `cr_yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량연식',
  `trvl_dst` decimal(7,0) DEFAULT NULL COMMENT '주행거리',
  `psn_crp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인법인구분코드',
  `et_cs_rs` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타비용사유',
  `smamt` decimal(15,0) DEFAULT '0' COMMENT '합계금액',
  `sb_cs_chrg_metd_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물비용부담방식코드',
  `sb_keep_entnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물보관업체명',
  `sb_keep_chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물보관담당자명',
  `sb_keep_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물보관주소',
  `sb_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물전화지역번호',
  `sb_tl_tno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물전화국번',
  `sb_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물전화일련번호',
  `biamt_opb_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '낙찰가공개여부',
  `sb_et_tp_rs` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '잔존물기타유형사유',
  `af_dl_inscp_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '후처리보험사코드',
  `af_dl_inscp_dm_flg_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '후처리보험사손해구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_tnd_spc_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`tnd_dgre`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='입찰내역';
