--
-- Table structure for table `ccm_adv_aos_dmdr`
--

DROP TABLE IF EXISTS `ccm_adv_aos_dmdr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_adv_aos_dmdr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `rltm_rcv_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '실시간수신여부',
  `dm_ts_seqno` decimal(3,0) NOT NULL COMMENT '청구전송순번',
  `dm_seq` decimal(3,0) NOT NULL COMMENT '청구회차',
  `dmdr_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청구처종류코드',
  `dmdr_bzmno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청구처사업자번호',
  `aos_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS담보코드',
  `dmdrm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구처명',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `aos_admno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS관리번호',
  `dmdt` date DEFAULT NULL COMMENT '청구일자',
  `dm_hms` decimal(4,0) DEFAULT NULL COMMENT '청구시간',
  `dmas_entp_agryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해사정업체동의여부',
  `dmas_entp_agmdt` date DEFAULT NULL COMMENT '손해사정업체동의일자',
  `dmas_entp_agre_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해사정업체동의시간',
  `rnt_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트경로코드',
  `hndov_plccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인계장소코드',
  `hndov_plc_memo` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인계장소메모',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `rntnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차인명',
  `rntps_hpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차인휴대폰번호',
  `rnt_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트차량번호',
  `rnt_crcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트차량코드',
  `rnt_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트차량명',
  `rnt_car_mdlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트차량모델코드',
  `rnt_car_mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트차량모델명',
  `dm_rnt_strdt` date DEFAULT NULL COMMENT '청구렌트시작일자',
  `as_rnt_strdt` date DEFAULT NULL COMMENT '사정렌트시작일자',
  `dm_rnt_str_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구렌트시작시간',
  `as_rnt_str_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정렌트시작시간',
  `dm_rnt_rtndt` date DEFAULT NULL COMMENT '청구렌트반납일자',
  `as_rnt_rtndt` date DEFAULT NULL COMMENT '사정렌트반납일자',
  `dm_rnt_rtn_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구렌트반납시간',
  `as_rnt_rtn_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정렌트반납시간',
  `dm_rnt_days` decimal(5,0) DEFAULT NULL COMMENT '청구렌트일수',
  `as_rnt_days` decimal(5,0) DEFAULT NULL COMMENT '사정렌트일수',
  `dm_rnt_hms` decimal(4,0) DEFAULT NULL COMMENT '청구렌트시간',
  `as_rnt_hms` decimal(4,0) DEFAULT NULL COMMENT '사정렌트시간',
  `dm_cg_dscrt` decimal(3,0) DEFAULT NULL COMMENT '청구요금할인율',
  `as_cg_dscrt` decimal(3,0) DEFAULT NULL COMMENT '사정요금할인율',
  `dm_rnt_appr_dunpr` decimal(15,0) DEFAULT NULL COMMENT '청구렌트인정일단가',
  `as_rnt_appr_dunpr` decimal(15,0) DEFAULT NULL COMMENT '사정렌트인정일단가',
  `dm_rnt_appr_days` decimal(5,0) DEFAULT NULL COMMENT '청구렌트인정일수',
  `as_rnt_appr_days` decimal(5,0) DEFAULT NULL COMMENT '사정렌트인정일수',
  `dm_rnt_appr_hunpr` decimal(15,0) DEFAULT NULL COMMENT '청구렌트인정시간단가',
  `as_rnt_appr_hunpr` decimal(15,0) DEFAULT NULL COMMENT '사정렌트인정시간단가',
  `dm_rnt_appr_hms` decimal(4,0) DEFAULT NULL COMMENT '청구렌트인정시간',
  `as_rnt_appr_hms` decimal(4,0) DEFAULT NULL COMMENT '사정렌트인정시간',
  `balcs_or_rcaam` decimal(15,0) DEFAULT NULL COMMENT '대차료/휴차료',
  `tabl_meta_id` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '테이블메타ID',
  `meta_atr_1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성1값',
  `meta_atr_2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성2값',
  `meta_atr_3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성3값',
  `meta_atr_4_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성4값',
  `meta_atr_5_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성5값',
  `meta_atr_6_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성6값',
  `meta_atr_7_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성7값',
  `meta_atr_8_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성8값',
  `meta_atr_9_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성9값',
  `meta_atr_10_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성10값',
  `meta_atr_11_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성11값',
  `meta_atr_12_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성12값',
  `meta_atr_13_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성13값',
  `meta_atr_14_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성14값',
  `meta_atr_15_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성15값',
  `meta_atr_16_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성16값',
  `meta_atr_17_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성17값',
  `meta_atr_18_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성18값',
  `meta_atr_19_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성19값',
  `meta_atr_20_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성20값',
  `meta_atr_21_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성21값',
  `meta_atr_22_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성22값',
  `meta_atr_23_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성23값',
  `meta_atr_24_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성24값',
  `meta_atr_25_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성25값',
  `meta_atr_26_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성26값',
  `meta_atr_27_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성27값',
  `meta_atr_28_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성28값',
  `meta_atr_29_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성29값',
  `meta_atr_30_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성30값',
  `meta_atr_31_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성31값',
  `meta_atr_32_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성32값',
  `meta_atr_33_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성33값',
  `meta_atr_34_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성34값',
  `meta_atr_35_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성35값',
  `meta_atr_36_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성36값',
  `meta_atr_37_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성37값',
  `meta_atr_38_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성38값',
  `meta_atr_39_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성39값',
  `meta_atr_40_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성40값',
  `meta_atr_41_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성41값',
  `meta_atr_42_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성42값',
  `meta_atr_43_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성43값',
  `meta_atr_44_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성44값',
  `meta_atr_45_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성45값',
  `meta_atr_46_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성46값',
  `meta_atr_47_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성47값',
  `meta_atr_48_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성48값',
  `meta_atr_49_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성49값',
  `meta_atr_50_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성50값',
  `meta_atr_51_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성51값',
  `meta_atr_52_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성52값',
  `meta_atr_53_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성53값',
  `meta_atr_54_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성54값',
  `meta_atr_55_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성55값',
  `meta_atr_56_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성56값',
  `meta_atr_57_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성57값',
  `meta_atr_58_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성58값',
  `meta_atr_59_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성59값',
  `meta_atr_60_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성60값',
  `meta_atr_61_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성61값',
  `meta_atr_62_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성62값',
  `meta_atr_63_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성63값',
  `meta_atr_64_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성64값',
  `meta_atr_65_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성65값',
  `meta_atr_66_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성66값',
  `meta_atr_67_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성67값',
  `meta_atr_68_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성68값',
  `meta_atr_69_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성69값',
  `meta_atr_70_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성70값',
  `meta_atr_71_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성71값',
  `meta_atr_72_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성72값',
  `meta_atr_73_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성73값',
  `meta_atr_74_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성74값',
  `meta_atr_75_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성75값',
  `meta_atr_76_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성76값',
  `meta_atr_77_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성77값',
  `meta_atr_78_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성78값',
  `meta_atr_79_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성79값',
  `meta_atr_80_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성80값',
  `meta_atr_81_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성81값',
  `meta_atr_82_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성82값',
  `meta_atr_83_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성83값',
  `meta_atr_84_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성84값',
  `meta_atr_85_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성85값',
  `meta_atr_86_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성86값',
  `meta_atr_87_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성87값',
  `meta_atr_88_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성88값',
  `meta_atr_89_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성89값',
  `meta_atr_90_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성90값',
  `meta_atr_91_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성91값',
  `meta_atr_92_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성92값',
  `meta_atr_93_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성93값',
  `meta_atr_94_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성94값',
  `meta_atr_95_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성95값',
  `meta_atr_96_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성96값',
  `meta_atr_97_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성97값',
  `meta_atr_98_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성98값',
  `meta_atr_99_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성99값',
  `meta_atr_100_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성100값',
  `meta_atr_101_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성101값',
  `meta_atr_102_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성102값',
  `meta_atr_103_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성103값',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_adv_aos_dmdr_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`rltm_rcv_yn`,`dm_ts_seqno`,`dm_seq`,`dmdr_kndcd`,`dmdr_bzmno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='선진화AOS청구처';
