--
-- Table structure for table `ccm_adv_aos_frst_stm`
--

DROP TABLE IF EXISTS `ccm_adv_aos_frst_stm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_adv_aos_frst_stm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `frst_stm_seq` decimal(3,0) NOT NULL COMMENT '선견적회차',
  `rltm_rcv_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '실시간수신여부',
  `frst_stm_ts_seqno` decimal(3,0) NOT NULL COMMENT '선견적전송순번',
  `aos_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS담보코드',
  `frst_stm_seqno` decimal(3,0) NOT NULL COMMENT '선견적순번',
  `aos_admno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS관리번호',
  `frst_stm_wrtdt` date DEFAULT NULL COMMENT '선견적작성일자',
  `frst_stm_wrt_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선견적작성시간',
  `frst_stm_tsdt` date DEFAULT NULL COMMENT '선견적전송일자',
  `frst_stm_ts_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선견적전송시간',
  `paym_gu_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지불보증여부',
  `paym_gu_dt` date DEFAULT NULL COMMENT '지불보증일자',
  `paym_gu_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지불보증시간',
  `xmn_ctn_asr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토의견회신여부',
  `xmn_ctn_asrdt` date DEFAULT NULL COMMENT '검토의견회신일자',
  `xmn_ctn_asr_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토의견회신시간',
  `xmn_ctn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토의견구분코드',
  `xmn_ctn_memo` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검토의견메모',
  `dmas_dt` date DEFAULT NULL COMMENT '손해사정일자',
  `dmas_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해사정시간',
  `wrk_memo` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '작업메모',
  `rpair_strdt` date DEFAULT NULL COMMENT '수리시작일자',
  `rpair_str_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리시작시간',
  `rpair_nd_prdt` date DEFAULT NULL COMMENT '수리종료예정일자',
  `rpair_nd_pr_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리종료예정시간',
  `xp_rpair_days` decimal(5,0) DEFAULT NULL COMMENT '예상수리일수',
  `mntn_fctcd` varchar(12) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정비공장코드',
  `mntn_fctnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정비공장명',
  `inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사코드',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직원번호',
  `chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자명',
  `rpair_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량번호',
  `rpair_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차대번호',
  `owrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자명',
  `drvnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자명',
  `drv_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자전화번호',
  `drv_mail_adr` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자이메일주소',
  `rpair_crcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량코드',
  `rpair_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량명',
  `rpair_car_mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량모델명',
  `rpair_cramt` decimal(15,0) DEFAULT NULL COMMENT '수리차량가액',
  `rpair_car_trvl_dst` decimal(7,0) DEFAULT NULL COMMENT '수리차량주행거리',
  `rpair_car_schnd_amt` decimal(15,0) DEFAULT NULL COMMENT '수리차량중고금액',
  `rpair_cr_fr_rgtdt` date DEFAULT NULL COMMENT '수리차량최초등록일자',
  `rpair_car_ac_apdt` date DEFAULT NULL COMMENT '수리차량부품적용일자',
  `nrd_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험차량번호',
  `nrdps_cr_owrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자차량소유자명',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `ntgdt` date DEFAULT NULL COMMENT '입고일자',
  `tra_plc` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '견인장소',
  `tra_dst` decimal(3,0) DEFAULT NULL COMMENT '견인거리',
  `tra_engnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '견인기사명',
  `ctp_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종용도코드',
  `aos_own_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS소유구분코드',
  `aos_ntg_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS입고경로코드',
  `aos_ver_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS버전구분코드',
  `brow_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브라우저종류코드',
  `aos_dl_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS처리방법코드',
  `aos_dm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS손해구분코드',
  `as_tkatt_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정탈부착작업시간종류코드',
  `dm_tkatt_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구탈부착작업시간종류코드',
  `dm_cotg_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구도장작업시간종류코드',
  `as_cotg_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정도장작업시간종류코드',
  `dm_cotgc_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구도장코트종류코드',
  `as_cotgc_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정도장코트종류코드',
  `tabl_meta_id` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '테이블메타ID',
  `meta_atr_1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성1값',
  `meta_atr_2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성2값',
  `meta_atr_3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성3값',
  `meta_atr_4_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성4값',
  `meta_atr_5_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성5값',
  `meta_atr_6_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성6값',
  `meta_atr_7_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성7값',
  `meta_atr_8_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성8값',
  `meta_atr_9_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성9값',
  `meta_atr_10_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성10값',
  `meta_atr_11_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성11값',
  `meta_atr_12_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성12값',
  `meta_atr_13_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성13값',
  `meta_atr_14_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성14값',
  `meta_atr_15_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성15값',
  `meta_atr_16_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성16값',
  `meta_atr_17_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성17값',
  `meta_atr_18_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성18값',
  `meta_atr_19_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성19값',
  `meta_atr_20_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성20값',
  `meta_atr_21_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성21값',
  `meta_atr_22_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성22값',
  `meta_atr_23_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성23값',
  `meta_atr_24_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성24값',
  `meta_atr_25_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성25값',
  `meta_atr_26_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성26값',
  `meta_atr_27_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성27값',
  `meta_atr_28_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성28값',
  `meta_atr_29_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성29값',
  `meta_atr_30_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성30값',
  `meta_atr_31_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성31값',
  `meta_atr_32_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성32값',
  `meta_atr_33_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성33값',
  `meta_atr_34_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성34값',
  `meta_atr_35_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성35값',
  `meta_atr_36_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성36값',
  `meta_atr_37_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성37값',
  `meta_atr_38_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성38값',
  `meta_atr_39_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성39값',
  `meta_atr_40_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성40값',
  `meta_atr_41_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성41값',
  `meta_atr_42_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성42값',
  `meta_atr_43_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성43값',
  `meta_atr_44_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성44값',
  `meta_atr_45_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성45값',
  `meta_atr_46_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성46값',
  `meta_atr_47_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성47값',
  `meta_atr_48_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성48값',
  `meta_atr_49_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성49값',
  `meta_atr_50_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성50값',
  `meta_atr_51_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성51값',
  `meta_atr_52_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성52값',
  `meta_atr_53_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성53값',
  `meta_atr_54_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성54값',
  `meta_atr_55_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성55값',
  `meta_atr_56_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성56값',
  `meta_atr_57_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성57값',
  `meta_atr_58_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성58값',
  `meta_atr_59_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성59값',
  `meta_atr_60_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성60값',
  `meta_atr_61_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성61값',
  `meta_atr_62_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성62값',
  `meta_atr_63_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성63값',
  `meta_atr_64_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성64값',
  `meta_atr_65_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성65값',
  `meta_atr_66_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성66값',
  `meta_atr_67_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성67값',
  `meta_atr_68_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성68값',
  `meta_atr_69_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성69값',
  `meta_atr_70_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성70값',
  `meta_atr_71_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성71값',
  `meta_atr_72_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성72값',
  `meta_atr_73_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성73값',
  `meta_atr_74_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성74값',
  `meta_atr_75_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성75값',
  `meta_atr_76_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성76값',
  `meta_atr_77_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성77값',
  `meta_atr_78_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성78값',
  `meta_atr_79_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성79값',
  `meta_atr_80_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성80값',
  `meta_atr_81_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성81값',
  `meta_atr_82_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성82값',
  `meta_atr_83_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성83값',
  `meta_atr_84_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성84값',
  `meta_atr_85_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성85값',
  `meta_atr_86_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성86값',
  `meta_atr_87_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성87값',
  `meta_atr_88_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성88값',
  `meta_atr_89_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성89값',
  `meta_atr_90_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성90값',
  `meta_atr_91_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성91값',
  `meta_atr_92_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성92값',
  `meta_atr_93_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성93값',
  `meta_atr_94_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성94값',
  `meta_atr_95_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성95값',
  `meta_atr_96_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성96값',
  `meta_atr_97_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성97값',
  `meta_atr_98_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성98값',
  `meta_atr_99_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성99값',
  `meta_atr_100_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성100값',
  `meta_atr_101_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성101값',
  `meta_atr_102_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성102값',
  `meta_atr_103_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성103값',
  `meta_atr_104_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성104값',
  `meta_atr_105_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성105값',
  `meta_atr_106_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성106값',
  `meta_atr_107_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성107값',
  `meta_atr_108_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성108값',
  `meta_atr_109_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성109값',
  `meta_atr_110_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성110값',
  `meta_atr_111_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성111값',
  `meta_atr_112_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성112값',
  `mfgdt` date DEFAULT NULL COMMENT '출고일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_adv_aos_frst_stm_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`frst_stm_seq`,`rltm_rcv_yn`,`frst_stm_ts_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='선진화AOS선견적';
