--
-- Table structure for table `ccm_pln_mvo`
--

DROP TABLE IF EXISTS `ccm_pln_mvo`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_pln_mvo` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `pln_mvo_seqno` decimal(3,0) NOT NULL COMMENT '현장출동순번',
  `stmvo_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동구분코드',
  `clm_pln_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고현장조치유무',
  `flt_qrrl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과실다툼유무',
  `lrge_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대형사고유무',
  `main_chrct_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주요인물사고유무',
  `is_fct_crtfn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입사실증명원유무',
  `mvo_rq_et_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동요청기타사유',
  `mvodt` date NOT NULL COMMENT '출동일자',
  `mvo_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '출동시분',
  `mvo_ordr_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '출동지시직원번호',
  `mvo_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동담당자직원번호',
  `pln_mvops_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동자구분코드',
  `mvo_awamt` decimal(15,0) DEFAULT '0' COMMENT '출동수당금액',
  `aw_appr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수당인정여부',
  `aw_md_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수당조정사유코드',
  `ctm_x_cdnvl` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객X좌표값',
  `ctm_y_cdnvl` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객Y좌표값',
  `mvo_rq_et_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동요청기타여부',
  `mvo_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동결과코드',
  `mvo_ccl_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동취소사유코드',
  `mvo_ccl_et_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동취소기타사유',
  `arvdt` date DEFAULT NULL COMMENT '도착일자',
  `arv_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도착시분',
  `mng_cpldt` date DEFAULT NULL COMMENT '조치완료일자',
  `mng_cplt_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조치완료시분',
  `py_dmbil_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급청구서유무',
  `licce_cpy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허증사본유무',
  `cr_rgtce_cpy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량등록증사본유무',
  `et_clrq_dcu_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타징구서류유무',
  `et_clrq_dcunm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타징구서류명',
  `nots` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요',
  `emeg_mvo_rcpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '긴급출동접수번호',
  `cvap_xpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원예상코드',
  `prnt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자성명',
  `prnt_tl_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자전화지역번호',
  `prnt_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자전화국번',
  `prnt_tl_sno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자전화일련번호',
  `prnt_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보내용',
  `rpt_cplt_dthms` datetime DEFAULT NULL COMMENT '보고완료일시',
  `pln_mvops_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동자ID',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '협력업체순번',
  `mstr_car_rcpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마스터카접수번호',
  `mstr_car_rcp_chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마스터카접수담당자명',
  `pln_mvo_tlmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동전문코드',
  `mvo_entcd` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동업체코드',
  `mvo_entnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동업체명',
  `mvo_entp_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동업체전화지역번호',
  `mvo_entp_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동업체전화국번',
  `mvo_entp_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동업체전화일련번호',
  `mvo_engnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사명',
  `mvo_engnr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사전화지역번호',
  `mvo_engnr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사전화국번',
  `mvo_engnr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동기사전화일련번호',
  `mng_pout_mtt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조치특이사항',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_pln_mvo_00` (`rcp_yymm`,`rcp_nv_seqno`,`pln_mvo_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='현장출동';
