--
-- Table structure for table `ccm_ai_aos_frst_stm`
--

DROP TABLE IF EXISTS `ccm_ai_aos_frst_stm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_ai_aos_frst_stm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `frst_stm_seq` decimal(3,0) NOT NULL COMMENT '선견적회차',
  `rltm_rcv_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '실시간수신여부',
  `frst_stm_ts_seqno` decimal(3,0) NOT NULL COMMENT '선견적전송순번',
  `aos_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS담보코드',
  `frst_stm_seqno` decimal(3,0) NOT NULL COMMENT '선견적순번',
  `aos_admno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS관리번호',
  `ai_stm_id` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인공지능견적ID',
  `ai_stm_seqno` decimal(3,0) DEFAULT NULL COMMENT '인공지능견적순번',
  `ai_stm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인공지능견적구분코드',
  `ai_frst_stm_wrtdt` date DEFAULT NULL COMMENT '인공지능선견적작성일자',
  `ai_frst_stm_wrt_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인공지능선견적작성시간',
  `ai_frst_stm_tsdt` date DEFAULT NULL COMMENT '인공지능선견적전송일자',
  `ai_frst_stm_ts_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인공지능선견적전송시간',
  `dmdr_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구처사업자번호',
  `dmdrm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구처명',
  `inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사코드',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직원번호',
  `chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자명',
  `rpair_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량번호',
  `rpair_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차대번호',
  `rpair_crcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량코드',
  `rpair_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량명',
  `rpair_car_mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량모델명',
  `rpair_car_trvl_dst` decimal(7,0) DEFAULT NULL COMMENT '수리차량주행거리',
  `rpair_cr_fr_rgtdt` date DEFAULT NULL COMMENT '수리차량최초등록일자',
  `rpair_car_ac_apdt` date DEFAULT NULL COMMENT '수리차량부품적용일자',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `ntgdt` date DEFAULT NULL COMMENT '입고일자',
  `aos_ntg_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS입고경로코드',
  `tabl_meta_id` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '테이블메타ID',
  `meta_atr_1_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성1값',
  `meta_atr_3_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성3값',
  `meta_atr_5_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성5값',
  `dm_tkatt_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구탈부착작업시간종류코드',
  `meta_atr_7_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성7값',
  `meta_atr_9_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성9값',
  `meta_atr_11_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성11값',
  `meta_atr_13_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성13값',
  `meta_atr_15_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성15값',
  `meta_atr_27_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성27값',
  `meta_atr_19_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성19값',
  `meta_atr_25_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성25값',
  `dm_cotg_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구도장작업시간종류코드',
  `dm_cotg_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구도장분류코드',
  `dm_cotg_colr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구도장컬러명',
  `dm_cotgc_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구도장코트종류코드',
  `dm_tot_cotam` decimal(15,0) DEFAULT NULL COMMENT '청구전체도장금액',
  `dm_tot_cotg_aprt` decimal(5,2) DEFAULT NULL COMMENT '청구전체도장적용율',
  `dm_part_shtmt_aprt` decimal(5,2) DEFAULT NULL COMMENT '청구부분판금적용율',
  `dm_matcs_aprt` decimal(5,2) DEFAULT NULL COMMENT '청구재료비적용율',
  `meta_atr_35_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성35값',
  `meta_atr_41_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성41값',
  `meta_atr_43_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성43값',
  `meta_atr_45_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성45값',
  `meta_atr_47_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성47값',
  `meta_atr_49_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성49값',
  `meta_atr_51_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성51값',
  `meta_atr_93_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성93값',
  `meta_atr_95_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성95값',
  `meta_atr_97_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성97값',
  `meta_atr_59_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성59값',
  `meta_atr_57_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성57값',
  `meta_atr_65_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성65값',
  `meta_atr_67_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성67값',
  `meta_atr_85_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성85값',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_ai_aos_frst_stm_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`frst_stm_seq`,`rltm_rcv_yn`,`frst_stm_ts_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='AIAOS선견적';
