--
-- Table structure for table `ccm_dm_rd_rptg`
--

DROP TABLE IF EXISTS `ccm_dm_rd_rptg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_dm_rd_rptg` (
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험종목코드',
  `dm_rd_rptg_seqno` decimal(3,0) NOT NULL COMMENT '손해감소보고서순번',
  `siu_admno_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SIU관리번호년도',
  `siu_admno_seqno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SIU관리번호순번',
  `psclm_xi_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인사고추산보험금액',
  `gd_clm_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '물사고추산보험금액',
  `psclm_xp_dmamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인사고예상손해금액',
  `gd_clm_xp_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '물사고예상보험금액',
  `psclm_rcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인사고환수금액',
  `prclm_rcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '물사고환수금액',
  `ltrm_gn_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장기일반추산보험금액',
  `ltrm_gn_xp_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장기일반예상보험금액',
  `ltrm_gn_rcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장기일반환수금액',
  `imu_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면책유형코드',
  `rptdt` date DEFAULT NULL COMMENT '보고일자',
  `detc_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사기관명',
  `ndtdt` date DEFAULT NULL COMMENT '고발일자',
  `detc_cn` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사내용',
  `vwpt` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '착안점',
  `imu_mtt_dmnst_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면책사항입증내용',
  `nvgt_cnb_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사역기여내용',
  `rptg_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보고서상태코드',
  `vl_appr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가인정여부',
  `psclm_ibamt_rdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인사고보험금액감소금액',
  `gd_clm_ibamt_rdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '물사고보험금액감소금액',
  `ltrm_gn_ibamt_rdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장기일반보험금액감소금액',
  `moff_vl_vwbl_poct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '본점평가착안점수',
  `dfwk_poct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '난이도점수',
  `fdg_poct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '노력도점수',
  `psc_pmn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검찰경찰구분코드',
  `lclt_psc_pmncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지방검찰경찰코드',
  `psc_pcecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검찰경찰서코드',
  `wrter_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '작성자직원번호',
  `wrtdt` date DEFAULT NULL COMMENT '작성일자',
  `vl_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가년월',
  `cvap_rcgnt_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '민원인식여부',
  `rptg_nv_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보고서조사유형코드',
  `detc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사여부',
  `otcm_ltrm_amt_rdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '타사장기금액감소금액',
  `dm_rd_vl_poct` decimal(7,2) DEFAULT NULL COMMENT '손해감소평가점수',
  `non_appr_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '불인정사유',
  `prnt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보유형코드',
  `ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전송여부',
  `sdpst_acd_detc_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건수사기관명',
  `sdpst_acd_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건년도',
  `sdpst_acdno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건번호',
  `crmcs_acd_detc_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사사건수사기관명',
  `crmcs_jstno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사재판번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`rcp_yymm`,`rcp_nv_seqno`,`ins_imcd`,`dm_rd_rptg_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손해감소보고서';
