--
-- Table structure for table `ccm_is_fct_crtfn_is`
--

DROP TABLE IF EXISTS `ccm_is_fct_crtfn_is`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_is_fct_crtfn_is` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `is_ordr` decimal(5,0) NOT NULL COMMENT '발급순차',
  `cmpu_isdt` date NOT NULL COMMENT '전산발급일자',
  `cmpu_is_seqno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '전산발급순번',
  `crtfn_is_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '증명원발급구분코드',
  `reis_rscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '재발급사유코드',
  `et_reis_rs` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타재발급사유',
  `ogcy_ry_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원본회수여부',
  `hwrk_is_seqno` decimal(5,0) DEFAULT NULL COMMENT '수작업발급순번',
  `isps_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '발급자직원번호',
  `isdt` date NOT NULL COMMENT '발급일자',
  `rqapl_ctmno` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT '신청인고객번호',
  `nrdps_relcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자관계코드',
  `trnm_vcrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전달대행코드',
  `rcr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수령자명',
  `fax_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스지역번호',
  `fax_tno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스국번',
  `fax_sno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스일련번호',
  `drv_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자고객번호',
  `drvnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자명',
  `clm_plc_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소우편번호',
  `clm_plc_sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소시도',
  `clm_plc_sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소시군구',
  `clm_plc_twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소읍면동',
  `clplc_ri_or_lrdlp` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소리/대량배달처',
  `clm_plc_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소상세주소',
  `hwy_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고속도로사고여부',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `clm_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고차량번호',
  `pcenm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경찰서명',
  `bdin_prs_vicnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인대표피해자명',
  `bdin_victm_num` decimal(3,0) DEFAULT NULL COMMENT '대인피해자수',
  `prdm_prs_dmgnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물대표피해물명',
  `prdm_dmgit_num` decimal(3,0) DEFAULT NULL COMMENT '대물피해물수',
  `is_pth_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발급경로구분코드',
  `nw_clplc_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신사고장소우편번호',
  `nw_ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신리/대량배달처',
  `nw_clplc_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신사고장소참고항목',
  `nw_clplc_road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신사고장소도로명',
  `nw_clplc_undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신사고장소지하구분코드',
  `nw_clplc_mn_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신사고장소주건물번호',
  `nw_clplc_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신사고장소부건물번호',
  `nw_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신참고항목',
  `nw_road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신도로명',
  `nw_undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신지하구분코드',
  `nw_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신주건물번호',
  `nw_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_is_fct_crtfn_is_00` (`rcp_yymm`,`rcp_nv_seqno`,`is_ordr`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='가입사실증명원발급';
