--
-- Table structure for table `ccm_pln_mvo_cplt_rpt`
--

DROP TABLE IF EXISTS `ccm_pln_mvo_cplt_rpt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_pln_mvo_cplt_rpt` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `pln_mvo_seqno` decimal(3,0) NOT NULL COMMENT '현장출동순번',
  `arv_stt_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도착상황코드',
  `dmge_stt_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해상황코드',
  `clm_rsm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고개요내용',
  `pln_mvo_dmge_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동피해코드',
  `ot_inscp_mvo_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타보험사출동여부',
  `pln_photo_pht_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장사진촬영여부',
  `pln_idc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장표시여부',
  `owcr_tra_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자차견인여부',
  `et_pout_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타특이사항',
  `pln_rpt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장보고여부',
  `wrt_dthms` datetime DEFAULT NULL COMMENT '작성일시',
  `victm_psct` decimal(3,0) DEFAULT NULL COMMENT '피해자인원수',
  `dmgit_tct` decimal(3,0) DEFAULT NULL COMMENT '피해물총건수',
  `emeg_mvo_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '긴급출동여부',
  `drvnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자명',
  `nrdps_drv_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자운전자관계코드',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `drv_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자주민번호',
  `lic_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허종별코드',
  `licno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허번호',
  `vald_trm_stdt` date DEFAULT NULL COMMENT '유효기간시기일자',
  `vald_trm_clsdt` date DEFAULT NULL COMMENT '유효기간종기일자',
  `rptg_wrt_flg_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보고서작성구분코드',
  `lic_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허유무',
  `lic_arecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허지역코드',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `pce_rpr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경찰서신고여부',
  `pcenm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경찰서명',
  `chr_pmn_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경찰명',
  `chr_pmn_tl_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경찰전화지역번호',
  `chr_pmn_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경찰전화국번',
  `chr_pmn_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경찰전화일련번호',
  `cvap_xpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원예상코드',
  `cas_of_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원인제공차량명',
  `cas_of_carno` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원인제공차량번호',
  `prnt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자성명',
  `prnt_tl_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자전화지역번호',
  `prnt_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자전화국번',
  `prnt_tl_sno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보자전화일련번호',
  `prnt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보유형코드',
  `prnt_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제보내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_pln_mvo_cplt_rpt_00` (`rcp_yymm`,`rcp_nv_seqno`,`pln_mvo_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='현장출동완료보고';
