--
-- Table structure for table `ccm_clm_rcp_nv`
--

DROP TABLE IF EXISTS `ccm_clm_rcp_nv`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_clm_rcp_nv` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `rcp_nv_crr_seqno` decimal(3,0) NOT NULL COMMENT '접수조사이력순번',
  `ap_str_dthms` datetime NOT NULL COMMENT '적용시작일시',
  `ap_nd_dthms` datetime NOT NULL COMMENT '적용종료일시',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `clmdt` date NOT NULL COMMENT '사고일자',
  `db_clmno` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '중복사고번호',
  `clm_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '사고시분',
  `cr_cnf_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '계약확인여부',
  `nrdps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객번호',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `nrdps_rl_jb_kornm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자실제직업한글명',
  `gpc_xstf_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '그룹사임직원관계코드',
  `clm_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고차량번호',
  `carnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차명',
  `clm_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고차량구분코드',
  `cr_inqno` decimal(4,0) DEFAULT NULL COMMENT '차량조회번호',
  `rprnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '통보자명',
  `nrdps_rprtr_relcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자통보자관계코드',
  `rprtr_cntad_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '통보자연락처구분코드',
  `rprtr_tlano` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '통보자전화지역번호',
  `rprtr_tltno` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '통보자전화국번',
  `rprtr_tlsno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '통보자전화일련번호',
  `drvnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자명',
  `drv_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자고객번호',
  `age` decimal(3,0) DEFAULT NULL COMMENT '연령',
  `lic_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허종별코드',
  `licno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허번호',
  `sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성별코드',
  `nrdps_drv_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자운전자관계코드',
  `drv_cntad_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자연락처구분코드',
  `drv_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자전화지역번호',
  `drv_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자전화국번',
  `drv_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자전화일련번호',
  `drv_rl_jb_kornm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자실제직업한글명',
  `rcp_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '접수유형코드',
  `clm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고유형코드',
  `ctm_rq_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객요구유형코드',
  `pln_mvo_rq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동요청여부',
  `stmvo_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동구분코드',
  `frst_stmvo_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선현장출동여부',
  `pce_rpr_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '경찰서신고여부',
  `pcenm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경찰서명',
  `pmn_acdno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경찰사건번호',
  `rp119_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '119신고여부',
  `chr_pofnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경관명',
  `chr_pof_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경관전화지역번호',
  `chr_pof_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경관전화국번',
  `chr_pof_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당경관전화일련번호',
  `rcpdt` date NOT NULL COMMENT '접수일자',
  `rcp_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '접수시분',
  `rcpr_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '접수자직원번호',
  `as_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배정직원번호',
  `gn_bz_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '보장사업여부',
  `hrm_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해자주민번호',
  `hrmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해자명',
  `hrm_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해자전화지역번호',
  `hrm_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해자전화국번',
  `hrm_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해자전화일련번호',
  `hrm_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해자차량번호',
  `harm_cr_owrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량소유자명',
  `harm_car_ownr_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량소유자주민번호',
  `drv_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자주민번호',
  `drv_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자직업코드',
  `harm_cr_ownr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량소유자전화지역번호',
  `harm_cr_ownr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량소유자전화국번',
  `harm_cr_ownr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량소유자전화일련번호',
  `harm_cr_is_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량가입회사코드',
  `harm_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가해차량명',
  `is_cr_ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입차량보험종목코드',
  `gvmt_gn_bzclm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장사업사고유형코드',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직원번호',
  `gd_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물담당자직원번호',
  `road_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로형태코드',
  `et_clm_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타사고원인코드',
  `nrdps_flt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자과실여부',
  `clm_nv_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고조사결과코드',
  `co_ilglt_bhvcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동불법행위코드',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin NOT NULL COMMENT '사고내용',
  `oper_rowcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운행경위코드',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `rob_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '도난유무',
  `clm_cr_chncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고발생채널코드',
  `hwy_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고속도로사고여부',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `owcr_bordn_psct` decimal(5,0) DEFAULT NULL COMMENT '자차탑승인원수',
  `owcr_tra_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자차견인여부',
  `owcr_asent_ntc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자차지정업체안내여부',
  `asmt_entp_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지정업체고객번호',
  `asmt_entp_cpent_seqno` decimal(3,0) DEFAULT NULL COMMENT '지정업체협력업체순번',
  `asmt_entp_ntc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지정업체안내여부',
  `noflt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무과실구분코드',
  `pln_mvo_xp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동예상여부',
  `bdin_sms_rcv_rejet_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인SMS수신거부여부',
  `prdm_sms_rcv_rejet_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물SMS수신거부여부',
  `gu_fire_rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구화재접수년월',
  `gu_fire_rcpnv_seqno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구화재접수조사순번',
  `cmp_rcp_pth_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상접수경로구분코드',
  `ag_drv_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리운전자사고여부',
  `nw_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신우편번호',
  `nw_ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신리/대량배달처',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `noflt_xp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무과실예상여부',
  `foma_clmnv_prgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외산사고조사진행코드',
  `madmo_dubt_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마디모의심사고여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_clm_rcp_nv_00` (`rcp_yymm`,`rcp_nv_seqno`,`rcp_nv_crr_seqno`),
  KEY `idx_ccm_clm_rcp_nv_04` (`clmdt`,`ap_nd_dthms`,`rcp_yymm`,`rcp_nv_seqno`),
  KEY `idx_ccm_clm_rcp_nv_07` (`clm_carno`,`ap_nd_dthms`,`rcpdt`),
  KEY `idx_ccm_clm_rcp_nv_01` (`plyno`,`ap_nd_dthms`,`clmdt`,`rcpdt`,`db_clmno`,`clm_hhmm`)
) ENGINE=InnoDB AUTO_INCREMENT=205 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고접수조사';
