--
-- Table structure for table `ccm_dvpns_obi_ibnf`
--

DROP TABLE IF EXISTS `ccm_dvpns_obi_ibnf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_dvpns_obi_ibnf` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `adm_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '관리년월',
  `adm_sno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '관리일련번호',
  `dvpns_ins_cmpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원보험회사코드',
  `clm_cvr_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고담보종목코드',
  `dvpns_obi_da_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원자손자료구분코드',
  `clm_sno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고일련번호',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해서열',
  `end_cmp_tmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결보상팀명',
  `end_chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결담당자명',
  `end_chrps_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결담당자전화번호',
  `clm_dthms` datetime DEFAULT NULL COMMENT '사고일시',
  `clm_plc_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소우편번호',
  `fnl_enddt` date DEFAULT NULL COMMENT '최종종결일자',
  `crncd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호코드',
  `dmgit_car_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물차량구분코드',
  `dmgit_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물차량번호',
  `vicnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자명',
  `victm_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자주민번호',
  `victm_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자전화번호',
  `dvpns_clm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원사고구분코드',
  `stinr_wear_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전구착용여부',
  `dvpns_ag_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원합의유형코드',
  `fnl_hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종병원코드',
  `inj_gri` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부상급항',
  `inj_1_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상1보험금액',
  `inj_2_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상2보험금액',
  `inj_3_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상3보험금액',
  `inj_4_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상4보험금액',
  `inj_5_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상5보험금액',
  `inj_6_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상6보험금액',
  `inj_7_ibamt` decimal(15,0) DEFAULT '0' COMMENT '부상7보험금액',
  `dvpns_obi_obs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원자손장해구분코드',
  `lbr_blt_losrt` decimal(5,2) DEFAULT '0.00' COMMENT '노동능력상실율',
  `obs_gri` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장해급항',
  `obs_1_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해1보험금액',
  `obs_2_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해2보험금액',
  `obs_3_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해3보험금액',
  `obs_4_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해4보험금액',
  `obs_5_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해5보험금액',
  `obs_6_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해6보험금액',
  `obs_7_ibamt` decimal(15,0) DEFAULT '0' COMMENT '장해7보험금액',
  `de_1_ibamt` decimal(15,0) DEFAULT '0' COMMENT '사망1보험금액',
  `de_2_ibamt` decimal(15,0) DEFAULT '0' COMMENT '사망2보험금액',
  `de_3_ibamt` decimal(15,0) DEFAULT '0' COMMENT '사망3보험금액',
  `de_4_ibamt` decimal(15,0) DEFAULT '0' COMMENT '사망4보험금액',
  `de_5_ibamt` decimal(15,0) DEFAULT '0' COMMENT '사망5보험금액',
  `de_6_ibamt` decimal(15,0) DEFAULT '0' COMMENT '사망6보험금액',
  `owcr_fltrt` decimal(3,0) DEFAULT '0' COMMENT '자차과실율',
  `othcr_fltrt` decimal(3,0) DEFAULT '0' COMMENT '타차과실율',
  `obi_1_is_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손1가입회사코드',
  `obi_2_is_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손2가입회사코드',
  `obi_3_is_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손3가입회사코드',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고담보코드',
  `thcp_dmge_rank` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당사피해서열',
  `py_ndm_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급미청구사유코드',
  `py_ndm_et_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급미청구기타사유',
  `nbj_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비대상사유코드',
  `nbj_et_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비대상기타사유',
  `obi_clm_rcp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손사고접수여부',
  `dmnst_da_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입증자료유무',
  `dmnst_da_tpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입증자료유형코드',
  `py_obi_ibnf` decimal(15,0) DEFAULT NULL COMMENT '지급자손보험금',
  `ntc_dt` date DEFAULT NULL COMMENT '안내일자',
  `ntc_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안내내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_dvpns_obi_ibnf_00` (`adm_yymm`,`adm_sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개발원자손보험금자료';
