--
-- Table structure for table `ccm_dmge_nv`
--

DROP TABLE IF EXISTS `ccm_dmge_nv`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_dmge_nv` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `dmge_nv_crr_seqno` decimal(3,0) NOT NULL COMMENT '피해조사이력순번',
  `ap_str_dthms` datetime NOT NULL COMMENT '적용시작일시',
  `ap_nd_dthms` datetime NOT NULL COMMENT '적용종료일시',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `rprtr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자성명',
  `rprtr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화지역번호',
  `rprtr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화국번',
  `rprtr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화일련번호',
  `rcpr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수자직원번호',
  `rcp_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수사유',
  `rcpdt` date DEFAULT NULL COMMENT '접수일자',
  `rcp_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수시분',
  `victm_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자고객번호',
  `vicnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자명',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `dmge_nv_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '피해조사상태코드',
  `lw_prp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송제기구분코드',
  `sh_clm_ndt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위장사고고발여부',
  `cvap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원여부',
  `adm_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리담당자직원번호',
  `dmge_crccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해정도코드',
  `psn_info_utl_agrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인정보활용동의코드',
  `dmge_nv_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '피해조사구분코드',
  `idm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상구분코드',
  `gvmt_gn_indc_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장유치자직원번호',
  `gvmt_gn_dmdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장청구자명',
  `gvmt_gn_dmdr_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장청구자주민등록번호',
  `gvmt_gn_dmdr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장청구자전화지역번호',
  `gvmt_gn_dmdr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장청구자전화국번',
  `gvmt_gn_dmdr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장청구자전화일련번호',
  `rcp_nv_crr_seqno` decimal(3,0) DEFAULT NULL COMMENT '접수조사이력순번',
  `rob_nv_seqno` decimal(5,0) DEFAULT NULL COMMENT '도난조사순번',
  `pln_mvo_ag_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장출동합의구분코드',
  `gane_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '양수인고객번호',
  `cprt_entp_pout_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협력업체특이사항',
  `dmgnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물명',
  `dmgit_cnmcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물차명코드',
  `dmgit_carnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물차명',
  `dmgit_yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물년식',
  `fr_rgtdt` date DEFAULT NULL COMMENT '최초등록일자',
  `nwcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차구분코드',
  `dmgit_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물유형코드',
  `dmgit_dt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물세부유형코드',
  `dmgit_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물용도코드',
  `dmgit_catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물차종코드',
  `dmgit_is_inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물가입보험사코드',
  `othcr_drve_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타차운전여부',
  `dma_foma_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국산외산구분코드',
  `cr_dmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량손해코드',
  `cr_inqno` decimal(4,0) DEFAULT NULL COMMENT '차량조회번호',
  `rpair_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리구분코드',
  `rnt_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트사용여부',
  `tra_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '견인여부',
  `ntgdt` date DEFAULT NULL COMMENT '입고일자',
  `xp_rpair_days` decimal(5,0) DEFAULT NULL COMMENT '예상수리일수',
  `rl_cramt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실차량가액합계',
  `rl_cramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실차량가액',
  `rl_caamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실차량부속가액',
  `aoscm_dlrpt_rltn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '아래콤일보연계여부',
  `rcarp_aoscm_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접보아래콤전송여부',
  `end_aoscm_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결아래콤전송여부',
  `mntn_fctnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정비공장명',
  `mntn_fct_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정비공장고객번호',
  `mntn_cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '정비협력업체순번',
  `ismb_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입회방법코드',
  `ntg_supt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입고지원여부',
  `ntg_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입고방법코드',
  `mvamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상가액구분코드',
  `ntg_supt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입고지원직원번호',
  `ntg_gu_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입고보증구분코드',
  `ntg_gu_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입고보증상태코드',
  `ntg_supt_dthms` datetime DEFAULT NULL COMMENT '입고지원일시',
  `ownr_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자식별번호',
  `chsno_or_tmpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차대번호/임시번호',
  `dmgit_dspl` decimal(7,0) DEFAULT NULL COMMENT '피해물배기량',
  `dmgit_colcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물색상코드',
  `cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량용도코드',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성별코드',
  `victm_jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자직업명',
  `victm_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해자상태코드',
  `dmge_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해유형코드',
  `bordn_pstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '탑승위치코드',
  `stinr_wear_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전구착용여부',
  `lic_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면허유무',
  `bordn_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '탑승차량번호',
  `rgtnm_nrdps_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기명피보험자관계코드',
  `bordn_cr_drv_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '탑승차량운전자관계코드',
  `agrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의권자명',
  `agrps_victm_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의권자피해자관계코드',
  `agrps_tl_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의권자전화지역번호',
  `agrps_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의권자전화국번',
  `agrps_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의권자전화일련번호',
  `crmcs_ag_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사합의유무',
  `crmcs_agamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '형사합의금액',
  `dmge_cncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해내용코드',
  `dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구방법코드',
  `open_dmrt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '포괄청구율',
  `ic_dmnst_da_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득입증자료유무',
  `asrt_mnth_icamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '주장월소득금액',
  `appr_mnth_avg_icamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인정월평균소득금액',
  `aglm` decimal(3,0) DEFAULT NULL COMMENT '정년',
  `age` decimal(3,0) DEFAULT NULL COMMENT '연령',
  `ic_st_ch_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득기준변경사유코드',
  `hspnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원명',
  `ic_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득기준구분코드',
  `ccpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직종코드',
  `hsp_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원고객번호',
  `hsp_cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '병원협력업체순번',
  `st_ic_seqno` decimal(3,0) DEFAULT NULL COMMENT '기준소득순번',
  `tmp_end_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가종결여부',
  `anpe_yn_nv_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타인여부조사사항',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `clm_cnn_crcrr_seqno` decimal(3,0) DEFAULT NULL COMMENT '사고관련차량이력순번',
  `clm_cnn_cr_seqno` decimal(3,0) DEFAULT NULL COMMENT '사고관련차량순번',
  `madmo_clm_ds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마디모사고결정여부',
  `madmo_clm_rqudt` date DEFAULT NULL COMMENT '마디모사고의뢰일자',
  `madmo_clm_dsdt` date DEFAULT NULL COMMENT '마디모사고결정일자',
  `madmo_dc_xc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마디모할인할증여부',
  `chrps_ntg_prg_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자입고진행상태코드',
  `frst_stm_seqno` decimal(3,0) DEFAULT NULL COMMENT '선견적순번',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_dmge_nv_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`dmge_nv_crr_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=484 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='피해조사';
