--
-- Table structure for table `ccm_dm_rd_rptg_relcc`
--

DROP TABLE IF EXISTS `ccm_dm_rd_rptg_relcc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_dm_rd_rptg_relcc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험종목코드',
  `dm_rd_rptg_seqno` decimal(3,0) NOT NULL COMMENT '손해감소보고서순번',
  `relcc_seqno` decimal(3,0) NOT NULL COMMENT '관련자순번',
  `nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성명',
  `rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주민번호',
  `nrdps_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자관계코드',
  `jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업코드',
  `relcc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련자유형코드',
  `ctm_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호구분코드',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `sp_rpt_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인지보고직업코드',
  `spcn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의구분코드',
  `hndph_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰전화지역번호',
  `hndph_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰전화국번',
  `hndph_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰전화일련번호',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `pvpy_amt` decimal(15,0) DEFAULT NULL COMMENT '기지급금액',
  `t_ryamt` decimal(15,0) DEFAULT NULL COMMENT '총회수금액',
  `sramt` decimal(15,0) DEFAULT '0' COMMENT '잔존가액',
  `swdl_tp_lclcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사기유형대분류코드',
  `swdl_tp_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사기유형세부코드',
  `ag_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의여부',
  `acdno_crtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호법원코드',
  `acdno_rcp_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호접수년도',
  `acdno_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호분류코드',
  `acdno_seqno` decimal(7,0) DEFAULT NULL COMMENT '사건번호순번',
  `pscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검찰번호',
  `crmcs_jstno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사재판번호',
  `chr_acd_crtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당사건법원코드',
  `detc_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사결과코드',
  `just_prg_crscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재판진행과정코드',
  `just_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재판결과코드',
  `just_rst_mntct` decimal(10,0) DEFAULT NULL COMMENT '재판결과개월수',
  `just_rst_days` decimal(10,0) DEFAULT NULL COMMENT '재판결과일수',
  `just_rstam` decimal(15,0) DEFAULT '0' COMMENT '재판결과금액',
  `snt_grc_mntct` decimal(10,0) DEFAULT NULL COMMENT '선고유예개월수',
  `psvn_iscn_mntct` decimal(10,0) DEFAULT NULL COMMENT '보호감찰개월수',
  `xc_grc_mntct` decimal(10,0) DEFAULT NULL COMMENT '집행유예개월수',
  `scil_srv_hms` decimal(10,0) DEFAULT NULL COMMENT '사회봉사시간',
  `pnlty_amt` decimal(15,0) DEFAULT '0' COMMENT '벌금금액',
  `note_cncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고내용코드',
  `note_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고내용',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_dm_rd_rptg_relcc_00` (`rcp_yymm`,`rcp_nv_seqno`,`ins_imcd`,`dm_rd_rptg_seqno`,`relcc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손해감소보고서관련자';
