--
-- Table structure for table `ccm_srips_adm_list`
--

DROP TABLE IF EXISTS `ccm_srips_adm_list`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_srips_adm_list` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `adm_seqno` decimal(10,0) NOT NULL COMMENT '관리순번',
  `aprh_dy_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근접일사고여부',
  `carno_eqal_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호일치여부',
  `cr_ownr_eqal_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량소유자일치여부',
  `trt_cnf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약확인여부',
  `ntc_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고지위반여부',
  `nv_requ_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사의뢰여부',
  `main_clm_rpt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주요사고보고여부',
  `dubt_par_eqal_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의심부위일치여부',
  `clm_pln_cnf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고현장확인여부',
  `cr_rgtce_cnf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량등록증확인여부',
  `drve_lic_elig_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전면허적격여부',
  `spcl_cr_drve_lic_elig_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수차량운전면허적격여부',
  `drnk_drve_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '음주운전여부',
  `pce_rpr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경찰서신고여부',
  `trfac_fct_cnfst_clrq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '교통사고사실확인서징구여부',
  `crmcs_ag_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사합의유무',
  `crmcs_ag_amt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사합의금액여부',
  `bnd_trsf_nt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권양도통지여부',
  `oper_row_nt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운행경위통지여부',
  `othcr_sng_flt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타차단독과실여부',
  `cmps_tr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유상운송여부',
  `idac_ins_dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재보험처리여부',
  `sh_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위장사고여부',
  `lb_dtyob_pvpy_fct_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배상의무자기지급사실여부',
  `lb_dtyob_pvpy_amt_cnf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배상의무자기지급금액확인여부',
  `av_idm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가능구상여부',
  `et_idm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타구상여부',
  `cidps_bnd_itg_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피구상자채권보전조치여부',
  `slfch_ex_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기부담금환입여부',
  `shr_cnfst_clrq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분담확인서징구여부',
  `ic_rqst_dgnnm_eqal_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득질의진단명일치여부',
  `safe_belt_wear_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전벨트착용여부',
  `rdtgr_fct_cnfst_clrq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동승사실확인서징구여부',
  `dubt_par_dgnnm_eqal_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의심부위진단명일치여부',
  `pvsp_nv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기왕증조사여부',
  `md_cnst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료자문여부',
  `pt_adm_rptg_propt_trm_wrt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환자관리보고서적정기간작성여부',
  `icr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득자구분코드',
  `wpcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직장명',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_srips_adm_list_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`adm_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='중상자 관리 리스트';
