--
-- Table structure for table `ccm_swdl_bnd`
--

DROP TABLE IF EXISTS `ccm_swdl_bnd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_swdl_bnd` (
  `swdl_bnd_rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '사기채권접수년월',
  `swdl_bnd_rcp_sno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '사기채권접수일련번호',
  `idm_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '구상업무구분코드',
  `swdl_bnd_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사기채권상태코드',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해서열',
  `clm_nv_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고조사종류코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `nv_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사년도',
  `bscrl_coonv_seqno` decimal(10,0) DEFAULT NULL COMMENT '업계공동조사순번',
  `siu_inp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SIU입력구분코드',
  `ch_seqno` decimal(5,0) DEFAULT NULL COMMENT '변경순번',
  `nrd_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험차량번호',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `nrdps_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자생년월일',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `spcn_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의대상구분코드',
  `spcn_bjnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의대상명',
  `spcn_bj_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의대상주민번호',
  `spcn_bj_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의대상생년월일',
  `spcn_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의유형코드',
  `spcn_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혐의내용',
  `cmp_cnr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상센터기관코드',
  `cmp_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상팀기관코드',
  `cmp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상직원번호',
  `acdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건명',
  `swdl_bnd_swdl_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사기채권사기유형코드',
  `swdl_bnd_nv_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사기채권조사유형코드',
  `chmcp_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주간사회사코드',
  `sjtdn_amt` decimal(15,0) DEFAULT NULL COMMENT '적발금액',
  `rcv_xpamt` decimal(15,0) DEFAULT NULL COMMENT '환수예상금액',
  `detc_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사기관명',
  `detc_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수사결과코드',
  `sdpst_acd_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건년도',
  `sdpst_acdno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송치사건번호',
  `crmcs_jstno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '형사재판번호',
  `asso_no_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협회번호년도',
  `asso_no_sno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협회번호일련번호',
  `acdno_crtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호법원코드',
  `acdno_rcp_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호접수년도',
  `acdno_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호분류코드',
  `acdno_seqno` decimal(7,0) DEFAULT NULL COMMENT '사건번호순번',
  `just_prg_crscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재판진행과정코드',
  `just_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재판결과코드',
  `ag_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의여부',
  `rulng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '판결문여부',
  `fr_xp_rgt_dthms` datetime DEFAULT NULL COMMENT '최초예상등록일시',
  `fr_cr_rgt_dthms` datetime DEFAULT NULL COMMENT '최초발생등록일시',
  `fr_end_rgt_dthms` datetime DEFAULT NULL COMMENT '최초종결등록일시',
  `end_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종결여부',
  `end_dthms` datetime DEFAULT NULL COMMENT '종결일시',
  `rpr_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보대상여부',
  `nrept_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미통보사유코드',
  `idm_xp_rgt_dthms` datetime DEFAULT NULL COMMENT '구상예상등록일시',
  `idm_xp_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상예상등록직원번호',
  `idm_xp_rgt_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상예상등록결과코드',
  `idm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상접수년월',
  `idm_rcp_sno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상접수일련번호',
  `idm_xp_admno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상예상관리번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`swdl_bnd_rcp_yymm`,`swdl_bnd_rcp_sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사기채권';
