--
-- Table structure for table `ccm_balcs_cs_cc`
--

DROP TABLE IF EXISTS `ccm_balcs_cs_cc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_balcs_cs_cc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `as_it_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사정항목구분코드',
  `cc_sno` decimal(5,0) NOT NULL COMMENT '산출일련번호',
  `cc_stdt` date NOT NULL COMMENT '산출기준일자',
  `rpair_strdt` date DEFAULT NULL COMMENT '수리시작일자',
  `rpair_nddt` date DEFAULT NULL COMMENT '수리종료일자',
  `appr_days` decimal(5,0) NOT NULL DEFAULT '0' COMMENT '인정일수',
  `appr_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인정시간',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `emamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '청구금액',
  `appr_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인정금액',
  `appr_amt_spls_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인정금액초과여부',
  `lend_ctpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대여차종명',
  `lend_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대여차량번호',
  `lend_strdt` date DEFAULT NULL COMMENT '대여시작일자',
  `lend_nddt` date DEFAULT NULL COMMENT '대여종료일자',
  `lend_drv_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대여운전자주민번호',
  `lend_drv_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대여운전자성명',
  `dfrn_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대차계약여부',
  `ltrm_dfrn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기대차여부',
  `ctp_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종그룹코드',
  `aprt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용율구분코드',
  `dfrn_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대차사용여부',
  `balcs_aprt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '대차료적용율',
  `dtcl_balcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '일자별대차료',
  `tmcl_balcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '시간별대차료',
  `auto_grbx_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동변속기유무',
  `auto_grbx_adrt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '자동변속기가산율',
  `rcaam_itcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴차료항목코드',
  `rcaam_dy1_appr_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '휴차료1일인정금액',
  `rcar_dmnst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴차입증여부',
  `rcaam_bz_inamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '휴차료영업수입금액',
  `rcaam_oper_bg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '휴차료운행경비',
  `drct_rpcrg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '직접수리비',
  `cramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '차량가액',
  `ctn_vlamt_aprt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '경락가액적용율',
  `ctn_vlamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '경락가액',
  `lend_str_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대여시작시분',
  `lend_nd_hhmm` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대여종료시분',
  `drtcs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간접비구분코드',
  `drt_dm_spc_seqno` decimal(3,0) DEFAULT NULL COMMENT '간접손해내역순번',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_balcs_cs_cc_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`as_it_flgcd`,`cc_sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='대차료비용산출';
