--
-- Table structure for table `ccm_hira_dmur_xc_ud`
--

DROP TABLE IF EXISTS `ccm_hira_dmur_xc_ud`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_hira_dmur_xc_ud` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `hira_rcp_yr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '심평원접수년도',
  `hira_rcpno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '심평원접수번호',
  `hira_dmbil_sno` decimal(3,0) NOT NULL COMMENT '심평원청구서일련번호',
  `hira_spcft_sno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '심평원명세서일련번호',
  `dmur_sno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '이의제기일련번호',
  `dmur_xc_sno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '이의제기정산일련번호',
  `hira_xc_ud_sno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심평원정산심사일련번호',
  `hira_form_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심평원서식구분코드',
  `hira_xc_ud_dgre` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심평원정산심사차수',
  `hira_xc_rprdt` date NOT NULL COMMENT '심평원정산통보일자',
  `hira_dm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원청구구분코드',
  `inscp_clm_rcpno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사사고접수번호',
  `py_gu_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급보증번호',
  `rqdc_rcp_org_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청서접수기관구분코드',
  `pt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환자성명',
  `hira_md_orgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원의료기관코드',
  `hira_ud_dgre` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원심사차수',
  `hira_bndl_no` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원묶음번호',
  `hira_dm_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원청구형태코드',
  `dmur_chr_depnm` varchar(40) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이의제기담당부서명',
  `dmur_chrps_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이의제기담당자성명',
  `dmur_chrps_no` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이의제기담당자번호',
  `dmur_chrps_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이의제기담당자전화번호',
  `hira_xc_udcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원정산심사코드',
  `hira_xc_bsnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원정산업무명',
  `hira_ud_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원심사구분코드',
  `hira_appr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심평원인정구분코드',
  `mdorg_ad_rt` decimal(3,0) DEFAULT NULL COMMENT '의료기관가산비율',
  `befo_trmt_opndt` date DEFAULT NULL COMMENT '이전진료개시일자',
  `befo_scwnd_csf_symb` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이전상병분류기호',
  `befo_fr_trpa` decimal(15,0) DEFAULT NULL COMMENT '이전최초진료비',
  `befo_re_trpa` decimal(15,0) DEFAULT NULL COMMENT '이전재진료비',
  `befo_trpa_tamt` decimal(15,0) DEFAULT NULL COMMENT '이전진료비총금액',
  `befo_ud_dsamt` decimal(15,0) DEFAULT NULL COMMENT '이전심사결정금액',
  `befo_trst_drct_pyamt` decimal(15,0) DEFAULT NULL COMMENT '이전위탁직접지급금액',
  `befo_drfe_mxdam_tamt` decimal(15,0) DEFAULT NULL COMMENT '이전약제비상한차액총액',
  `befo_pt_pym_tamt` decimal(15,0) DEFAULT NULL COMMENT '이전환자납부총액',
  `befo_fsmde_ct` decimal(3,0) DEFAULT NULL COMMENT '이전초진횟수',
  `befo_fsmde_ad_ct` decimal(3,0) DEFAULT NULL COMMENT '이전초진가산횟수',
  `befo_mdrxm_ct` decimal(3,0) DEFAULT NULL COMMENT '이전재진횟수',
  `befo_mdrxm_ad_ct` decimal(3,0) DEFAULT NULL COMMENT '이전재진가산횟수',
  `befo_hsp_days` decimal(3,0) DEFAULT NULL COMMENT '이전입원일수',
  `befo_trmt_days` decimal(3,0) DEFAULT NULL COMMENT '이전진료일수',
  `befo_prtn_ct` decimal(3,0) DEFAULT NULL COMMENT '이전처방횟수',
  `befo_rd_1_amt` decimal(15,0) DEFAULT NULL COMMENT '이전삭감1금액',
  `befo_rd_2_amt` decimal(15,0) DEFAULT NULL COMMENT '이전삭감2금액',
  `befo_drfe_mxdam_rdamt` decimal(15,0) DEFAULT NULL COMMENT '이전약제비상한차액삭감금액',
  `befo_1_icamt` decimal(15,0) DEFAULT NULL COMMENT '이전1증액',
  `befo_2_icamt` decimal(15,0) DEFAULT NULL COMMENT '이전2증액',
  `befo_idamt_sm` decimal(15,0) DEFAULT NULL COMMENT '이전증감액합계',
  `befo_1_stot_amt` decimal(15,0) DEFAULT NULL COMMENT '이전1소계금액',
  `befo_2_stot_amt` decimal(15,0) DEFAULT NULL COMMENT '이전2소계금액',
  `crnt_fr_trpa` decimal(15,0) DEFAULT NULL COMMENT '현재최초진료비',
  `crnt_re_trpa` decimal(15,0) DEFAULT NULL COMMENT '현재재진료비',
  `crnt_trpa_tamt` decimal(15,0) DEFAULT NULL COMMENT '현재진료비총금액',
  `crnt_ud_dsamt` decimal(15,0) DEFAULT NULL COMMENT '현재심사결정금액',
  `crnt_trst_drct_pyamt` decimal(15,0) DEFAULT NULL COMMENT '현재위탁직접지급금액',
  `crnt_drfe_mxdam_tamt` decimal(15,0) DEFAULT NULL COMMENT '현재약제비상한차액총액',
  `crnt_pt_pym_tamt` decimal(15,0) DEFAULT NULL COMMENT '현재환자납부총액',
  `xc_ud_ds_diamt` decimal(15,0) DEFAULT NULL COMMENT '정산심사결정차액금액',
  `crnt_fsmde_ct` decimal(3,0) DEFAULT NULL COMMENT '현재초진횟수',
  `crnt_fsmde_ad_ct` decimal(3,0) DEFAULT NULL COMMENT '현재초진가산횟수',
  `crnt_mdrxm_ct` decimal(3,0) DEFAULT NULL COMMENT '현재재진횟수',
  `crnt_mdrxm_ad_ct` decimal(3,0) DEFAULT NULL COMMENT '현재재진가산횟수',
  `crnt_hsp_days` decimal(3,0) DEFAULT NULL COMMENT '현재입원일수',
  `crnt_trmt_days` decimal(3,0) DEFAULT NULL COMMENT '현재진료일수',
  `crnt_prtn_ct` decimal(3,0) DEFAULT NULL COMMENT '현재처방횟수',
  `crnt_rd_1_amt` decimal(15,0) DEFAULT NULL COMMENT '현재삭감1금액',
  `crnt_rd_2_amt` decimal(15,0) DEFAULT NULL COMMENT '현재삭감2금액',
  `crnt_drfe_mxdam_rdamt` decimal(15,0) DEFAULT NULL COMMENT '현재약제비상한차액삭감금액',
  `crnt_1_icamt` decimal(15,0) DEFAULT NULL COMMENT '현재1증액',
  `crnt_2_icamt` decimal(15,0) DEFAULT NULL COMMENT '현재2증액',
  `crnt_idamt_sm` decimal(15,0) DEFAULT NULL COMMENT '현재증감액합계',
  `crnt_1_stot_amt` decimal(15,0) DEFAULT NULL COMMENT '현재1소계금액',
  `crnt_2_stot_amt` decimal(15,0) DEFAULT NULL COMMENT '현재2소계금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_hira_dmur_xc_ud_00` (`hira_rcp_yr`,`hira_rcpno`,`hira_dmbil_sno`,`hira_spcft_sno`,`dmur_sno`,`dmur_xc_sno`,`hira_xc_ud_sno`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='심평원이의제기정산심사';
