--
-- Table structure for table `ccm_ai_aos_dm`
--

DROP TABLE IF EXISTS `ccm_ai_aos_dm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_ai_aos_dm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `dm_seq` decimal(3,0) NOT NULL COMMENT '청구회차',
  `rltm_rcv_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '실시간수신여부',
  `dm_ts_seqno` decimal(3,0) NOT NULL COMMENT '청구전송순번',
  `aos_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS담보코드',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `aos_admno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT 'AOS관리번호',
  `ai_stm_id` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT '인공지능견적ID',
  `ai_stm_seqno` decimal(3,0) NOT NULL COMMENT '인공지능견적순번',
  `ai_stm_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '인공지능견적구분코드',
  `ai_dm_wrtdt` date DEFAULT NULL COMMENT '인공지능청구작성일자',
  `ai_dm_wrt_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인공지능청구작성시간',
  `ai_dm_tsdt` date DEFAULT NULL COMMENT '인공지능청구전송일자',
  `ai_dm_ts_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인공지능청구전송시간',
  `dmdr_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구처사업자번호',
  `dmdrm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구처명',
  `inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사코드',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직원번호',
  `chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자명',
  `rpair_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량번호',
  `rpair_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차대번호',
  `rpair_crcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량코드',
  `rpair_crnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량명',
  `rpair_car_mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리차량모델명',
  `rpair_car_trvl_dst` decimal(7,0) DEFAULT NULL COMMENT '수리차량주행거리',
  `rpair_cr_fr_rgtdt` date DEFAULT NULL COMMENT '수리차량최초등록일자',
  `rpair_car_ac_apdt` date DEFAULT NULL COMMENT '수리차량부품적용일자',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `ntgdt` date DEFAULT NULL COMMENT '입고일자',
  `aos_ntg_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS입고경로코드',
  `tabl_meta_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '테이블메타ID',
  `meta_atr_2_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성2값',
  `meta_atr_4_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성4값',
  `meta_atr_6_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성6값',
  `as_tkatt_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정탈부착작업시간종류코드',
  `meta_atr_8_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성8값',
  `meta_atr_10_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성10값',
  `meta_atr_12_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성12값',
  `meta_atr_14_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성14값',
  `meta_atr_16_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성16값',
  `meta_atr_28_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성28값',
  `meta_atr_20_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성20값',
  `meta_atr_26_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성26값',
  `as_cotg_wkhms_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정도장작업시간종류코드',
  `as_cotg_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정도장분류코드',
  `as_cotg_colr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정도장컬러명',
  `as_cotgc_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사정도장코트종류코드',
  `as_tot_cotam` decimal(15,0) DEFAULT NULL COMMENT '사정전체도장금액',
  `as_tot_cotg_aprt` decimal(5,2) DEFAULT NULL COMMENT '사정전체도장적용율',
  `as_part_shtmt_aprt` decimal(5,2) DEFAULT NULL COMMENT '사정부분판금적용율',
  `as_matcs_aprt` decimal(5,2) DEFAULT NULL COMMENT '사정재료비적용율',
  `meta_atr_36_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성36값',
  `meta_atr_42_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성42값',
  `meta_atr_44_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성44값',
  `meta_atr_46_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성46값',
  `meta_atr_48_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성48값',
  `meta_atr_50_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성50값',
  `meta_atr_52_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성52값',
  `meta_atr_94_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성94값',
  `meta_atr_96_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성96값',
  `meta_atr_98_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성98값',
  `meta_atr_60_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성60값',
  `meta_atr_58_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성58값',
  `meta_atr_66_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성66값',
  `meta_atr_68_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성68값',
  `meta_atr_86_vl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메타속성86값',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_ai_aos_dm_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`dm_seq`,`rltm_rcv_yn`,`dm_ts_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='AIAOS청구';
