--
-- Table structure for table `ccm_agamt_cc`
--

DROP TABLE IF EXISTS `ccm_agamt_cc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_agamt_cc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `cc_seq` decimal(3,0) NOT NULL COMMENT '산출회차',
  `cc_st_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '산출기준구분코드',
  `appr_mnth_avg_icamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인정월평균소득금액',
  `dmge_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해유형코드',
  `dmge_cncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해내용코드',
  `fltrt` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '과실율',
  `fnl_dsamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '최종결정금액',
  `mdcf_stf_ppamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '치료비상계기지급금액',
  `mdcf_stf_npamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '치료비상계미지급금액',
  `mdcf_pvamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '치료비충당금액',
  `part_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '일부지급금액',
  `hsp_st` date DEFAULT NULL COMMENT '입원시기',
  `hsp_clstr` date DEFAULT NULL COMMENT '입원종기',
  `hsp_days` decimal(5,0) NOT NULL DEFAULT '0' COMMENT '입원일수',
  `otp_st` date DEFAULT NULL COMMENT '통원시기',
  `otp_clstr` date DEFAULT NULL COMMENT '통원종기',
  `otp_days` decimal(5,0) NOT NULL DEFAULT '0' COMMENT '통원일수',
  `cv_obsrt` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '환산장해율',
  `de_obs_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사망장해구분코드',
  `hsp_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원등급코드',
  `surgy_spsk_mtt` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외과특기사항',
  `plst_hsp_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성형병원등급코드',
  `plst_spsk_mtt` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성형특기사항',
  `nsamt_appr_bjpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개호비인정대상코드',
  `nsamt_py_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개호비지급방법코드',
  `nml_rol` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '정상여명',
  `exp_rol` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '기대여명',
  `sht_rol` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '단축여명',
  `rol_nddt` date DEFAULT NULL COMMENT '여명종료일자',
  `dfrn_bordr_fltap_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '대차탑승자과실적용여부',
  `emamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '청구금액',
  `dm_rcpdt` date DEFAULT NULL COMMENT '청구접수일자',
  `tpamt_dmdr_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가지급금청구자고객번호',
  `tpamt_dmdr_cpent_seqno` decimal(3,0) DEFAULT NULL COMMENT '가지급금청구자협력업체순번',
  `tpamt_dmdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가지급금청구자명',
  `dmdr_relcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '청구자관계코드',
  `dmdr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구자전화지역번호',
  `dmdr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구자전화국번',
  `dmdr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구자전화일련번호',
  `tpamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가지급금구분코드',
  `np_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미지급사유',
  `cc_st_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산출기준종류코드',
  `agamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의금구분코드',
  `rmdy_crs_otp_days` decimal(5,0) DEFAULT NULL COMMENT '치료과정통원일수',
  `rmdy_crs_hsp_days` decimal(5,0) DEFAULT NULL COMMENT '치료과정입원일수',
  `sel_obs_nv_seqno` decimal(3,0) DEFAULT NULL COMMENT '후유장해조사순번',
  `sel_obs_optdc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '후유장해임의확정구분코드',
  `injr_grd_optdc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해등급임의확정구분코드',
  `injr_grd_seqno` decimal(3,0) DEFAULT NULL COMMENT '상해등급순번',
  `ic_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득기준구분코드',
  `st_ic_seqno` decimal(3,0) DEFAULT NULL COMMENT '기준소득순번',
  `ccpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직종코드',
  `relt_ic_cc_seqno` decimal(3,0) DEFAULT NULL COMMENT '현실소득산출순번',
  `rcp_nv_flt_seqno` decimal(3,0) NOT NULL COMMENT '접수조사과실순번',
  `flt_seqno` decimal(3,0) NOT NULL COMMENT '과실순번',
  `nrdsc_appr_st` date DEFAULT NULL COMMENT '간병비인정시기',
  `nrdsc_appr_clstr` date DEFAULT NULL COMMENT '간병비인정종기',
  `nrdsc_appr_days` decimal(5,0) DEFAULT NULL COMMENT '간병비인정일수',
  `nrdsc_clc_dy_avgam` decimal(15,0) DEFAULT NULL COMMENT '간병비산정일평균금액',
  `nrdsc_emamt` decimal(15,0) DEFAULT NULL COMMENT '간병비청구금액',
  `nrdsc_ad_pybj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간병비추가지급대상여부',
  `nrdsc_ad_pybj_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간병비추가지급대상사유',
  `mig_py_ordr` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'MIG지급순차',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_agamt_cc_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`cc_seq`,`cc_st_flgcd`)
) ENGINE=InnoDB AUTO_INCREMENT=195 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='합의금산출';
