--
-- Table structure for table `ccm_py_rslt_mstr`
--

DROP TABLE IF EXISTS `ccm_py_rslt_mstr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ccm_py_rslt_mstr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `dmge_rank` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '피해서열',
  `py_rslt_no` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '지급결의번호',
  `rpt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보고구분코드',
  `dm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구구분코드',
  `ds_dthms` datetime DEFAULT NULL COMMENT '결정일시',
  `adm_chrps_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '관리담당자직원번호',
  `adm_chrps_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '관리담당자기관코드',
  `adm_chrps_tm_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '관리담당자팀기관코드',
  `adm_chrps_rsdnc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리담당자주재기관코드',
  `ibamt_py_mtdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험금액지급방법코드',
  `cmp_mtdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보상방법코드',
  `pln_py_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '현장지급유무',
  `hamt_ap_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '고액승인유무',
  `dlay_nt_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '지연이자유무',
  `atpli_is_inscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자배책가입보험사코드',
  `idmpl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상처구분코드',
  `idm_inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상보험사코드',
  `idm_ex_nt_cs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '구상환입이자비용',
  `adtx_incld_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '부가세포함여부',
  `cmp_py_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보상지급유형코드',
  `ex_itcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환입항목코드',
  `gvmt_gn_bz_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정부보장사업구분코드',
  `ag_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합의구분코드',
  `agdt` date DEFAULT NULL COMMENT '합의일자',
  `dm_sy_trst_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '손해사정인위탁여부',
  `py_stamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지급기준금액',
  `dm_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '청구보험금액',
  `rpbl_de_dsamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임사망결정금액',
  `rpbl_inj_dsamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임부상결정금액',
  `rpbl_tth_dsamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임치아결정금액',
  `rpbl_obs_dsamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임장해결정금액',
  `rpbl_dsamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임결정금액합계',
  `optn_dsamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임의결정금액합계',
  `trt_dsamt` decimal(15,0) DEFAULT NULL COMMENT '특약결정금액',
  `ds_ibamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '결정보험금액',
  `part_dsno_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부결정번호기관코드',
  `part_dsno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부결정번호구분코드',
  `part_dsno_yy` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부결정번호년',
  `part_dsno_mnth` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부결정번호월',
  `part_ds_sno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일부결정일련번호',
  `xi_rvsn_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추산정정사유코드',
  `rpbl_de_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임사망추산보험금액',
  `rpbl_inj_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임부상추산보험금액',
  `rpbl_tth_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임치아추산보험금액',
  `rpbl_obs_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임장해추산보험금액',
  `rpbl_xiamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임추산보험금액합계',
  `optn_xiamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임의추산보험금액합계',
  `trt_xiamt` decimal(15,0) DEFAULT NULL COMMENT '특약추산금액',
  `xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '추산보험금액',
  `rpbl_de_remn_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임사망잔여추산보험금액',
  `rpbl_inj_remn_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임부상잔여추산보험금액',
  `rpbl_tth_remn_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임치아잔여추산보험금액',
  `rpbl_obs_remn_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임장해잔여추산보험금액',
  `rpbl_remn_xiamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '책임잔여추산보험금액합계',
  `optn_remn_xiamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임의잔여추산보험금액합계',
  `trt_remn_xiamt` decimal(15,0) DEFAULT NULL COMMENT '특약잔여추산금액',
  `remn_xiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '잔여추산보험금액',
  `dm_seqno` decimal(5,0) DEFAULT NULL COMMENT '청구순번',
  `dm_ud_seqno` decimal(3,0) DEFAULT NULL COMMENT '청구심사순번',
  `cc_seq` decimal(3,0) DEFAULT NULL COMMENT '산출회차',
  `cmp_py_rltno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상지급연계번호',
  `cc_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산출기준구분코드',
  `dmge_nv_crr_seqno` decimal(3,0) DEFAULT NULL COMMENT '피해조사이력순번',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ccm_py_rslt_mstr_00` (`rcp_yymm`,`rcp_nv_seqno`,`clm_cvrcd`,`dmge_rank`,`py_rslt_no`)
) ENGINE=InnoDB AUTO_INCREMENT=368 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='지급결의서마스터';
