--
-- Table structure for table `gea_cm_inr`
--

DROP TABLE IF EXISTS `gea_cm_inr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_cm_inr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `cm_rgtno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '통신등록번호',
  `cm_csfcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '통신분류코드',
  `itmcd` varchar(15) COLLATE utf8mb4_bin NOT NULL COMMENT '품목코드',
  `cm_bzpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '통신사업자코드',
  `opndt` date NOT NULL COMMENT '개통일자',
  `rqdt` date DEFAULT NULL COMMENT '신청일자',
  `rq_seqno` decimal(5,0) DEFAULT NULL COMMENT '신청순번',
  `rq_spc_seqno` decimal(5,0) DEFAULT NULL COMMENT '신청내역순번',
  `rqor_cd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '신청기관코드',
  `rq_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '신청직원번호',
  `fnl_apdt` date DEFAULT NULL COMMENT '최종승인일자',
  `fnl_ap_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종승인기관코드',
  `fnl_ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종승인직원번호',
  `cnldt` date DEFAULT NULL COMMENT '해지일자',
  `use` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '용도',
  `chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자명',
  `chrps_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화지역번호',
  `chrps_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화국번',
  `chrps_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화일련번호',
  `chrps_celph_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자이동전화지역번호',
  `chrps_celph_tno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자이동전화국번',
  `chrps_celph_sno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자이동전화일련번호',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `cm_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '통신상태코드',
  `linct` decimal(3,0) DEFAULT NULL COMMENT '회선수',
  `lin_speed_stdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선속도규격코드',
  `us_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이용구분코드',
  `lin_sctcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선구간코드',
  `dst` decimal(10,0) DEFAULT NULL COMMENT '거리',
  `ppr_tlonm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위전화국명',
  `ppr_bran_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위지국주소',
  `sbd_tlonm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '하위전화국명',
  `sbd_bran_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '하위지국주소',
  `pwd` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '패스워드',
  `gdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품명',
  `srvnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '서비스명',
  `ntl_plc_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치장소우편번호',
  `ntl_plc_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치장소기본주소',
  `ntl_plc_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치장소상세주소',
  `ntl_plc_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치장소전화지역번호',
  `ntl_plc_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치장소전화국번',
  `ntl_plc_tlsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치장소전화일련번호',
  `crtm_cg_dscrt` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '계약기간요금할인율',
  `sync_co_apl_dscrt` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '동시공동청약할인율',
  `fx_ip_a_clss` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고정아이피A클래스',
  `fx_ip_b_clss` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고정아이피B클래스',
  `fx_ip_c_clss` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고정아이피C클래스',
  `fx_ip_sno` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고정아이피일련번호',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `surb_tl_bzpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시외전화사업자코드',
  `rsvt_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '유보원금',
  `rsvt_rtamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '유보환급금액',
  `cm_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통신등급코드',
  `no_mv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '번호이동여부',
  `intr_tl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인터넷전화여부',
  `dgtph_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '디지털폰여부',
  `hdof_pst_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본사소속여부',
  `fax_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스여부',
  `lin_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선종류코드',
  `lin_us_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선사용형태코드',
  `lin_sctnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선구간명',
  `lin_prs_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선대표번호',
  `lin_itgnw_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선지능망번호',
  `lin_subo_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회선종속번호',
  `prs_lin_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표회선여부',
  `chnct` decimal(3,0) DEFAULT NULL COMMENT '채널수',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_gea_cm_inr_00` (`cm_rgtno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='통신통합';
