--
-- Table structure for table `gea_supt_rq_spc`
--

DROP TABLE IF EXISTS `gea_supt_rq_spc`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_supt_rq_spc` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rqdt` date NOT NULL COMMENT '신청일자',
  `rq_seqno` decimal(5,0) NOT NULL COMMENT '신청순번',
  `rq_spc_seqno` decimal(5,0) NOT NULL COMMENT '신청내역순번',
  `rq_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '신청종류코드',
  `rq_rq_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '신청요청구분코드',
  `rq_rq_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청요청사유코드',
  `dl_hpdt` date DEFAULT NULL COMMENT '처리희망일자',
  `dl_prdt` date DEFAULT NULL COMMENT '처리예정일자',
  `entp_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업체고객번호',
  `itmcd` varchar(15) COLLATE utf8mb4_bin NOT NULL COMMENT '품목코드',
  `itm_std` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '품목규격',
  `supt_rq_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지원신청단가',
  `supt_rq_qant` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '지원신청수량',
  `supt_md_qant` decimal(7,0) DEFAULT '0' COMMENT '지원조정수량',
  `supt_rqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지원신청금액',
  `supt_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지원단가',
  `cr_ordg_supt_qant` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '계약발주지원수량',
  `hdof_stock_supt_qant` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '본사재고지원수량',
  `mv_supt_qant` decimal(7,0) DEFAULT NULL COMMENT '이동지원수량',
  `wst_supt_qant` decimal(7,0) DEFAULT NULL COMMENT '폐기지원수량',
  `suamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지원금액',
  `supt_xcpt_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '지원제외여부',
  `amv_prdt` date DEFAULT NULL COMMENT '이사예정일자',
  `lndr_wdmt_rpr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대인구두통보여부',
  `rnt_ry_note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차회수비고사항',
  `mnth_xp_us_qant` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '월예상사용수량',
  `us_strdt` date DEFAULT NULL COMMENT '사용시작일자',
  `us_nddt` date DEFAULT NULL COMMENT '사용종료일자',
  `aseno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산번호',
  `xp_us_trm_info` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예상사용기간정보',
  `prd_cmpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제조회사명',
  `mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모델명',
  `prdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제조번호',
  `prts_paqu` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인쇄물지질',
  `prts_std` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인쇄물규격',
  `prts_chrm` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인쇄물색도',
  `prts_pagct` decimal(3,0) DEFAULT NULL COMMENT '인쇄물페이지수',
  `prts_bind` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인쇄물제본',
  `prts_afprs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인쇄물후가공',
  `wrk_chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '작업담당자명',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `mv_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전화지역번호',
  `mv_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전화국번',
  `mv_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전화일련번호',
  `mvbf_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전우편번호',
  `mvbf_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전기본주소',
  `mvbf_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전상세주소',
  `mvaf_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동후우편번호',
  `mvaf_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동후기본주소',
  `mvaf_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동후상세주소',
  `rq_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청처리구분코드',
  `rq_dl_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청처리상태코드',
  `rq_dl_cpldt` date DEFAULT NULL COMMENT '신청처리완료일자',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `mvbf_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전주건물번호',
  `mvbf_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전부건물번호',
  `mvbf_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전참고항목',
  `mvaf_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동후주건물번호',
  `mvaf_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동후부건물번호',
  `mvaf_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동후참고항목',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_gea_supt_rq_spc_00` (`rqdt`,`rq_seqno`,`rq_spc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='지원신청내역';
