--
-- Table structure for table `gea_dl_inr`
--

DROP TABLE IF EXISTS `gea_dl_inr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_dl_inr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `dl_inrno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '거래통합번호',
  `rv_py_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '수납지급구분코드',
  `ta_dltp_o1_cd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '총무거래유형1차코드',
  `ta_dltp_o2_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총무거래유형2차코드',
  `deldt` date NOT NULL COMMENT '거래일자',
  `dl_bj_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래대상년월',
  `dl_dl_act_ntacc` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '거래처리회계계정과목',
  `dl_qant_sm` decimal(15,0) DEFAULT '0' COMMENT '거래수량합계',
  `dnamt_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '거래금액합계',
  `dlpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처명',
  `dlplc_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처고객번호',
  `dlplc_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처식별번호',
  `xcdt` date DEFAULT NULL COMMENT '정산일자',
  `xc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정산기관코드',
  `xcno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정산번호',
  `dl_inr_ntty_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래통합실체구분코드',
  `ldgno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원장번호',
  `rstm_rgtno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산등록번호',
  `rqdt` date DEFAULT NULL COMMENT '신청일자',
  `rq_seqno` decimal(5,0) DEFAULT NULL COMMENT '신청순번',
  `rq_spc_seqno` decimal(5,0) DEFAULT NULL COMMENT '신청내역순번',
  `ac_tf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경리이체여부',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `rv_sbno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납대기번호',
  `rpdt` date DEFAULT NULL COMMENT '영수일자',
  `bzwpl_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업장사업자번호',
  `dlplc_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처은행코드',
  `dlplc_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처계좌번호',
  `dl_dl_bdg_ntacc` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처리예산계정과목',
  `admcs_dm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비청구유형코드',
  `cc_strdt` date DEFAULT NULL COMMENT '산출시작일자',
  `cc_nddt` date DEFAULT NULL COMMENT '산출종료일자',
  `cc_bsc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산출근거',
  `cm_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통신분류코드',
  `ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험회사코드',
  `iramt_plyno` varchar(25) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보증권번호',
  `iramt_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보대상구분코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `ins_gdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험상품명',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `aprt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '적용율',
  `age_trt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연령특약',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_gea_dl_inr_00` (`dl_inrno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='거래통합';
