--
-- Table structure for table `gea_hot_bzcs_evd_adm`
--

DROP TABLE IF EXISTS `gea_hot_bzcs_evd_adm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_hot_bzcs_evd_adm` (
  `hot_rgtno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '임대차등록번호',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '기준년월',
  `dl_seqno` decimal(5,0) NOT NULL COMMENT '처리순번',
  `evdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙번호',
  `evddt` date DEFAULT NULL COMMENT '증빙일자',
  `evd_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙종류코드',
  `pypl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처구분코드',
  `pypl_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처대상구분코드',
  `pylno` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처번호',
  `pylnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처명',
  `pypl_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처은행코드',
  `pypl_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처계좌번호',
  `pypl_dpsr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처예금주',
  `py_prdt` date DEFAULT NULL COMMENT '지급예정일자',
  `pydt` date DEFAULT NULL COMMENT '지급일자',
  `dlplc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처구분코드',
  `dlpno` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처번호',
  `dlpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처명',
  `evd_buy` decimal(5,0) DEFAULT NULL COMMENT '증빙매수',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `woamt` decimal(15,0) DEFAULT '0' COMMENT '원화금액',
  `syamt` decimal(15,0) DEFAULT '0' COMMENT '공급가액',
  `axamt` decimal(15,0) DEFAULT '0' COMMENT '부가세액',
  `etamt` decimal(15,0) DEFAULT '0' COMMENT '기타금액',
  `dc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제유형코드',
  `dcrt` decimal(12,6) DEFAULT '0.000000' COMMENT '공제율',
  `dl_tp_o2_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래유형2차분류코드',
  `bzwpl_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업장사업자번호',
  `trste_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수탁자식별번호',
  `rl_us_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사용직원번호',
  `pymdt` date DEFAULT NULL COMMENT '납부일자',
  `rcp_diay_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대일지입력여부',
  `rcppc_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처식별번호',
  `rcppc_conm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처상호명',
  `rcppc_depnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처부서명',
  `rcppc_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대처성명',
  `rcp_oj` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대목적',
  `rcp_et_mtt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대기타사항',
  `rcp_plc_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대장소사업자번호',
  `rcp_plc_conm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접대장소상호명',
  `ap_retn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인반려구분코드',
  `dldt` date DEFAULT NULL COMMENT '처리일자',
  `dl_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리기관코드',
  `dl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리직원번호',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `evd_ap_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙승인대상여부',
  `evd_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙상태코드',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `inp_scr_id` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력화면ID',
  `rr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속기관코드',
  `py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급여부',
  `hqbld_rgtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사옥등록코드',
  `elec_tx_bll_apno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전자세금계산서승인번호',
  `rstm_py_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산지급구분코드',
  `elec_evd_img_bsnno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전자증빙이미지업무번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`hot_rgtno`,`st_yymm`,`dl_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='임대차사업비증빙관리';
