--
-- Table structure for table `gea_hot`
--

DROP TABLE IF EXISTS `gea_hot`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_hot` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `hot_rgtno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '임대차등록번호',
  `les_rnt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '임대임차구분코드',
  `hot_crano` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대차계약번호',
  `spcl_relco_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수관계사구분코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `cr_strdt` date DEFAULT NULL COMMENT '계약시작일자',
  `cr_nddt` date DEFAULT NULL COMMENT '계약종료일자',
  `cn_prdt` date DEFAULT NULL COMMENT '해지예정일자',
  `rnt_cr_trmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차계약기간코드',
  `crtm` decimal(3,0) DEFAULT NULL COMMENT '계약기간',
  `hot_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대차고객번호',
  `bzps_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자등록여부',
  `tx_bzps_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과세사업자유형코드',
  `lndr_crd_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대인신용등급코드',
  `cr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약기관코드',
  `les_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대구분코드',
  `hot_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대차종류코드',
  `cr_are` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '계약면적',
  `xc_are` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '전용면적',
  `hot_guamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대차보증금액',
  `hot_admcs_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대차관리비선수금액',
  `hot_guamt_pyung_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대차보증금액평단가',
  `cv_guamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '환산보증금액',
  `cv_guamt_pyung_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '환산보증금액평단가',
  `cv_guamt_rt` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '환산보증금액율',
  `pp_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선급금액',
  `mnth_hotcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '월임대차료',
  `mnth_hotcs_pyung_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '월임대차료평단가',
  `mnth_hotcs_adtx_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '월임대차료부가세여부',
  `mnth_admcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '월관리비',
  `mnth_admcs_pyung_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '월관리비평단가',
  `mnth_admcs_adtx_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '월관리비부가세여부',
  `admcs_pymdt` date DEFAULT NULL COMMENT '관리비납부일자',
  `admcs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비구분코드',
  `rntrt_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차료청구일정보',
  `admcs_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비청구일정보',
  `elnt_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료청구일정보',
  `wtrt_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료청구일정보',
  `clamt_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료청구일정보',
  `pbcrx_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비청구일정보',
  `rx_dmdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실비청구일정보',
  `rntrt_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차료청구방법코드',
  `admcs_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비청구방법코드',
  `elnt_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료청구방법코드',
  `wtrt_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료청구방법코드',
  `clamt_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료청구방법코드',
  `pbcrx_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비청구방법코드',
  `rx_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실비청구방법코드',
  `rntrt_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차료연체료반영여부',
  `admcs_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비연체료반영여부',
  `elnt_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료연체료반영여부',
  `wtrt_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료연체료반영여부',
  `clamt_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료연체료반영여부',
  `pbcrx_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비연체료반영여부',
  `rx_arrs_rflt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실비연체료반영여부',
  `rntrt_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차료사용월정보',
  `admcs_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비사용월정보',
  `elnt_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료사용월정보',
  `wtrt_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료사용월정보',
  `clamt_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료사용월정보',
  `pbcrx_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비사용월정보',
  `rx_us_mnth_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실비사용월정보',
  `rntrt_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차료지급예정일정보',
  `admcs_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비지급예정일정보',
  `elnt_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료지급예정일정보',
  `wtrt_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료지급예정일정보',
  `clamt_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료지급예정일정보',
  `pbcrx_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비지급예정일정보',
  `rx_py_prdy_info` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실비지급예정일정보',
  `mw_cn_bfrpr_mnt` decimal(3,0) DEFAULT NULL COMMENT '중도해지사전통보개월',
  `mw_cn_dlbr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도해지손해배상여부',
  `cr_rnw_bfrpr_mnt` decimal(3,0) DEFAULT NULL COMMENT '계약갱신사전통보개월',
  `nd_cn_bfrpr_mnt` decimal(3,0) DEFAULT NULL COMMENT '만기해지사전통보개월',
  `sbd_ntl_impr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간판설치불가여부',
  `frnt_sbdct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전면간판수',
  `prjtn_sbdct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '돌출간판수',
  `sthld_sbdct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '지주간판수',
  `chr_sbdct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '문자간판수',
  `et_sbdct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '기타간판수',
  `free_pk_ct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '무료주차대수',
  `chrg_pk_ct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '유료주차대수',
  `chrg_pkamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '유료주차금액',
  `part_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '칸막이공사필요여부',
  `cm_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통신공사필요여부',
  `acht_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '냉난방공사필요여부',
  `hshgd_fixnt_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '집기비품설치필요여부',
  `ntl_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치공사필요여부',
  `et_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타공사필요여부',
  `et_wrk_note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타공사비고사항',
  `mvidt` date DEFAULT NULL COMMENT '입주일자',
  `cn_rprdt` date DEFAULT NULL COMMENT '해지통보일자',
  `cnldt` date DEFAULT NULL COMMENT '해지일자',
  `cn_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해지사유코드',
  `orst_rest_nddt` date DEFAULT NULL COMMENT '원상복구종료일자',
  `crdm_us_form_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약서사용서식구분코드',
  `crtm_nd_cn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약기간만료해지여부',
  `guamt_xc_tblam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보증금정산잔액',
  `guamt_xc_cplt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보증금정산완료여부',
  `guamt_xc_cpldt` date DEFAULT NULL COMMENT '보증금정산완료일자',
  `rx_ifamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실비추정금액',
  `elnt_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료실비대상여부',
  `wtrt_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료실비대상여부',
  `clamt_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료실비대상여부',
  `pbcrx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비대상여부',
  `et_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타실비대상여부',
  `co_own_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동소유여부',
  `co_ownr_info` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동소유자정보',
  `es_av_obj_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설정가능물건종류코드',
  `plr_rnt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '복수임차구분코드',
  `rstm_rgtno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '부동산등록번호',
  `hot_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대차상태코드',
  `rqdt` date DEFAULT NULL COMMENT '신청일자',
  `rq_seqno` decimal(5,0) DEFAULT NULL COMMENT '신청순번',
  `rq_spc_seqno` decimal(5,0) DEFAULT NULL COMMENT '신청내역순번',
  `fr_cr_strdt` date DEFAULT NULL COMMENT '최초계약시작일자',
  `fr_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초계약여부',
  `bf_hot_rgtno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전임대차등록번호',
  `nots_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요사항',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `bnd_fprm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권확보구분코드',
  `bnd_fprm_strdt` date DEFAULT NULL COMMENT '채권확보시작일자',
  `bnd_fprm_nddt` date DEFAULT NULL COMMENT '채권확보종료일자',
  `les_vcrps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대대행인고객번호',
  `fxcl_ot_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근저당타담보여부',
  `ot_cvrpl_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지우편번호',
  `ot_cvrpl_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지기본주소',
  `ot_cvrpl_dt_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지상세주소',
  `acdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건번호',
  `aucdt` date DEFAULT NULL COMMENT '경매일자',
  `jrd_crtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관할법원명',
  `dvdt` date DEFAULT NULL COMMENT '배당일자',
  `rprdt` date DEFAULT NULL COMMENT '통보일자',
  `sdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '배당금액',
  `bsns_adx_file_dscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무첨부파일식별번호',
  `rr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '귀속기관코드',
  `ot_cvrpl_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지주건물번호',
  `ot_cvrpl_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지부건물번호',
  `ot_cvrpl_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지참고항목',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_gea_hot_00` (`hot_rgtno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='임대차';
