--
-- Table structure for table `gea_tl_adcrg`
--

DROP TABLE IF EXISTS `gea_tl_adcrg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_tl_adcrg` (
  `dmdt` date NOT NULL COMMENT '청구일자',
  `tl_dscno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '전화식별번호',
  `dm_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '청구년월',
  `no_mv_dt` date DEFAULT NULL COMMENT '번호이동일자',
  `opndt` date DEFAULT NULL COMMENT '개통일자',
  `bacs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기본료',
  `eqpcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장치비',
  `inrsd_cnvcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '구내통화료',
  `city_cnvcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '시내통화료',
  `surb_cnvcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '시외통화료',
  `mv_cmcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '이동통신료',
  `ngbr_surb_cnvcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인접시외통화료',
  `info_usamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '정보이용료',
  `intr_cnvcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '국제통화료',
  `pc_cmamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT 'PC통신금액',
  `dcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '할인금액',
  `mdamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '조정금액',
  `itgnw_usamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '지능망사용금액',
  `ad_srvrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부가서비스료',
  `tgrrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전보료',
  `hrbr_cnvcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '항만통화료',
  `intr_tlcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인터넷전화비',
  `intr_cmcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인터넷통신비',
  `intr_crpcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '인터넷부대비',
  `wrls_caamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '무선호출금액',
  `eqmt_rent` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장비임대료',
  `eqmt_slcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '장비판매료',
  `xc_lincs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전용회선료',
  `rx_cgamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '감면요금금액',
  `tf_dcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '이체할인금액',
  `tl114_uiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전화114공제금액',
  `et_mdamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '기타조정금액',
  `part_smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부분합계금액',
  `equcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '설비비',
  `tl_txamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전화세액',
  `axamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '부가세액',
  `bfmm_ndamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '전월미청구금액',
  `npy_cg` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '미납요금',
  `adamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '가산금액',
  `ppamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '선납금액',
  `wtamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원절사금액',
  `guamt_sbamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '보증금액대체금액',
  `smamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '합계금액',
  `linct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '회선수',
  `dl_inrno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래통합번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`dmdt`,`tl_dscno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='전화과금';
