--
-- Table structure for table `gea_cmpu_ase_rptg`
--

DROP TABLE IF EXISTS `gea_cmpu_ase_rptg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_cmpu_ase_rptg` (
  `reqno` varchar(11) COLLATE utf8mb4_bin NOT NULL COMMENT '요청번호',
  `rq_supt_seqno` decimal(3,0) NOT NULL COMMENT '요청지원순번',
  `ntl_ch_unprc` decimal(15,0) DEFAULT NULL COMMENT '설치변경단가',
  `ntl_ch_qant` decimal(5,0) DEFAULT NULL COMMENT '설치변경수량',
  `ntl_chamt` decimal(15,0) DEFAULT NULL COMMENT '설치변경금액',
  `ntl_ch_labcs` decimal(15,0) DEFAULT NULL COMMENT '설치변경인건비',
  `ntl_ch_tamt` decimal(15,0) DEFAULT NULL COMMENT '설치변경총액',
  `inrsd_unprc` decimal(15,0) DEFAULT NULL COMMENT '구내단가',
  `inrsd_qant` decimal(5,0) DEFAULT NULL COMMENT '구내수량',
  `inrsd_amt` decimal(15,0) DEFAULT NULL COMMENT '구내금액',
  `inrsd_labcs` decimal(15,0) DEFAULT NULL COMMENT '구내인건비',
  `inrsd_tamt` decimal(15,0) DEFAULT NULL COMMENT '구내총액',
  `lan_unprc` decimal(15,0) DEFAULT NULL COMMENT 'LAN단가',
  `lan_qant` decimal(5,0) DEFAULT NULL COMMENT 'LAN수량',
  `lan_amt` decimal(15,0) DEFAULT NULL COMMENT 'LAN금액',
  `lan_labcs` decimal(15,0) DEFAULT NULL COMMENT 'LAN인건비',
  `lan_tamt` decimal(15,0) DEFAULT NULL COMMENT 'LAN총액',
  `cmpu_wrk_rpt_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산공사보고의견',
  `pc_qant` decimal(5,0) DEFAULT NULL COMMENT 'PC수량',
  `pc_trspt_cs` decimal(15,0) DEFAULT NULL COMMENT 'PC운반비용',
  `pc_labcs` decimal(15,0) DEFAULT NULL COMMENT 'PC인건비',
  `pc_tamt` decimal(15,0) DEFAULT NULL COMMENT 'PC총액',
  `prntr_qant` decimal(5,0) DEFAULT NULL COMMENT '프린터수량',
  `prntr_trspt_cs` decimal(15,0) DEFAULT NULL COMMENT '프린터운반비용',
  `prntr_labcs` decimal(15,0) DEFAULT NULL COMMENT '프린터인건비',
  `prntr_tamt` decimal(15,0) DEFAULT NULL COMMENT '프린터총액',
  `et_eqmt_qant` decimal(5,0) DEFAULT NULL COMMENT '기타장비수량',
  `eqmt_trspt_cs` decimal(15,0) DEFAULT NULL COMMENT '장비운반비용',
  `et_eqmt_labcs` decimal(15,0) DEFAULT NULL COMMENT '기타장비인건비',
  `et_eqmt_tamt` decimal(15,0) DEFAULT NULL COMMENT '기타장비총액',
  `cmpu_mch_rpt_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산기기보고의견',
  `ntl_ch_fnl_unprc` decimal(15,0) DEFAULT NULL COMMENT '설치변경최종단가',
  `ntl_ch_fnl_qant` decimal(5,0) DEFAULT NULL COMMENT '설치변경최종수량',
  `ntl_ch_fnl_amt` decimal(15,0) DEFAULT NULL COMMENT '설치변경최종금액',
  `ntl_ch_fnl_labcs` decimal(15,0) DEFAULT NULL COMMENT '설치변경최종인건비',
  `ntl_ch_fnl_tamt` decimal(15,0) DEFAULT NULL COMMENT '설치변경최종총액',
  `inrsd_fnl_unprc` decimal(15,0) DEFAULT NULL COMMENT '구내최종단가',
  `inrsd_fnl_qant` decimal(5,0) DEFAULT NULL COMMENT '구내최종수량',
  `inrsd_fnl_amt` decimal(15,0) DEFAULT NULL COMMENT '구내최종금액',
  `inrsd_fnl_labcs` decimal(15,0) DEFAULT NULL COMMENT '구내최종인건비',
  `inrsd_fnl_tamt` decimal(15,0) DEFAULT NULL COMMENT '구내최종총액',
  `lan_fnl_unprc` decimal(15,0) DEFAULT NULL COMMENT 'LAN최종단가',
  `lan_fnl_qant` decimal(5,0) DEFAULT NULL COMMENT 'LAN최종수량',
  `lan_fnl_amt` decimal(15,0) DEFAULT NULL COMMENT 'LAN최종금액',
  `lan_fnl_labcs` decimal(15,0) DEFAULT NULL COMMENT 'LAN최종인건비',
  `lan_fnl_tamt` decimal(15,0) DEFAULT NULL COMMENT 'LAN최종총액',
  `cmpu_wrk_fnl_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산공사최종의견',
  `pc_fnl_qant` decimal(5,0) DEFAULT NULL COMMENT 'PC최종수량',
  `pc_fnl_trspt_cs` decimal(15,0) DEFAULT NULL COMMENT 'PC최종운반비용',
  `pc_fnl_labcs` decimal(15,0) DEFAULT NULL COMMENT 'PC최종인건비',
  `pc_fnl_tamt` decimal(15,0) DEFAULT NULL COMMENT 'PC최종총액',
  `prntr_fnl_qant` decimal(5,0) DEFAULT NULL COMMENT '프린터최종수량',
  `prntr_fnl_trspt_cs` decimal(15,0) DEFAULT NULL COMMENT '프린터최종운반비용',
  `prntr_fnl_labcs` decimal(15,0) DEFAULT NULL COMMENT '프린터최종인건비',
  `prntr_fnl_tamt` decimal(15,0) DEFAULT NULL COMMENT '프린터최종총액',
  `et_eqmt_fnl_qant` decimal(5,0) DEFAULT NULL COMMENT '기타장비최종수량',
  `eqmt_fnl_trspt_cs` decimal(15,0) DEFAULT NULL COMMENT '장비최종운반비용',
  `et_eqmt_fnl_labcs` decimal(15,0) DEFAULT NULL COMMENT '기타장비최종인건비',
  `et_eqmt_fnl_tamt` decimal(15,0) DEFAULT NULL COMMENT '기타장비최종총액',
  `cmpu_mch_fnl_ctn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산기기최종의견',
  `ers_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '삭제여부',
  `rgtdt` date DEFAULT NULL COMMENT '등록일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`reqno`,`rq_supt_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='전산자산보고서';
