--
-- Table structure for table `gea_ase_inr`
--

DROP TABLE IF EXISTS `gea_ase_inr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_ase_inr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `aseno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '자산번호',
  `asenm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '자산명',
  `cqdt` date NOT NULL COMMENT '취득일자',
  `cqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '취득금액',
  `ase_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자산구분코드',
  `ase_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자산유형코드',
  `ase_untcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자산단위코드',
  `ase_std` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산규격',
  `mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모델명',
  `dp_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '상각금액',
  `dlplc_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래처고객번호',
  `bcd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '바코드',
  `re_vlbe_cqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '재평가전취득가액',
  `dpamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '처분가액',
  `org_ntty_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관실체구분코드',
  `crnt_adm_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '현재관리기관코드',
  `crnt_adm_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '현재관리직원번호',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기본주소',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `iramt_is_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '부보가입여부',
  `itmcd` varchar(15) COLLATE utf8mb4_bin NOT NULL COMMENT '품목코드',
  `cr_rgtno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '계약등록번호',
  `cmpu_admno` varchar(23) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산관리번호',
  `prd_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제조회사코드',
  `crnt_ase_stadt` date DEFAULT NULL COMMENT '현재자산상태일자',
  `crnt_ase_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '현재자산상태코드',
  `usr_ase_stadt` date DEFAULT NULL COMMENT '사용자자산상태일자',
  `usr_ase_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용자자산상태코드',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `mv_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전화지역번호',
  `mv_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전화국번',
  `mv_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이동전화일련번호',
  `uddt` date DEFAULT NULL COMMENT '인수일자',
  `ase_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산등록여부',
  `ase_rgtdt` date DEFAULT NULL COMMENT '자산등록일자',
  `ase_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산등록직원번호',
  `oseno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구자산번호',
  `ase_pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자산특이사항',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `bsns_adx_file_dscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무첨부파일식별번호',
  `carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호',
  `rstm_rgtno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산등록번호',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_gea_ase_inr_00` (`aseno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='자산통합';
