--
-- Table structure for table `gea_rnt_rq`
--

DROP TABLE IF EXISTS `gea_rnt_rq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gea_rnt_rq` (
  `rqdt` date NOT NULL COMMENT '신청일자',
  `rq_seqno` decimal(5,0) NOT NULL COMMENT '신청순번',
  `rq_spc_seqno` decimal(5,0) NOT NULL COMMENT '신청내역순번',
  `bldnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '건물명',
  `pstno` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '우편번호',
  `ba_adr` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '기본주소',
  `dtadr` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '상세주소',
  `spcl_relco_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수관계사구분코드',
  `ownr_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유자고객번호',
  `bzps_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자등록여부',
  `tx_bzps_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과세사업자유형코드',
  `lndr_crd_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대인신용등급코드',
  `les_vcrps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대대행인고객번호',
  `fxcl_ot_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근저당타담보여부',
  `ot_cvrpl_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지우편번호',
  `ot_cvrpl_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지기본주소',
  `ot_cvrpl_dt_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지상세주소',
  `grod_flct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '지상층수',
  `undg_flct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '지하층수',
  `acht_eqmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '냉난방시설코드',
  `acht_actvt_info` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '냉난방가동정보',
  `free_pk_ct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '무료주차대수',
  `chrg_pk_ct` decimal(7,0) NOT NULL DEFAULT '0' COMMENT '유료주차대수',
  `chrg_pkamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '유료주차금액',
  `pasgr_elvct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '승객용승강기수',
  `frus_elvct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '화물용승강기수',
  `emeus_elvct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '비상용승강기수',
  `ntl_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설치공사필요여부',
  `part_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '칸막이공사필요여부',
  `cm_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통신공사필요여부',
  `acht_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '냉난방공사필요여부',
  `hshgd_fixnt_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '집기비품설치필요여부',
  `et_wrk_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타공사필요여부',
  `et_wrk_note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타공사비고사항',
  `sbd_ntl_impr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간판설치불가여부',
  `frnt_sbdct` decimal(3,0) NOT NULL COMMENT '전면간판수',
  `prjtn_sbdct` decimal(3,0) NOT NULL COMMENT '돌출간판수',
  `sthld_sbdct` decimal(3,0) NOT NULL COMMENT '지주간판수',
  `chr_sbdct` decimal(3,0) NOT NULL COMMENT '문자간판수',
  `et_sbdct` decimal(3,0) NOT NULL COMMENT '기타간판수',
  `cr_are` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '계약면적',
  `xc_are` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '전용면적',
  `rl_are` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '실면적',
  `plr_rnt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '복수임차구분코드',
  `bnd_fprm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권확보구분코드',
  `bnd_fprm_strdt` date DEFAULT NULL COMMENT '채권확보시작일자',
  `bnd_fprm_nddt` date DEFAULT NULL COMMENT '채권확보종료일자',
  `own_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소유대상구분코드',
  `co_cvres_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동담보설정가능여부',
  `bnd_fpagr_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채권확보동의가능여부',
  `es_av_obj_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설정가능물건종류코드',
  `rnt_fl_info` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차층정보',
  `rnt_guamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임차보증금액',
  `hot_admcs_pcamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '임대차관리비선수금액',
  `mnth_rntrt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '월임차료',
  `mnth_rntrt_adtx_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '월임차료부가세여부',
  `cv_guamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '환산보증금액',
  `mvi_prdt` date DEFAULT NULL COMMENT '입주예정일자',
  `cr_pr_strdt` date DEFAULT NULL COMMENT '계약예정시작일자',
  `cr_pr_nddt` date DEFAULT NULL COMMENT '계약예정종료일자',
  `cr_cn_prdt` date DEFAULT NULL COMMENT '계약해지예정일자',
  `cr_cnldt` date DEFAULT NULL COMMENT '계약해지일자',
  `rnt_cr_trmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차계약기간코드',
  `co_own_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동소유여부',
  `co_ownr_info` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동소유자정보',
  `mw_cn_bfrpr_mnt` decimal(3,0) DEFAULT NULL COMMENT '중도해지사전통보개월',
  `mw_cn_dlbr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도해지손해배상여부',
  `cr_rnw_bfrpr_mnt` decimal(3,0) DEFAULT NULL COMMENT '계약갱신사전통보개월',
  `nd_cn_bfrpr_mnt` decimal(3,0) DEFAULT NULL COMMENT '만기해지사전통보개월',
  `admcs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비구분코드',
  `mnth_admcs` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '월관리비',
  `mnth_admcs_adtx_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '월관리비부가세여부',
  `elnt_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기료실비대상여부',
  `wtrt_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수도료실비대상여부',
  `clamt_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청소료실비대상여부',
  `pbcrx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공공실비대상여부',
  `et_rx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타실비대상여부',
  `rx_ifamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '실비추정금액',
  `crdm_us_form_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약서사용서식구분코드',
  `admcs_dm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리비청구방법코드',
  `rnt_trt_spc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임차특약내역',
  `rstm_rgtno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산등록번호',
  `rstm_prv_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산기등록여부',
  `relco_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계회사여부',
  `bld_bnd_vl_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '건물채권평가단가',
  `land_bnd_vl_unprc` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대지채권평가단가',
  `bld_bnd_vlamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '건물채권평가금액',
  `land_bnd_vlamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '대지채권평가금액',
  `bld_bnd_vl_st` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물채권평가기준',
  `land_bnd_vl_st` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대지채권평가기준',
  `bnd_itg_lmrt` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '채권보전한도율',
  `bnd_itg_lmamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '채권보전한도금액',
  `bld_cn_yyct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '건물내용년수',
  `bld_rnd_yyct` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '건물경과년수',
  `bld_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물우편번호',
  `bld_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물기본주소',
  `bld_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물상세주소',
  `land_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '토지우편번호',
  `land_ba_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '토지기본주소',
  `land_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '토지상세주소',
  `hot_rgtno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대차등록번호',
  `note_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고사항',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `bld_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물주건물번호',
  `bld_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물부건물번호',
  `bld_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물참고항목',
  `land_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '토지주건물번호',
  `land_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '토지부건물번호',
  `land_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '토지참고항목',
  `ot_cvrpl_mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지주건물번호',
  `ot_cvrpl_sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지부건물번호',
  `ot_cvrpl_ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타담보지참고항목',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`rqdt`,`rq_seqno`,`rq_spc_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='임차신청';
