--
-- Table structure for table `ins_dvpns_ts_cr_da`
--

DROP TABLE IF EXISTS `ins_dvpns_ts_cr_da`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_dvpns_ts_cr_da` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `da_wrtdt` date NOT NULL COMMENT '자료작성일자',
  `admno` decimal(6,0) NOT NULL COMMENT '관리번호',
  `dvpns_ins_cmpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원보험회사코드',
  `dvpns_ikdcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원보종코드',
  `cr_yr` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약년도',
  `dvpns_crano` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원계약번호',
  `cr_ts_da_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약전송자료구분코드',
  `cr_da_ndscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자료배서코드',
  `nrdps_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자변경여부',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `nrdps_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호구분코드',
  `nrdps_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호',
  `cr_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량변경여부',
  `crgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량관코드',
  `cr_chsno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량차대번호구분코드',
  `cr_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량차대번호',
  `bdin1_cmp_lm_amtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인1보상한도금액코드',
  `bdin1_pyp_ct` decimal(2,0) DEFAULT NULL COMMENT '대인1분납횟수',
  `bdin1_pym_ct` decimal(2,0) DEFAULT NULL COMMENT '대인1납입횟수',
  `prdm1_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물1변경여부',
  `prdm1_ins_st` date DEFAULT NULL COMMENT '대물1보험시기',
  `prdm1_ins_clstr` date DEFAULT NULL COMMENT '대물1보험종기',
  `prdm1_cmp_lm_amtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물1보상한도금액코드',
  `prdm1_sep_ct` decimal(2,0) DEFAULT NULL COMMENT '대물1분할횟수',
  `prdm1_pym_ct` decimal(2,0) DEFAULT NULL COMMENT '대물1납입횟수',
  `bdin2_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인2변경여부',
  `bdin2_ins_st` date DEFAULT NULL COMMENT '대인2보험시기',
  `bdin2_ins_clstr` date DEFAULT NULL COMMENT '대인2보험종기',
  `bdin2_cmp_lm_amtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인2보상한도금액코드',
  `bdin2_pyp_ct` decimal(2,0) DEFAULT NULL COMMENT '대인2분납횟수',
  `bdin2_pym_ct` decimal(2,0) DEFAULT NULL COMMENT '대인2납입횟수',
  `auto_rnw_trtch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동갱신특약변경여부',
  `dvpns_trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원특약구분코드',
  `wrkdt` date DEFAULT NULL COMMENT '작업일자',
  `nds_stdt` date DEFAULT NULL COMMENT '배서기준일자',
  `thcp_crano` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '당사계약번호',
  `adr_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주소변경여부',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `dvpns_dtyns_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원의무보험업무구분코드',
  `bdin1_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인1변경여부',
  `bdin1_ins_st` date DEFAULT NULL COMMENT '대인1보험시기',
  `bdin1_ins_clstr` date DEFAULT NULL COMMENT '대인1보험종기',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_dvpns_ts_cr_da_00` (`da_wrtdt`,`admno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개발원전송계약자료';
