--
-- Table structure for table `ins_dvpns_pstng_tlm`
--

DROP TABLE IF EXISTS `ins_dvpns_pstng_tlm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_dvpns_pstng_tlm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `nrdcd` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자코드',
  `carno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '차량번호',
  `ins_st` date NOT NULL COMMENT '보험시기',
  `tlm_cr_dthms` datetime NOT NULL COMMENT '전문발생일시',
  `dvpns_ins_cmpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원보험회사코드',
  `dvpns_ikdcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원보종코드',
  `same_ply_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일증권여부',
  `da_tsdt` date DEFAULT NULL COMMENT '자료전송일자',
  `cmpu_inp_dthms` datetime DEFAULT NULL COMMENT '전산입력일시',
  `dvpns_cr_rgtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원차량등록지코드',
  `dvpns_ce_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원모집형태코드',
  `crncd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호코드',
  `dvpns_carno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원차량번호구분코드',
  `chsno_or_tmpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차대번호/임시번호',
  `cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량용도코드',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `cnmcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차명코드',
  `yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연식',
  `rgsct` decimal(5,0) DEFAULT NULL COMMENT '정원수',
  `load_fxqtt` decimal(10,0) DEFAULT NULL COMMENT '적재정량',
  `dspl` decimal(4,0) DEFAULT NULL COMMENT '배기량',
  `dvpns_cr_tycd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원차형태코드',
  `aircn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '에어컨여부',
  `stro_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '스테레오여부',
  `carph_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카폰여부',
  `voic_eqp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '음성장치여부',
  `tv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '텔레비전여부',
  `foma_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외산여부',
  `rgtnm_nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기명피보험자명',
  `rgtnm_nrdno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기명피보험자번호',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `auto_rnw_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동갱신특약가입여부',
  `cmps_tr_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유상운송특약가입여부',
  `pyp_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분납특약가입여부',
  `plus_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '플러스특약가입여부',
  `dvpns_age_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원연령한정특약코드',
  `pk_vlt_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주차위반특약가입여부',
  `bdin1_once_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인1일시적담보가입여부',
  `cr_dmxct_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량손해제외특약가입여부',
  `dvpns_drv_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원운전자한정특약코드',
  `ag_drv_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리운전자특약가입여부',
  `wekpl_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일제특약가입여부',
  `nanum_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '나눔특약가입여부',
  `milg_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지특약가입여부',
  `milg_trt_dc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지특약할인유형코드',
  `milg_agr_spls_dst` decimal(10,0) DEFAULT NULL COMMENT '마일리지약정초과거리',
  `milg_agr_belo_dst` decimal(10,0) DEFAULT NULL COMMENT '마일리지약정이하거리',
  `emgmv_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '긴급출동가입여부',
  `mcheq_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기계장치특별요율가입여부',
  `spceq_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수장비특별요율가입여부',
  `airb_eqp_pst` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '에어백장치위치',
  `sprts_cr_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '스포츠자동차특별요율가입여부',
  `low_age_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '저연령특별요율가입여부',
  `rbprv_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도난방지특별요율가입여부',
  `emgmv_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '긴급출동특별요율가입여부',
  `hgpr_cr_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고가차량특별요율가입여부',
  `abs_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ABS특별요율가입여부',
  `auto_spcrt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AUTO특별요율가입여부',
  `mtlxc_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물적할증가입여부',
  `mtral_xc_stamt` decimal(15,0) DEFAULT NULL COMMENT '물적할증기준금액',
  `slfch_chrg_rt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금부담비율',
  `slfch_llamt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금하한가액',
  `slfch_mxamt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금상한가액',
  `bdin2_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인2가입여부',
  `dvpns_bdin2_isamt_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원대인2가입금액구분코드',
  `bdin2_isamt` decimal(15,0) DEFAULT NULL COMMENT '대인2가입금액',
  `prdm_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물가입여부',
  `dvpns_prdm_isamt_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원대물가입금액구분코드',
  `prdm_isamt` decimal(15,0) DEFAULT NULL COMMENT '대물가입금액',
  `obi_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손가입여부',
  `dvpns_obi_isamt_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원자손가입금액구분코드',
  `obi_de_isamt` decimal(15,0) DEFAULT NULL COMMENT '자손사망가입금액',
  `obi_inj_isamt` decimal(15,0) DEFAULT NULL COMMENT '자손부상가입금액',
  `obi_sel_isamt` decimal(15,0) DEFAULT NULL COMMENT '자손후유가입금액',
  `injr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해가입여부',
  `cr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량가입여부',
  `cramt` decimal(15,0) DEFAULT NULL COMMENT '차량가액',
  `atch_vlamt` decimal(15,0) DEFAULT NULL COMMENT '부속가액',
  `mch_vlamt` decimal(15,0) DEFAULT NULL COMMENT '기계가액',
  `car_isamt` decimal(15,0) DEFAULT NULL COMMENT '차량가입금액',
  `mch_isamt` decimal(15,0) DEFAULT NULL COMMENT '기계가입금액',
  `sb_trfx` decimal(15,0) DEFAULT NULL COMMENT '대체교통비',
  `cr_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량등급코드',
  `dvpns_nwcr_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원신차구분코드',
  `dvpns_usdcr_yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원중고차연식',
  `psn_info_utagr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인정보활용동의여부',
  `hpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴대폰번호',
  `mail_adr` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일주소',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `co_prm` decimal(15,0) DEFAULT NULL COMMENT '공동보험료',
  `dvpns_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원할인할증등급코드',
  `dvpns_spc_xccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원특별할증코드',
  `dvpns_rglt_vltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원법규위반코드',
  `dvpns_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원가입경력코드',
  `pstng_rgtno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '포스팅등록번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_dvpns_pstng_tlm_00` (`nrdcd`,`carno`,`ins_st`,`tlm_cr_dthms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개발원포스팅전문';
