--
-- Table structure for table `ins_ihthe_inq_log`
--

DROP TABLE IF EXISTS `ins_ihthe_inq_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_ihthe_inq_log` (
  `ihthe_inq_log_no` decimal(13,0) NOT NULL COMMENT '상속인조회로그번호',
  `trscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'TRANSACTION코드',
  `opn_chr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '개시문자',
  `tlm_specd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전문종별코드',
  `bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업무구분코드',
  `tlm_opndt` date DEFAULT NULL COMMENT '전문개시일자',
  `tlm_opn_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문개시시간',
  `tlm_admno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문관리번호',
  `tlm_trs_orgcd` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문송신기관코드',
  `tlm_rcv_orgcd` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문수신기관코드',
  `da_lngth` decimal(4,0) DEFAULT NULL COMMENT '자료길이',
  `trmno` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기번호',
  `trm_oprtr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기조작자ID',
  `trm_oprtr_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기조작자성명',
  `anscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '응답코드',
  `tlm_rcpno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문접수번호',
  `rcpdt` date DEFAULT NULL COMMENT '접수일자',
  `contr_ihthe_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피상속인주민번호',
  `contr_ihthe_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피상속인성명',
  `dedt` date DEFAULT NULL COMMENT '사망일자',
  `ihthe_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상속인주민번호',
  `ihthe_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상속인성명',
  `rel` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계',
  `tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화번호',
  `adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주소',
  `email_adr` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'EMAIL주소',
  `hndph_no` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰번호',
  `agnt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인성명',
  `agnt_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인주민번호',
  `agnt_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인전화번호',
  `agnt_tot_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인전체주소',
  `agnt_hpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인휴대폰번호',
  `agnt_mail_adr` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인이메일주소',
  `inq_stdt` date DEFAULT NULL COMMENT '조회기준일자',
  `t_dact` decimal(2,0) DEFAULT NULL COMMENT '총자료건수',
  `ins_inct` decimal(2,0) DEFAULT NULL COMMENT '보험가입건수',
  `lnct` decimal(2,0) DEFAULT NULL COMMENT '대출건수',
  `gu_de_ct` decimal(2,0) DEFAULT NULL COMMENT '보증채무건수',
  `inq_reply_seqno` decimal(2,0) DEFAULT NULL COMMENT '조회회보순번',
  `inq_reply_ct` decimal(2,0) DEFAULT NULL COMMENT '조회회보건수',
  `tlm_rgt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문등록구분코드',
  `tlm_inq_cr_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전문조회발생사유코드',
  `mw_ibnf_ct` decimal(3,0) DEFAULT NULL COMMENT '중도보험금건수',
  `sep_ibnf_ct` decimal(3,0) DEFAULT NULL COMMENT '분할보험금건수',
  `dv_ibnf_ct` decimal(3,0) DEFAULT NULL COMMENT '배당보험금건수',
  `nd_ibnf_ct` decimal(3,0) DEFAULT NULL COMMENT '만기보험금건수',
  `exis_anct` decimal(3,0) DEFAULT NULL COMMENT '생존연금건수',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`ihthe_inq_log_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='상속인조회LOG';
