--
-- Table structure for table `ins_nlisr_asso_tlm_inq`
--

DROP TABLE IF EXISTS `ins_nlisr_asso_tlm_inq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_nlisr_asso_tlm_inq` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `tlm_opndt` date NOT NULL COMMENT '전문개시일자',
  `tlm_admno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '전문관리번호',
  `tlm_ts_seqno` decimal(5,0) NOT NULL COMMENT '전문전송순번',
  `tlm_specd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전문종별코드',
  `tlm_spe_dtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전문종별세부코드',
  `trscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'TRANSACTION코드',
  `knia` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT 'KNIA',
  `tlm_opn_hms` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '전문개시시간',
  `trs_org` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '송신기관',
  `rcv_org` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '수신기관',
  `dat_lngth` decimal(4,0) NOT NULL COMMENT '데이터길이',
  `sndr_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '송신자직원번호',
  `anscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '응답코드',
  `tlm_inq_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '전문조회업무구분코드',
  `inq_stdt` date NOT NULL COMMENT '조회기준일자',
  `bk_brcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행지점코드',
  `bk_extn_qfp` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행유자격자',
  `bk_ipps` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행입력자',
  `ctm_rsno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '고객주민번호',
  `ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객명',
  `crdif_utl_agre_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '신용정보활용동의여부',
  `t_rgt_ct` decimal(3,0) NOT NULL COMMENT '총등록건수',
  `rgt_cn_more` decimal(1,0) NOT NULL COMMENT '등록내용MORE',
  `inq_reply_ct` decimal(2,0) NOT NULL COMMENT '조회회보건수',
  `wrcs_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동의서유형코드',
  `wrcs_admno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동의서관리번호',
  `pblct_out_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발행물출력여부',
  `mdcs_tlm_opndt` date DEFAULT NULL COMMENT '의료비전문개시일자',
  `mdcs_tlm_admno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문관리번호',
  `crdis_usr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보원사용자ID',
  `usr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용인성명',
  `usr_ip_adr` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용자IP주소',
  `us_mntct` decimal(5,0) DEFAULT NULL COMMENT '이용개월수',
  `ps_mntct` decimal(5,0) DEFAULT NULL COMMENT '보유개월수',
  `lgin_ky` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인키',
  `da_inq_ojccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료조회목적코드',
  `inq_bj_mntct` decimal(5,0) DEFAULT NULL COMMENT '조회대상개월수',
  `bscrl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업계구분코드',
  `grin_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단체보험포함여부',
  `scp_info_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자사정보포함여부',
  `lap_cr_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실효계약포함여부',
  `trvlr_ins_incyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '여행자보험포함여부',
  `ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험회사코드',
  `nlisr_asso_plyno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손보협회증권번호',
  `ppr_tlm_opndt` date DEFAULT NULL COMMENT '상위전문개시일자',
  `ppr_tlm_admno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위전문관리번호',
  `ppr_tlm_ts_seqno` decimal(5,0) DEFAULT NULL COMMENT '상위전문전송순번',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_nlisr_asso_tlm_inq_00` (`tlm_opndt`,`tlm_admno`,`tlm_ts_seqno`),
  KEY `idx_ins_nlisr_asso_tlm_inq_10` (`ctm_rsno`)
) ENGINE=InnoDB AUTO_INCREMENT=2484 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손보협회전문조회';
