--
-- Table structure for table `ins_nlisr_cr_prm_inq_tlm`
--

DROP TABLE IF EXISTS `ins_nlisr_cr_prm_inq_tlm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_nlisr_cr_prm_inq_tlm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rqaps_tmpno` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT '신청자임시번호',
  `car_seqno` decimal(5,0) NOT NULL COMMENT '차량순번',
  `is_info_seqno` decimal(5,0) NOT NULL COMMENT '가입정보순번',
  `rqdt` date NOT NULL COMMENT '신청일자',
  `tlm_cr_dthms` datetime NOT NULL COMMENT '전문발생일시',
  `is_inscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입보험사코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `crano` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약번호',
  `my_car_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '다수차량여부',
  `carno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호구분코드',
  `crgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량관코드',
  `crncd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호코드',
  `endt` date DEFAULT NULL COMMENT '만기일자',
  `carnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차명',
  `cnmcd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차명코드구분코드',
  `cnmcd` varchar(11) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차명코드',
  `nwcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차구분코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `inscp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사구분코드',
  `cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량용도코드',
  `drv_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자한정특약코드',
  `bdin2_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인2가입여부',
  `bdin2_isamt` decimal(15,0) DEFAULT NULL COMMENT '대인2가입금액',
  `prdm_isamt` decimal(15,0) DEFAULT NULL COMMENT '대물가입금액',
  `obi_sbinj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손자상구분코드',
  `obi_de_isamt` decimal(15,0) DEFAULT NULL COMMENT '자손사망가입금액',
  `obi_inj_isamt` decimal(15,0) DEFAULT NULL COMMENT '자손부상가입금액',
  `owcr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자차가입여부',
  `slfch_chrg_rt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금부담비율',
  `mtral_xc_stamt` decimal(15,0) DEFAULT NULL COMMENT '물적할증기준금액',
  `unins_cr_injr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무보험차량상해가입여부',
  `othcr_drve_cvr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타차운전담보가입여부',
  `emgmv_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '긴급출동가입여부',
  `co_udrtk_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동인수여부',
  `lowt_drv_brtyr_mndy` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최저운전자생년월일',
  `dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인할증등급코드',
  `spc_xccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증코드',
  `is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입경력코드',
  `rglt_vltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법규위반코드',
  `befo_y1_clmct` decimal(5,0) DEFAULT NULL COMMENT '직전1년사고건수',
  `befo_y1_clm_poct` decimal(5,0) DEFAULT NULL COMMENT '직전1년사고점수',
  `befo_y3_clmct` decimal(7,0) DEFAULT NULL COMMENT '직전3년사고건수',
  `annu1_clmct` decimal(3,0) DEFAULT NULL COMMENT '1년간사고건수',
  `annu2_clmct` decimal(3,0) DEFAULT NULL COMMENT '2년간사고건수',
  `annu3_clmct` decimal(3,0) DEFAULT NULL COMMENT '3년간사고건수',
  `nrdps_cr_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자차량가입경력코드',
  `self_auth_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본인인증방식코드',
  `inq_agre_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조회동의방식코드',
  `inq_agmdt` date DEFAULT NULL COMMENT '조회동의일자',
  `inq_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조회동의여부',
  `bdin1_prm` decimal(15,0) DEFAULT NULL COMMENT '대인1보험료',
  `bdin2_prm` decimal(15,0) DEFAULT NULL COMMENT '대인2보험료',
  `prdm1_prm` decimal(15,0) DEFAULT NULL COMMENT '대물1보험료',
  `prdm2_prm` decimal(15,0) DEFAULT NULL COMMENT '대물2보험료',
  `obi_prm` decimal(15,0) DEFAULT NULL COMMENT '자손보험료',
  `unins_cr_prm` decimal(15,0) DEFAULT NULL COMMENT '무보험차량보험료',
  `owcr_prm` decimal(15,0) DEFAULT NULL COMMENT '자차보험료',
  `emgmv_prm` decimal(15,0) DEFAULT NULL COMMENT '긴급출동보험료',
  `othcr_drve_cvr_prm` decimal(15,0) DEFAULT NULL COMMENT '타차운전담보보험료',
  `sm_prm` decimal(15,0) DEFAULT NULL COMMENT '합계보험료',
  `plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설계번호',
  `yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연식',
  `asso_cr_is_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협회자동차가입유형코드',
  `asso_cr_inflw_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협회자동차유입경로코드',
  `cramt` decimal(15,0) DEFAULT NULL COMMENT '차량가액',
  `milg_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지특약가입여부',
  `blkbx_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '블랙박스특약가입여부',
  `chd_dc_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자녀할인특약가입여부',
  `clm_rpr_eqp_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고통보장치특약가입여부',
  `pub_trf_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대중교통특약가입여부',
  `safe_drve_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전운전특약가입여부',
  `dctp_milg_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인형마일리지특약가입여부',
  `mail_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일특약가입여부',
  `nanum_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '나눔특약가입여부',
  `milg_trt_trdst` decimal(10,0) DEFAULT NULL COMMENT '마일리지특약주행거리',
  `blkbx_atch_amt` decimal(15,0) DEFAULT NULL COMMENT '블랙박스부속금액',
  `chd_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자녀생년월일',
  `pub_trf_us_av` decimal(15,0) DEFAULT NULL COMMENT '대중교통이용실적',
  `drve_exec_poct` decimal(3,0) DEFAULT NULL COMMENT '운전수행점수',
  `dctp_milg_bfyy_avg_trdst` decimal(10,0) DEFAULT NULL COMMENT '할인형마일리지전년도평균주행거리',
  `dctp_milg_bf1yr_trdst` decimal(10,0) DEFAULT NULL COMMENT '할인형마일리지직전1년주행거리',
  `milg_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지특약적용여부',
  `blkbx_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '블랙박스특약적용여부',
  `chd_dc_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자녀할인특약적용여부',
  `clm_rpr_eqp_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고통보장치특약적용여부',
  `pub_trf_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대중교통특약적용여부',
  `safe_drve_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전운전특약적용여부',
  `dctp_milg_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인형마일리지특약적용여부',
  `mail_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일특약적용여부',
  `nanum_trt_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '나눔특약적용여부',
  `dctp_milg_trt_ap_prmsm` decimal(15,0) DEFAULT NULL COMMENT '할인형마일리지특약적용보험료합계',
  `milg_trt_ap_prmsm` decimal(15,0) DEFAULT NULL COMMENT '마일리지특약적용보험료합계',
  `ldws_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차선이탈경고장치구분코드',
  `bf_rm_clah_prvtn_eqp_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전방충돌방지장치구분코드',
  `safe_drve_dc_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전운전할인구분코드',
  `safe_drve_dc_poct` decimal(3,0) DEFAULT NULL COMMENT '안전운전할인점수',
  `inqr_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조회자성명',
  `ldws_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차선이탈경고장치가입유무',
  `bf_rm_clah_prvtn_eqp_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전방충돌방지장치가입유무',
  `safe_drve_dc_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안전운전할인가입유무',
  `drve_scl_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전범위생년월일',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_nlisr_cr_prm_inq_tlm_00` (`rqaps_tmpno`,`car_seqno`,`is_info_seqno`,`rqdt`,`tlm_cr_dthms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손보협회자동차보험료조회전문';
