--
-- Table structure for table `ins_rlpmi_trt_cr_rgt`
--

DROP TABLE IF EXISTS `ins_rlpmi_trt_cr_rgt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_rlpmi_trt_cr_rgt` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `mdcs_tlm_opndt` date NOT NULL COMMENT '의료비전문개시일자',
  `mdcs_tlm_admno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '의료비전문관리번호',
  `mdcs_tlm_ts_seqno` decimal(5,0) NOT NULL COMMENT '의료비전문전송순번',
  `mdcs_tlm_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문종별코드',
  `mdcs_tlm_spe_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문종별세부코드',
  `trscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'TRANSACTION코드',
  `knia` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KNIA',
  `mdcs_tlm_opn_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문개시시분초',
  `trs_org` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송신기관',
  `rcv_org` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수신기관',
  `dat_lngth` decimal(4,0) DEFAULT NULL COMMENT '데이터길이',
  `sndr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송신자직원번호',
  `anscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '응답코드',
  `mdcs_trt_rgt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비특약등록구분코드',
  `mdcs_tlm_dl_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문처리상태코드',
  `rgt_bj_vald_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '등록대상유효여부',
  `nrdps_relpc_seqno` decimal(10,0) DEFAULT NULL COMMENT '피보험자관계자순번',
  `nrdps_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자주민번호',
  `ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험회사코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `nds_stdt` date DEFAULT NULL COMMENT '배서기준일자',
  `chaf_nrdps_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후피보험자주민번호',
  `nrdps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자성명',
  `mdcs_trt_ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비특약보험종목코드',
  `ins_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험상품코드',
  `ins_gdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험상품명',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `ins_crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험계약자명',
  `chaf_cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후계약상태코드',
  `cr_st_chdt` date DEFAULT NULL COMMENT '계약상태변경일자',
  `rvidt` date DEFAULT NULL COMMENT '부활일자',
  `mdcs_trt_cvr_ct` decimal(2,0) DEFAULT NULL COMMENT '의료비특약담보건수',
  `nds_dcndt` date DEFAULT NULL COMMENT '배서확정일자',
  `cr_dcndt` date DEFAULT NULL COMMENT '계약확정일자',
  `befo_inq_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전조회대상여부',
  `nrdps_rsno_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자주민번호오류여부',
  `ins_cmpcd_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험회사코드오류여부',
  `plyno_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호오류여부',
  `ndsno_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호오류여부',
  `nds_stdt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서기준일자오류여부',
  `chaf_npnno_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후피보험자주민번호오류여부',
  `nrdps_nm_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자성명오류여부',
  `ins_imcd_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드오류여부',
  `ins_gdcd_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험상품코드오류여부',
  `ins_gdnm_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험상품명오류여부',
  `injr_rnkcd_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드오류여부',
  `ins_trm_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험기간오류여부',
  `ins_crrnm_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험계약자명오류여부',
  `chaf_cr_stcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후계약상태코드오류여부',
  `cr_st_chdt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약상태변경일자오류여부',
  `rvidt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부활일자오류여부',
  `trcvg_ct_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약담보건수오류여부',
  `trcvg_rgt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특약담보등록오류여부',
  `cmpu_wrkdt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전산작업일자오류여부',
  `et_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타오류여부',
  `nds_dcndt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서확정일자오류여부',
  `cr_dcndt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약확정일자오류여부',
  `befo_inq_bjyn_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전조회대상여부오류여부',
  `crt_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자주민번호',
  `nw_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신우편번호',
  `gu_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구우편번호',
  `gu_pstno_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구우편번호오류여부',
  `nw_pstno_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신우편번호오류여부',
  `ins_crt_rsno_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험계약자주민번호오류여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_rlpmi_trt_cr_rgt_00` (`mdcs_tlm_opndt`,`mdcs_tlm_admno`,`mdcs_tlm_ts_seqno`),
  KEY `idx_ins_rlpmi_trt_cr_rgt_10` (`plyno`)
) ENGINE=InnoDB AUTO_INCREMENT=1005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='실손특약계약등록';
