--
-- Table structure for table `ins_cr_cvr_cl`
--

DROP TABLE IF EXISTS `ins_cr_cvr_cl`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_cr_cvr_cl` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `ap_strdt` date DEFAULT NULL COMMENT '적용시작일자',
  `ap_nddt` date DEFAULT NULL COMMENT '적용종료일자',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `vald_nds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유효배서여부',
  `nds_ap_str_dthms` datetime DEFAULT NULL COMMENT '배서승인시작일시',
  `nds_ap_nd_dthms` datetime DEFAULT NULL COMMENT '배서승인종료일시',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `cvr_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보대상구분코드',
  `relpc_oj_seqno` decimal(10,0) DEFAULT NULL COMMENT '관계자목적물순번',
  `cvr_ba_trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보기본특약구분코드',
  `cvr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태코드',
  `cvr_st_chdt` date DEFAULT NULL COMMENT '담보상태변경일자',
  `isamt` decimal(17,2) DEFAULT NULL COMMENT '가입금액',
  `ba_prm` decimal(15,0) DEFAULT NULL COMMENT '기본보험료',
  `ap_prm` decimal(17,2) DEFAULT NULL COMMENT '적용보험료',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_st_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험시기시각',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `ins_clstr_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종기시각',
  `rnw_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신유형코드',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `pym_trmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간코드',
  `cvr_st_st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보시기기준년월',
  `pym_xmp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입면제여부',
  `pym_xmp_str_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입면제시작년월',
  `rfamt_clc_ins_st` date DEFAULT NULL COMMENT '준비금액산정보험시기',
  `rfamt_clc_ins_clstr` date DEFAULT NULL COMMENT '준비금액산정보험종기',
  `auto_rnw_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동갱신가능여부',
  `auto_rnw_cvr_cnldt` date DEFAULT NULL COMMENT '자동갱신담보해지일자',
  `cvr_fnl_pym_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보최종납입년월',
  `cvr_fnl_pym_seq` decimal(5,0) DEFAULT NULL COMMENT '담보최종납입회차',
  `nd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기구분코드',
  `nd` decimal(3,0) DEFAULT NULL COMMENT '만기',
  `ndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기코드',
  `rl_nd_trm` decimal(3,0) DEFAULT NULL COMMENT '실만기기간',
  `pym_trm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간구분코드',
  `pym_trm` decimal(3,0) DEFAULT NULL COMMENT '납입기간',
  `rl_pym_trm` decimal(3,0) DEFAULT NULL COMMENT '실납입기간',
  `nrdps_ap_age` decimal(3,0) DEFAULT NULL COMMENT '피보험자적용연령',
  `bfrnw_cvrsn` decimal(5,0) DEFAULT NULL COMMENT '갱신전담보순번',
  `bfrnw_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신전담보코드',
  `trt_preg_rnd_wkct` decimal(2,0) DEFAULT NULL COMMENT '특약임신경과주수',
  `cvr_is_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보가입유형코드',
  `rnw_nddt` date DEFAULT NULL COMMENT '갱신종료일자',
  `rnw_cvr_nclm_dcamt` decimal(15,0) DEFAULT NULL COMMENT '갱신담보무사고할인금액',
  `rwcvr_nclm_ad_dcamt` decimal(15,0) DEFAULT NULL COMMENT '갱신담보무사고추가할인금액',
  `sustd_xc_rk_ndx` decimal(7,2) DEFAULT NULL COMMENT '표준하체할증위험지수',
  `stdbd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준체보험료',
  `sustd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체보험료',
  `dcamt` decimal(15,0) DEFAULT NULL COMMENT '할인금액',
  `cvr_xtn_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보소멸상태코드',
  `nrdps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객번호',
  `nrdps_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객명',
  `nrdps_ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객식별번호',
  `nrdps_ap_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자적용성별코드',
  `rnw_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신담보여부',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `rnw_dgre` decimal(2,0) DEFAULT NULL COMMENT '갱신차수',
  `preg_rndwk` decimal(2,0) DEFAULT NULL COMMENT '임신경과주',
  `embr_mnt_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '태아개월담보여부',
  `rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율KEY조립코드',
  `bzcs_rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업비요율KEY조립코드',
  `sustd_rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준하체요율KEY조립코드',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`cls_yymm`,`plyno`,`cvrcd`,`cvr_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계약담보마감';
