--
-- Table structure for table `ins_crcr_dcls_nelp_prm`
--

DROP TABLE IF EXISTS `ins_crcr_dcls_nelp_prm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_crcr_dcls_nelp_prm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `clsdt` date NOT NULL COMMENT '마감일자',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `gdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품코드',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `trtcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '특약코드',
  `dty_cvr_seqno` decimal(5,0) NOT NULL COMMENT '의무담보순번',
  `nelp_da_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미경과자료구분코드',
  `ins_itm_smccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목소분류코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `cvr_ins_st` date DEFAULT NULL COMMENT '담보보험시기',
  `cvr_ins_clstr` date DEFAULT NULL COMMENT '담보보험종기',
  `cvr_ap_prm` decimal(17,2) DEFAULT NULL COMMENT '담보적용보험료',
  `isamt_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액코드',
  `nelp_days` decimal(6,0) DEFAULT NULL COMMENT '미경과일수',
  `nelp_prm` decimal(17,2) DEFAULT NULL COMMENT '미경과보험료',
  `ce_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집지점기관코드',
  `ce_bzp_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집영업소기관코드',
  `ce_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집직원번호',
  `cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량용도코드',
  `rp_pth_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수경로구분코드',
  `cvr_ad_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보추가계약여부',
  `co_obj_as_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동물건배정여부',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `sng_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단독계약구분코드',
  `gn_co_obj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일반공동물건구분코드',
  `gn_co_appr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일반공동인정구분코드',
  `prdm1_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물1가입여부',
  `co_obj_psrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동물건보유율',
  `ps_st_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '보유기준미경과보험료',
  `sys_mpv_dt` date DEFAULT NULL COMMENT '제도개선일자',
  `chbf_nelp_days` decimal(6,0) DEFAULT NULL COMMENT '변경전미경과일수',
  `chaf_nelp_days` decimal(6,0) DEFAULT NULL COMMENT '변경후미경과일수',
  `chbf_ap_prm` decimal(15,0) DEFAULT NULL COMMENT '변경전적용보험료',
  `chaf_ap_prm` decimal(15,0) DEFAULT NULL COMMENT '변경후적용보험료',
  `chbf_aprt` decimal(12,4) DEFAULT NULL COMMENT '변경전적용율',
  `chaf_aprt` decimal(12,4) DEFAULT NULL COMMENT '변경후적용율',
  `chbf_pym_prm` decimal(15,0) DEFAULT NULL COMMENT '변경전납입보험료',
  `chaf_pym_prm` decimal(15,0) DEFAULT NULL COMMENT '변경후납입보험료',
  `chbf_ins_days` decimal(6,0) DEFAULT NULL COMMENT '변경전보험일수',
  `chaf_ins_days` decimal(6,0) DEFAULT NULL COMMENT '변경후보험일수',
  `annu_ins_days` decimal(6,0) DEFAULT NULL COMMENT '년간보험일수',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `apldt` date DEFAULT NULL COMMENT '청약일자',
  `wekpl_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일제특약가입여부',
  `wekpl_trt_apdt` date DEFAULT NULL COMMENT '요일제특약적용일자',
  `wekpl_trt_nelp_days` decimal(6,0) DEFAULT NULL COMMENT '요일제특약미경과일수',
  `wekpl_nrnpr` decimal(17,2) DEFAULT NULL COMMENT '요일제미경과보험료',
  `gn_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '일반미경과보험료',
  `wekpl_psst_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '요일제보유기준미경과보험료',
  `gn_psst_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '일반보유기준미경과보험료',
  `onw_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신구계약구분코드',
  `ce_bf_psgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집전소속기관코드',
  `cvr_spqu_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보특성구분코드',
  `milg_is_amtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지가입금액코드',
  `milg_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지담보코드',
  `prort_shtrt` decimal(12,6) DEFAULT NULL COMMENT '일할단기율',
  `ap_numr` decimal(10,0) DEFAULT NULL COMMENT '적용분자',
  `ap_dnmt` decimal(10,0) DEFAULT NULL COMMENT '적용분모',
  `milg_dscrt` decimal(12,4) DEFAULT NULL COMMENT '마일리지할인율',
  `rl_cvr_st` date DEFAULT NULL COMMENT '실제담보시기',
  `rl_cvr_clstr` date DEFAULT NULL COMMENT '실제담보종기',
  `pym_pr_prm` decimal(15,0) DEFAULT NULL COMMENT '납입예정보험료',
  `milg_xc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지정산여부',
  `milg_xc_is_amtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마일리지정산가입금액코드',
  `milg_xc_amt` decimal(15,0) DEFAULT NULL COMMENT '마일리지정산금액',
  `dctp_trt_is_amtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인형특약가입금액코드',
  `dctp_trt_dscrt` decimal(12,4) DEFAULT NULL COMMENT '할인형특약할인율',
  `age_auto_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연령자동변경여부',
  `shtm_drv_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단기운전자특약가입여부',
  `age_auto_ch_ndsdt` date DEFAULT NULL COMMENT '연령자동변경배서일자',
  `trt_ap_cvr_prmsm` decimal(17,2) DEFAULT NULL COMMENT '특약적용담보보험료합계',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_crcr_dcls_nelp_prm_00` (`cls_yymm`,`clsdt`,`plyno`,`gdcd`,`cvrcd`,`cvr_seqno`,`trtcd`,`dty_cvr_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='자동차계약일마감미경과보험료';
