--
-- Table structure for table `ins_dvpns_cr_week_info`
--

DROP TABLE IF EXISTS `ins_dvpns_cr_week_info`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_dvpns_cr_week_info` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `menu_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '메뉴구분코드',
  `crdt` date NOT NULL COMMENT '발생일자',
  `cr_seqno` decimal(7,0) NOT NULL COMMENT '발생순번',
  `dvpns_ins_cmpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원보험회사코드',
  `cr_yr` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약년도',
  `dvpns_crano` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원계약번호',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `trt_1_strdt` date DEFAULT NULL COMMENT '특약1시작일자',
  `trt_1_nddt` date DEFAULT NULL COMMENT '특약1종료일자',
  `week_1_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일1코드',
  `trt_2_strdt` date DEFAULT NULL COMMENT '특약2시작일자',
  `trt_2_nddt` date DEFAULT NULL COMMENT '특약2종료일자',
  `week_2_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일2코드',
  `trt_3_strdt` date DEFAULT NULL COMMENT '특약3시작일자',
  `trt_3_nddt` date DEFAULT NULL COMMENT '특약3종료일자',
  `week_3_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일3코드',
  `trt_4_strdt` date DEFAULT NULL COMMENT '특약4시작일자',
  `trt_4_nddt` date DEFAULT NULL COMMENT '특약4종료일자',
  `week_4_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일4코드',
  `trt_5_strdt` date DEFAULT NULL COMMENT '특약5시작일자',
  `trt_5_nddt` date DEFAULT NULL COMMENT '특약5종료일자',
  `week_5_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일5코드',
  `rgtnm_nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기명피보험자명',
  `rgtnm_nrdno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기명피보험자번호',
  `cmpu_inp_dthms` datetime DEFAULT NULL COMMENT '전산입력일시',
  `cr_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량변경여부',
  `nrdps_1_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자1차량번호',
  `nrdps_2_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자2차량번호',
  `nrdps_1_nds_stdt` date DEFAULT NULL COMMENT '피보험자1배서기준일자',
  `nrdps_3_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자3차량번호',
  `nrdps_2_nds_stdt` date DEFAULT NULL COMMENT '피보험자2배서기준일자',
  `nrdps_4_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자4차량번호',
  `nrdps_3_nds_stdt` date DEFAULT NULL COMMENT '피보험자3배서기준일자',
  `nrdps_5_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자5차량번호',
  `nrdps_4_nds_stdt` date DEFAULT NULL COMMENT '피보험자4배서기준일자',
  `cr_dscno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차식별번호',
  `trm_sno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기일련번호',
  `trm_autno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기인증번호',
  `fr_trm_tkatt_dthms` datetime DEFAULT NULL COMMENT '최초단말기탈부착일시',
  `vald_trm_tkatt_dthms` datetime DEFAULT NULL COMMENT '유효단말기탈부착일시',
  `fnl_trm_tkatt_dthms` datetime DEFAULT NULL COMMENT '최종단말기탈부착일시',
  `oper_info_rcgnt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운행정보인식오류여부',
  `trm_sno_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기일련번호오류여부',
  `autno_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인증번호오류여부',
  `trm_tkatt_dlay_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기탈부착지연여부',
  `tsdt_dlay_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전송일자지연여부',
  `chg_bf_ts_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '교체전전송여부',
  `trm_db_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기중복여부',
  `trm_db_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기중복회사코드',
  `trt_db_st` date DEFAULT NULL COMMENT '특약중복시기',
  `trt_db_clstr` date DEFAULT NULL COMMENT '특약중복종기',
  `db_cr_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중복계약차량번호',
  `anal_rst_ts_dthms` datetime DEFAULT NULL COMMENT '분석결과전송일시',
  `anal_id` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분석ID',
  `dl_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리결과코드',
  `ercd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '오류코드',
  `trm_prv_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단말기기등록여부',
  `cr_prv_rgt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차기등록여부',
  `oper_dst` decimal(7,0) DEFAULT NULL COMMENT '운행거리',
  `trm_tkatt_days` decimal(7,0) DEFAULT NULL COMMENT '단말기탈부착일수',
  `t_oper_days` decimal(7,0) DEFAULT NULL COMMENT '총운행일수',
  `mon_oper_days` decimal(7,0) DEFAULT NULL COMMENT '월요일운행일수',
  `tue_oper_days` decimal(7,0) DEFAULT NULL COMMENT '화요일운행일수',
  `wed_oper_days` decimal(7,0) DEFAULT NULL COMMENT '수요일운행일수',
  `thr_oper_days` decimal(7,0) DEFAULT NULL COMMENT '목요일운행일수',
  `fri_oper_days` decimal(7,0) DEFAULT NULL COMMENT '금요일운행일수',
  `sat_oper_days` decimal(7,0) DEFAULT NULL COMMENT '토요일운행일수',
  `sun_oper_days` decimal(7,0) DEFAULT NULL COMMENT '일요일운행일수',
  `trt_is_trm` decimal(5,0) DEFAULT NULL COMMENT '특약가입기간',
  `t_vlt_days` decimal(7,0) DEFAULT NULL COMMENT '총위반일수',
  `mon_vlt_days` decimal(7,0) DEFAULT NULL COMMENT '월요일위반일수',
  `tue_vlt_days` decimal(7,0) DEFAULT NULL COMMENT '화요일위반일수',
  `wed_vlt_days` decimal(7,0) DEFAULT NULL COMMENT '수요일위반일수',
  `thr_vlt_days` decimal(7,0) DEFAULT NULL COMMENT '목요일위반일수',
  `fri_vlt_days` decimal(7,0) DEFAULT NULL COMMENT '금요일위반일수',
  `oper_rst` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운행결과',
  `jnsno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_dvpns_cr_week_info_00` (`plyno`,`menu_flgcd`,`crdt`,`cr_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개발원승용차요일정보';
