--
-- Table structure for table `ins_dvpns_rnwrt_da`
--

DROP TABLE IF EXISTS `ins_dvpns_rnwrt_da`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_dvpns_rnwrt_da` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `dvpns_ins_cmpcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '개발원보험회사코드',
  `dvpns_ikdcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '개발원보종코드',
  `cr_yr` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '계약년도',
  `dvpns_crano` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '개발원계약번호',
  `nrdps_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호구분코드',
  `nrdps_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호',
  `cr_dbcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량차대구분코드',
  `crgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량관코드',
  `cr_or_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량/차대번호',
  `cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량용도코드',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `frg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외국인여부',
  `nrdps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자성명',
  `spcf_obj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특정물건여부',
  `cn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해지여부',
  `ndv_gr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개별단체구분코드',
  `dvpns_us_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원사용용도코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `vald_nddt` date DEFAULT NULL COMMENT '유효종료일자',
  `sep_ct` decimal(2,0) DEFAULT NULL COMMENT '분할횟수',
  `bdin1_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인1가입여부',
  `bdin2_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인2가입여부',
  `prdm_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물가입여부',
  `obi_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손가입여부',
  `cr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량가입여부',
  `injr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해가입여부',
  `age_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연령한정특약코드',
  `drv_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자한정특약코드',
  `ovavc_bdl_cvr_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전차량일괄담보특약코드',
  `dc_xcrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '할인할증율',
  `ad_xcrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '추가할증율',
  `nds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서여부',
  `rpbl_cr_dvpns_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임계약개발원증권번호',
  `rpbl_ins_st` date DEFAULT NULL COMMENT '책임보험시기',
  `rpbl_ins_clstr` date DEFAULT NULL COMMENT '책임보험종기',
  `rpbl_vldtm_nddt` date DEFAULT NULL COMMENT '책임유효기간말일자',
  `rpbl_obj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임물건구분코드',
  `rpbl_cn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임해지구분코드',
  `rpbl_dc_xcrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '책임할인할증율',
  `rnw_ins_st` date DEFAULT NULL COMMENT '갱신보험시기',
  `rnw_ins_clstr` date DEFAULT NULL COMMENT '갱신보험종기',
  `rnw_y3_clmct` decimal(2,0) DEFAULT NULL COMMENT '갱신3년사고건수',
  `rnw_clm_poct` decimal(4,1) DEFAULT NULL COMMENT '갱신사고점수',
  `rnw_my_crps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신다수차량보유여부',
  `rnw_rnw_ap_rt` decimal(15,7) NOT NULL DEFAULT '0.0000000' COMMENT '갱신갱신적용요율',
  `spc_xc1_grd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증1등급',
  `spc_xc1_smcl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증1소분류',
  `spc_xc1_cn_vl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증1내용값',
  `spc_xc1ct` decimal(1,0) DEFAULT NULL COMMENT '특별할증1건수',
  `spc_xc2_grd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증2등급',
  `spc_xc2_smcl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증2소분류',
  `spc_xc2_cn_vl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증2내용값',
  `spc_xc2ct` decimal(1,0) DEFAULT NULL COMMENT '특별할증2건수',
  `spc_xc3_grd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증3등급',
  `spc_xc3_smcl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증3소분류',
  `spc_xc3_cn_vl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증3내용값',
  `spc_xc3ct` decimal(1,0) DEFAULT NULL COMMENT '특별할증3건수',
  `pgsv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개문발차여부',
  `ftway_invs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보도침범여부',
  `ntt_imu_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고의면책여부',
  `sh_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위장사고여부',
  `drnkn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주취여부',
  `drnk_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '음주여부',
  `sgnl_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신호위반여부',
  `ctln_invs_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중앙선침범여부',
  `speed_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '속도위반여부',
  `pass_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '앞지르기여부',
  `rcmtd_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건널목통과방법위반여부',
  `crswk_vlt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '횡단보도위반여부',
  `fleeg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도주여부',
  `crme_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '범죄사고여부',
  `medi_txc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약물중독여부',
  `et_clm_mtt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타사고사항여부',
  `fr_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초가입경력코드',
  `is_crrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '가입경력코드',
  `is_crr_trm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입경력기간',
  `optn_is_crrrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '임의가입경력율',
  `rpbl_is_crrrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '책임가입경력율',
  `carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호',
  `da_incdt` date DEFAULT NULL COMMENT '자료수록일자',
  `da_inc_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료수록시간',
  `da_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료구분코드',
  `nlic_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '무면허사고여부',
  `plus_trt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '플러스특약여부',
  `rpbl_same_ply_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임동일증권여부',
  `rpbl_spcf_obj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임특정물건여부',
  `optn_same_ply_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임의동일증권여부',
  `optn_spcf_obj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임의특정물건여부',
  `pym_ct` decimal(3,0) DEFAULT NULL COMMENT '납입횟수',
  `rglt_vltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법규위반코드',
  `rglt_vlt_crrrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '법규위반경력율',
  `rpbl_nwgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임신상품코드',
  `optn_nwgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임의신상품코드',
  `dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인할증등급코드',
  `rpbl_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임할인할증등급코드',
  `rnw_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신할인할증등급코드',
  `same_grd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일등급여부',
  `mtral_xc_stamt` decimal(15,0) DEFAULT NULL COMMENT '물적할증기준금액',
  `dvpns_week_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원요일코드',
  `week_vlt_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요일위반사고여부',
  `spc_xc4_grd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증4등급',
  `spc_xc4_smcl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증4소분류',
  `spc_xc4_cn_vl` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증4내용값',
  `spc_xc4ct` decimal(1,0) DEFAULT NULL COMMENT '특별할증4건수',
  `ibnr_1_clmdt` date DEFAULT NULL COMMENT 'IBNR1사고일자',
  `ibnr_1_rcrdt` date DEFAULT NULL COMMENT 'IBNR1접보일자',
  `ibnr_1_clm_poct` decimal(3,0) DEFAULT NULL COMMENT 'IBNR1사고점수',
  `ibnr_2_clmdt` date DEFAULT NULL COMMENT 'IBNR2사고일자',
  `ibnr_2_rcrdt` date DEFAULT NULL COMMENT 'IBNR2접보일자',
  `ibnr_2_clm_poct` decimal(3,0) DEFAULT NULL COMMENT 'IBNR2사고점수',
  `ibnr_3_clmdt` date DEFAULT NULL COMMENT 'IBNR3사고일자',
  `ibnr_3_rcrdt` date DEFAULT NULL COMMENT 'IBNR3접보일자',
  `ibnr_3_clm_poct` decimal(3,0) DEFAULT NULL COMMENT 'IBNR3사고점수',
  `rnw_grd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신등급',
  `shtm_dc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단기할인여부',
  `y1_clm_ct` decimal(3,0) DEFAULT NULL COMMENT '1년사고횟수',
  `annu1_clmct` decimal(3,0) DEFAULT NULL COMMENT '1년간사고건수',
  `annu2_clmct` decimal(3,0) DEFAULT NULL COMMENT '2년간사고건수',
  `annu3_clmct` decimal(3,0) DEFAULT NULL COMMENT '3년간사고건수',
  `cr_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량가입경력코드',
  `dvpns_obj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원물건구분코드',
  `dvpns_nrdcd_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원피보험자코드변경여부',
  `dvpns_madmo_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원마디모등급코드',
  `lwflt_grc_clm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '저과실유예사고여부',
  `lwflt_grc_clm_poct` decimal(5,1) DEFAULT NULL COMMENT '저과실유예사고점수',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_dvpns_rnwrt_da_00` (`dvpns_ins_cmpcd`,`dvpns_ikdcd`,`cr_yr`,`dvpns_crano`),
  KEY `idx_ins_dvpns_rnwrt_da_10` (`nrdps_dscno`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개발원갱신율자료';
