--
-- Table structure for table `ins_rlpmi_trt_cvr_rgt`
--

DROP TABLE IF EXISTS `ins_rlpmi_trt_cvr_rgt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_rlpmi_trt_cvr_rgt` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `mdcs_tlm_opndt` date NOT NULL COMMENT '의료비전문개시일자',
  `mdcs_tlm_admno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '의료비전문관리번호',
  `mdcs_tlm_ts_seqno` decimal(5,0) NOT NULL COMMENT '의료비전문전송순번',
  `mdcs_cvr_seqno` decimal(5,0) NOT NULL COMMENT '의료비담보순번',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `isamt` decimal(17,2) NOT NULL COMMENT '가입금액',
  `dcof_uiamt` decimal(15,0) NOT NULL COMMENT '의원공제금액',
  `hsp_uiamt` decimal(15,0) NOT NULL COMMENT '병원공제금액',
  `rcpr_org_uiamt` decimal(15,0) NOT NULL COMMENT '요양기관공제금액',
  `drfe_uiamt` decimal(15,0) NOT NULL COMMENT '약제비공제금액',
  `uiamt` decimal(17,2) NOT NULL COMMENT '공제금액',
  `gn_cncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보장내용코드',
  `cvr_spcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보특성코드',
  `cpyt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'COPAYMENT구분코드',
  `uiamt_stncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제금액기준코드',
  `cmp_trmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상기간코드',
  `ward_diamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병실차액구분코드',
  `npp_hlprm_napc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국민건강보험미적용구분코드',
  `mdcs_tlm_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문종별코드',
  `mdcs_tlm_spe_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문종별세부코드',
  `trscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'TRANSACTION코드',
  `knia` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KNIA',
  `mdcs_tlm_opn_hms` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문개시시분초',
  `trs_org` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송신기관',
  `rcv_org` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수신기관',
  `cvr_sno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보일련번호',
  `sndr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송신자직원번호',
  `anscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '응답코드',
  `cvr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태코드',
  `mdcs_trt_rgt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비특약등록구분코드',
  `mdcs_tlm_dl_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비전문처리상태코드',
  `rgt_bj_vald_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '등록대상유효여부',
  `nrdps_relpc_seqno` decimal(10,0) DEFAULT NULL COMMENT '피보험자관계자순번',
  `nrdps_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자주민번호',
  `ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험회사코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `st_chdt` date DEFAULT NULL COMMENT '상태변경일자',
  `cvr_ch_dcndt` date DEFAULT NULL COMMENT '담보변경확정일자',
  `gu_uiamt` decimal(15,0) DEFAULT NULL COMMENT '구공제금액',
  `ins_cmpcd_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험회사코드오류여부',
  `plyno_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호오류여부',
  `nrdps_rsno_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자주민번호오류여부',
  `gn_cncd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보장내용코드오류여부',
  `cvr_spcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보특성코드오류여부',
  `cvr_sno_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보일련번호오류여부',
  `cpyt_flgcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'COPAYMENT구분코드오류여부',
  `uiamt_stncd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공제금액기준코드오류여부',
  `cmp_trmcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상기간코드오류여부',
  `ward_diamt_rstcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병실차액결과코드오류여부',
  `hlprm_cmp_rstcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건강보험보상결과코드오류여부',
  `cvr_trm_strdt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보기간시작일자오류여부',
  `cvr_trm_nddt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보기간종료일자오류여부',
  `cvr_stcd_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태코드오류여부',
  `cvr_st_chdt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태변경일자오류여부',
  `cvr_ch_dcndt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보변경확정일자오류여부',
  `isamt_er_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액오류여부',
  `dcof_uiamt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의원공제금액오류여부',
  `hsp_uiamt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원공제금액오류여부',
  `rcpr_org_uiamt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요양기관공제금액오류여부',
  `drfe_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약제비오류여부',
  `gu_uiamt_eryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구공제금액오류여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_rlpmi_trt_cvr_rgt_00` (`mdcs_tlm_opndt`,`mdcs_tlm_admno`,`mdcs_tlm_ts_seqno`,`mdcs_cvr_seqno`),
  KEY `idx_ins_rlpmi_trt_cvr_rgt_10` (`plyno`)
) ENGINE=InnoDB AUTO_INCREMENT=3389 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='실손특약담보등록';
