--
-- Table structure for table `ins_gn_rn_dm_clg_info`
--

DROP TABLE IF EXISTS `ins_gn_rn_dm_clg_info`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_gn_rn_dm_clg_info` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `rn_rtro_cr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '원수수재계약구분코드',
  `rertr_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '출수재구분코드',
  `cls_bjno` varchar(40) COLLATE utf8mb4_bin NOT NULL COMMENT '마감대상번호',
  `ibnf_cs_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험금비용구분코드',
  `xi_py_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '추산지급구분코드',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고담보코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수조사순번',
  `clmps_seqno` decimal(3,0) DEFAULT NULL COMMENT '사고자순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `cc_seq` decimal(3,0) DEFAULT NULL COMMENT '산출회차',
  `xi_py_spc_seqno` decimal(3,0) DEFAULT NULL COMMENT '추산지급내역순번',
  `oj_seqno` decimal(5,0) DEFAULT NULL COMMENT '목적물순번',
  `cr_cvrcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약담보코드',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `clmdt` date DEFAULT NULL COMMENT '사고일자',
  `udrtk_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수형태코드',
  `thcp_qtrt` decimal(12,6) DEFAULT NULL COMMENT '당사지분율',
  `crt_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자사업자번호',
  `crma_rs_or_crpno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약주주민/법인번호',
  `clm_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고대상구분코드',
  `clmps_bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고자사업자번호',
  `clmps_rs_or_crpno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고자주민/법인번호',
  `py_ibnf` decimal(17,2) DEFAULT NULL COMMENT '지급보험금',
  `py_ibnf_examt` decimal(17,2) DEFAULT NULL COMMENT '지급보험금환입금액',
  `xiamt` decimal(17,2) DEFAULT NULL COMMENT '추산보험금',
  `nvcs` decimal(17,2) DEFAULT NULL COMMENT '조사비',
  `nvcs_rfamt` decimal(17,2) DEFAULT NULL COMMENT '조사비준비금액',
  `woncr_py_ibnf` decimal(15,0) DEFAULT NULL COMMENT '원화지급보험금',
  `woncr_ibnf_examt` decimal(15,0) DEFAULT NULL COMMENT '원화보험금환입금액',
  `woncr_xiamt` decimal(15,0) DEFAULT NULL COMMENT '원화추산보험금액',
  `woncr_nvcs` decimal(15,0) DEFAULT NULL COMMENT '원화조사비',
  `woncr_nvcs_rfamt` decimal(15,0) DEFAULT NULL COMMENT '원화조사비준비금액',
  `xi_py_flg_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추산지급구분사유코드',
  `ce_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집기관코드',
  `ce_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집직원번호',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `chrps_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자기관코드',
  `chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자직원번호',
  `chr_admr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당관리자기관코드',
  `chr_admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당관리자직원번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  PRIMARY KEY (`cls_yymm`,`rn_rtro_cr_flgcd`,`rertr_flgcd`,`cls_bjno`,`ibnf_cs_flgcd`,`xi_py_flgcd`,`mncd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='일반원수손해결산정보'
