--
-- Table structure for table `sam_org`
--

DROP TABLE IF EXISTS `sam_org`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sam_org` (
  `orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '기관코드',
  `orgnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '기관명',
  `org_ennm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관영문명',
  `org_shtnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '기관단축명',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `org_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관구분코드',
  `org_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관유형코드',
  `org_spcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관특성코드',
  `org_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관상태코드',
  `org_stb_rscd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관개설사유코드',
  `org_stbdt` date NOT NULL COMMENT '기관개설일자',
  `org_clo_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관폐쇄사유코드',
  `org_clodt` date NOT NULL COMMENT '기관폐쇄일자',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `orghd_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관장직원번호',
  `orghd_apodt` date DEFAULT NULL COMMENT '기관장발령일자',
  `ppr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위기관코드',
  `rcapm_org_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '출납기관여부',
  `rcapm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출납기관코드',
  `act_org_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '회계기관여부',
  `act_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회계기관코드',
  `rv_org_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '수납기관여부',
  `rv_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수납기관코드',
  `jrd_uofcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관할관청코드',
  `crp_eqdtx_pymbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인균등할법인세납부대상여부',
  `insbz_lictx_pymbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험업면허세납부대상여부',
  `pdwkp_txpym_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재산할사업소세납부대상여부',
  `ofwk_stf_apo_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '내근직원발령여부',
  `bz_strdt` date DEFAULT NULL COMMENT '영업시작일자',
  `tm_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팀종류코드',
  `vl_gp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가그룹구분코드',
  `mncs_gp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운영비그룹구분코드',
  `are_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지역구분코드',
  `org_rl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '기관실제구분코드',
  `trn_tm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '육성팀구분코드',
  `fr_rgt_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초등록회사코드',
  `fire_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화재기관코드',
  `vl_adm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가관리직원번호',
  `vl_adm_stf_apodt` date DEFAULT NULL COMMENT '평가관리직원발령일자',
  `vl_ppr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평가상위기관코드',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `adm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관코드',
  `stgy_org_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전략기관구분코드',
  `sfp_org_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SFP기관구분코드',
  `bf_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전우편번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`orgcd`),
  KEY `idx_sam_org_01` (`ppr_orgcd`,`org_stcd`,`org_spcd`,`org_flgcd`,`org_clodt`,`org_tpcd`,`orgcd`),
  KEY `idx_sam_org_10` (`adm_orgcd`),
  KEY `idx_sam_org_11` (`rcapm_orgcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='기관';
