--
-- Table structure for table `sam_stf`
--

DROP TABLE IF EXISTS `sam_stf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sam_stf` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '직원번호',
  `stf_bz_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '직원영업상태코드',
  `stadt` date NOT NULL COMMENT '상태일자',
  `rsno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '주민번호',
  `nm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '성명',
  `mail_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일아이디',
  `mail_domn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일도메인',
  `hmpag_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '홈페이지주소',
  `blog_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '블로그주소',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `actno_chdt` date DEFAULT NULL COMMENT '계좌번호변경일자',
  `ntrdt` date DEFAULT NULL COMMENT '입사일자',
  `retdt` date NOT NULL COMMENT '퇴사일자',
  `incb_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해촉사유코드',
  `stf_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '직원구분코드',
  `fnl_edbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종학력코드',
  `hnor_cmp_stf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '명예보상직원여부',
  `adm_orgn_wrk_strdt` date DEFAULT NULL COMMENT '관리조직근무시작일자',
  `adm_orgn_wrk_nddt` date DEFAULT NULL COMMENT '관리조직근무종료일자',
  `rl_brtyr_mndy` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실제생년월일',
  `slcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '양음구분코드',
  `apo_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위촉구분코드',
  `apo_flg_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위촉구분상세코드',
  `crnt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현재기관코드',
  `crnt_tm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현재팀기관코드',
  `adm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관코드',
  `relco_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계회사직원번호',
  `scil_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사회경력코드',
  `photo_pth` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사진경로',
  `aconm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌주명',
  `fr_ntr_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최초입사회사코드',
  `fire_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화재직원번호',
  `bz_stch_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업상태변경사유코드',
  `adm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리직원번호',
  `adm_stf_apodt` date DEFAULT NULL COMMENT '관리직원발령일자',
  `cno_info` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접속정보',
  `sb_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대체직원번호',
  `wrkpl_cd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근무지코드',
  `ins_bscrl_pno` varchar(14) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험업계고유번호',
  `brof_cd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출장소코드',
  `dptcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과코드',
  `outs_org_onsf_cd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부기관자체코드',
  `bnc_autcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카권한코드',
  `bz_agy_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업대리점구분코드',
  `crpno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인번호',
  `mthr_agy_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모대리점구분코드',
  `agy_lfinr_sjb_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점생보겸업구분코드',
  `agy_rgt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점등록구분코드',
  `bnc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카등급코드',
  `dty_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직책세부코드',
  `bnc_br_spcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카지점특성코드',
  `bnc_dh_agycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카취급대리점코드',
  `bnc_bk_br_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카은행지점그룹코드',
  `bnc_bk_br_gpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '방카은행지점그룹명',
  `bz_act_avyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업활동가능여부',
  `dep_mail_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부서메일사용여부',
  `asso_rgt_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협회등록종류코드',
  `eng_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문성명',
  `crnt_pst_apodt` date DEFAULT NULL COMMENT '현재소속발령일자',
  `bdtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직무코드',
  `bdt_apodt` date DEFAULT NULL COMMENT '직무발령일자',
  `dtycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직책코드',
  `dty_apodt` date DEFAULT NULL COMMENT '직책발령일자',
  `ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직위코드',
  `grdpa_apodt` date DEFAULT NULL COMMENT '급호발령일자',
  `ptn_apodt` date DEFAULT NULL COMMENT '직위발령일자',
  `clpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직급코드',
  `pays_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '호봉코드',
  `rtm_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '퇴직사유코드',
  `wdg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결혼여부',
  `drve_lic_own_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전면허소유여부',
  `indc_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유치자직원번호',
  `indc_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유치자관계코드',
  `atr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유치구분코드',
  `befo_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이전직원번호',
  `grpwr_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '그룹웨어사용여부',
  `msngr_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '메신저사용여부',
  `stfno_grtdt` date DEFAULT NULL COMMENT '직원번호부여일자',
  `intr_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도입유형코드',
  `bz_atrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업속성코드',
  `bz_atr_chdt` date DEFAULT NULL COMMENT '영업속성변경일자',
  `psn_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인등급코드',
  `psn_grd_grtdt` date DEFAULT NULL COMMENT '개인등급부여일자',
  `psn_grd_nddt` date DEFAULT NULL COMMENT '개인등급종료일자',
  `bz_fml_qufcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업가족자격코드',
  `quf_dlgdt` date DEFAULT NULL COMMENT '자격위임일자',
  `bz_fml_tmnd_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업가족팀장등급코드',
  `quf_grd_chdt` date DEFAULT NULL COMMENT '자격등급변경일자',
  `quf_grd_nddt` date DEFAULT NULL COMMENT '자격등급종료일자',
  `pstn_chccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신분변동코드',
  `pstn_chcdt` date DEFAULT NULL COMMENT '신분변동일자',
  `club_mbr_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '클럽멤버등급코드',
  `club_mbr_grd_grtdt` date DEFAULT NULL COMMENT '클럽멤버등급부여일자',
  `club_mbr_grd_nddt` date DEFAULT NULL COMMENT '클럽멤버등급종료일자',
  `trf_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '교통수단코드',
  `attd_nd_timcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출근소요시간코드',
  `notb_own_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '노트북소유여부',
  `onfml_pf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한가족우대여부',
  `onfml_pf_grd_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한가족우대등급등급코드',
  `onfml_pf_grd_grtdt` date DEFAULT NULL COMMENT '한가족우대등급부여일자',
  `onfml_pf_grd_nddt` date DEFAULT NULL COMMENT '한가족우대등급종료일자',
  `ltrm_aw_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기수당그룹코드',
  `ltrm_aw_gp_chdt` date DEFAULT NULL COMMENT '장기수당그룹변경일자',
  `atch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전속여부',
  `atch_yn_chdt` date DEFAULT NULL COMMENT '전속여부변경일자',
  `agy_quf_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점자격등급코드',
  `agy_quf_grd_chdt` date DEFAULT NULL COMMENT '대리점자격등급변경일자',
  `agy_pntcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점인격코드',
  `agy_pntcd_chdt` date DEFAULT NULL COMMENT '대리점인격코드변경일자',
  `offc_accpt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '점포수용구분코드',
  `agynm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점명',
  `pdtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자명',
  `org_rgt_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원등록회사코드',
  `cm_ap_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수수료적용그룹코드',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `admr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리자직원번호',
  `admr_apodt` date DEFAULT NULL COMMENT '관리자발령일자',
  `st_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기준직원번호',
  `adm_agycd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리대리점코드',
  `adm_agy_apodt` date DEFAULT NULL COMMENT '관리대리점발령일자',
  `brc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지사기관코드',
  `crnt_brc_apodt` date DEFAULT NULL COMMENT '현재지사발령일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_sam_stf_00` (`stfno`),
  KEY `idx_sam_stf_01` (`crnt_orgcd`,`stf_bz_stcd`,`stf_flgcd`,`bdtcd`,`retdt`,`ntrdt`,`stfno`,`nm`),
  KEY `idx_sam_stf_19` (`crnt_tm_orgcd`,`stf_bz_stcd`,`stfno`),
  KEY `idx_sam_stf_11` (`nm`),
  KEY `idx_sam_stf_10` (`rsno`)
) ENGINE=InnoDB AUTO_INCREMENT=641 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='직원';
