--
-- Table structure for table `ins_pl_nds_dt_temp`
--

DROP TABLE IF EXISTS `ins_pl_nds_dt_temp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_pl_nds_dt_temp` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호',
  `cgaf_ch_seqno` decimal(5,0) NOT NULL DEFAULT '0' COMMENT '발행후변경순번',
  `nds_dt_seqno` decimal(5,0) NOT NULL COMMENT '배서상세순번',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `ch_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경구분코드',
  `chbf_cnn_tabnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전관련테이블명',
  `chbf_ky_clmvl_1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값1',
  `chbf_ky_clmvl_2` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값2',
  `chbf_ky_clmvl_3` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값3',
  `chbf_ky_clmvl_4` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값4',
  `chbf_ky_clmvl_5` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값5',
  `chbf_ky_clmvl_6` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값6',
  `chbf_ky_clmvl_7` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값7',
  `chbf_ky_clmvl_8` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값8',
  `chbf_ky_clmvl_9` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값9',
  `chbf_ky_clmvl_10` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값10',
  `chbf_ky_clmvl_11` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값11',
  `chbf_ky_clmvl_12` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값12',
  `chbf_ky_clmvl_13` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값13',
  `chbf_ky_clmvl_14` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값14',
  `chbf_ky_clmvl_15` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전키컬럼값15',
  `chbf_ap_nddt` date DEFAULT NULL COMMENT '변경전적용종료일자',
  `chbf_ap_strdt` date DEFAULT NULL COMMENT '변경전적용시작일자',
  `chbf_ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전배서번호',
  `chbf_vald_nds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전유효배서여부',
  `chbf_ndsap_str_dthms` datetime DEFAULT NULL COMMENT '변경전배서승인시작일시',
  `chbf_ndsap_nd_dthms` datetime DEFAULT NULL COMMENT '변경전배서승인종료일시',
  `chaf_cnn_tabnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후관련테이블명',
  `chaf_ky_clmvl_1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값1',
  `chaf_ky_clmvl_2` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값2',
  `chaf_ky_clmvl_3` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값3',
  `chaf_ky_clmvl_4` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값4',
  `chaf_ky_clmvl_5` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값5',
  `chaf_ky_clmvl_6` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값6',
  `chaf_ky_clmvl_7` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값7',
  `chaf_ky_clmvl_8` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값8',
  `chaf_ky_clmvl_9` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값9',
  `chaf_ky_clmvl_10` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값10',
  `chaf_ky_clmvl_11` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값11',
  `chaf_ky_clmvl_12` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값12',
  `chaf_ky_clmvl_13` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값13',
  `chaf_ky_clmvl_14` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값14',
  `chaf_ky_clmvl_15` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후키컬럼값15',
  `nds_note` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서비고',
  `atrcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '속성코드',
  `chbvl` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경전값',
  `chavl` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경후값',
  `nds_dt_itnm` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서상세항목명',
  `ap_xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '적용환율',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `xcrt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환율구분코드',
  `ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '적용보험료',
  `isamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액',
  `woncr_cv_ap_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산적용보험료',
  `woncr_cv_isamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산가입금액',
  `nds_isamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '배서가입금액',
  `nds_ba_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '배서기본보험료',
  `nds_ap_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '배서적용보험료',
  `nds_woncv_ap_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '배서원화환산적용보험료',
  `nds_woncr_cv_isamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '배서원화환산가입금액',
  `nds_woncv_ba_prm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '배서원화환산기본보험료',
  `prort_shtm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일할단기구분코드',
  `prort_shtrt` decimal(12,6) DEFAULT NULL COMMENT '일할단기율',
  `gvmt_asamt` decimal(17,2) DEFAULT NULL COMMENT '정부보조금액',
  `gvmt_nds_asamt` decimal(17,2) DEFAULT NULL COMMENT '정부배서보조금액',
  `sd_asamt` decimal(17,2) DEFAULT NULL COMMENT '시도보조금액',
  `sd_nds_asamt` decimal(17,2) DEFAULT NULL COMMENT '시도배서보조금액',
  `sgng_asamt` decimal(17,2) DEFAULT NULL COMMENT '시군구보조금액',
  `sgng_nds_asamt` decimal(17,2) DEFAULT NULL COMMENT '시군구배서보조금액',
  `crt_prm` decimal(17,2) DEFAULT NULL COMMENT '계약자보험료',
  `crt_nds_prm` decimal(17,2) DEFAULT NULL COMMENT '계약자배서보험료',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_pl_nds_dt_temp_00` (`plno`,`cgaf_ch_seqno`,`nds_dt_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=1368 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='설계배서상세임시';
