--
-- Table structure for table `ins_gr_nrdps_upld_da`
--

DROP TABLE IF EXISTS `ins_gr_nrdps_upld_da`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_gr_nrdps_upld_da` (
  `nrdps_da_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자자료구분코드',
  `plno_or_plyno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호/증권번호',
  `upld_ordr` decimal(3,0) NOT NULL COMMENT '업로드순차',
  `nrdps_rsno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자주민번호',
  `nt_seqno` decimal(5,0) DEFAULT NULL COMMENT '통지순번',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `relpc_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계자식별번호구분코드',
  `eng_relnm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문관계자명',
  `ctm_ennm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객영문명여부',
  `frg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외국인여부',
  `sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성별코드',
  `jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업코드',
  `upld_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업로드상태코드',
  `gp_is_tp` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '그룹가입유형',
  `relpc_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계자상태코드',
  `mn_nrdps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주피보험자여부',
  `crt_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자관계코드',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `trf_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '교통급수코드',
  `rank3_xc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3급할증여부',
  `nrdps_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자관계코드',
  `pfbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자명',
  `pfb_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자주민번호',
  `pfb_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자식별번호구분코드',
  `pfb_ennm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자영문명',
  `pfb_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자성별코드',
  `pfb_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자고객번호',
  `nrdps_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자동의여부',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `drve_lic_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전면허종별코드',
  `isrdt` date DEFAULT NULL COMMENT '가입일자',
  `cnldt` date DEFAULT NULL COMMENT '해지일자',
  `st_apdt` date DEFAULT NULL COMMENT '상태적용일자',
  `ssng_cmp_gdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '여행회사상품명',
  `crcc_colus_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약체결수집이용동의여부',
  `crcc_crdir_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약체결신용정보조회동의여부',
  `crcc_crdio_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약체결신용정보제공동의여부',
  `crcc_sesin_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약체결민감정보동의여부',
  `mail_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일아이디',
  `mail_domn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일도메인',
  `hpno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴대폰번호',
  `xc_nrdps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정산피보험자여부',
  `exis_pfbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자명',
  `exis_pfb_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자주민등록번호',
  `exis_pfb_ennm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자영문명',
  `exis_pfb_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자성별코드',
  `exis_pfb_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자고객번호',
  `exis_pfb_relpc_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자관계자식별번호구분코드',
  `exis_pfb_agryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생존수익자동의여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`nrdps_da_flgcd`,`plno_or_plyno`,`upld_ordr`,`nrdps_rsno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='단체피보험자업로드자료';
