--
-- Table structure for table `ins_pl_oj`
--

DROP TABLE IF EXISTS `ins_pl_oj`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_pl_oj` (
  `plno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호',
  `cgaf_ch_seqno` decimal(5,0) NOT NULL COMMENT '발행후변경순번',
  `oj_seqno` decimal(5,0) NOT NULL COMMENT '목적물순번',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `oj_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '목적물상태코드',
  `oj_sign` decimal(3,0) DEFAULT NULL COMMENT '목적물부호',
  `hngl_ojnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글목적물명',
  `eng_ojnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문목적물명',
  `rt_ap_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율적용분류코드',
  `rt_apcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율적용코드',
  `oj_dt_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물상세내용',
  `mngm_bn_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영위업종분류코드',
  `mngm_btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영위업종코드',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `oj_qant` decimal(5,0) DEFAULT NULL COMMENT '목적물수량',
  `obj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물건구분코드',
  `cvr_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보내용',
  `cvr_arecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보지역코드',
  `cvr_are_ad_cnd` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보지역추가조건',
  `agmt_aqr_rt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협정구득요율구분코드',
  `aqr_rt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구득요율구분코드',
  `ordr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발주자구분코드',
  `bz_stdt` date DEFAULT NULL COMMENT '사업시기일자',
  `bz_clsdt` date DEFAULT NULL COMMENT '사업종기일자',
  `wrk_mntct` decimal(3,0) DEFAULT NULL COMMENT '공사개월수',
  `trrun_mntct` decimal(3,0) DEFAULT NULL COMMENT '시운전개월수',
  `pln_bzccp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '현장사무직구분코드',
  `wrk_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공사구분코드',
  `wrk_entp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공사업체구분코드',
  `tisrd_adm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보자관리여부',
  `tisct` decimal(5,0) DEFAULT NULL COMMENT '부보자수',
  `inrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '부보율',
  `lb_rpbl_cvr_stncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배상책임담보기준코드',
  `retr_cvrdt` date DEFAULT NULL COMMENT '소급담보일자',
  `retr_cvrdt_ad_cnd` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소급담보일자추가조건',
  `carg_lb_is_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적재물배상가입구분코드',
  `nt_trm_xt_cvrdy` decimal(5,0) DEFAULT NULL COMMENT '통지기간연장담보일수',
  `hsp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원구분코드',
  `cmp_rt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '보상비율',
  `ba_cvr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기초담보구분코드',
  `grod_undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지상지하구분코드',
  `accpt_plc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수용장소',
  `sch_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '학교구분코드',
  `sch_flg_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '학교구분세부코드',
  `spcl_sch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수학교여부',
  `spcl_bld_objno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수건물물건번호',
  `spcl_bld_btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특수건물업종코드',
  `self_chamt_ad_cndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기부담금추가조건코드',
  `self_chamt_ad_cnd` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기부담금추가조건',
  `self_chamt_prap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기부담금우선적용여부',
  `evnt_strdt` date DEFAULT NULL COMMENT '행사시작일자',
  `evnt_nddt` date DEFAULT NULL COMMENT '행사종료일자',
  `evnt_ct` decimal(5,0) DEFAULT NULL COMMENT '행사횟수',
  `ap_vlrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '감정평가율',
  `gn_vlamt_spc` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보장가액내역',
  `cmp_spcl_cndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상특수조건코드',
  `cmp_spcl_cndvl` decimal(7,0) DEFAULT NULL COMMENT '보상특수조건값',
  `cvr_xstn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보존재여부',
  `note` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비고',
  `ppr_oj_seqno` decimal(5,0) DEFAULT NULL COMMENT '상위목적물순번',
  `scntr_pscvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '하도급인담보여부',
  `oj_tp_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물유형분류코드',
  `oj_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물유형코드',
  `lctcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지코드',
  `oj_bdlno` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물일괄번호',
  `rk_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험유형코드',
  `labcs_cc_stncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인건비산출기준코드',
  `idac_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재가입여부',
  `unf_rt_ap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단일요율적용여부',
  `avg_age_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '평균연령구분코드',
  `is_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입유형코드',
  `gas_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가스종류코드',
  `accpt_plc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수용장소구분코드',
  `fn_org_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융기관여부',
  `bzp_odtm_rsd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업소상시거주여부',
  `brdg_avgpa_clcrt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승선평균임금산정율구분코드',
  `dsmnt_rk_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해체위험여부',
  `brdps_num` decimal(5,0) DEFAULT NULL COMMENT '승선원수',
  `rvps_num` decimal(5,0) DEFAULT NULL COMMENT '예비원수',
  `plcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '플랜코드',
  `sp_are_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공급지역구분코드',
  `bd_dlbr_rpbl_btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신체손해배상책임업종코드',
  `bld_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건물급수코드',
  `rcn_bjyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사대상여부',
  `aprt_mngm_bn_dt` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용율영위업종상세',
  `mngm_bn_dt` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영위업종상세',
  `rt_ap_obj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율적용물건구분코드',
  `sep_cr_cn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '분리계약해약여부',
  `hscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'HS코드',
  `hp_pftrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '희망이익률',
  `pack_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '포장방법코드',
  `crman_satct` decimal(7,0) DEFAULT NULL COMMENT '승무원좌석수',
  `pasgr_satct` decimal(5,0) DEFAULT NULL COMMENT '승객좌석수',
  `pr_fly_hms` decimal(10,0) DEFAULT NULL COMMENT '예정비행시간',
  `rviba_nds_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부활후배서필요여부',
  `ltrm_nds_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기배서처리구분코드',
  `oj_rlpmi_cmp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물실손보상구분코드',
  `atch_bld_btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부속건물업종코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`plno`,`cgaf_ch_seqno`,`oj_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='설계목적물';
