--
-- Table structure for table `ins_pl_nrdps_tisrd_atr`
--

DROP TABLE IF EXISTS `ins_pl_nrdps_tisrd_atr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_pl_nrdps_tisrd_atr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plno` varchar(17) COLLATE utf8mb4_bin NOT NULL COMMENT '설계번호',
  `cgaf_ch_seqno` decimal(5,0) NOT NULL COMMENT '발행후변경순번',
  `relpc_seqno` decimal(10,0) NOT NULL COMMENT '관계자순번',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `nrdps_tisrd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자부보자구분코드',
  `pl_plcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설계플랜코드',
  `pl_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '플랜분류코드',
  `md_nrdps_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료피보험자구분코드',
  `gp_is_tp` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '그룹가입유형',
  `nrdps_or_tisct` decimal(5,0) DEFAULT NULL COMMENT '피보험자/부보자수',
  `fmlct` decimal(5,0) DEFAULT NULL COMMENT '가족수',
  `man_psct` decimal(7,0) DEFAULT NULL COMMENT '남자인원수',
  `fml_psct` decimal(7,0) DEFAULT NULL COMMENT '여자인원수',
  `rxam_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재심사대상여부',
  `twhvc_drve_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이륜차운전여부',
  `drve_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전여부',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_st_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험시기시각',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `ins_clstr_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종기시각',
  `rfd_clc_st` date DEFAULT NULL COMMENT '준비금산정시기',
  `rfd_clc_clstr` date DEFAULT NULL COMMENT '준비금산정종기',
  `drve_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전형태코드',
  `brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생년월일',
  `embr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '태아여부',
  `sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성별코드',
  `age` decimal(3,0) DEFAULT NULL COMMENT '연령',
  `jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업코드',
  `jb_ch_seqno` decimal(5,0) DEFAULT NULL COMMENT '직업변경순번',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `trf_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '교통급수코드',
  `injr_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해등급코드',
  `ptn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직위',
  `bdt` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직무',
  `bthdt` date DEFAULT NULL COMMENT '출산일자',
  `stbdt` date DEFAULT NULL COMMENT '사산일자',
  `preg_rndwk` decimal(2,0) DEFAULT NULL COMMENT '임신경과주',
  `mdcs_rgt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비등록구분코드',
  `mdcs_rgt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비등록상태코드',
  `stt_pfsst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '학생교직원구분코드',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `tisrd_rcpdt` date DEFAULT NULL COMMENT '부보자접수일자',
  `acdis_rgtdt` date DEFAULT NULL COMMENT '학원등록일자',
  `drve_lic_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전면허종별코드',
  `pa_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임금화폐코드',
  `mnth_avg_pa` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '월평균임금',
  `year_pa_tamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '연임금총액',
  `xc_ap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할증적용여부',
  `brdps_rvps_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승선원예비원구분코드',
  `dtycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직책코드',
  `rcn_bjyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실사대상여부',
  `dgn_ud_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진단심사대상여부',
  `ad_irt_ap_chdct` decimal(5,0) DEFAULT '0' COMMENT '가산금리적용자녀수',
  `embr_is_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '태아가입가능여부',
  `bth_prdt` date DEFAULT NULL COMMENT '출산예정일자',
  `nwbby_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신생아성명',
  `nwbby_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신생아주민번호',
  `preg_rndwk_stdt` date DEFAULT NULL COMMENT '임신경과주기준일자',
  `mdcs_inq_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비조회동의여부',
  `smok_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '흡연여부',
  `dscrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '할인율',
  `rviba_nds_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부활후배서필요여부',
  `ltrm_nds_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기배서처리구분코드',
  `wpcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직장명',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `ce_plcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집플랜코드',
  `xclc_bd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우량신체여부',
  `unf_rt_ap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단일요율적용여부',
  `twhvc_sub_cvrtr_is_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이륜차부담보특약가입구분코드',
  `dc_age` decimal(3,0) DEFAULT NULL COMMENT '할인연령',
  `hlt_age_prm_ap_trt_is_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건강연령보험료적용특약가입구분코드',
  `hlt_age_dc_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '건강연령할인적용구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_pl_nrdps_tisrd_atr_00` (`plno`,`cgaf_ch_seqno`,`relpc_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=73370 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='설계피보험자부보자속성';
