--
-- Table structure for table `aud_rtx_rtn_ldg`
--

DROP TABLE IF EXISTS `aud_rtx_rtn_ldg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `aud_rtx_rtn_ldg` (
  `rtx_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증종류코드',
  `rtx_ss_yr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증발행년도',
  `rtx_bkno` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증책번호',
  `rtx_isdt` date DEFAULT NULL COMMENT '영수증발급일자',
  `tgnrt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄기관코드',
  `tgnrt_org_mfgdt` date DEFAULT NULL COMMENT '총괄기관출고일자',
  `tgnrt_org_rcdt` date DEFAULT NULL COMMENT '총괄기관수령일자',
  `adm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관코드',
  `adm_org_mfgdt` date DEFAULT NULL COMMENT '관리기관출고일자',
  `adm_org_rcdt` date DEFAULT NULL COMMENT '관리기관수령일자',
  `dh_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지점기관코드',
  `dh_br_mfgdt` date DEFAULT NULL COMMENT '취급지점출고일자',
  `dh_br_rcdt` date DEFAULT NULL COMMENT '취급지점수령일자',
  `dhgnc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급소기관코드',
  `dhgnc_mfgdt` date DEFAULT NULL COMMENT '취급소출고일자',
  `dhgnc_rcdt` date DEFAULT NULL COMMENT '취급소수령일자',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `rtx_dh_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증취급지점기관코드',
  `rtx_dh_br_mfgdt` date DEFAULT NULL COMMENT '영수증취급지점출고일자',
  `rtx_dh_br_rcdt` date DEFAULT NULL COMMENT '영수증취급지점수령일자',
  `rtx_dhtrb_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증취급점기관코드',
  `rtx_dhtrb_mfgdt` date DEFAULT NULL COMMENT '영수증취급점출고일자',
  `rtx_dhtrb_rcdt` date DEFAULT NULL COMMENT '영수증취급점수령일자',
  `rtx_dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증취급직원번호',
  `rtx_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증상태구분코드',
  `rtx_st_flgdt` date DEFAULT NULL COMMENT '영수증상태구분일자',
  `rtn_bf_rtx_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납전영수증상태구분코드',
  `rtn_bf_rtx_st_flgdt` date DEFAULT NULL COMMENT '반납전영수증상태구분일자',
  `rtndt` date DEFAULT NULL COMMENT '반납일자',
  `rtn_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납등록직원번호',
  `re_rtndt` date DEFAULT NULL COMMENT '재반납일자',
  `rrtn_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재반납등록직원번호',
  `rtn_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납승인여부',
  `rtn_apdt` date DEFAULT NULL COMMENT '반납승인일자',
  `rtn_ap_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납승인등록직원번호',
  `rrtn_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재반납승인여부',
  `rrtn_apdt` date DEFAULT NULL COMMENT '재반납승인일자',
  `rrtn_ap_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재반납승인등록직원번호',
  `rtrs_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반송사유내용',
  `rtdt` date DEFAULT NULL COMMENT '반송일자',
  `rt_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반송등록직원번호',
  `us_strdt` date DEFAULT NULL COMMENT '사용시작일자',
  `us_nddt` date DEFAULT NULL COMMENT '사용종료일자',
  `no1_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번영수증상태코드',
  `no1_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1번영수증미수납여부',
  `no2_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번영수증상태코드',
  `no2_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2번영수증미수납여부',
  `no3_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번영수증상태코드',
  `no3_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3번영수증미수납여부',
  `no4_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번영수증상태코드',
  `no4_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '4번영수증미수납여부',
  `no5_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번영수증상태코드',
  `no5_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '5번영수증미수납여부',
  `no6_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번영수증상태코드',
  `no6_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '6번영수증미수납여부',
  `no7_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번영수증상태코드',
  `no7_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '7번영수증미수납여부',
  `no8_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번영수증상태코드',
  `no8_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '8번영수증미수납여부',
  `no9_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번영수증상태코드',
  `no9_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '9번영수증미수납여부',
  `no10_rtx_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번영수증상태코드',
  `no10_rtx_nrv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '10번영수증미수납여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`rtx_kndcd`,`rtx_ss_yr`,`rtx_bkno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='영수증반납원장';
