--
-- Table structure for table `aud_rtx_retr_info`
--

DROP TABLE IF EXISTS `aud_rtx_retr_info`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `aud_rtx_retr_info` (
  `rtx_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증종류코드',
  `rtx_ss_yr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증발행년도',
  `rtx_bkno` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증책번호',
  `mfgdt` date DEFAULT NULL COMMENT '출고일자',
  `strdt` date DEFAULT NULL COMMENT '시작일자',
  `nddt` date DEFAULT NULL COMMENT '종료일자',
  `tgnrt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄기관코드',
  `adm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `rtx_plyno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증증권번호',
  `prm` decimal(17,2) DEFAULT NULL COMMENT '보험료',
  `dpamt` decimal(15,0) DEFAULT NULL COMMENT '입금금액',
  `dp_bknm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금은행명',
  `dpdt` date DEFAULT NULL COMMENT '입금일자',
  `chr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당직원번호',
  `chrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자명',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `rtx_retr_rs` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증소급사유',
  `o1_af_inp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차후입력구분코드',
  `o1_prvdt` date DEFAULT NULL COMMENT '1차결재일자',
  `o1_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차결재직원번호',
  `o1_re_af_inp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차재후입력구분코드',
  `o1_re_prvdt` date DEFAULT NULL COMMENT '1차재결재일자',
  `o1_re_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차재결재직원번호',
  `o2_afprv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차후결구분코드',
  `o2_prvdt` date DEFAULT NULL COMMENT '2차결재일자',
  `o2_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차결재직원번호',
  `o2_re_afprv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차재후결구분코드',
  `o2_re_prvdt` date DEFAULT NULL COMMENT '2차재결재일자',
  `o2_re_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차재결재직원번호',
  `o3_afprv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차후결구분코드',
  `o3_prvdt` date DEFAULT NULL COMMENT '3차결재일자',
  `o3_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차결재직원번호',
  `o3_re_afprv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차재후결구분코드',
  `o3_re_prvdt` date DEFAULT NULL COMMENT '3차재결재일자',
  `o3_re_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차재결재직원번호',
  `tgnrt_o1_af_inp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄1차후입력구분코드',
  `tgnrt_o1_prvdt` date DEFAULT NULL COMMENT '총괄1차결재일자',
  `tgnrt_o1_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄1차결재직원번호',
  `tgnrt_o1_re_af_inp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄1차재후입력구분코드',
  `tgnrt_o1_re_prvdt` date DEFAULT NULL COMMENT '총괄1차재결재일자',
  `tgnrt_o1_re_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄1차재결재직원번호',
  `tgnrt_o2_afprv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄2차후결구분코드',
  `tgnrt_o2_prvdt` date DEFAULT NULL COMMENT '총괄2차결재일자',
  `tgnrt_o2_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄2차결재직원번호',
  `tgnrt_o2_re_afprv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄2차재후결구분코드',
  `tgnrt_o2_re_prvdt` date DEFAULT NULL COMMENT '총괄2차재결재일자',
  `tgnrt_o2_re_prv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄2차재결재직원번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`rtx_kndcd`,`rtx_ss_yr`,`rtx_bkno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='영수증소급정보';
