--
-- Table structure for table `aud_bnc_rtx_apldo_ldg`
--

DROP TABLE IF EXISTS `aud_bnc_rtx_apldo_ldg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `aud_bnc_rtx_apldo_ldg` (
  `rtx_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증종류코드',
  `rtx_ss_yr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증발행년도',
  `rtx_bk_sno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '영수증책일련번호',
  `rtx_isdt` date DEFAULT NULL COMMENT '영수증발급일자',
  `tgnrt_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총괄기관코드',
  `tgnrt_org_mfgdt` date DEFAULT NULL COMMENT '총괄기관출고일자',
  `tgnrt_org_rcdt` date DEFAULT NULL COMMENT '총괄기관수령일자',
  `adm_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관코드',
  `adm_org_mfgdt` date DEFAULT NULL COMMENT '관리기관출고일자',
  `adm_org_mfg_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리기관출고직원번호',
  `adm_org_rcdt` date DEFAULT NULL COMMENT '관리기관수령일자',
  `dh_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급지점기관코드',
  `dh_br_mfgdt` date DEFAULT NULL COMMENT '취급지점출고일자',
  `dh_br_rcdt` date DEFAULT NULL COMMENT '취급지점수령일자',
  `adm_br_rc_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리지점수령직원번호',
  `dhgnc_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급소기관코드',
  `dhgnc_mfgdt` date DEFAULT NULL COMMENT '취급소출고일자',
  `dhgnc_rcdt` date DEFAULT NULL COMMENT '취급소수령일자',
  `rtx_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증상태구분코드',
  `rtx_st_flgdt` date DEFAULT NULL COMMENT '영수증상태구분일자',
  `rc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수령여부',
  `rtn_bf_rtx_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납전영수증상태구분코드',
  `rtn_bf_rtx_st_flgdt` date DEFAULT NULL COMMENT '반납전영수증상태구분일자',
  `rtndt` date DEFAULT NULL COMMENT '반납일자',
  `rtn_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납등록직원번호',
  `re_rtndt` date DEFAULT NULL COMMENT '재반납일자',
  `rrtn_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재반납등록직원번호',
  `rtn_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납승인여부',
  `rtn_apdt` date DEFAULT NULL COMMENT '반납승인일자',
  `rtn_ap_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반납승인등록직원번호',
  `rrtn_aryn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재반납승인여부',
  `rrtn_apdt` date DEFAULT NULL COMMENT '재반납승인일자',
  `rrtn_ap_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재반납승인등록직원번호',
  `rtrs_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반송사유내용',
  `rtdt` date DEFAULT NULL COMMENT '반송일자',
  `rt_rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반송등록직원번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `rpdt` date DEFAULT NULL COMMENT '영수일자',
  `rvdt` date DEFAULT NULL COMMENT '수납일자',
  `prm` decimal(17,2) DEFAULT NULL COMMENT '보험료',
  `pym_seq` decimal(5,0) DEFAULT NULL COMMENT '납입회차',
  `pym_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입년월',
  `grcdt` date DEFAULT NULL COMMENT '유예일자',
  `rtx_plyno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증증권번호',
  `rtx_plyno_dgre` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영수증증권번호차수',
  `rs_bzmno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주민사업자번호',
  `ins_strdt` date DEFAULT NULL COMMENT '보험시작일자',
  `ins_nddt` date DEFAULT '9999-12-31' COMMENT '보험종료일자',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `crtdt` date DEFAULT '9999-12-31' COMMENT '생성일자',
  `orgcr_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원계약년도',
  `orgcr_ins_endt` date DEFAULT NULL COMMENT '원계약보험만기일자',
  `orgcr_pym_dudt` date DEFAULT NULL COMMENT '원계약납입응당일자',
  `orgcr_prm` decimal(17,2) DEFAULT NULL COMMENT '원계약보험료',
  `org_crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원계약자명',
  `orgcr_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원계약전화번호',
  `orgcr_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원계약우편번호',
  `orgcr_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원계약주소',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`rtx_kndcd`,`rtx_ss_yr`,`rtx_bk_sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='방카영수증청약서원장';
