--
-- Table structure for table `aud_fn_clmam`
--

DROP TABLE IF EXISTS `aud_fn_clmam`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `aud_fn_clmam` (
  `fn_acd_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '금융사건년월',
  `fn_acd_seqno` decimal(5,0) NOT NULL COMMENT '금융사건순번',
  `fn_acdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건명',
  `fn_acd_1_crzcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건1발생기관코드',
  `fn_acd_2_crzcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건2발생기관코드',
  `fn_acd_3_crzcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건3발생기관코드',
  `fn_acd_4_crzcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건4발생기관코드',
  `fn_acd_5_crzcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건5발생기관코드',
  `acd_cr_strdt` date DEFAULT NULL COMMENT '사건발생시작일자',
  `acd_cr_nddt` date DEFAULT NULL COMMENT '사건발생종료일자',
  `acd_cnfdt` date DEFAULT NULL COMMENT '사건확인일자',
  `rgt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '등록직원번호',
  `rgtdt` date DEFAULT NULL COMMENT '등록일자',
  `fn_acd_amt` decimal(15,0) DEFAULT NULL COMMENT '금융사건금액',
  `fn_acd_ryamt` decimal(15,0) DEFAULT NULL COMMENT '금융사건회수금액',
  `fn_acd_tp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건유형구분코드',
  `fn_rule_vlt_bhvr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융규칙위반행위구분코드',
  `fr_rptdt` date DEFAULT NULL COMMENT '최초보고일자',
  `o1_mid_rptdt` date DEFAULT NULL COMMENT '1차중간보고일자',
  `o2_mid_rptdt` date DEFAULT NULL COMMENT '2차중간보고일자',
  `o3_mid_rptdt` date DEFAULT NULL COMMENT '3차중간보고일자',
  `fnl_rptdt` date DEFAULT NULL COMMENT '최종보고일자',
  `fn_acd_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건내용',
  `fn_acd_fr_rpt_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건최초보고내용',
  `o1_mid_rpt_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1차중간보고내용',
  `o2_mid_rpt_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '2차중간보고내용',
  `o3_mid_rpt_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '3차중간보고내용',
  `fn_acd_fnl_rpt_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금융사건최종보고내용',
  `acd_1_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건1직원번호',
  `acd_1_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건1직원명',
  `acd_1_ndtdt` date DEFAULT NULL COMMENT '사건1고발일자',
  `acd_1_ndtpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건1고발처명',
  `acd_1_paff_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건1인사조치여부',
  `acd_1_paff_mngdt` date DEFAULT NULL COMMENT '사건1인사조치일자',
  `acd_2_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건2직원번호',
  `acd_2_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건2직원명',
  `acd_2_ndtdt` date DEFAULT NULL COMMENT '사건2고발일자',
  `acd_2_ndtpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건2고발처명',
  `acd_2_paff_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건2인사조치여부',
  `acd_2_paff_mngdt` date DEFAULT NULL COMMENT '사건2인사조치일자',
  `acd_3_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건3직원번호',
  `acd_3_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건3직원명',
  `acd_3_ndtdt` date DEFAULT NULL COMMENT '사건3고발일자',
  `acd_3_ndtpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건3고발처명',
  `acd_3_paff_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건3인사조치여부',
  `acd_3_paff_mngdt` date DEFAULT NULL COMMENT '사건3인사조치일자',
  `acd_4_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건4직원번호',
  `acd_4_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건4직원명',
  `acd_4_ndtdt` date DEFAULT NULL COMMENT '사건4고발일자',
  `acd_4_ndtpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건4고발처명',
  `acd_4_paff_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건4인사조치여부',
  `acd_4_paff_mngdt` date DEFAULT NULL COMMENT '사건4인사조치일자',
  `acd_5_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건5직원번호',
  `acd_5_stfnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건5직원명',
  `acd_5_ndtdt` date DEFAULT NULL COMMENT '사건5고발일자',
  `acd_5_ndtpl_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건5고발처명',
  `acd_5_paff_mng_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사건5인사조치여부',
  `acd_5_paff_mngdt` date DEFAULT NULL COMMENT '사건5인사조치일자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`fn_acd_yymm`,`fn_acd_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='금융사고관리';
