--
-- Table structure for table `igd_gd_us_atr`
--

DROP TABLE IF EXISTS `igd_gd_us_atr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `igd_gd_us_atr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `gd_atrno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품속성번호',
  `ap_nddt` date NOT NULL DEFAULT '9999-12-31' COMMENT '적용종료일자',
  `ap_strdt` date NOT NULL COMMENT '적용시작일자',
  `atrcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '속성코드',
  `gd_atr_use_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품속성용도구분코드',
  `essn_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '필수구분코드',
  `mdf_av_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '수정가능구분코드',
  `nds_av_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '배서가능여부',
  `scr_idcnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화면표시명',
  `scr_idc_ordr` decimal(5,0) DEFAULT '1' COMMENT '화면표시순서',
  `scr_idc_copel_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화면표시구성요소구분코드',
  `scr_idc_copel_lngth` decimal(5,0) DEFAULT NULL COMMENT '화면표시구성요소길이',
  `scr_idc_copel_nolns` decimal(2,0) DEFAULT NULL COMMENT '화면표시구성요소행수',
  `scr_idc_copel_tag` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화면표시구성요소태그',
  `scr_idc_atr_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화면표시속성그룹코드',
  `subo_rel_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종속관계구분코드',
  `atr_bavl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '속성기본값',
  `pfb_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자구분코드',
  `us_av_strdt` date NOT NULL COMMENT '사용가능시작일자',
  `us_av_nddt` date NOT NULL DEFAULT '9999-12-31' COMMENT '사용가능종료일자',
  `self_chamt_bavl` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '자기부담금기본값',
  `self_chamt_lowvl` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '자기부담금최저값',
  `self_chamt_mxvl` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '자기부담금최대값',
  `coobj_is_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동물건가입가능여부',
  `psn_crp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인법인구분코드',
  `rtamt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환급금유형코드',
  `oj_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '목적물유형코드',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `relpc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관계자유형코드',
  `lb_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배상구분코드',
  `cmp_lmamt_untcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상한도금액단위코드',
  `isamt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입금액유형코드',
  `isamt_bavl` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액기본값',
  `isamt_mnvl` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액최소값',
  `isamt_mxvl` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액최대값',
  `isamt_id_unt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '가입금액증감단위',
  `rk_tpcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험유형코드',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보코드',
  `plcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '플랜코드',
  `act1_unamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '구좌1단위금액',
  `subo_rel_tpcd` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종속관계유형코드',
  `subo_rel_ap_lvl` decimal(1,0) DEFAULT NULL COMMENT '종속관계적용레벨',
  `lvl_1_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '레벨1세부코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_igd_gd_us_atr_00` (`gd_atrno`,`ap_nddt`,`ap_strdt`),
  KEY `idx_igd_gd_us_atr_08` (`gdcd`,`plcd`,`ap_nddt`,`ap_strdt`,`cvrcd`)
) ENGINE=InnoDB AUTO_INCREMENT=306128 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='상품사용속성';
