--
-- Table structure for table `igd_ltrm_rato`
--

DROP TABLE IF EXISTS `igd_ltrm_rato`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `igd_ltrm_rato` (
  `ltrm_rt_tabl_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '장기요율테이블구분코드',
  `sno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '일련번호',
  `ap_strdt` date NOT NULL COMMENT '적용시작일자',
  `ap_nddt` date NOT NULL COMMENT '적용종료일자',
  `cop_chrvl1` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값1',
  `cop_chrvl2` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값2',
  `cop_chrvl3` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값3',
  `cop_chrvl4` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값4',
  `cop_chrvl5` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값5',
  `cop_chrvl6` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값6',
  `cop_chrvl7` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값7',
  `cop_chrvl8` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값8',
  `cop_chrvl9` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값9',
  `cop_chrvl10` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값10',
  `cop_chrvl11` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값11',
  `cop_chrvl12` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값12',
  `cop_chrvl13` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값13',
  `cop_chrvl14` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값14',
  `cop_chrvl15` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값15',
  `cop_chrvl16` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값16',
  `cop_chrvl17` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값17',
  `cop_chrvl18` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값18',
  `cop_chrvl19` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값19',
  `cop_chrvl20` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값20',
  `cop_chrvl21` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구성문자값21',
  `out_dat_vl1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값1',
  `out_dat_vl2` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값2',
  `out_dat_vl3` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값3',
  `out_dat_vl4` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값4',
  `out_dat_vl5` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값5',
  `out_dat_vl6` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값6',
  `out_dat_vl7` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값7',
  `out_dat_vl8` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값8',
  `out_dat_vl9` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값9',
  `out_dat_vl10` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값10',
  `out_dat_vl11` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값11',
  `out_dat_vl12` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값12',
  `out_dat_vl13` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값13',
  `out_dat_vl14` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값14',
  `out_dat_vl15` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값15',
  `out_dat_vl16` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값16',
  `out_dat_vl17` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값17',
  `out_dat_vl18` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값18',
  `out_dat_vl19` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값19',
  `out_dat_vl20` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값20',
  `out_dat_vl21` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값21',
  `out_dat_vl22` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값22',
  `out_dat_vl23` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값23',
  `out_dat_vl24` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값24',
  `out_dat_vl25` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출력데이터값25',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`ltrm_rt_tabl_flgcd`,`ap_strdt`,`sno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='장기이율';
