--
-- Table structure for table `igd_gd_cvr`
--

DROP TABLE IF EXISTS `igd_gd_cvr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `igd_gd_cvr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `gdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품코드',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `ap_nddt` date NOT NULL DEFAULT '9999-12-31' COMMENT '적용종료일자',
  `ap_strdt` date NOT NULL COMMENT '적용시작일자',
  `cvr_prsnm` varchar(500) COLLATE utf8mb4_bin NOT NULL COMMENT '담보대표명',
  `cvr_kornm` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보한글명',
  `cvr_hngl_shtnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보한글단축명',
  `cvr_ennm` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보영문명',
  `cvr_eng_shtnm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보영문단축명',
  `cvr_perdt` date DEFAULT NULL COMMENT '담보인가일자',
  `cvr_cla_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보약관내용',
  `cvr_ba_trt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '담보기본특약구분코드',
  `is_bj_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '가입대상여부',
  `isamt_need_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '가입금액필요여부',
  `prm_adm_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '보험료관리여부',
  `prm_sum_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '1' COMMENT '보험료합산대상여부',
  `cr_lvl_cvr_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '계약레벨담보여부',
  `pblct_out_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '1' COMMENT '발행물출력여부',
  `scr_idc_cvr_gpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화면표시담보그룹코드',
  `pym_xmp_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입면제가능여부',
  `xtn_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소멸가능여부',
  `dt_inpsc_xstn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '상세입력화면존재여부',
  `age_wkct_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연령주수구분코드',
  `mn_is_age` decimal(3,0) DEFAULT NULL COMMENT '최소가입연령',
  `mx_is_age` decimal(3,0) DEFAULT NULL COMMENT '최대가입연령',
  `is_av_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입가능성별코드',
  `mrrd_bj_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '기혼대상담보여부',
  `onw_cla_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신구약관구분코드',
  `invc_out_prg` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송장출력문구',
  `ply_out_prg_1` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권출력문구1',
  `ply_out_prg_2` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권출력문구2',
  `inp_rt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력요율여부',
  `lowt_inp_rt` decimal(15,7) NOT NULL DEFAULT '0.0000000' COMMENT '최저입력요율',
  `mx_inp_rt` decimal(15,7) NOT NULL DEFAULT '0.0000000' COMMENT '최대입력요율',
  `mdcs_rgt_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비등록대상여부',
  `auto_rnw_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동갱신가능여부',
  `cvr_dbis_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보중복가입구분코드',
  `rnw_af_cvrcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신후담보코드',
  `is_av_drve_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입가능운전형태코드',
  `is_av_rel_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입가능관계구분코드',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `sl_strdt` date NOT NULL COMMENT '판매시작일자',
  `sl_nddt` date NOT NULL DEFAULT '9999-12-31' COMMENT '판매종료일자',
  `dt_scr_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '세부화면ID',
  `rnw_xc_cvr_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '갱신전용담보여부',
  `rl_sl_opndt` date DEFAULT NULL COMMENT '실제판매개시일자',
  `rl_sl_nddt` date DEFAULT NULL COMMENT '실제판매종료일자',
  `coobj_is_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동물건가입가능여부',
  `pymtm_atnd_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급시유의사항',
  `nrdps_sl_strdt` date DEFAULT NULL COMMENT '피보험자판매시작일자',
  `nrdps_sl_nddt` date DEFAULT NULL COMMENT '피보험자판매종료일자',
  `rlpmi_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손담보여부',
  `cvr_trt_gp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보특약그룹구분코드',
  `rnw_cvr_nclm_dscrt` decimal(5,2) DEFAULT '0.00' COMMENT '갱신담보무사고할인율',
  `rwcvr_nclm_ad_dscrt` decimal(5,2) DEFAULT NULL COMMENT '갱신담보무사고추가할인율',
  `rwcvr_nclm_ad_dctrm` decimal(4,0) DEFAULT NULL COMMENT '갱신담보무사고추가할인기간',
  `rmimc_xcpt_prmex_bjyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손의료비제외보험료예시대상여부',
  `prs_clm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표사고담보코드',
  `cvr_xcpt_dlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보예외처리코드',
  `nds_xc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서전용구분코드',
  `clm_nds_xc_cvrcd` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고배서전용담보코드',
  `cvr_dc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보할인구분코드',
  `indpd_trt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '독립특약여부',
  `indpd_trt_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '독립특약상품코드',
  `gd_cvr_dscrt` decimal(5,2) DEFAULT NULL COMMENT '상품담보할인율',
  `sb_pym_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대체납입유형코드',
  `cvr_xtn_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보소멸처리구분코드',
  `cla_seqno` decimal(3,0) NOT NULL COMMENT '약관순번',
  `ibnr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IBNR구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_igd_gd_cvr_00` (`gdcd`,`cvrcd`,`ap_nddt`,`ap_strdt`),
  KEY `idx_igd_gd_cvr_01` (`cvrcd`,`gdcd`,`ap_nddt`,`ap_strdt`),
  KEY `idx_igd_gd_cvr_02` (`gdcd`,`cvr_ba_trt_flgcd`,`ap_nddt`,`ap_strdt`)
) ENGINE=InnoDB AUTO_INCREMENT=193017 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='상품담보';
