--
-- Table structure for table `igd_gd`
--

DROP TABLE IF EXISTS `igd_gd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `igd_gd` (
  `gdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품코드',
  `ap_nddt` date NOT NULL DEFAULT '9999-12-31' COMMENT '적용종료일자',
  `ap_strdt` date NOT NULL COMMENT '적용시작일자',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보험종목코드',
  `cla_lng_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '약관언어구분코드',
  `gd_ty_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품형태구분코드',
  `gd_slnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '상품판매명',
  `gd_shtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품단축명',
  `gd_kornm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품한글명',
  `gd_ennm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품영문명',
  `gd_xpnm` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품설명',
  `gd_per_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '상품인가여부',
  `gd_pernm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품인가명',
  `gd_per_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품인가유형코드',
  `gd_perdt` date DEFAULT NULL COMMENT '상품인가일자',
  `gd_sl_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품판매유형코드',
  `cr_opn_ba_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약개시기본시간',
  `cr_nd_ba_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약종료기본시간',
  `fc_dh_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '외화취급여부',
  `re_unt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출재단위구분코드',
  `pym_xmp_unt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '납입면제단위구분코드',
  `ppy_prm_prm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '1' COMMENT '선납보험료허용여부',
  `ppy_prm_mxpsb_mc` decimal(4,0) DEFAULT NULL COMMENT '선납보험료최대가능월수',
  `psncl_dbins_prm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '개인별중복보험허용여부',
  `cv_ins_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '전환보험가능여부',
  `auto_tf_dc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '자동이체할인여부',
  `type_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종구분코드',
  `type_cn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종내용구분코드',
  `spe_scr_rnw_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '종별화면갱신여부',
  `dv_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배당유형코드',
  `prm_str_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료구조구분코드',
  `mw_rtamt_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도환급금액발생구분코드',
  `nd_rtamt_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '만기환급금액발생여부',
  `dgn_gd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '진단상품여부',
  `auto_rnw_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '자동갱신가능여부',
  `prm_inp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '보험료입력구분코드',
  `cu_prm_ocpym_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적립보험료수시납입여부',
  `ctu_crdtf_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계속카드이체가능여부',
  `cla_ln_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '약관대출가능여부',
  `sb_pym_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '대체납입구분코드',
  `sb_pym_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대체납입유형코드',
  `age_cc_st_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연령산출기준구분코드',
  `bz_mtdrp_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업방법서분류코드',
  `is_pl_cht_wrtyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입설계차트출력여부',
  `xtn_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소멸유형코드',
  `xtntm_rtamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소멸시환급금구분코드',
  `trmcl_expl_ntc_mntct` decimal(5,0) DEFAULT NULL COMMENT '기간별예시안내개월수',
  `rmimc_flgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손의료비구분코드',
  `gr_is_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '단체가입구분코드',
  `gr_dc_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '단체할인가능여부',
  `gr_mn_is_psct` decimal(3,0) DEFAULT NULL COMMENT '단체최소가입인원수',
  `avg_rt_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '평균요율사용여부',
  `pr_es_prm_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '질권설정허용여부',
  `lowt_prm_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최저보험료화폐코드',
  `lowt_prm` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '최저보험료',
  `cvr_prm_sgdlg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보보험료단수처리구분코드',
  `apprm_sglr_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용보험료단수처리구분코드',
  `sl_pl_adm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '판매플랜관리여부',
  `cr_logfl_pst_info` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약LOG파일위치정보',
  `op_envr_cv_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '운용환경전환여부',
  `ins_trm_bavl` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험기간기본값',
  `ins_trm_lm` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험기간한도',
  `pym_grc_trm` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입유예기간',
  `tx_pf_gd_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '세금우대상품분류코드',
  `sl_pl_op_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '판매플랜운용유형코드',
  `ply_out_tp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권출력유형구분코드',
  `type_ch_av_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종변경가능여부',
  `gd_dt_scr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품세부화면여부',
  `dt_scr_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '세부화면ID',
  `dc_ap_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인적용구분코드',
  `dt_inpsc_xstn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세입력화면존재여부',
  `dt_inpsc_id` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세입력화면ID',
  `mw_wdra_av_rt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '중도인출가능비율',
  `mw_wdra_str_rndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도인출시작경과코드',
  `mw_wdra_cr_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도인출발생주기코드',
  `mw_wdra_cr_caseq` decimal(5,0) DEFAULT NULL COMMENT '중도인출발생호출회차',
  `dvpns_rpr_ikdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원통보보종코드',
  `gd_exppr_out_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품해설서출력여부',
  `marne_nelp_cal_metcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해상미경과계산방식코드',
  `pect_sl_mntr_bjpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '완전판매모니터링대상코드',
  `prm_inp_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료입력유형코드',
  `rntcl_dscrt_ap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT 'N' COMMENT '경과기간별할인율적용여부',
  `gds_mx_dc_lmrt` decimal(5,2) DEFAULT NULL COMMENT '상품별최대할인한도율',
  `prm_sb_pym_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료대체납입유형코드',
  `prm_npy_sb_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료미납대체구분코드',
  `scr_idc_ordr` decimal(5,0) DEFAULT NULL COMMENT '화면표시순서',
  `mx_mn_cc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최대최소산출유형코드',
  `rnwdc_fund_chek_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신할인재원체크여부',
  `rmimc_rkrt_dcl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손의료비위험율공시여부',
  `anul_bzprm_rt_adtm` decimal(3,0) DEFAULT NULL COMMENT '매년영업보험료비율부가기간',
  `cc_xcpt_dlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산출예외처리코드',
  `indpd_trt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '독립특약유형코드',
  `indpd_trt_incld_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '독립특약포함여부',
  `gd_mx_is_age` decimal(3,0) DEFAULT NULL COMMENT '상품최대가입연령',
  `mx_rnw_trm` decimal(3,0) DEFAULT NULL COMMENT '최대갱신기간',
  `sm_prm_mn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '합계보험료유지여부',
  `rlpmi_md_ins_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손의료보험분류코드',
  `psvn_bj_gd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보호대상상품여부',
  `re_isgd_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재가입상품유형코드',
  `adpym_prm_lm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추가납입보험료한도구분코드',
  `irt_cn_gd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금리연동상품여부',
  `ltrm_gd_grp_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기상품군분류코드',
  `sof_gd_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '감독원상품분류코드',
  `crycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약형태코드',
  `is_av_oj_tpcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입가능목적물유형코드',
  `rtn_tp_info_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환급유형정보코드',
  `adpym_av_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추가납입가능구분코드',
  `mwwdr_av_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중도인출가능구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`gdcd`,`ap_nddt`,`ap_strdt`),
  KEY `idx_igd_gd_10` (`ins_imcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='상품';
