--
-- Table structure for table `ins_ud`
--

DROP TABLE IF EXISTS `ins_ud`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_ud` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `udno` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT '심사번호',
  `ndv_ud_seqno` decimal(5,0) NOT NULL COMMENT '개별심사순번',
  `tgnrt_ud_bj_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '총괄심사대상여부',
  `ud_bj_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심사대상구분코드',
  `ud_rel_atr_1` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '심사관계속성1',
  `ud_rel_atr_2` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사관계속성2',
  `ud_rel_atr_3` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사관계속성3',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `ud_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심사업무구분코드',
  `ud_rkcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심사단계코드',
  `ud_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심사구분코드',
  `ud_prg_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '심사진행상태코드',
  `ud_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사결과코드',
  `ud_cplt_perdt` date DEFAULT NULL COMMENT '심사완료기한일자',
  `ud_xmn_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사검토내용',
  `udrtk_cnd_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수조건내용',
  `rqtno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '의뢰직원번호',
  `requ_dthms` datetime NOT NULL COMMENT '의뢰일시',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급직원번호',
  `usrno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용인번호',
  `ud_chr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사담당기관코드',
  `ud_chr_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사담당직원번호',
  `ud_chr_org_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사담당기관구분코드',
  `fnl_ud_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종심사직원번호',
  `fnl_ud_cplt_dthms` datetime DEFAULT NULL COMMENT '최종심사완료일시',
  `fnl_ud_st_info` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종심사상태정보',
  `fnl_udwr_ctn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종심사자의견',
  `ud_dl_bz_days` decimal(5,0) DEFAULT NULL COMMENT '심사처리영업일수',
  `is_plmdf_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '가입설계수정필요여부',
  `rk_admno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위험관리번호',
  `ltrm_plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기설계번호',
  `sms_ts_prg` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS전송문구',
  `spccf_ud_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '특인심사대상여부',
  `dgn_ud_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '진단심사대상여부',
  `nrdcd` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자코드',
  `bn_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종분류코드',
  `ins_btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험업종코드',
  `entp_xmn_rq_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업체검토요청내용',
  `emeg_ud_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '긴급심사대상여부',
  `apldo_prss_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청약서선발행대상여부',
  `ap_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인사유코드',
  `spccf_bj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특인대상구분코드',
  `carno_hngl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호한글',
  `vald_strdt` date DEFAULT NULL COMMENT '유효시작일자',
  `vald_nddt` date DEFAULT NULL COMMENT '유효종료일자',
  `cr_spccf_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차특인유형코드',
  `lowt_drv_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최저운전자주민번호',
  `sms_rcvpt_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS수신자ID',
  `sms_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS수신여부',
  `msg_rcvpt_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'MSG수신자ID',
  `msg_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'MSG수신여부',
  `auto_apl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동청약여부',
  `dcu_cpmt_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '서류보완필요여부',
  `prs_plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표설계번호',
  `udwr_is_plmdf_need_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사자가입설계수정필요여부',
  `rt_ud_requ_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율심사의뢰사유',
  `cr_prv_flgcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차결재구분코드',
  `cr_prv_rstcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차결재결과코드',
  `cr_prv_chrps_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차결재담당자직원번호',
  `cr_prv_ctn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차결재의견',
  `cr_prv_dthms` datetime DEFAULT NULL COMMENT '자동차결재일시',
  `dgndc_adxdt` date DEFAULT NULL COMMENT '진단서첨부일자',
  `rcn_rptg_adxdt` date DEFAULT NULL COMMENT '실사보고서첨부일자',
  `apldo_adxdt` date DEFAULT NULL COMMENT '청약서첨부일자',
  `sbcvr_ud_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '부담보심사여부',
  `sbcvr_cnfst_adxdt` date DEFAULT NULL COMMENT '부담보확인서첨부일자',
  `img_ud_end_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '이미지심사종결여부',
  `ppr_ud_seqno` decimal(5,0) DEFAULT NULL COMMENT '상위심사순번',
  `ud_rq_rs` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '심사의뢰사유',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_ud_00` (`udno`,`ndv_ud_seqno`),
  KEY `idx_ins_ud_02` (`ud_rel_atr_1`,`ud_prg_stcd`,`ud_bj_flgcd`,`ikd_grpcd`,`ud_flgcd`)
) ENGINE=InnoDB AUTO_INCREMENT=2066 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='심사';
