#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_pstno_rodnm_ba_adr.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_pstpo_rcpl.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_pstno_rodnm_srh_adr.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_ctm_act.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_jb.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_ctm_cntad.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_ctm_cntrt_crr.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_ctm_adr_crr.sql com.skims
#./dbtbl2msa.sh ./dbtbl/cus/고객/cus_ctm.sql com.skims
#./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_nrdps_tisrd_atr.sql com.skims
#./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_dh_stf.sql com.skims
#./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_cvr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/설계/ins_ins_pl.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_relpc.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_nc_mtt.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_auto_tf_rq.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_relpc_adr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/설계/ins_pl_relpc_rel.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_xi_py.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_otcm_cr.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_clm_nv_cs_spc.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_clm_nv.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_clm_bsns_prg_st.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_clm_rcp.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_clmps.sql com.skims
./dbtbl2msa.sh ./dbtbl/lse/보상/lse_xi_py_spc.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_ldg_acc_crr.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_py_xc.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_slp.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_np_acc_ldg.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_py_cr.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_prm_rv_sb.sql com.skims
./dbtbl2msa.sh ./dbtbl/fin/재무회계/fin_slp_spc.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_ins_cr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_nrdps_tisrd_atr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_cvr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_whpy_rq.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_inr_cr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_st_crr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cm_mtd.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_nc_mtt.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_whpy_bj.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_relpc_rel.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_relpc.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_dh_stf_crr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/계약/ins_cr_relpc_adr_crr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/심사관리/ins_udwr.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/심사관리/ins_ud.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_ltrm_bzcs.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_gd_cvr.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_cvr.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_ltrm_prm.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_ltrm_rato_cop_it.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_gd.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_ltrm_rato.sql com.skims
./dbtbl2msa.sh ./dbtbl/igd/보험상품기본/igd_ltrm_gd_rt_info.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_cvr_incm_prm.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_auto_tf_spc.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_auto_trfrq.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_incm_prm.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_whpy_bj.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_auto_tf_schd.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_py_dc.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_py.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_dp_dl_er.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_rp_adm.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_tf_wrk_dl_crst.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_inprm_dh_stf.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_tf_ercd.sql com.skims
./dbtbl2msa.sh ./dbtbl/ins/입출금/ins_auto_tf_rq.sql com.skims
