--
-- Table structure for table `cus_kyc_exec_crr`
--

DROP TABLE IF EXISTS `cus_kyc_exec_crr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cus_kyc_exec_crr` (
  `kyc_exec_sno` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT 'KYC수행일련번호',
  `kyc_exec_dthms` datetime NOT NULL COMMENT 'KYC수행일시',
  `kyc_cplt_dthms` datetime DEFAULT NULL COMMENT 'KYC완료일시',
  `kyc_bsns_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC업무구분코드',
  `kyc_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC거래구분코드',
  `kyc_relpc_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC관계자유형코드',
  `plno_or_plyno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설계번호/증권번호',
  `kyc_ctm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC고객유형코드',
  `kyc_ctmdn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC고객식별번호구분코드',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `hngl_ctmnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글고객명',
  `eng_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문고객명',
  `ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국적코드',
  `kyc_rgfrg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC내외국인구분코드',
  `rsd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거주여부',
  `brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생년월일',
  `kyc_lstst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC상장구분코드',
  `kyc_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC결과코드',
  `hgrk_grp_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고위험군사유코드',
  `jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업코드',
  `std_ind_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준산업분류코드',
  `wpcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직장명',
  `dl_fd_sorc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래자금출처구분코드',
  `dl_fd_sorc_cn` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래자금출처내용',
  `dl_oj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래목적구분코드',
  `dl_oj_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래목적내용',
  `bzps_imnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자종목명',
  `rl_ownr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자여부',
  `rl_ownr_ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자국적코드',
  `rl_ownr_nm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자성명',
  `rl_ownr_eng_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자영문고객명',
  `rl_ownr_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자주민번호',
  `rl_ownr_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자생년월일',
  `rl_ownr_cnf_xmp_bjpcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자확인면제대상코드',
  `ctm_rel_dt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객관계세부유형코드',
  `qtrt` decimal(12,6) DEFAULT NULL COMMENT '지분율',
  `pdt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자성명',
  `pdt_ennm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자영문명',
  `pdt_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자생년월일',
  `pdt_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자주민번호',
  `pdt_ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자국적코드',
  `agnt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인성명',
  `agnt_ennm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인영문명',
  `agnt_ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리인고객식별번호',
  `crt_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자관계코드',
  `nminr_chd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미성년자녀여부',
  `idnty_cnfc_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증종류코드',
  `idnty_cnfc_et_info` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증기타정보',
  `idnty_cnfc_no` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증번호',
  `idnty_cnfc_isdt` date DEFAULT NULL COMMENT '신원확인증발급일자',
  `idnty_cnfc_is_orgnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증발급기관명',
  `idnty_cnf_pdtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인대표자명',
  `idnty_cnf_truth_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인진위여부',
  `idnty_cnf_truth_cnfdt` date DEFAULT NULL COMMENT '신원확인진위확인일자',
  `idnty_cnf_evd_dcu_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신원확인증빙서류구분코드',
  `fnd_oj_evd_dcu_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '설립목적증빙서류구분코드',
  `rl_ownr_evd_dcu_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실소유자증빙서류구분코드',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `kyc_ogcy_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KYC원본결과코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`kyc_exec_sno`),
  KEY `idx_cus_kyc_exec_crr_10` (`ctmno`,`kyc_exec_dthms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='KYC수행이력';
