--
-- Table structure for table `cus_ctm_info_rv_bj_sts`
--

DROP TABLE IF EXISTS `cus_ctm_info_rv_bj_sts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cus_ctm_info_rv_bj_sts` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '기준년월',
  `stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '직원번호',
  `ppr_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위기관코드',
  `orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관코드',
  `nhgst_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차상위기관코드',
  `dnhgt_orncd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차차상위조직코드',
  `adr_rtct` decimal(10,0) DEFAULT NULL COMMENT '주소반송건수',
  `adr_rt_dlct` decimal(10,0) DEFAULT NULL COMMENT '주소반송처리건수',
  `adr_rt_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '주소반송처리불가건수',
  `adr_dher_same_erct` decimal(10,0) DEFAULT NULL COMMENT '주소취급자동일오류건수',
  `adr_dher_same_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '주소취급자동일오류처리건수',
  `adr_dher_same_er_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '주소취급자동일오류처리불가건수',
  `adr_radnm_erct` decimal(10,0) DEFAULT NULL COMMENT '주소도로명오류건수',
  `adr_radnm_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '주소도로명오류처리건수',
  `adr_pstno_abov_cnf_imrct` decimal(10,0) DEFAULT NULL COMMENT '주소우편번호이상확인불가건수',
  `mail_tp_erct` decimal(10,0) DEFAULT NULL COMMENT '이메일형식오류건수',
  `mail_tp_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '이메일형식오류처리건수',
  `mail_tp_er_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '이메일형식오류처리불가건수',
  `mail_dher_same_erct` decimal(10,0) DEFAULT NULL COMMENT '이메일취급자동일오류건수',
  `mail_dher_same_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '이메일취급자동일오류처리건수',
  `mail_dher_same_er_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '이메일취급자동일오류처리불가건수',
  `tlno_erct` decimal(10,0) DEFAULT NULL COMMENT '전화번호오류건수',
  `tl_noer_dlct` decimal(10,0) DEFAULT NULL COMMENT '전화번호오류처리건수',
  `tl_noer_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '전화번호오류처리불가건수',
  `tlno_lngth_erct` decimal(10,0) DEFAULT NULL COMMENT '전화번호길이오류건수',
  `tlno_lngth_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '전화번호길이오류처리건수',
  `tlno_lngth_er_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '전화번호길이오류처리불가건수',
  `tlno_cntn_no_er_ct` decimal(10,0) DEFAULT NULL COMMENT '전화번호연속번호오류건수',
  `tlno_cntn_no_er_dl_ct` decimal(10,0) DEFAULT NULL COMMENT '전화번호연속번호오류처리건수',
  `tlno_cntn_no_er_dl_impr_ct` decimal(10,0) DEFAULT NULL COMMENT '전화번호연속번호오류처리불가건수',
  `tlno_dher_same_erct` decimal(10,0) DEFAULT NULL COMMENT '전화번호취급자동일오류건수',
  `tlno_dher_same_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '전화번호취급자동일오류처리건수',
  `tlno_dher_same_er_dl_impr_ct` decimal(10,0) DEFAULT NULL COMMENT '전화번호취급자동일오류처리불가건수',
  `tot_erct` decimal(10,0) DEFAULT NULL COMMENT '전체오류건수',
  `tot_er_dlct` decimal(10,0) DEFAULT NULL COMMENT '전체오류처리건수',
  `tot_er_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '전체오류처리불가건수',
  `adr_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '주소오류전체건수',
  `adr_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '주소오류전체처리건수',
  `adr_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '주소오류전체처리불가건수',
  `hp_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰오류전체건수',
  `hp_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰오류전체처리건수',
  `hp_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰오류전체처리불가건수',
  `hp_out_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰외오류전체건수',
  `hp_out_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰외오류전체처리건수',
  `hp_out_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰외오류전체처리불가건수',
  `mail_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '이메일오류전체건수',
  `mail_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '이메일오류전체처리건수',
  `mail_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '이메일오류전체처리불가건수',
  `hpno_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰번호오류전체건수',
  `hpno_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰번호오류전체처리건수',
  `hpno_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰번호오류전체처리불가건수',
  `hpno_lngth_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰번호길이오류전체건수',
  `hpno_lngth_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰번호길이오류전체처리건수',
  `hpno_lngth_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰번호길이오류전체처리불가건수',
  `hp_cntn_no_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰연속번호오류전체건수',
  `hp_cntn_no_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰연속번호오류전체처리건수',
  `hp_cntn_no_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰연속번호오류전체처리불가건수',
  `hp_dher_same_er_tot_ct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰취급자동일오류전체건수',
  `hp_dher_same_er_tot_dlct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰취급자동일오류전체처리건수',
  `hp_dher_same_er_tot_dl_imrct` decimal(10,0) DEFAULT NULL COMMENT '휴대폰취급자동일오류전체처리불가건수',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_cus_ctm_info_rv_bj_sts_00` (`st_yymm`,`stfno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='고객정보보정대상통계';
