--
-- Table structure for table `cus_ntp_info`
--

DROP TABLE IF EXISTS `cus_ntp_info`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cus_ntp_info` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `ntp_cd` varchar(15) COLLATE utf8mb4_bin NOT NULL COMMENT '기업코드',
  `conm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상호명',
  `cmpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회사명',
  `ennm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문명',
  `chnc_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한문고객명',
  `pdtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자명',
  `eng_relnm` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문관계자명',
  `chnc_pdt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한문대표자성명',
  `fs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'FS구분코드',
  `clgmm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결산월',
  `ntp_fndt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업창업구분코드',
  `ntp_fnd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업설립구분코드',
  `ntp_lstst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업상장구분코드',
  `org_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기관상태코드',
  `ntp_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업형태코드',
  `ntp_sclcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업규모코드',
  `empct_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종업원수구분코드',
  `st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기준년월',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `crpno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인번호',
  `sts_davl` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통계자료값',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `rtrs_cn` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '반송사유내용',
  `qtit_exmp_cn` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '문항보기내용',
  `adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주소',
  `lctn_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지우편번호',
  `hdof_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본사전화번호',
  `hdof_fxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본사팩스번호',
  `lctn_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소재지상세주소',
  `tot_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전체주소',
  `cvr_oj_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보목적물주소',
  `fct_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장우편번호',
  `fct_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장전화번호',
  `fct_fxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장팩스번호',
  `fct_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장상세주소',
  `jns_tot_adr` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가맹점전체주소',
  `bzofc_adr_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사무실주소상세주소',
  `bzp_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업소우편번호',
  `bzp_tlno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업소전화번호',
  `bzp_fxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업소팩스번호',
  `bzp_dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영업소상세주소',
  `attd_inp_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출근입력경로코드',
  `mdf_av_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수정가능구분코드',
  `mntr_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주거래은행코드',
  `brnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지점명',
  `nsccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계열사코드',
  `btpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_cus_ntp_info_00` (`ntp_cd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='기업정보';
