--
-- Table structure for table `cus_bz_fml_ctm`
--

DROP TABLE IF EXISTS `cus_bz_fml_ctm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cus_bz_fml_ctm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '직원번호',
  `bz_fml_ctm_seqno` decimal(10,0) NOT NULL COMMENT '영업가족고객순번',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `hngl_ctmnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글고객명',
  `eng_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문고객명',
  `chnc_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한문고객명',
  `hngl_abrv_ctmnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글축약고객명',
  `eng_abrv_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문축약고객명',
  `cr_own_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량소유여부',
  `drve_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전여부',
  `ctm_dat_acq_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객데이터획득경로코드',
  `sms_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS수신여부',
  `tl_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화수신여부',
  `crdif_utl_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보활용동의여부',
  `mail_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일수신여부',
  `ntclt_mail_rcv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안내문이메일수신여부',
  `rgbrd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '내외국구분코드',
  `et_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타주소구분코드',
  `wdg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결혼여부',
  `relgn_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '종교코드',
  `fnl_edbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종학력코드',
  `hndps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애인여부',
  `hnd_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애등급코드',
  `hnd_grd_vald_trm` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애등급유효기간',
  `hndnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애명',
  `hnd_grdpa_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장애급호코드',
  `ntn_mrtmn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국가유공자여부',
  `rwxno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보훈번호',
  `btplc_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출생지코드',
  `grdu_sch` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출신학교',
  `slcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '양음구분코드',
  `rl_brtyr_mndy` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실제생년월일',
  `rh_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'RH형태코드',
  `bldty_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '혈액형코드',
  `wpcnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직장명',
  `depnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부서명',
  `ptn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직위',
  `bdt` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직무',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업코드',
  `jb_ch_seqno` decimal(5,0) DEFAULT NULL COMMENT '직업변경순번',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `jb_dt_cn` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업상세내용',
  `emp_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고용형태코드',
  `wrk_arecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근무지역코드',
  `sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성별코드',
  `ba_life_sadps_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기초생활수급자여부',
  `smok_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '흡연여부',
  `de_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망여부',
  `htn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고향',
  `wot_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '맞벌이여부',
  `frg_rlnm_ctfct_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외국인실명증표구분코드',
  `ntlcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국적코드',
  `pspno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '여권번호',
  `rcmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추천인명',
  `rcm_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추천인주민번호',
  `dher_rcm_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급자추천인관계코드',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `ctm_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호구분코드',
  `ta_crno` varchar(12) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이관발생번호',
  `tabf_dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이관전취급직원번호',
  `bz_fmlcu_cr_seqno` decimal(10,0) DEFAULT NULL COMMENT '영업가족고객발생순번',
  `indpd_mrtmn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '독립유공자여부',
  `dflt_pt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고엽제환자여부',
  `dmrcy_518_injd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민주518부상자여부',
  `pss_ctm_cvdt` date DEFAULT NULL COMMENT '가망고객전환일자',
  `rlnm_cnf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실명확인구분코드',
  `cnv_hp_tmst_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통화희망시간대코드',
  `born_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출생년도',
  `born_mndy` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출생월일',
  `rl_born_mndy` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실제출생월일',
  `mktg_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마케팅동의여부',
  `psn_info_cvap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개인정보민원여부',
  `usr_adm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사용인관리직원번호',
  `reln_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연고구분코드',
  `nw_pss_ctm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규가망고객여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_cus_bz_fml_ctm_00` (`stfno`,`bz_fml_ctm_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='영업가족고객';
