--
-- Table structure for table `cus_crdif_outs_of`
--

DROP TABLE IF EXISTS `cus_crdif_outs_of`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cus_crdif_outs_of` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `ctmno` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT '고객번호',
  `info_ofdt` date NOT NULL COMMENT '정보제공일자',
  `bsns_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '업무구분코드',
  `crdif_of_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '신용정보제공구분코드',
  `info_of_seqno` decimal(5,0) NOT NULL COMMENT '정보제공순번',
  `info_us_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '정보이용기관코드',
  `info_us_org_dtnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보이용기관세부명',
  `info_usps_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보이용자주민번호',
  `info_us_ojccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보이용목적코드',
  `grc_rq_strdt` date DEFAULT NULL COMMENT '유예요청시작일자',
  `grc_rq_nddt` date DEFAULT NULL COMMENT '유예요청종료일자',
  `info_of_cncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '정보제공내용코드',
  `rsno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주민번호제공여부',
  `ctmnm_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객명제공여부',
  `brth_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생년월일제공여부',
  `mail_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일제공여부',
  `plyno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호제공여부',
  `actno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호제공여부',
  `hp_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '휴대전화제공여부',
  `home_tlno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자택전화번호제공여부',
  `wpc_tlno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직장전화번호제공여부',
  `home_adr_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자택주소제공여부',
  `wpc_adr_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직장주소제공여부',
  `et_adr_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타주소제공여부',
  `mmpym_prm_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '월납입보험료제공여부',
  `tpy_prm_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총납입보험료제공여부',
  `pibam_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급보험금제공여부',
  `nd_rtamt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기환급금제공여부',
  `et_rtamt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타환급금제공여부',
  `carno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호제공여부',
  `is_cvr_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입담보제공여부',
  `clm_rcpno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수번호제공여부',
  `crdno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '카드번호제공여부',
  `mpn_no_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '마이핀번호제공여부',
  `crpno_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법인번호제공여부',
  `sex_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '성별제공여부',
  `conm_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상호제공여부',
  `jb_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업제공여부',
  `cvr_knd_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보종류제공여부',
  `lnamt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출금액제공여부',
  `ln_trm_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출기간제공여부',
  `ln_oj_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출목적제공여부',
  `ln_rfdy_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출상환일제공여부',
  `ln_knd_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출종류제공여부',
  `hot_cr_cn_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임대차계약내용제공여부',
  `nd_sct_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기구간제공여부',
  `rstm_info_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부동산정보제공여부',
  `icamt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소득금액제공여부',
  `aramt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체금액제공여부',
  `ar_rckdy_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체기산일제공여부',
  `ar_bj_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체대상제공여부',
  `ar_yn_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체여부제공여부',
  `ardt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체일자제공여부',
  `ar_cnc_rs_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체해제사유제공여부',
  `ar_cncdt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연체해제일자제공여부',
  `piamt_rf_mtd_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원리금상환방법제공여부',
  `vald_cvr_vlamt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유효담보가액제공여부',
  `ntrt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이자율제공여부',
  `rsm_mvgn_info_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주민등록전입정보제공여부',
  `hous_ln_yn_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주택대출여부제공여부',
  `de_guamt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무보증금액제공여부',
  `de_udrtk_agr_amt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무인수약정금액제공여부',
  `de_gu_dt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무보증일자제공여부',
  `de_gu_cncdt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '채무보증해제일자제공여부',
  `lm_dl_stt_of_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한도거래상황제공여부',
  `pg_id` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '프로그램ID',
  `nots_cn` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적요내용',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_cus_crdif_outs_of_00` (`ctmno`,`info_ofdt`,`bsns_flgcd`,`crdif_of_flgcd`,`info_of_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='신용정보외부제공';
