--
-- Table structure for table `cus_cprt_entp`
--

DROP TABLE IF EXISTS `cus_cprt_entp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cus_cprt_entp` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `ctmno` varchar(13) COLLATE utf8mb4_bin NOT NULL COMMENT '고객번호',
  `cprt_entp_seqno` decimal(3,0) NOT NULL COMMENT '협력업체순번',
  `ap_nd_dthms` datetime NOT NULL COMMENT '적용종료일시',
  `ap_str_dthms` datetime NOT NULL COMMENT '적용시작일시',
  `hngl_ctmnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글고객명',
  `eng_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '영문고객명',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국내외구분코드',
  `cprt_entp_crr_seqno` decimal(3,0) NOT NULL COMMENT '협력업체이력순번',
  `cprt_entp_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '협력업체구분코드',
  `cprt_entp_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협력업체상세구분코드',
  `asmt_cprt_entp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지정협력업체여부',
  `cprt_entp_pout_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협력업체특이사항',
  `cprt_entp_hngl_absnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협력업체한글축약명',
  `cprt_entp_eng_absnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협력업체영문축약명',
  `pdt_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대표자고객번호',
  `srvt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지역권구분코드',
  `dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '거래구분코드',
  `mnbrn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본지점구분코드',
  `wh_cltn_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원천징수대상여부',
  `tx_bzps_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과세사업자유형코드',
  `mdch_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수가계약여부',
  `lgin_usr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인사용자ID',
  `lgin_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인여부',
  `etdv_vcrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입출고대행코드',
  `cotam` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '도장금액',
  `ppr_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상위고객번호',
  `ppr_cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '상위협력업체순번',
  `coop_levcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제휴수준코드',
  `eqmt_levcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시설수준코드',
  `mang_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운영형태코드',
  `eqmt_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시설형태코드',
  `fnrh_num` decimal(5,0) DEFAULT NULL COMMENT '빈소수',
  `dadbd_plmnt_blt_num` decimal(3,0) DEFAULT NULL COMMENT '시신안치능력수',
  `cprt_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '협력사항',
  `eqmt_scl_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시설규모사항',
  `good_srv_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '용품서비스사항',
  `prc_info_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가격정보사항',
  `hsp_orgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원기관코드',
  `hsp_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원종별코드',
  `hsp_spe_adrt` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '병원종별가산율',
  `wrct` decimal(7,0) DEFAULT NULL COMMENT '병실수',
  `bedct` decimal(7,0) DEFAULT NULL COMMENT '베드수',
  `mprm_ct` decimal(7,0) DEFAULT NULL COMMENT '다인실건수',
  `hsp_prpns_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원성향등급코드',
  `fct_specd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장종별코드',
  `mdch_naamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '수가계약금액',
  `mdch_cr_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수가계약등급코드',
  `nsp_vcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검사대행구분코드',
  `fct_spec_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장특징코드',
  `fct_spec_dtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공장특징세부코드',
  `rnt_car_rsdnc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '렌트카상주여부',
  `mvo_cnn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동관련여부',
  `nspcr_atr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '검사장유치여부',
  `csiu_adm_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'CSIU관리대상여부',
  `cr_nsp_cm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '승용차검사수수료',
  `van_nsp_cm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '승합차검사수수료',
  `trck_nsp_cm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '화물차검사수수료',
  `aos_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'AOS사용여부',
  `cnsdr_licno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자문의면허번호',
  `cnsdr_spfel_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자문의전문분야코드',
  `mvo_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동구분코드',
  `mvo_prs_arecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '출동대표지역코드',
  `onsf_tra_ct` decimal(7,0) DEFAULT NULL COMMENT '자체견인대수',
  `mvo_cr_ct` decimal(7,0) DEFAULT NULL COMMENT '출동차량대수',
  `adtx_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부가세대상여부',
  `wrk_av_prdcp_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '작업가능제작사코드',
  `indcp_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공업사형태코드',
  `ac_pur_tycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부품구입형태코드',
  `tkatt_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '탈부착금액',
  `shtmt_crct_amt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '판금교정금액',
  `cotg_ndxcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도장지수코드',
  `cotg_matcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도장재료코드',
  `rmkgd_us_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재생품사용여부',
  `ac_xcd_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부품상회급수코드',
  `rpcrg_cr_flg_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리비계약구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_cus_cprt_entp_00` (`ctmno`,`cprt_entp_seqno`,`ap_nd_dthms`,`ap_str_dthms`),
  KEY `idx_cus_cprt_entp_09` (`hsp_orgcd`,`ap_nd_dthms`,`ctmno`,`cprt_entp_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='협력업체';
