--
-- Table structure for table `ins_py`
--

DROP TABLE IF EXISTS `ins_py`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_py` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `pyno` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '지급번호',
  `plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증권번호',
  `py_cr_brcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생지점코드',
  `py_crdt` date DEFAULT NULL COMMENT '지급발생일자',
  `opyno` varchar(21) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구지급번호',
  `ac_py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경리지급여부',
  `ac_pydt` date DEFAULT NULL COMMENT '경리지급일자',
  `py_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급방법코드',
  `ex_rcv_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '환입환수구분코드',
  `py_uramt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급발생금액',
  `uiamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '공제금액',
  `py_rsamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '지급보류금액',
  `sb_pyamt` decimal(17,2) NOT NULL DEFAULT '0.00' COMMENT '차감지급금액',
  `woncv_py_uramt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산지급발생금액',
  `woncv_uiamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산공제금액',
  `woncv_sb_pyamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '원화환산차감지급금액',
  `mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '화폐코드',
  `xcrt_apdt` date DEFAULT NULL COMMENT '환율적용일자',
  `xcrt` decimal(12,6) NOT NULL DEFAULT '1.000000' COMMENT '환율',
  `self_chamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '자기부담금액',
  `baamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기본금액구분코드',
  `pfb_rcps_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수익자수령인관계코드',
  `py_bjnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급대상명',
  `py_bj_rs_bzmno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급대상주민사업자번호',
  `rqaps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청자명',
  `rqaps_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청자주민번호',
  `dlg_py_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위임지급사유코드',
  `bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '은행코드',
  `actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌번호',
  `dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주명',
  `dpsr_rs_bzmno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주주민사업자번호',
  `py_bj_dpsr_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급대상예금주관계코드',
  `acct_bdlrm_inp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통장일괄송금입력여부',
  `ap_tx_pf_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적용세금우대구분코드',
  `cr_dh_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약취급직원번호',
  `py_cr_ptncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생경로코드',
  `bdl_rm_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일괄송금증권번호',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수조사순번',
  `bdlrm_relpc_clmps_seqno` decimal(5,0) DEFAULT NULL COMMENT '일괄송금관계자사고자순번',
  `py_act_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급계좌구분코드',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `cprt_entp_seqno` decimal(3,0) DEFAULT NULL COMMENT '협력업체순번',
  `adtx_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부가세여부',
  `cmp_py_rltno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상지급연계번호',
  `py_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급상태코드',
  `py_crno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급발생번호',
  `tab_py_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추심지급여부',
  `olcrr_seqno` decimal(5,0) DEFAULT '0' COMMENT '구이력순번',
  `sms_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS대상여부',
  `rtamt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '환급금유형코드',
  `py_cstno` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급품의번호',
  `ln_py_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대출지급상세구분코드',
  `py_bj_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급대상종류코드',
  `py_bj_victm_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급대상피해자관계코드',
  `evdno` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '증빙번호',
  `rm_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '송금방법코드',
  `ovse_tf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외이체여부',
  `pypl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급처구분코드',
  `ibnf_cs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금비용구분코드',
  `ovse_py_bjnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급대상명',
  `ovse_py_bj_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급대상주소',
  `ovse_py_bknm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급은행명',
  `ovse_py_bk_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급은행주소',
  `ntn_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국가별은행코드',
  `swf` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SWIFT',
  `py_bk_ctynm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급은행도시명',
  `py_bk_ntnnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급은행국가명',
  `ovse_rm_bk_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외송금은행유형코드',
  `osea_cm_chrg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국외수수료부담구분코드',
  `ovse_rqapl_rel` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외신청인관계',
  `ovse_py_rs` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급사유',
  `ovse_rcpnt_ref_rs` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외수취인참고사유',
  `ovse_rqapl_rel_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외신청인관계내용',
  `ovse_py_rs_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외지급사유내용',
  `ovse_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해외계좌번호',
  `py_dlay_nt` decimal(15,0) DEFAULT '0' COMMENT '지급지연이자',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_py_00` (`pyno`),
  KEY `idx_ins_py_10` (`plyno`),
  KEY `idx_ins_py_12` (`cmp_py_rltno`),
  KEY `idx_ins_py_13` (`rcp_yymm`,`rcp_nv_seqno`),
  KEY `idx_ins_py_14` (`actno`),
  KEY `idx_ins_py_15` (`py_crno`)
) ENGINE=InnoDB AUTO_INCREMENT=1313 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='지급';
