--
-- Table structure for table `b1_220314_lse_clm_rcp`
--

DROP TABLE IF EXISTS `b1_220314_lse_clm_rcp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `b1_220314_lse_clm_rcp` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(5) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `rcp_crr_seqno` varchar(3) COLLATE utf8mb4_bin NOT NULL COMMENT '접수이력순번',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `ap_str_dthms` datetime NOT NULL COMMENT '적용시작일시',
  `ap_nd_dthms` datetime NOT NULL COMMENT '적용종료일시',
  `rcpdt` date NOT NULL COMMENT '접수일자',
  `rcp_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '접수시분',
  `xp_dmamt` decimal(17,5) NOT NULL DEFAULT '0.00000' COMMENT '예상손해액',
  `clm_rcp_stcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고접수상태코드',
  `clmdt` date NOT NULL COMMENT '사고일자',
  `clm_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '사고시분',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '국내외구분코드',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin NOT NULL COMMENT '사고내용',
  `rcp_pth_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '접수경로구분코드',
  `rprnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '통보자명',
  `rprtr_cmpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자회사명',
  `rprtr_tl_ntncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화국가코드',
  `rprtr_tlano_1` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화지역번호1',
  `rprtr_tltno_1` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화국번1',
  `rprtr_tlsno_1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화일련번호1',
  `rprtr_tlano_2` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화지역번호2',
  `rprtr_tltno_2` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화국번2',
  `rprtr_tlsno_2` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자전화일련번호2',
  `fax_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스지역번호',
  `fax_tno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스국번',
  `fax_sno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '팩스일련번호',
  `rcpr_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '접수자직원번호',
  `ad_dmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '추가청구코드',
  `rcp_ccldt` date DEFAULT NULL COMMENT '접수취소일자',
  `rcp_ccl_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수취소사유코드',
  `clmps_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고자관계코드',
  `dmd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자구분코드',
  `dmd_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자성명',
  `dmd_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자전화지역번호',
  `dmd_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자전화국번',
  `dmd_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청자전화일련번호',
  `rcp_ccl_note` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수취소비고',
  `rcp_ccl_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수취소직원번호',
  `olclm_rcpno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구사고접수번호',
  `inr_clm_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '통합사고여부',
  `cr_clm_rcp_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차사고접수년월',
  `cr_rcp_nv_seqno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동차접수조사순번',
  `otcm_mg_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '타사간사여부',
  `marne_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '해상여부',
  `end_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '종결여부',
  `enddt` date DEFAULT NULL COMMENT '종결일자',
  `prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결재구분코드',
  `prvdt` date DEFAULT NULL COMMENT '결재일자',
  `cmp_ky_yr` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상키년도',
  `cmp_ky_seqno` decimal(10,0) DEFAULT NULL COMMENT '보상키순번',
  `dlg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위임여부',
  `mail_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일아이디',
  `mail_domn` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이메일도메인',
  `py_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급방법코드',
  `py_bkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급은행코드',
  `py_dpsnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급예금주명',
  `py_actno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급계좌번호',
  `dpsr_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주식별번호',
  `dpsr_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예금주고객번호',
  `xp_dmamt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예상손해액구분코드',
  `ntc_mtt_of_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '안내사항제공방법코드',
  `crdif_utl_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보활용동의여부',
  `clm_rcp_ccl_no` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고접수취소번호',
  `trpa_dtspc_clrq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료비세부내역징구여부',
  `ogcy_clrq_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원본징구여부',
  `rcp_vcr_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수대행동의여부',
  `agre_inscp_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동의보험사코드',
  `agre_inscp_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동의보험사명',
  `chrps_rq_dt_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자요청세부사항',
  `ibnf_rigt_dlg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금권리위임여부',
  `dm_dcu_dlg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구서류위임여부',
  `agy_ipps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점입력자명',
  `agy_ipps_empno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점입력자사원번호',
  `agy_ipps_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점입력자전화지역번호',
  `agy_ipps_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점입력자전화국번',
  `agy_ipps_tlsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대리점입력자전화일련번호',
  `clm_nv_pass_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '사고조사PASS여부',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `ntncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국가코드',
  `ctycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도시코드',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `mg_clmno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '간사사고번호',
  `ctm_cnr_rcp_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객센터접수상태코드',
  `sh_prnt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위장제보구분코드',
  `py_mtt_of_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급사항제공방법코드',
  `befo_ntclt_snd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사전안내장발송여부',
  `fp_ntc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'FP안내여부',
  `fp_py_ntc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'FP지급안내여부',
  `hsp_dm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입원청구여부',
  `otp_dm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원청구여부',
  `rlpmi_joint_rpbl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손연대책임여부',
  `rlpmi_joint_dcn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실손연대확정여부',
  `md_slr_sadrp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료급여수급권자여부',
  `ins_dl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험처리구분코드',
  `rcp_ins_cmpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수보험회사코드',
  `nv_org_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사기관종류코드',
  `hwrk_dv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수작업배당여부',
  `jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업코드',
  `jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직업명',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `nrdps_adr_apyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자주소적용여부',
  `self_dv_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본인배당여부',
  `rprtr_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통보자관계코드',
  `dcu_rcpdt` date DEFAULT NULL COMMENT '서류접수일자',
  `rcp_tl_mail_cntad` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수전화메일연락처',
  `sms_ntc_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS안내전화지역번호',
  `sms_ntc_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS안내전화국번',
  `sms_ntc_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS안내전화일련번호',
  `sms_ntc_rprtr_hp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SMS안내통보자휴대폰여부',
  `wire_ntc_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유선안내전화지역번호',
  `wire_ntc_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유선안내전화국번',
  `wire_ntc_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유선안내전화일련번호',
  `wire_ntc_rprtr_hp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유선안내통보자휴대폰여부',
  `carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호',
  `org_rcp_dv_chrps_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '본접수배당담당자ID',
  `dv_dthms` datetime DEFAULT NULL COMMENT '배당일시',
  `acci_ps_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재해자구분코드',
  `acci_ps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재해자명',
  `act_cnf_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계좌확인여부',
  `tmp_rcp_dv_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가접수배당직원번호',
  `dlay_mtt_of_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지연사항제공방법코드',
  `chrps_mtt_of_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자사항제공방법코드',
  `rcp_ccl_mtt_of_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수취소사항제공방법코드',
  `rcp_ccl_reln_clm_rcpno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수취소연관사고접수번호',
  `rcp_mdf_usr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접수수정사용자ID',
  `rcp_mdf_dthms` datetime DEFAULT NULL COMMENT '접수수정일시',
  `nrdps_jb_ch_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자직업변경여부',
  `nrdps_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자직업코드',
  `nrdps_injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자상해급수코드',
  `nrdps_jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자직업명',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_clm_rcp_00` (`rcp_yymm`,`rcp_nv_seqno`,`rcp_crr_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=1029 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고접수';
