--
-- Table structure for table `igd_lsetm_cvr_adm_temp`
--

DROP TABLE IF EXISTS `igd_lsetm_cvr_adm_temp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `igd_lsetm_cvr_adm_temp` (
  `gdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '상품코드',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `rkrt_cd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '위험율코드',
  `clm_cvrcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고담보코드',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `ref_gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참조상품코드',
  `rnw_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신담보여부',
  `gd_tm_inp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품팀입력직원번호',
  `gd_tm_inp_dthms` datetime DEFAULT NULL COMMENT '상품팀입력일시',
  `lsetm_tm_inp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사팀입력직원번호',
  `lsetm_tm_inp_dthms` datetime DEFAULT NULL COMMENT '손사팀입력일시',
  `accpb_tm_inp_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계리팀입력직원번호',
  `accpb_tm_inp_dthms` datetime DEFAULT NULL COMMENT '계리팀입력일시',
  `cvr_ba_trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보기본특약구분코드',
  `clm_cvrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고담보명',
  `llse_adm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대손사관리담보코드',
  `mlse_adm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중손사관리담보코드',
  `slse_adm_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소손사관리담보코드',
  `llse_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대손사분류코드',
  `mlse_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '중손사분류코드',
  `slse_csfcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소손사분류코드',
  `sel_ddalw_mdcs_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '후유일당의료비구분코드',
  `inssw_ba_dat_lclcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사기기초데이터대분류코드',
  `inssw_ba_dat_mdccd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사기기초데이터중분류코드',
  `inssw_ba_dat_smccd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험사기기초데이터소분류코드',
  `fsvs_cvr_flgcd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금감원담보구분코드',
  `dvpns_cvrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개발원담보코드',
  `isamt_cmp_pyrt` decimal(7,2) DEFAULT NULL COMMENT '가입금액대비지급율',
  `t1_per_pyrt` decimal(7,2) DEFAULT NULL COMMENT '1회당지급율',
  `part_cmp_trm_days` decimal(5,0) DEFAULT NULL COMMENT '일부보상기간일수',
  `part_cmprt` decimal(5,2) DEFAULT NULL COMMENT '일부보상비율',
  `anul_cr_dy_st_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '매년계약일기준여부',
  `annu_cmplm_ct` decimal(3,0) DEFAULT NULL COMMENT '연간보상한도횟수',
  `rs_rlv_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사유해당일자구분코드',
  `t1_py_unt_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '1회지급단위유형코드',
  `cmplm_stdy_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상한도기준일구분코드',
  `cmplm_trm_days` decimal(5,0) DEFAULT NULL COMMENT '보상한도기간일수',
  `mdcs_cal_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의료비계산방법코드',
  `otp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '통원구분코드',
  `otp_lmamt` decimal(15,0) DEFAULT NULL COMMENT '통원한도금액',
  `hspmc_cmplm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입원의료비보상한도구분코드',
  `ddalw_lm_days` decimal(5,0) DEFAULT NULL COMMENT '일당한도일수',
  `hsp_frdy_xcpt_days` decimal(5,0) DEFAULT NULL COMMENT '입원초일제외일수',
  `nrdsc_py_dgre` decimal(3,0) DEFAULT NULL COMMENT '간병비지급차수',
  `imu_dcsn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '면책판단구분코드',
  `nw_wknd_cmp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신주말보상여부',
  `cmp_dsacd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상질병코드',
  `cmp_impr_dsacd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보상불가질병코드',
  `auto_xi_slc_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동추산선택코드',
  `lsetm_cvr_slc_1_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사담보선택1코드',
  `lsetm_cvr_slc_2_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사담보선택2코드',
  `lsetm_cvr_slc_3_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사담보선택3코드',
  `lsetm_cvr_slc_4_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사담보선택4코드',
  `lsetm_cvr_slc_5_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손사담보선택5코드',
  `auto_xi_cal_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동추산계산코드',
  `gn_opn_imu_days` decimal(5,0) DEFAULT NULL COMMENT '보장개시면책일수',
  `extr_cmp_lmamt` decimal(15,0) DEFAULT NULL COMMENT '별도보상한도금액',
  `ibnr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'IBNR구분코드',
  `hsp_otp_op_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입원통원수술구분코드',
  `an_fmlr_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연금식담보여부',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`gdcd`,`cvrcd`,`rkrt_cd`,`clm_cvrcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='손사담보관리';
