--
-- Table structure for table `ins_accpb_cvr_prm_diss`
--

DROP TABLE IF EXISTS `ins_accpb_cvr_prm_diss`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_accpb_cvr_prm_diss` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `accpb_cls_flgcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '계리마감구분코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) NOT NULL COMMENT '수입보험료발생순번',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `prm_diss_seqno` decimal(5,0) NOT NULL COMMENT '보험료분해순번',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보종군코드',
  `cvr_ba_trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보기본특약구분코드',
  `cvr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태코드',
  `prm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료구분코드',
  `dp_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금원인코드',
  `dp_dt_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금세부원인코드',
  `cnn_incm_prmcr_seqno` decimal(5,0) DEFAULT NULL COMMENT '관련수입보험료발생순번',
  `isamt` decimal(17,2) DEFAULT NULL COMMENT '가입금액',
  `rp_prm` decimal(15,0) DEFAULT NULL COMMENT '영수보험료',
  `ba_prm` decimal(15,0) DEFAULT NULL COMMENT '기본보험료',
  `ap_prm` decimal(17,2) DEFAULT NULL COMMENT '적용보험료',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `pym_trmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간코드',
  `pym_trm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간구분코드',
  `pym_trm` decimal(3,0) DEFAULT NULL COMMENT '납입기간',
  `nd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기구분코드',
  `nd` decimal(3,0) DEFAULT NULL COMMENT '만기',
  `rl_nd_trm` decimal(3,0) DEFAULT NULL COMMENT '실만기기간',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `nrdps_age` decimal(3,0) DEFAULT NULL COMMENT '피보험자연령',
  `nrdps_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자성별코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `rl_pym_trm` decimal(3,0) DEFAULT NULL COMMENT '실납입기간',
  `ap_nddt` date DEFAULT NULL COMMENT '적용종료일자',
  `nw_rnw_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규갱신구분코드',
  `rnd_yyct` decimal(5,0) DEFAULT NULL COMMENT '경과년수',
  `rnd_mc` decimal(5,0) DEFAULT NULL COMMENT '경과월수',
  `rnd_mntct` decimal(5,0) DEFAULT NULL COMMENT '경과개월수',
  `nrdps_ap_age` decimal(3,0) DEFAULT NULL COMMENT '피보험자적용연령',
  `rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율KEY조립코드',
  `bzcs_rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업비요율KEY조립코드',
  `st_isamt` decimal(17,2) DEFAULT NULL COMMENT '기준가입금액',
  `dp_mc` decimal(5,0) DEFAULT NULL COMMENT '상각월수',
  `nprm` decimal(17,7) DEFAULT NULL COMMENT '순보험료',
  `beye_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '연초보험료적립금액',
  `yend_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '연말보험료적립금액',
  `sustd_xc_rk_ndx` decimal(7,2) DEFAULT NULL COMMENT '표준하체할증위험지수',
  `sustd_rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준하체요율KEY조립코드',
  `sustd_nprm` decimal(17,7) DEFAULT NULL COMMENT '표준하체순보험료',
  `sustd_beye_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체연초보험료적립금액',
  `sustd_yend_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체연말보험료적립금액',
  `sustd_rnd_gn_rfamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체경과보장준비금액',
  `cmlcs_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '수금비영업보험료비율',
  `dm_nv_rt` decimal(12,6) DEFAULT NULL COMMENT '손해조사비율',
  `nwcrt_isamt_rt` decimal(12,6) DEFAULT NULL COMMENT '신계약비가입금액비율',
  `nwcrt_fsyr_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '신계약비초년도영업보험료비율',
  `nwcrt_anul_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '신계약비매년영업보험료비율',
  `bcpay_mncs_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '완납전유지비영업보험료비율',
  `acpay_mncs_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '완납후유지비영업보험료비율',
  `rk_prm` decimal(15,0) DEFAULT NULL COMMENT '위험보험료',
  `sv_prm` decimal(15,0) DEFAULT NULL COMMENT '저축보험료',
  `nprmt_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '순보험료식신계약비',
  `ppy_prm` decimal(15,0) DEFAULT NULL COMMENT '선납보험료',
  `nelp_prm` decimal(17,2) DEFAULT NULL COMMENT '미경과보험료',
  `rnd_prm` decimal(17,2) DEFAULT NULL COMMENT '경과보험료',
  `cn_prm` decimal(17,2) DEFAULT NULL COMMENT '해지보험료',
  `cnclb_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '해약식신계약비',
  `rpttp_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '보고식신계약비',
  `bcpay_mncs` decimal(15,0) DEFAULT NULL COMMENT '완납전유지비',
  `acpay_mncs` decimal(15,0) DEFAULT NULL COMMENT '완납후유지비',
  `cmlcs` decimal(15,0) DEFAULT NULL COMMENT '수금비',
  `nrpym_nwcrt` decimal(17,2) DEFAULT NULL COMMENT '미상각신계약비',
  `cnclb_sv_prm` decimal(17,2) DEFAULT NULL COMMENT '해약식저축보험료',
  `pr_dm_nvcs` decimal(15,0) DEFAULT NULL COMMENT '예정손해조사비',
  `anul_bzprm_cmp_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '매년영업보험료대비신계약비',
  `pr_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '예정신계약비',
  `pr_nwcrt_tamt` decimal(15,0) DEFAULT NULL COMMENT '예정신계약비총액',
  `sustd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체보험료',
  `sustd_rk_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체위험보험료',
  `sustd_sv_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체저축보험료',
  `sustd_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체미경과보험료',
  `sustd_rnd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체경과보험료',
  `accbt_tfdt` date DEFAULT NULL COMMENT '계정간이체일자',
  `rn_diss_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원수분해구분코드',
  `rn_diss_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원수분해세부구분코드',
  `tf_dlay_nt` decimal(15,0) DEFAULT NULL COMMENT '이체지연이자',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`cls_yymm`,`accpb_cls_flgcd`,`plyno`,`incm_prm_cr_seqno`,`cvrcd`,`cvr_seqno`,`prm_diss_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계리담보보험료분해';
