--
-- Table structure for table `ins_accpb_cr_prm_diss_crr`
--

DROP TABLE IF EXISTS `ins_accpb_cr_prm_diss_crr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_accpb_cr_prm_diss_crr` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `accpb_cls_flgcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '계리마감구분코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `incm_prm_cr_seqno` decimal(5,0) NOT NULL COMMENT '수입보험료발생순번',
  `prm_diss_seqno` decimal(5,0) NOT NULL COMMENT '보험료분해순번',
  `pym_seq` decimal(5,0) DEFAULT NULL COMMENT '납입회차',
  `ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서번호',
  `fnl_pym_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종납입년월',
  `pyp_t_seq` decimal(5,0) DEFAULT NULL COMMENT '분납총회차',
  `ccldt` date DEFAULT NULL COMMENT '취소일자',
  `ccl_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취소구분코드',
  `ppdt` date DEFAULT NULL COMMENT '계상일자',
  `ppy_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선납여부',
  `ppy_dc_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선납할인여부',
  `dcbf_prm` decimal(15,0) DEFAULT NULL COMMENT '할인전보험료',
  `rv_dldt` date DEFAULT NULL COMMENT '수납처리일자',
  `rp_prm` decimal(15,0) DEFAULT NULL COMMENT '영수보험료',
  `ap_prm` decimal(17,2) DEFAULT NULL COMMENT '적용보험료',
  `cu_prm` decimal(15,0) DEFAULT NULL COMMENT '적립보험료',
  `dcbf_cu_prm` decimal(15,0) DEFAULT NULL COMMENT '할인전적립보험료',
  `cu_nprm` decimal(15,0) DEFAULT NULL COMMENT '적립순보험료',
  `ba_cvr_prm` decimal(15,0) DEFAULT NULL COMMENT '기본담보보험료',
  `trt_prm` decimal(15,0) DEFAULT NULL COMMENT '특약보험료',
  `ba_prm` decimal(15,0) DEFAULT NULL COMMENT '기본보험료',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `prm_diss_ppdt` date DEFAULT NULL COMMENT '보험료분해계상일자',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약상태코드',
  `cr_dt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약세부상태코드',
  `prm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험료구분코드',
  `dp_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금원인코드',
  `dp_dt_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입금세부원인코드',
  `cnn_incm_prmcr_seqno` decimal(5,0) DEFAULT NULL COMMENT '관련수입보험료발생순번',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `pym_trm` decimal(3,0) DEFAULT NULL COMMENT '납입기간',
  `rl_pym_trm` decimal(3,0) DEFAULT NULL COMMENT '실납입기간',
  `rl_nd_trm` decimal(3,0) DEFAULT NULL COMMENT '실만기기간',
  `rk_prm` decimal(15,0) DEFAULT NULL COMMENT '위험보험료',
  `sv_prm` decimal(15,0) DEFAULT NULL COMMENT '저축보험료',
  `nprmt_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '순보험료식신계약비',
  `ppy_prm` decimal(15,0) DEFAULT NULL COMMENT '선납보험료',
  `nelp_prm` decimal(17,2) DEFAULT NULL COMMENT '미경과보험료',
  `rnd_prm` decimal(17,2) DEFAULT NULL COMMENT '경과보험료',
  `cn_prm` decimal(17,2) DEFAULT NULL COMMENT '해지보험료',
  `cnclb_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '해약식신계약비',
  `rpttp_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '보고식신계약비',
  `bcpay_mncs` decimal(15,0) DEFAULT NULL COMMENT '완납전유지비',
  `acpay_mncs` decimal(15,0) DEFAULT NULL COMMENT '완납후유지비',
  `cmlcs` decimal(15,0) DEFAULT NULL COMMENT '수금비',
  `nrpym_nwcrt` decimal(17,2) DEFAULT NULL COMMENT '미상각신계약비',
  `cnclb_sv_prm` decimal(17,2) DEFAULT NULL COMMENT '해약식저축보험료',
  `pr_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '예정신계약비',
  `tf_dlay_nt` decimal(15,0) DEFAULT NULL COMMENT '이체지연이자',
  `pr_dm_nvcs` decimal(15,0) DEFAULT NULL COMMENT '예정손해조사비',
  `anul_bzprm_cmp_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '매년영업보험료대비신계약비',
  `sustd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체보험료',
  `sustd_rk_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체위험보험료',
  `sustd_sv_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체저축보험료',
  `sustd_nelp_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체미경과보험료',
  `sustd_rnd_prm` decimal(15,0) DEFAULT NULL COMMENT '표준하체경과보험료',
  `rn_diss_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원수분해구분코드',
  `rn_diss_dt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '원수분해세부구분코드',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`cls_yymm`,`accpb_cls_flgcd`,`plyno`,`incm_prm_cr_seqno`,`prm_diss_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계리계약보험료분해이력';
