--
-- Table structure for table `ins_accpb_stch_cr_rfd_crr`
--

DROP TABLE IF EXISTS `ins_accpb_stch_cr_rfd_crr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_accpb_stch_cr_rfd_crr` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `accpb_cls_flgcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '계리마감구분코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `rfamt_cr_cascd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '준비금액발생원인코드',
  `ap_strdt` date NOT NULL COMMENT '적용시작일자',
  `ap_nddt` date NOT NULL COMMENT '적용종료일자',
  `ndsno` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '배서번호',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `cnrdt` date DEFAULT NULL COMMENT '계약일자',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약상태코드',
  `cr_dt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약세부상태코드',
  `rl_nd_trm` decimal(3,0) DEFAULT NULL COMMENT '실만기기간',
  `rl_pym_trm` decimal(3,0) DEFAULT NULL COMMENT '실납입기간',
  `nd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기구분코드',
  `pym_trm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간구분코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `ps_rfd_remn_mntct` decimal(4,0) DEFAULT NULL COMMENT '보유준비금잔여개월수',
  `rnd_yyct` decimal(5,0) DEFAULT NULL COMMENT '경과년수',
  `rnd_mc` decimal(5,0) DEFAULT NULL COMMENT '경과월수',
  `nelp_mc` decimal(5,0) DEFAULT NULL COMMENT '미경과월수',
  `ap_prm` decimal(17,2) DEFAULT NULL COMMENT '적용보험료',
  `fnl_pym_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종납입년월',
  `fnl_cr_st_chdt` date DEFAULT NULL COMMENT '최종계약상태변경일자',
  `ltrm_bz_av_gdgcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장기사업실적상품군코드',
  `rato_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이율구분코드',
  `rato_ap_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '이율적용유형코드',
  `nd_aprat` decimal(7,4) DEFAULT NULL COMMENT '만기적용이율',
  `ap_rato` decimal(12,6) DEFAULT NULL COMMENT '적용이율',
  `pr_rato` decimal(12,6) DEFAULT NULL COMMENT '예정이율',
  `lowt_gu_rato` decimal(12,6) DEFAULT NULL COMMENT '최저보증이율',
  `y1wi_lap_rato` decimal(12,6) DEFAULT NULL COMMENT '1년이내실효이율',
  `y1_aft_lap_rato` decimal(12,5) DEFAULT NULL COMMENT '1년이후실효이율',
  `rnd_rfd_sm` decimal(15,0) DEFAULT NULL COMMENT '경과준비금합계',
  `nelp_rfamt` decimal(15,0) DEFAULT NULL COMMENT '미경과준비금액',
  `nelp_gn_rfamt` decimal(15,0) DEFAULT NULL COMMENT '미경과보장준비금액',
  `nelp_cu_rfamt` decimal(15,0) DEFAULT NULL COMMENT '미경과적립준비금액',
  `nelp_ppy_prm_cuamt` decimal(17,2) DEFAULT NULL COMMENT '미경과선납보험료적립금액',
  `py_dlay_nt` decimal(15,0) DEFAULT NULL COMMENT '지급지연이자',
  `lap_rfamt` decimal(17,2) DEFAULT NULL COMMENT '실효준비금액',
  `cnarx_gn_rnd_rfd_smamt` decimal(17,2) DEFAULT NULL COMMENT '해지식보장경과준비금합계금액',
  `cnarx_cu_rnd_rfd_smamt` decimal(17,2) DEFAULT NULL COMMENT '해지식적립경과준비금합계금액',
  `gn_pr_cm_nrpym_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '보장예정당월미상각신계약비',
  `cu_pr_cm_nrpym_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '적립예정당월미상각신계약비',
  `gn_netp_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '보장순보식보험료적립금액',
  `cu_netp_prm_cuamt` decimal(17,2) DEFAULT NULL COMMENT '적립순보식보험료적립금액',
  `ppy_nt_nd_rfamt` decimal(17,2) DEFAULT NULL COMMENT '선납이자만기준비금액',
  `cu_std_cn_uiamt` decimal(15,0) DEFAULT NULL COMMENT '적립표준해약공제금액',
  `gn_std_cn_uiamt` decimal(15,0) DEFAULT NULL COMMENT '보장표준해약공제금액',
  `cnarx_rnd_rfd` decimal(15,0) DEFAULT NULL COMMENT '해지식경과준비금',
  `sustd_rnd_gn_rfamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체경과보장준비금액',
  `crt_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자고객번호',
  `crt_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자성명',
  `crt_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자식별번호구분코드',
  `crt_ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자고객식별번호',
  `pym_xmp_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입면제여부',
  `t_pym_prm` decimal(15,0) DEFAULT NULL COMMENT '총납입보험료',
  `ce_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `accpb_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계리상태코드',
  `std_nwcrt_tamt` decimal(15,0) DEFAULT NULL COMMENT '표준신계약비총액',
  `pr_nwcrt_tamt` decimal(15,0) DEFAULT NULL COMMENT '예정신계약비총액',
  `bacvg_cnclb_cumny_sum_amt` decimal(15,0) DEFAULT NULL COMMENT '기본담보해약식적립금합금액',
  `ins_imcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험종목코드',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`cls_yymm`,`accpb_cls_flgcd`,`plyno`,`rfamt_cr_cascd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계리상태변경계약준비금이력';
