--
-- Table structure for table `ins_accpb_stch_cvr_rfd`
--

DROP TABLE IF EXISTS `ins_accpb_stch_cvr_rfd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_accpb_stch_cvr_rfd` (
  `cls_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '마감년월',
  `accpb_cls_flgcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '계리마감구분코드',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `rfamt_cr_cascd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '준비금액발생원인코드',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `nw_rnw_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규갱신구분코드',
  `cvr_ba_trt_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보기본특약구분코드',
  `cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약상태코드',
  `cr_dt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약세부상태코드',
  `cvr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보상태코드',
  `cvr_st_chdt` date DEFAULT NULL COMMENT '담보상태변경일자',
  `pym_cyccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입주기코드',
  `pym_trm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간구분코드',
  `pym_trm` decimal(3,0) DEFAULT NULL COMMENT '납입기간',
  `nd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '만기구분코드',
  `rl_nd_trm` decimal(3,0) DEFAULT NULL COMMENT '실만기기간',
  `nd` decimal(3,0) DEFAULT NULL COMMENT '만기',
  `injr_rnkcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상해급수코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `rl_pym_trm` decimal(3,0) DEFAULT NULL COMMENT '실납입기간',
  `ap_nddt` date DEFAULT NULL COMMENT '적용종료일자',
  `pym_trmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입기간코드',
  `rnd_yyct` decimal(5,0) DEFAULT NULL COMMENT '경과년수',
  `rnd_mc` decimal(5,0) DEFAULT NULL COMMENT '경과월수',
  `rnd_mntct` decimal(5,0) DEFAULT NULL COMMENT '경과개월수',
  `nrdps_ap_age` decimal(3,0) DEFAULT NULL COMMENT '피보험자적용연령',
  `nrdps_ap_sexcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자적용성별코드',
  `cvr_fnl_pym_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보최종납입년월',
  `cvr_pym_seq` decimal(5,0) DEFAULT NULL COMMENT '담보납입회차',
  `isamt` decimal(17,2) DEFAULT NULL COMMENT '가입금액',
  `ba_prm` decimal(15,0) DEFAULT NULL COMMENT '기본보험료',
  `nwfsq_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신초차구분코드',
  `ppy_ct` decimal(5,0) DEFAULT NULL COMMENT '선납횟수',
  `gr_dscrt` decimal(12,6) DEFAULT NULL COMMENT '단체할인율',
  `rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요율KEY조립코드',
  `bzcs_rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업비요율KEY조립코드',
  `st_isamt` decimal(17,2) DEFAULT NULL COMMENT '기준가입금액',
  `dp_mc` decimal(5,0) DEFAULT NULL COMMENT '상각월수',
  `nprm` decimal(17,7) DEFAULT NULL COMMENT '순보험료',
  `beye_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '연초보험료적립금액',
  `yend_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '연말보험료적립금액',
  `std_cn_uiamt` decimal(21,6) DEFAULT NULL COMMENT '표준해약공제금액',
  `nwcrt_isamt_rt` decimal(12,6) DEFAULT NULL COMMENT '신계약비가입금액비율',
  `nwcrt_fsyr_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '신계약비초년도영업보험료비율',
  `nwcrt_anul_bzprm_rt` decimal(12,6) DEFAULT NULL COMMENT '신계약비매년영업보험료비율',
  `std_nwcrt_tamt` decimal(15,0) DEFAULT NULL COMMENT '표준신계약비총액',
  `rnd_gn_rfamt` decimal(15,0) DEFAULT NULL COMMENT '경과보장준비금액',
  `rnd_cu_pcamt` decimal(15,0) DEFAULT NULL COMMENT '경과적립원금',
  `rnd_cu_nt` decimal(15,0) DEFAULT NULL COMMENT '경과적립이자',
  `rnd_rfd_sm` decimal(15,0) DEFAULT NULL COMMENT '경과준비금합계',
  `nelp_gn_rfamt` decimal(15,0) DEFAULT NULL COMMENT '미경과보장준비금액',
  `ppy_prm` decimal(15,0) DEFAULT NULL COMMENT '선납보험료',
  `ppy_nt` decimal(15,0) DEFAULT NULL COMMENT '선납이자',
  `nelp_rfd_sm` decimal(15,0) DEFAULT NULL COMMENT '미경과준비금합계',
  `py_dlay_nt` decimal(15,0) DEFAULT NULL COMMENT '지급지연이자',
  `rfd_sm` decimal(17,2) DEFAULT NULL COMMENT '준비금합계',
  `pr_nwcrt_tamt` decimal(15,0) DEFAULT NULL COMMENT '예정신계약비총액',
  `cnarx_rnd_rfd` decimal(15,0) DEFAULT NULL COMMENT '해지식경과준비금',
  `pr_cm_nrpym_nwcrt` decimal(15,0) DEFAULT NULL COMMENT '예정당월미상각신계약비',
  `sustd_xc_rk_ndx` decimal(7,2) DEFAULT NULL COMMENT '표준하체할증위험지수',
  `sustd_rt_key_assmb_cd` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '표준하체요율KEY조립코드',
  `sustd_nprm` decimal(17,7) DEFAULT NULL COMMENT '표준하체순보험료',
  `sustd_beye_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체연초보험료적립금액',
  `sustd_yend_prm_cuamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체연말보험료적립금액',
  `sustd_rnd_gn_rfamt` decimal(15,0) DEFAULT NULL COMMENT '표준하체경과보장준비금액',
  `sustd_nelp_gn_rfd` decimal(17,2) DEFAULT NULL COMMENT '표준하체미경과보장준비금',
  `dc_xc_cfc` decimal(12,6) DEFAULT NULL COMMENT '할인할증계수',
  `rnw_cvr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신담보여부',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `ce_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모집기관코드',
  `dh_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '취급기관코드',
  `accpb_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계리상태코드',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`cls_yymm`,`accpb_cls_flgcd`,`plyno`,`rfamt_cr_cascd`,`cvrcd`,`cvr_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계리상태변경담보준비금';
