--
-- Table structure for table `lse_clmnv_rcp_st_trmt_temp`
--

DROP TABLE IF EXISTS `lse_clmnv_rcp_st_trmt_temp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_clmnv_rcp_st_trmt_temp` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `clmps_seqno` decimal(3,0) NOT NULL COMMENT '사고자순번',
  `clm_nv_seqno` decimal(3,0) NOT NULL COMMENT '사고조사순번',
  `trmt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '진료구분코드',
  `trmt_spc_seqno` decimal(5,0) NOT NULL COMMENT '진료내역순번',
  `sno` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '일련번호',
  `trmt_strdt` date NOT NULL COMMENT '진료시작일자',
  `trmt_nddt` date DEFAULT NULL COMMENT '진료종료일자',
  `hsp_days` decimal(5,0) DEFAULT NULL COMMENT '입원일수',
  `hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원코드',
  `hsp_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원등급코드',
  `trmt_sbjcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료과목코드',
  `rcpr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요양구분코드',
  `drnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의사명',
  `intns_licno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의사면허번호',
  `opcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술코드',
  `fce_op_cnmtr` decimal(3,0) DEFAULT NULL COMMENT '안면부수술센티미터',
  `amlg_op_cnmtr` decimal(3,0) DEFAULT NULL COMMENT '상하지수술센티미터',
  `obs_trm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장해기간구분코드',
  `obs_yyct` decimal(3,0) DEFAULT NULL COMMENT '장해년수',
  `obs_parcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장해부위코드',
  `obs_itcd` varchar(12) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장해항목코드',
  `de_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망종류코드',
  `drct_ders_de_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '직접사인사망원인코드',
  `de_cas_et_rs` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망원인기타사유',
  `outs_cas_clm_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부원인사고종류코드',
  `outs_cas_clm_knd_et_rs` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부원인사고종류기타사유',
  `outs_cas_ntt_clmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부원인고의사고코드',
  `dr_main_opn_cn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '의사주요소견내용',
  `py_bj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지급대상여부',
  `self_chamt_smamt` decimal(17,2) DEFAULT NULL COMMENT '본인부담금액합계금액',
  `pbco_chamt_smamt` decimal(17,2) DEFAULT NULL COMMENT '공단부담금합계금액',
  `tamt_self_chamt_smamt` decimal(17,2) DEFAULT NULL COMMENT '전액본인부담금합계금액',
  `slc_trpa_smamt` decimal(17,2) DEFAULT NULL COMMENT '선택진료비합계금액',
  `slc_trmt_xcpt_smamt` decimal(17,2) DEFAULT NULL COMMENT '선택진료이외합계금액',
  `self_chrg_mx_spls_amt` decimal(17,2) DEFAULT NULL COMMENT '본인부담상한초과금액',
  `self_chamt_mdamt` decimal(17,2) DEFAULT NULL COMMENT '본인부담금조정금액',
  `tamt_self_chamt_mdamt` decimal(17,2) DEFAULT NULL COMMENT '전액본인부담금조정금액',
  `slc_trpa_mdamt` decimal(17,2) DEFAULT NULL COMMENT '선택진료비조정금액',
  `slc_trmt_xcpt_mdamt` decimal(17,2) DEFAULT NULL COMMENT '선택진료이외조정금액',
  `fnl_self_chamt` decimal(17,2) DEFAULT NULL COMMENT '최종본인부담금액',
  `fnl_pbco_chamt` decimal(17,2) DEFAULT NULL COMMENT '최종공단부담금액',
  `fnl_tamt_self_chamt` decimal(17,2) DEFAULT NULL COMMENT '최종전액본인부담금액',
  `fnl_slc_trmt_amt` decimal(17,2) DEFAULT NULL COMMENT '최종선택진료금액',
  `fnl_slc_trmt_xcpt_amt` decimal(17,2) DEFAULT NULL COMMENT '최종선택진료이외금액',
  `trpa_udwr_ctn` varchar(3000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료비심사자의견',
  `trpa_udwr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료비심사자ID',
  `trpa_smamt` decimal(17,2) DEFAULT NULL COMMENT '진료비합계금액',
  `pt_chamt_sm` decimal(17,2) DEFAULT NULL COMMENT '환자부담금액합계',
  `trmt_ud_amt_smamt` decimal(17,2) DEFAULT NULL COMMENT '진료심사비합계금액',
  `trmt_ud_af_amt` decimal(17,2) DEFAULT NULL COMMENT '진료심사후금액',
  `obs_pst_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '장해위치구분코드',
  `trpa_ud_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료비심사여부',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `opnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수술명',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_clmnv_rcp_st_trmt_00` (`rcp_yymm`,`rcp_nv_seqno`,`dm_seqno`,`clmps_seqno`,`clm_nv_seqno`,`trmt_flgcd`,`trmt_spc_seqno`),
  KEY `idx_lse_clmnv_rcp_st_trmt_10` (`ctm_dscno`)
) ENGINE=InnoDB AUTO_INCREMENT=305 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사고조사접수기준진료';
