--
-- Table structure for table `str_bz_pl`
--

DROP TABLE IF EXISTS `str_bz_pl`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `str_bz_pl` (
  `cy_yr` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT 'CY년도',
  `bz_plcd` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '사업계획코드',
  `form_seq` decimal(3,0) NOT NULL COMMENT '양식회차',
  `bz_pl_itcd` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '사업계획항목코드',
  `bz_pl_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '사업계획기관코드',
  `bz_pl_ins_imcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사업계획보험종목코드',
  `as_orgcd` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '배정기관코드',
  `ch_seqno` decimal(5,0) NOT NULL COMMENT '변경순번',
  `chdt` date NOT NULL COMMENT '변경일자',
  `m1_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '1월계획금액',
  `m2_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '2월계획금액',
  `m3_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '3월계획금액',
  `m4_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '4월계획금액',
  `m5_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '5월계획금액',
  `m6_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '6월계획금액',
  `m7_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '7월계획금액',
  `m8_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '8월계획금액',
  `m9_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '9월계획금액',
  `m10_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '10월계획금액',
  `m11_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '11월계획금액',
  `m12_plamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '12월계획금액',
  `m10_av_xpamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '10월실적예상금액',
  `m11_av_xpamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '11월실적예상금액',
  `m12_av_xpamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '12월실적예상금액',
  `rq_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '신청직원번호',
  `rq_apdt` date DEFAULT NULL COMMENT '신청승인일자',
  `rq_ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청승인직원번호',
  `mddt` date DEFAULT NULL COMMENT '조정일자',
  `md_rqamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '조정요청금액',
  `md_rq_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조정요청기관코드',
  `md_rq_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조정요청직원번호',
  `md_rs` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조정사유',
  `bz_pl_apamt` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '사업계획승인금액',
  `apdt` date DEFAULT NULL COMMENT '승인일자',
  `ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인직원번호',
  `fnl_apdt` date DEFAULT NULL COMMENT '최종승인일자',
  `fnl_ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최종승인직원번호',
  `fnl_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '최종여부',
  `cy_y2_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT 'CY2년합계',
  `cy_y1_xc_av` decimal(15,0) NOT NULL DEFAULT '0' COMMENT 'CY1년집행실적',
  `cy_y1_av` decimal(15,0) NOT NULL DEFAULT '0' COMMENT 'CY1년실적',
  `annu_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '년간합계',
  `qutr1_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '1분기합계',
  `qutr2_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '2분기합계',
  `qutr3_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '3분기합계',
  `qutr4_sm` decimal(15,0) NOT NULL DEFAULT '0' COMMENT '4분기합계',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`cy_yr`,`bz_plcd`,`form_seq`,`bz_pl_itcd`,`bz_pl_orgcd`,`bz_pl_ins_imcd`,`as_orgcd`,`ch_seqno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사업계획';
