--
-- Table structure for table `ins_crdif_inq_agr_adm`
--

DROP TABLE IF EXISTS `ins_crdif_inq_agr_adm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_crdif_inq_agr_adm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `agre_admno` varchar(14) COLLATE utf8mb4_bin NOT NULL COMMENT '동의관리번호',
  `wrcs_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '동의서종류코드',
  `hngl_ctmnm` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '한글고객명',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `dh_stfno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '취급직원번호',
  `crdif_inq_agre_mtdcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '신용정보조회동의방법코드',
  `ap_nd_dthms` datetime NOT NULL COMMENT '적용종료일시',
  `ap_str_dthms` datetime NOT NULL COMMENT '적용시작일시',
  `crdif_inq_agre_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '신용정보조회동의여부',
  `agre_strdt` date DEFAULT NULL COMMENT '동의시작일자',
  `agre_nddt` date DEFAULT NULL COMMENT '동의종료일자',
  `scan_dcuno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '스캔문서번호',
  `adm_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관리직원번호',
  `crdir_agre_1_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보조회동의1여부',
  `crdir_agre_2_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보조회동의2여부',
  `rcgnt_mdfmr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인식수정자ID',
  `ta_mdfmr_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '총무수정자ID',
  `ta_cnf_dthms` datetime DEFAULT NULL COMMENT '총무확인일시',
  `rcgnt_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인식상태코드',
  `form_rcgnt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'FORM인식여부',
  `bcd_rcgnt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '바코드인식여부',
  `rq_rst_cn` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청결과내용',
  `ppa_rsno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '친권자주민번호',
  `ppa_nm` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '친권자성명',
  `nminr_chd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '미성년자녀여부',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `agre_autno_ssdt` date DEFAULT NULL COMMENT '동의인증번호발행일자',
  `ctm_agre_autno` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객동의인증번호',
  `ctm_brth` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객생년월일',
  `scan_cplt_dthms` datetime DEFAULT NULL COMMENT '스캔완료일시',
  `mnal_scan_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수동스캔여부',
  `wrcs_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동의서유형코드',
  `dcuno` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '문서번호',
  `recno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '녹취번호',
  `lms_autno` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'LMS인증번호',
  `auth_rq_dthms` datetime DEFAULT NULL COMMENT '인증요청일시',
  `auth_cplt_dthms` datetime DEFAULT NULL COMMENT '인증완료일시',
  `hndph_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰전화지역번호',
  `hndph_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰전화국번',
  `hndph_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '핸드폰전화일련번호',
  `ts_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전송직원번호',
  `asr_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신전화지역번호',
  `asr_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신전화국번',
  `asr_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '회신전화일련번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_crdif_inq_agr_adm_00` (`agre_admno`,`wrcs_kndcd`),
  KEY `idx_ins_crdif_inq_agr_adm_01` (`ctm_dscno`)
) ENGINE=InnoDB AUTO_INCREMENT=481066 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='신용정보조회동의관리';
