--
-- Table structure for table `ins_ndv_is_crtf`
--

DROP TABLE IF EXISTS `ins_ndv_is_crtf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_ndv_is_crtf` (
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `is_crtf_admno` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '가입증명서관리번호',
  `hngl_relnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '한글관계자명',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자명',
  `lctn_adr` varchar(200) COLLATE utf8mb4_bin NOT NULL COMMENT '소재지주소',
  `ins_st` date NOT NULL COMMENT '보험시기',
  `ins_clstr` date NOT NULL COMMENT '보험종기',
  `prps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '질권자성명',
  `peamt` decimal(17,2) DEFAULT NULL COMMENT '질권금액',
  `bnnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '업종명',
  `prop_rkcvg_is_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '재산위험담보가입여부',
  `prop_rkcvg_isamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보가입금액',
  `prop_rkcvg_stru_isamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보구축물가입금액',
  `prop_rkcvg_mch_isamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보기계가입금액',
  `prop_rkcvg_stock_isamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보재고가입금액',
  `prop_rkcvg_hshgd_isamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보집기가입금액',
  `prop_rkcvg_et_isamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보기타가입금액',
  `prop_rkcvg_cmp_lmamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보보상한도금액',
  `prop_rkcvg_self_chamt` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보자기부담금액',
  `prop_rkcvg_rknm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재산위험담보위험명',
  `prop_rkcvg_pym_prm` decimal(17,2) DEFAULT NULL COMMENT '재산위험담보납입보험료',
  `prop_rkcvg_spcft_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '재산위험담보명기사항',
  `mch_rkcvg_is_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '기계위험담보가입여부',
  `mch_rkcvg_isamt` decimal(17,2) DEFAULT NULL COMMENT '기계위험담보가입금액',
  `mch_rkcvg_self_chamt` decimal(17,2) DEFAULT NULL COMMENT '기계위험담보자기부담금액',
  `mch_rkcvg_pym_prm` decimal(17,2) DEFAULT NULL COMMENT '기계위험담보납입보험료',
  `ntp_rkcvg_is_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '기업위험담보가입여부',
  `ntp_rkcvg_isamt` decimal(17,2) DEFAULT NULL COMMENT '기업위험담보가입금액',
  `ntp_rkcvg_rknm` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기업위험담보위험명',
  `ntp_rkcvg_cvrdt` date DEFAULT NULL COMMENT '기업위험담보담보일자',
  `ntp_rkcvg_dcdt` date DEFAULT NULL COMMENT '기업위험담보공제일자',
  `ntp_rkcvg_pym_prm` decimal(17,2) DEFAULT NULL COMMENT '기업위험담보납입보험료',
  `lbtrs_is_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '배상책임가입여부',
  `lbtrs_eqmlb_bd1ps_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임시설배상대인1인당가입금액',
  `lbtrs_eqmlb_bd1cm_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임시설배상대인1사고가입금액',
  `lbtrs_eqmlb_prdm_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임시설배상대물가입금액',
  `lbtrs_rmdy_ps1_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임치료1인당가입금액',
  `lbtrs_rmdy_clmp1_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임치료1사고당가입금액',
  `lbtrs_gas_ps1_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임가스1인당가입금액',
  `lbtrs_gas_clmp1_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임가스1사고당가입금액',
  `lbtrs_fire_isamt` decimal(17,2) DEFAULT NULL COMMENT '배상책임화재가입금액',
  `lbtrs_cc_ba_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배상책임산출기초내용',
  `lbtrs_pym_prm` decimal(17,2) DEFAULT NULL COMMENT '배상책임납입보험료',
  `wrdng` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '워딩',
  `dn_ct` decimal(10,0) DEFAULT NULL COMMENT '다운횟수',
  `cvr_rknm_1` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보위험명1',
  `cvrnm_1` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보명1',
  `isam1` decimal(15,0) DEFAULT NULL COMMENT '가입금액1',
  `cvr_rknm_2` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보위험명2',
  `cvrnm_2` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보명2',
  `isam2` decimal(15,0) DEFAULT NULL COMMENT '가입금액2',
  `cvr_rknm_3` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보위험명3',
  `cvrnm_3` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보명3',
  `isam3` decimal(15,0) DEFAULT NULL COMMENT '가입금액3',
  `cvr_rknm_4` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보위험명4',
  `cvrnm_4` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보명4',
  `isam4` decimal(15,0) DEFAULT NULL COMMENT '가입금액4',
  `cvr_rknm_5` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보위험명5',
  `cvrnm_5` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보명5',
  `isam5` decimal(15,0) DEFAULT NULL COMMENT '가입금액5',
  `tisrd_cvr_rknm_1` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보자담보위험명1',
  `relmn_nm_1` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인성명1',
  `relmn_ctm_rgtno_1` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인고객등록번호1',
  `tisrd_cvr_rknm_2` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보자담보위험명2',
  `relmn_nm_2` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인성명2',
  `relmn_ctm_rgtno_2` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인고객등록번호2',
  `tisrd_cvr_rknm_3` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보자담보위험명3',
  `relmn_nm_3` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인성명3',
  `relmn_ctm_rgtno_3` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인고객등록번호3',
  `tisrd_cvr_rknm_4` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보자담보위험명4',
  `relmn_nm_4` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인성명4',
  `relmn_ctm_rgtno_4` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인고객등록번호4',
  `tisrd_cvr_rknm_5` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부보자담보위험명5',
  `relmn_nm_5` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인성명5',
  `relmn_ctm_rgtno_5` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '관련인고객등록번호5',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`plyno`,`is_crtf_admno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개별가입증명서';
