--
-- Table structure for table `ins_condt_bf_is_inq`
--

DROP TABLE IF EXISTS `ins_condt_bf_is_inq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_condt_bf_is_inq` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `condt_wrkdt` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '공동인수작업일자',
  `condt_wkhms` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '공동인수작업시간',
  `dvpns_rcpno` varchar(30) COLLATE utf8mb4_bin NOT NULL COMMENT '개발원접수번호',
  `rq_cmpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '요청회사코드',
  `rq_dthms` datetime DEFAULT NULL COMMENT '신청일시',
  `isflg_cd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입구분코드',
  `rst_asr_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '결과회신방법코드',
  `is_rq_ctmdn` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객식별번호',
  `is_rq_ctmnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객명',
  `is_rq_ctm_cral_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객휴대전화지역번호',
  `is_rq_ctm_cral_tlof_no` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객휴대전화국번호',
  `is_rq_ctm_cral_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객휴대전화일련번호',
  `is_rq_ctm_adr_pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객주소우편번호',
  `is_rq_ctm_et_adr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객기타주소',
  `is_rq_ctm_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청고객직업코드',
  `is_rq_insst` date DEFAULT NULL COMMENT '가입요청보험시기',
  `is_rq_inslt` date DEFAULT NULL COMMENT '가입요청보험종기',
  `is_rq_carno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차량번호구분코드',
  `is_rq_crgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차량관코드',
  `is_rq_cr_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차량차대번호',
  `is_rq_cr_yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차량연식',
  `is_rq_rglr_temp_carnm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청정규임시차명여부',
  `is_rq_cnmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차명코드',
  `is_rq_catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차종코드',
  `is_rq_bdin2_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청대인2가입여부',
  `is_rq_bdin2_isamt` decimal(15,0) DEFAULT NULL COMMENT '가입요청대인2가입금액',
  `is_rq_prdm_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청대물가입여부',
  `is_rq_prdm_isamt` decimal(15,0) DEFAULT NULL COMMENT '가입요청대물가입금액',
  `is_rq_obi_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청자손가입여부',
  `is_rq_obi_isamt` decimal(15,0) DEFAULT NULL COMMENT '가입요청자손가입금액',
  `is_rq_owcr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청자차가입여부',
  `is_rq_self_chrg_rt` decimal(3,0) DEFAULT NULL COMMENT '가입요청자기부담비율',
  `is_rq_unins_cr_injr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청무보험차상해가입여부',
  `is_rq_unins_cr_injr_isamt` decimal(15,0) DEFAULT NULL COMMENT '가입요청무보험차상해가입금액',
  `is_rq_mtlxc_stamt` decimal(15,0) DEFAULT NULL COMMENT '가입요청물적할증기준금액',
  `is_rq_emgmv_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청긴급출동가입여부',
  `is_rq_dvpns_drv_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청개발원운전자한정특약코드',
  `is_rq_lowt_age_drv_born_dt` date DEFAULT NULL COMMENT '가입요청최저연령운전자출생일자',
  `bfcr_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약증권번호',
  `bfcr_same_ply_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약동일증권구분코드',
  `bfcr_carno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약차량번호구분코드',
  `bfcr_crgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약차량관코드',
  `bfcr_cr_chsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약차량차대번호',
  `bfcr_cr_yytp` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약차량연식',
  `bfcr_cnmcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약차명코드',
  `bfcr_ins_st` date DEFAULT NULL COMMENT '전계약보험시기',
  `bfcr_ins_clstr` date DEFAULT NULL COMMENT '전계약보험종기',
  `bfcr_bdin1_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약대인1가입여부',
  `bfcr_bdin2_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약대인2가입여부',
  `bfcr_prdm_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약대물가입여부',
  `bfcr_obi_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약자손가입여부',
  `bfcr_owcr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약자차가입여부',
  `bfcr_slfch_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약자기부담금가입여부',
  `bfcr_unins_cr_injr_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약무보험차상해가입여부',
  `bfcr_dvpns_age_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약개발원연령한정특약코드',
  `bfcr_dvpns_drv_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약개발원운전자한정특약코드',
  `bfcr_mtlxc_stamt` decimal(15,0) DEFAULT NULL COMMENT '전계약물적할증기준금액',
  `bfcr_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약할인할증등급코드',
  `rnw_clm_poct` decimal(4,1) DEFAULT NULL COMMENT '갱신사고점수',
  `rnw_ap_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신적용등급코드',
  `rnw_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신가입경력코드',
  `rnw_rglt_vltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신법규위반코드',
  `nrdps_annu1_clmct` decimal(3,0) DEFAULT NULL COMMENT '피보험자1년간사고건수',
  `nrdps_annu3_clmct` decimal(3,0) DEFAULT NULL COMMENT '피보험자3년간사고건수',
  `nrdps_cr_annu1_clmct` decimal(3,0) DEFAULT NULL COMMENT '피보험자차량1년간사고건수',
  `nrdps_cr_annu2_clmct` decimal(3,0) DEFAULT NULL COMMENT '피보험자차량2년간사고건수',
  `nrdps_cr_annu3_clmct` decimal(3,0) DEFAULT NULL COMMENT '피보험자차량3년간사고건수',
  `crt_plyno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생성증권번호',
  `crt_plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '생성설계번호',
  `tlm_opn_dthms` datetime DEFAULT NULL COMMENT '전문개시일시',
  `dpc_trmno` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발신단말기번호',
  `da_ctu_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자료계속여부',
  `is_rq_xmn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청검토구분코드',
  `condt_prg_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '공동인수진행결과코드',
  `cr_dcn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약확정여부',
  `udrtk_rejet_rs_clm_my_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유사고다수여부',
  `udrtk_rejet_rs_rglt_vltyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유법규위반여부',
  `udrtk_rejet_rs_hgpr_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유고가차량여부',
  `udrtk_rejet_rs_rk_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유위험차량여부',
  `udrtk_rejet_rs_ntt_clmcr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유고의사고경력여부',
  `udrtk_rejet_rs_prm_avd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유보험료면탈여부',
  `udrtk_rejet_rs_rk_age_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유위험연령여부',
  `udrtk_rejet_rs_nm_non_eqlyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인수거부사유명의불일치여부',
  `et_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '기타사항',
  `bfcr_cr_yytp_nwcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약차량연식신차구분코드',
  `is_rq_cr_nwcr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청차량신차구분코드',
  `is_ikdcd` decimal(1,0) DEFAULT NULL COMMENT '가입보종코드',
  `is_rq_usecd` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청용도코드',
  `is_rq_use` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청용도',
  `is_rq_tratr_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청견인차특별요율',
  `is_rq_acmdf_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청수반차특별요율',
  `is_rq_rkgd_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청위험물특별요율',
  `is_rq_crane_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청기중기특별요율',
  `is_rq_mcheq_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청기계장치특별요율',
  `is_rq_spceq_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청특수장비특별요율',
  `is_rq_cmps_tr_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청유상운송특별요율',
  `is_rq_lessn_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청교습특별요율',
  `is_rq_stt_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청학생특별요율',
  `is_rq_delvy_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청택배특별요율',
  `is_rq_bxtrck_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청탑차특별요율',
  `is_rq_et_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청기타특별요율',
  `is_rq_spcrt_et_xpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입요청특별요율기타설명',
  `bfcr_tratr_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약견인차특별요율',
  `bfcr_acmdf_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약수반차특별요율',
  `bfcr_rkgd_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약위험물특별요율',
  `bfcr_crane_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약기중기특별요율',
  `bfcr_mcheq_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약기계장치특별요율',
  `bfcr_spceq_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약특수장비특별요율',
  `bfcr_cmps_tr_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약유상운송특별요율',
  `bfcr_lessn_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약교습특별요율',
  `bfcr_stt_spcrt` varchar(3) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약학생특별요율',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_condt_bf_is_inq_00` (`condt_wrkdt`,`condt_wkhms`,`dvpns_rcpno`,`rq_cmpcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='공동인수전가입조회';
