--
-- Table structure for table `ins_outs_carnm`
--

DROP TABLE IF EXISTS `ins_outs_carnm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_outs_carnm` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `stdt` date NOT NULL COMMENT '기준일자',
  `outs_nw_cnmcd` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '외부신차명코드',
  `outs_car_prd_cmpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '외부차량제작회사코드',
  `outs_mnftr_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부제조사명',
  `outs_dma_foma_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부국산외산구분코드',
  `modl_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모델번호',
  `mdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모델명',
  `modl_str_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모델시작년월',
  `modl_nd_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모델종료년월',
  `grd_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '등급번호',
  `grdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '등급명',
  `specf_grdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제원등급명',
  `outs_catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부차종코드',
  `outs_ctpnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부차종명',
  `lpg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'LPG여부',
  `mdf_ct_cn` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수정건수내용',
  `fnl_mdfdt` date DEFAULT NULL COMMENT '최종수정일자',
  `outs_schnd_cnmcd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부중고차명코드',
  `specf_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제원번호',
  `specf_modl_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제원모델번호',
  `specf_sris_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제원시리즈명',
  `specf_st_yr` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제원기준년도',
  `specf_stdmm` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제원기준월',
  `outs_engn_nm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부엔진명',
  `outs_dspl` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외부배기량',
  `fuel_nm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연료명',
  `tot_lngth` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전체길이',
  `tot_width` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전체너비',
  `tot_hght` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전체높이',
  `abrd_rgsct` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승차정원수',
  `auto_grbx_kndnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자동변속기종류명',
  `mnal_grbx_kndnm` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수동변속기종류명',
  `mx_speed` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '최대속도',
  `load_prmqt` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '적재허용량',
  `elcr_hg_out_qnty` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기차최고출력량',
  `elcr_mx_speed` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기차최대속도',
  `elcr_vltg_qnty` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기차전압량',
  `elcr_elcu_qnty` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전기차전류량',
  `nwcr_optn_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차옵션번호',
  `nwcr_optn_modl_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차옵션모델번호',
  `nwcr_optn_grd_no` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차옵션등급번호',
  `optn_ref_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '옵션참조등급코드',
  `optn_ky_nm` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '옵션키명',
  `nwcr_optn_stdy` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차옵션기준년도',
  `nwcr_optn_stdmm` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신차옵션기준월',
  `nwcr_prc` decimal(15,0) DEFAULT NULL COMMENT '신차가격',
  `grbx_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변속기구분코드',
  `usdcr_1_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차1차량가액',
  `usdcr_2_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차2차량가액',
  `usdcr_3_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차3차량가액',
  `usdcr_4_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차4차량가액',
  `usdcr_5_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차5차량가액',
  `usdcr_6_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차6차량가액',
  `usdcr_7_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차7차량가액',
  `usdcr_8_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차8차량가액',
  `usdcr_9_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차9차량가액',
  `usdcr_10_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차10차량가액',
  `usdcr_11_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차11차량가액',
  `usdcr_12_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차12차량가액',
  `usdcr_13_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차13차량가액',
  `usdcr_14_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차14차량가액',
  `usdcr_15_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차15차량가액',
  `usdcr_16_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차16차량가액',
  `usdcr_17_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차17차량가액',
  `usdcr_18_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차18차량가액',
  `usdcr_19_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차19차량가액',
  `usdcr_20_cramt` decimal(15,0) DEFAULT NULL COMMENT '중고차20차량가액',
  `nwcr_1_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차1차량가액',
  `nwcr_2_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차2차량가액',
  `nwcr_3_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차3차량가액',
  `nwcr_4_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차4차량가액',
  `nwcr_5_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차5차량가액',
  `nwcr_6_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차6차량가액',
  `nwcr_7_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차7차량가액',
  `nwcr_8_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차8차량가액',
  `nwcr_9_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차9차량가액',
  `nwcr_10_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차10차량가액',
  `nwcr_11_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차11차량가액',
  `nwcr_12_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차12차량가액',
  `nwcr_13_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차13차량가액',
  `nwcr_14_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차14차량가액',
  `nwcr_15_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차15차량가액',
  `nwcr_16_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차16차량가액',
  `nwcr_17_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차17차량가액',
  `nwcr_18_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차18차량가액',
  `nwcr_19_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차19차량가액',
  `nwcr_20_cramt` decimal(15,0) DEFAULT NULL COMMENT '신차20차량가액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_outs_carnm_00` (`stdt`,`outs_nw_cnmcd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='외부차명';
