--
-- Table structure for table `ins_dvpns_nds_inr_inq`
--

DROP TABLE IF EXISTS `ins_dvpns_nds_inr_inq`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_dvpns_nds_inr_inq` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `nrdps_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호구분코드',
  `nrdps_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자식별번호',
  `carno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호구분코드',
  `crgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량관코드',
  `crncd` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호코드',
  `carno_hngl` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량번호한글',
  `cr_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량용도코드',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `frg_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '외국인여부',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `same_ply_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일증권구분코드',
  `spcf_obj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특정물건여부',
  `cn_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '해지여부',
  `ndv_gr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '개별단체구분코드',
  `cr_us_usecd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량사용용도코드',
  `optn_ins_st` date DEFAULT NULL COMMENT '임의보험시기',
  `optn_ins_clstr` date DEFAULT NULL COMMENT '임의보험종기',
  `vald_trm_clsdt` date DEFAULT NULL COMMENT '유효기간종기일자',
  `pym_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '납입방법코드',
  `pym_ct` decimal(3,0) DEFAULT NULL COMMENT '납입횟수',
  `bdin1_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인1가입여부',
  `bdin2_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대인2가입여부',
  `prdm_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '대물가입여부',
  `obi_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자손가입여부',
  `owcr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자차가입여부',
  `is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입경력코드',
  `age_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연령한정특약코드',
  `drv_lmit_trtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운전자한정특약코드',
  `plus_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '플러스특약가입여부',
  `ovavc_bdl_trt_isyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전차량일괄특약가입여부',
  `std_dc_xcrt` decimal(5,2) DEFAULT NULL COMMENT '표준할인할증율',
  `dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '할인할증등급코드',
  `spc_xcrt` decimal(12,6) DEFAULT NULL COMMENT '특별할증율',
  `rgvlt_rt` decimal(5,2) DEFAULT NULL COMMENT '법규위반요율',
  `nds_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서구분코드',
  `optn_nwgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '임의신상품코드',
  `rpbl_same_ply_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임동일증권여부',
  `rpbl_ins_st` date DEFAULT NULL COMMENT '책임보험시기',
  `rpbl_ins_clstr` date DEFAULT NULL COMMENT '책임보험종기',
  `rpbl_spcf_obj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임특정물건여부',
  `rpbl_cn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임해지구분코드',
  `rpbl_dc_xcrt` decimal(12,6) DEFAULT NULL COMMENT '책임할인할증율',
  `rpbl_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임할인할증등급코드',
  `rpbl_nwgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '책임신상품코드',
  `nds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서여부',
  `mtral_xc_stamt` decimal(15,0) DEFAULT NULL COMMENT '물적할증기준금액',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_dvpns_nds_inr_inq_00` (`plyno`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='개발원배서통합조회';
