--
-- Table structure for table `ins_auto_ntc_adm`
--

DROP TABLE IF EXISTS `ins_auto_ntc_adm`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_auto_ntc_adm` (
  `aid` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `snd_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '발송년월',
  `atrnw_ntc_flgcd` varchar(2) COLLATE utf8mb4_bin NOT NULL COMMENT '자동갱신안내구분코드',
  `bj_extdt` date NOT NULL COMMENT '대상추출일자',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `cvrcd` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '담보코드',
  `cvr_seqno` decimal(5,0) NOT NULL COMMENT '담보순번',
  `cr_stcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약상태코드',
  `crt_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자고객번호',
  `nrdps_ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자고객번호',
  `isno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '발급번호',
  `crrnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약자명',
  `nrdnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자명',
  `gdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상품코드',
  `ins_st` date DEFAULT NULL COMMENT '보험시기',
  `ins_clstr` date DEFAULT NULL COMMENT '보험종기',
  `rnwdt` date DEFAULT NULL COMMENT '갱신일자',
  `rnw_cyc` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신주기',
  `cvr_instr` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담보보험기간',
  `rnw_age` decimal(3,0) DEFAULT NULL COMMENT '갱신연령',
  `nd_ris_age` decimal(3,0) DEFAULT NULL COMMENT '만기재가입연령',
  `cvr_isamt` decimal(15,0) DEFAULT NULL COMMENT '담보가입금액',
  `bfrnw_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전보험료',
  `bfrnw_dc_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전할인보험료',
  `bfrnw_gn_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전보장보험료',
  `bfrnw_rnw_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전갱신보험료',
  `bfrnw_cu_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전적립보험료',
  `bfrnw_sb_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전대체보험료',
  `bfrnw_cvr_ap_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신전담보적용보험료',
  `bfrnw_nclm_dcamt` decimal(18,0) DEFAULT NULL COMMENT '갱신전무사고할인금액',
  `rnw_af_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신후보험료',
  `rnw_af_dc_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신후할인보험료',
  `rnw_af_gn_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신후보장보험료',
  `rnw_af_rnw_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신후갱신보험료',
  `rnw_af_cu_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신후적립보험료',
  `rnw_af_sb_prm` decimal(15,0) DEFAULT NULL COMMENT '갱신후대체보험료',
  `rnw_af_cvr_apprm` decimal(15,0) DEFAULT NULL COMMENT '갱신후담보적용보험료',
  `rnw_af_nclm_dcamt` decimal(18,0) DEFAULT NULL COMMENT '갱신후무사고할인금액',
  `rnw_af_age_incrp_amt` decimal(18,0) DEFAULT NULL COMMENT '갱신후연령증가분금액',
  `rnw_af_rkrt_incrp_amt` decimal(18,0) DEFAULT NULL COMMENT '갱신후위험율증가분금액',
  `pym_trm` decimal(3,0) DEFAULT NULL COMMENT '납입기간',
  `rcvdt` date DEFAULT NULL COMMENT '수신일자',
  `snddt` date DEFAULT NULL COMMENT '발송일자',
  `cntrt_rstcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '접촉결과코드',
  `rnw_cplyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신완료여부',
  `rnw_rflt_dy` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '갱신반영일',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `inp_dthms` datetime NOT NULL COMMENT '입력일시',
  `mdf_dthms` datetime NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `idx_ins_auto_ntc_adm_00` (`snd_yymm`,`atrnw_ntc_flgcd`,`bj_extdt`,`plyno`,`cvrcd`,`cvr_seqno`),
  KEY `idx_ins_auto_ntc_adm_10` (`plyno`),
  KEY `idx_ins_auto_ntc_adm_11` (`isno`),
  KEY `idx_ins_auto_ntc_adm_12` (`crt_ctmno`),
  KEY `idx_ins_auto_ntc_adm_13` (`rnwdt`)
) ENGINE=InnoDB AUTO_INCREMENT=5810 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='자동갱신안내관리';
