--
-- Table structure for table `ins_cr_scp_rt`
--

DROP TABLE IF EXISTS `ins_cr_scp_rt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_cr_scp_rt` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `nrdps_rsno` varchar(48) COLLATE utf8mb4_bin NOT NULL COMMENT '피보험자주민번호',
  `carno` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '차량번호',
  `ins_strdt` date NOT NULL COMMENT '보험시작일자',
  `scp_rt_seqno` decimal(5,0) NOT NULL COMMENT '자사요율순번',
  `rt_ud_org_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '요율심사기관구분코드',
  `dvpns_rnwrt_xstn_yn` varchar(1) COLLATE utf8mb4_bin NOT NULL COMMENT '개발원갱신율존재여부',
  `cr_rt_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '자동차요율구분코드',
  `is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '가입경력코드',
  `stdrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '표준율',
  `spc_xccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특별할증코드',
  `spc_xcrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '특별할증율',
  `rglt_vltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '법규위반코드',
  `rglt_vltrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '법규위반율',
  `pst_rpbl_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '과거책임가입여부',
  `rq_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청가입경력코드',
  `rq_stdrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '요청표준율',
  `rq_spc_xccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청특별할증코드',
  `rq_spc_xcrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '요청특별할증율',
  `rq_rglt_vltcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청법규위반코드',
  `rq_rglt_vltrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '요청법규위반율',
  `rq_prpbl_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청과거책임가입여부',
  `bfcr_iscmp` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약가입회사',
  `bfcr_ikdcd` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약보종코드',
  `bfcr_year` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약연도',
  `bfcr_no` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약번호',
  `bfcr_ins_st` date DEFAULT NULL COMMENT '전계약보험시기',
  `bfcr_ins_clstr` date DEFAULT NULL COMMENT '전계약보험종기',
  `bfcr_aprt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '전계약적용율',
  `rq_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청할인할증등급코드',
  `ap_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인할인할증등급코드',
  `rq_same_grd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청동일등급여부',
  `ap_same_grd_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인동일등급여부',
  `bfcr_dc_xc_grdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약할인할증등급코드',
  `ers_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '삭제여부',
  `rq_plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청설계번호',
  `catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차종코드',
  `rq_catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청차종코드',
  `ap_catcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인차종코드',
  `vlt_spc_xccd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위반특별할증코드',
  `same_ply_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일증권여부',
  `rglt_vltct` decimal(7,0) DEFAULT NULL COMMENT '법규위반건수',
  `bfcr_obj_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약물건구분코드',
  `bfcr_mtlxc_d15w_clmct` decimal(5,0) DEFAULT NULL COMMENT '전계약물적할증15일이내사고건수',
  `bfcr_owcr_is_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전계약자차가입여부',
  `rq_y1_clm_ct` decimal(3,0) DEFAULT NULL COMMENT '요청1년사고횟수',
  `rq_y3_clm_ct` decimal(3,0) DEFAULT NULL COMMENT '요청3년사고횟수',
  `ap_y1_clm_ct` decimal(3,0) DEFAULT NULL COMMENT '승인1년사고횟수',
  `ap_y3_clm_ct` decimal(3,0) DEFAULT NULL COMMENT '승인3년사고횟수',
  `cr_chncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '계약채널코드',
  `rq_rnd_mngbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청경과조치대상여부',
  `ap_rnd_mngbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인경과조치대상여부',
  `rq_shtm_xctbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청단기특례대상여부',
  `ap_shtm_xctbj_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인단기특례대상여부',
  `cr_is_crrcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량가입경력코드',
  `same_ply_gpno` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '동일증권그룹번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  KEY `pix_ins_cr_scp_rt_00` (`nrdps_rsno`,`carno`,`ins_strdt`,`scp_rt_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=2080 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='자동차자사요율';
