--
-- Table structure for table `ins_cr_nds_mstr`
--

DROP TABLE IF EXISTS `ins_cr_nds_mstr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ins_cr_nds_mstr` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `plyno` varchar(16) COLLATE utf8mb4_bin NOT NULL COMMENT '증권번호',
  `ndsno` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '배서번호',
  `ikd_grpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '보종군코드',
  `ch_rvsn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '변경정정구분코드',
  `nds_cas_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서원인구분코드',
  `nds_wrdg` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서WORDING',
  `nds_prgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서문구코드',
  `prort_shtm_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '일할단기구분코드',
  `prort_cal_days` decimal(5,0) DEFAULT NULL COMMENT '일할계산일수',
  `prort_shtrt` decimal(12,6) NOT NULL DEFAULT '0.000000' COMMENT '일할단기율',
  `nds_rqdt` date DEFAULT NULL COMMENT '배서신청일자',
  `nds_ap_dthms` datetime DEFAULT NULL COMMENT '배서승인일시',
  `otcm_mg_apdt` date DEFAULT NULL COMMENT '타사간사승인일자',
  `nds_cr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서발생구분코드',
  `nds_stdt` date DEFAULT NULL COMMENT '배서기준일자',
  `nds_st_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서기준시각',
  `nds_nddt` date DEFAULT NULL COMMENT '배서종료일자',
  `rqfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요청직원번호',
  `ap_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '승인직원번호',
  `nds_acnmt_isdt` date DEFAULT NULL COMMENT '배서승인서발급일자',
  `nds_sno` decimal(10,0) DEFAULT NULL COMMENT '배서일련번호',
  `nds_ap_br_orgcd` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서승인지점기관코드',
  `retr_nds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소급배서여부',
  `frc_nds_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '강제배서여부',
  `inp_trm_ip` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '입력단말기아이피',
  `bsc_ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '근거배서번호',
  `amt_cr_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금액발생여부',
  `nds_plno` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서설계번호',
  `nds_cgaf_ch_seqno` decimal(5,0) DEFAULT NULL COMMENT '배서발행후변경순번',
  `retr_ndsof_ndsno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소급배서원배서번호',
  `whpy_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '제지급방법코드',
  `nds_rq_spc` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서신청내역',
  `nds_rq_rs` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서신청사유',
  `nds_ccmtd` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서산출식',
  `frc_nds_cas_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '강제배서원인구분코드',
  `rqapl_relcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청인관계코드',
  `rqaps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청자명',
  `nds_rq_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서신청유형코드',
  `rqaps_cntad_areno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청자연락처지역번호',
  `rqaps_cntad` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신청자연락처',
  `nds_rq_hms` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서신청시각',
  `nds_rq_rscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서신청사유코드',
  `nds_rq_rs_stdt` date DEFAULT NULL COMMENT '배서신청사유기준일자',
  `fr_ply_rcdt` date DEFAULT NULL COMMENT '최초증권수령일자',
  `apl_wdr_bj_cnyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청약철회대상해지여부',
  `nds_oj_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서목적유형코드',
  `prm_apdt` date DEFAULT NULL COMMENT '보험료적용일자',
  `nds_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서유형코드',
  `ndscd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서코드',
  `nds_rflt_stfno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배서반영직원번호',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_ins_cr_nds_mstr_00` (`plyno`,`ndsno`),
  KEY `idx_ins_cr_nds_mstr_02` (`nds_plno`)
) ENGINE=InnoDB AUTO_INCREMENT=3927 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='계약배서마스터';
