--
-- Table structure for table `lse_hprm_lb_dt`
--

DROP TABLE IF EXISTS `lse_hprm_lb_dt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_hprm_lb_dt` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `hprm_clm_nv_seqno` decimal(3,0) NOT NULL COMMENT 'HPRM사고조사순번',
  `lb_dt_seqno` decimal(3,0) NOT NULL COMMENT '배상상세순번',
  `clm_nv_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고조사종류코드',
  `ctmno` varchar(13) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객번호',
  `clmnm` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '사고자명',
  `ctm_dscno_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호구분코드',
  `ctm_dscno` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '고객식별번호',
  `crdif_utl_agre_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신용정보활용동의여부',
  `cntad_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '연락처구분코드',
  `tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화지역번호',
  `tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화국번',
  `tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '전화일련번호',
  `drct_dmamt` decimal(17,2) NOT NULL COMMENT '직접손해금액',
  `drt_dmamt` decimal(17,2) NOT NULL COMMENT '간접손해금액',
  `victm_fltrt` decimal(3,0) DEFAULT NULL COMMENT '피해자과실율',
  `xp_dmamt` decimal(17,5) NOT NULL COMMENT '예상손해액',
  `self_chamt` decimal(15,0) DEFAULT NULL COMMENT '자기부담금액',
  `ag_amt` decimal(17,2) NOT NULL COMMENT '합의금액',
  `hspcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원코드',
  `bzmno` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사업자번호',
  `fsvs_hsp_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '금감원병원구분코드',
  `hspnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '병원명',
  `nw_tth_supm_ct` decimal(3,0) DEFAULT NULL COMMENT '신규치아보철갯수',
  `prev_tth_supm_ct` decimal(3,0) DEFAULT NULL COMMENT '기존치아보철개수',
  `idac_dl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재처리여부',
  `idark` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재급',
  `idacl` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재호',
  `obsdt` date DEFAULT NULL COMMENT '장해일자',
  `obs_slamt` decimal(17,2) NOT NULL COMMENT '장해급여금액',
  `rcpr_slamt` decimal(17,2) NOT NULL COMMENT '요양급여금액',
  `srvfm_slamt` decimal(17,2) NOT NULL COMMENT '유족급여금액',
  `fnrcs` decimal(17,2) NOT NULL COMMENT '장제비',
  `et_slamt` decimal(17,2) NOT NULL COMMENT '기타급여금액',
  `idac_dl_pout_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '산재처리특이사항',
  `dl_org` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '처리기관',
  `de_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사망여부',
  `psbsn_slamt` decimal(17,2) DEFAULT NULL COMMENT '휴업급여금액',
  `actvt_nddt` date DEFAULT NULL COMMENT '가동종료일자',
  `merg_obsrt` decimal(5,2) DEFAULT NULL COMMENT '병합장해율',
  `chrps_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자성명',
  `chrps_tlano` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화지역번호',
  `chrps_tltno` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화국번',
  `chrps_tlsno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '담당자전화일련번호',
  `auili_srtcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수상레저기구코드',
  `auili_rsvyn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수상레저예약여부',
  `cg_prv_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '요금결재구분코드',
  `siu_dmgit_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SIU피해물유형코드',
  `dmgit_dt_mtt` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피해물세부사항',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국내외구분코드',
  `clm_carno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고차량번호',
  `rpair_rnt_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '수리렌트여부',
  `car_rpair_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량수리업체코드',
  `car_rnt_entcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '차량렌트업체코드',
  `nrdps_jbcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자직업코드',
  `nrdps_jbnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '피보험자직업명',
  `hous_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주택종류코드',
  `tot_pysz` decimal(13,2) DEFAULT NULL COMMENT '전체평수',
  `dmge_pysz` decimal(13,2) DEFAULT NULL COMMENT '피해평수',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_hprm_lb_dt_00` (`rcp_yymm`,`rcp_nv_seqno`,`hprm_clm_nv_seqno`,`lb_dt_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='HPRM배상상세';
