--
-- Table structure for table `lse_hprm_clm_nv`
--

DROP TABLE IF EXISTS `lse_hprm_clm_nv`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lse_hprm_clm_nv` (
  `aid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'AID',
  `rcp_yymm` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '접수년월',
  `rcp_nv_seqno` varchar(9) COLLATE utf8mb4_bin NOT NULL COMMENT '접수조사순번',
  `hprm_clm_nv_seqno` decimal(3,0) NOT NULL COMMENT 'HPRM사고조사순번',
  `requ_org_seqno` decimal(3,0) NOT NULL COMMENT '의뢰기관순번',
  `dm_seqno` decimal(5,0) NOT NULL COMMENT '청구순번',
  `clm_nv_kndcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고조사종류코드',
  `rcpdt` date NOT NULL COMMENT '접수일자',
  `rcp_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '접수시분',
  `clmdt` date NOT NULL COMMENT '사고일자',
  `clm_hhmm` varchar(4) COLLATE utf8mb4_bin NOT NULL COMMENT '사고시분',
  `dmos_flgcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '국내외구분코드',
  `pstno` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '우편번호',
  `dtadr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '상세주소',
  `clm_cn` varchar(1000) COLLATE utf8mb4_bin NOT NULL COMMENT '사고내용',
  `clm_tpcd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '사고유형코드',
  `clm_2_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고2유형코드',
  `pout_mtt` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '특이사항',
  `mncd` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '화폐코드',
  `nv_cs_tamt` decimal(15,0) NOT NULL COMMENT '조사비용총액',
  `clm_nv_baamt` decimal(15,0) NOT NULL COMMENT '사고조사기본금액',
  `ddalw_csamt` decimal(15,0) DEFAULT NULL COMMENT '일당비용금액',
  `trf_csamt` decimal(15,0) DEFAULT NULL COMMENT '교통비용금액',
  `cnst_csamt` decimal(15,0) DEFAULT NULL COMMENT '자문비용금액',
  `oupy_amt` decimal(15,0) DEFAULT NULL COMMENT '성과급금액',
  `et_csamt` decimal(15,0) DEFAULT NULL COMMENT '기타비용금액',
  `clm_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고원인코드',
  `clm_2_cascd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고2원인코드',
  `incpl_sl_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '불완전판매여부',
  `cvap_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '민원여부',
  `moral_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '모랄여부',
  `idm_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '구상여부',
  `lw_yn` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '소송여부',
  `dgnnm` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진단명',
  `trmt_orgnm` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '진료기관명',
  `dm_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '청구내용',
  `cnf_mtt` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '확인사항',
  `ot_inscp_cn` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '타보험사내용',
  `nv_rst` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '조사결과',
  `tr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송구분코드',
  `tr_tol_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송용구유형코드',
  `tr_tolcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송용구코드',
  `tr_tolnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송용구명',
  `lad_plyno` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선하증권번호',
  `trps_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송자구분코드',
  `trspr` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '운송인',
  `shpdt` date DEFAULT NULL COMMENT '선적일자',
  `dm_tpcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '손해유형코드',
  `pack_mtdcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '포장방법코드',
  `xp_dm_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예상손해화폐코드',
  `xp_dmamt` decimal(17,5) NOT NULL COMMENT '예상손해액',
  `cs_dm_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '비용손해화폐코드',
  `cs_dmamt` decimal(17,2) NOT NULL COMMENT '비용손해액',
  `lb_rpamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '배상책임금액화폐코드',
  `lb_rpamt` decimal(17,2) NOT NULL COMMENT '배상책임금액',
  `xp_xiamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '예상추산금액화폐코드',
  `xp_xiamt` decimal(17,2) NOT NULL COMMENT '예상추산금액',
  `vslnm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '선박명',
  `ibnf_rcrgp_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '보험금수령권자성명',
  `clm_plc` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '사고장소',
  `lttd_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도구분코드',
  `lttd_dgr` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도도',
  `lttd_min` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도분',
  `lttd_sec` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '위도초',
  `hdn_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도구분코드',
  `hdn_dgr` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도도',
  `hdn_min` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도분',
  `hdn_sec` varchar(48) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '경도초',
  `loss_cas` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'LOSS원인',
  `idm_xtn_prsdt` date DEFAULT NULL COMMENT '구상소멸시효일자',
  `gd_dmamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '물손해액화폐코드',
  `gd_dmamt` decimal(17,2) DEFAULT NULL COMMENT '물손해액',
  `man_dmamt_mncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '인손해액화폐코드',
  `man_dmamt` decimal(17,2) DEFAULT NULL COMMENT '인손해액',
  `sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시도',
  `sgng` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '시군구',
  `twmd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '읍면동',
  `ri_or_lrdlp` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '리/대량배달처',
  `ntncd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '국가코드',
  `ctycd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도시코드',
  `ref_it` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '참고항목',
  `road_nm` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '도로명',
  `undg_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '지하구분코드',
  `mn_bldno` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '주건물번호',
  `sub_bldno` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '부건물번호',
  `nw_adr_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '신규주소구분코드',
  `dcu_csamt` decimal(15,0) DEFAULT NULL COMMENT '서류비용금액',
  `vispl_num` decimal(3,0) DEFAULT NULL COMMENT '방문처수',
  `lkpvn_amt` decimal(17,2) DEFAULT NULL COMMENT '누수방지금액',
  `trvl_dst` decimal(7,0) DEFAULT NULL COMMENT '주행거리',
  `tgcs` decimal(15,0) DEFAULT NULL COMMENT '톨비',
  `oil_unprc` decimal(15,0) DEFAULT NULL COMMENT '유류단가',
  `oil_kndcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유류종류코드',
  `fuef` decimal(15,0) DEFAULT NULL COMMENT '연비',
  `oil_unprc_st_yymm` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유류단가기준년월',
  `oil_unprc_st_sd` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유류단가기준시도',
  `olcs` decimal(15,0) DEFAULT NULL COMMENT '유류대',
  `slfch_dc_flgcd` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '자기부담금공제구분코드',
  `inp_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '입력사용자ID',
  `inp_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
  `mdf_usr_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '수정사용자ID',
  `mdf_dthms` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`aid`),
  UNIQUE KEY `pux_lse_hprm_clm_nv_00` (`rcp_yymm`,`rcp_nv_seqno`,`hprm_clm_nv_seqno`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='HPRM사고조사';
